### ISSUE TITLE
更新后作品列表页下载出了偏差

### ISSUE THREAD

**Issue by MoeKing** [xuejianxianzun/PixivBatchDownloader#1]
![](https://i.loli.net/2018/07/19/5b506cf3b8304.png)
一直卡在这
67.0.3396.99
脚本下载正常

**Comment by xuejianxianzun** [comment]
谢谢您的反馈，现在我已经提交了 1.0.2 版本，请留意更新
https://chrome.google.com/webstore/detail/hfgoikdmppghehigkckknikdgdcjbfpl/
