### ISSUE TITLE
希望能保存过滤器设置

### ISSUE THREAD

**Issue by nyaachen** [xuejianxianzun/PixivBatchDownloader#10]
每次都要手动填写一遍过滤参数，希望能默认保存设置，然后加个重置按钮恢复默认设置

**Comment by xuejianxianzun** [comment]
宽高、收藏数的过滤器通用性不高，也就是说在一些页面可以用到，在另一些页面很少会用到。如果保存的话，有些页面里还得记得去清除过滤器设置，忘记清除就会浪费时间。所以我没有加这个功能。

**Comment by nyaachen** [comment]
我懂了，就是抓取歌曲是一个统一接口，然后对于不同的抓取过程没有额外的封装，所以过滤参数是全局的了。
