### ISSUE TITLE
圖片下載失敗

### ISSUE THREAD

**Issue by Kurisu3071** [xuejianxianzun/PixivBatchDownloader#100]
前幾天突然下載失敗
更新到最新版本也是同樣的情況
每個繪師的圖都是這個情況
已經試過重設設定也無法解決
![image](https://user-images.githubusercontent.com/70518352/91714967-6391c580-ebbf-11ea-8c92-5e2f540022bf.png)

**Comment by xuejianxianzun** [comment]
感觉是网络问题，或者你换 edge 浏览器试试

**Comment by xuejianxianzun** [comment]
有可能是 Chrome 版本 85 或以上产生的问题。昨天开始 Chrome 才推送了 85 版本。这个问题我需要进一步确认和修复。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/101

**Comment by Kurisu3071** [comment]
目前版本是85沒錯，網路是正常的，那應該就是Chrome的問題了
我先暫時用edge吧，謝謝!
![image](https://user-images.githubusercontent.com/70518352/91838387-fb56e880-ec7f-11ea-8520-a0ddc951f434.png)

**Comment by xuejianxianzun** [comment]
请尝试离线安装 7.2.0 版本，测试是否解决了问题：
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.2.0

**Comment by Kurisu3071** [comment]
已解決，謝謝
安裝7.2.0後不設定Chrome的`CORS for content scripts`也不會跳出無法下載的錯誤了
