### ISSUE TITLE
[Feature Suggestion] English Only or translated language only tags?

### ISSUE THREAD

**Issue by CELICA3** [xuejianxianzun/PixivBatchDownloader#102]
Any possiblity to remove japanese text from tags string and include only translated ones?

**Comment by xuejianxianzun** [comment]
One thing to note: some tags are not translated, only Japanese. If you save only the translated tags, some tags will be lost. What do you think?

**Comment by xuejianxianzun** [comment]
Added new naming tags `tags_transl_only` in version 7.3.0
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0
Only the translated tags are saved, not the original Japanese tags.
But if a tag is not translated, the original tag will be saved.
