### ISSUE TITLE
点击停止下载，刷新页面后又继续下载了

### ISSUE THREAD

**Issue by wt345316277** [xuejianxianzun/PixivBatchDownloader#103]
有的作品有几十张图片，开始下载后又不想要了，就点击停止，但是页面刷新后，或者下次又打开时会继续下载。没有个取消下载的功能吗？

**Comment by xuejianxianzun** [comment]
有的
1. 在首页打开下载面板，“其他”选项卡里可以清除保存的数据
2. 离线安装最新版本，已经解决了你说的这个问题

**Comment by wt345316277** [comment]
谢谢，版本更新很快~
