### ISSUE TITLE
希望能添加一个设置项用来隐藏搜索页顶部的"*users入り"

### ISSUE THREAD

**Issue by NekoAria** [xuejianxianzun/PixivBatchDownloader#105]
具体来说就是不在root节点下插入包含那9个元素的节点.

**Comment by xuejianxianzun** [comment]
这个如果你不使用的话，无视之就行了，没有其他影响吧。
因为设置选项已经太多了，所以我不想单独添加一个设置选项。你可以用 stylish 之类的扩展屏蔽 class `fastScreenArea`。
