### ISSUE TITLE
插件显示进度条显示完成，但浏览器没有下载

### ISSUE THREAD

**Issue by FungJiHsu** [xuejianxianzun/PixivBatchDownloader#106]
![QQ截图20200925210709](https://user-images.githubusercontent.com/14539399/94271006-925b4b80-ff73-11ea-9e48-5f00857a5062.png)

这样完成，但浏览器方面没显示下载东西

**Comment by xuejianxianzun** [comment]
是否使用了chrome最新版？
如果还不行你尝试排除一下其他扩展，关闭其他扩展试试

**Comment by FungJiHsu** [comment]
> 是否使用了chrome最新版？
> 如果还不行你尝试排除一下其他扩展，关闭其他扩展试试

因为新版本chrome没办法无限缩小窗口，所以一直没更新
排除了其他扩展也不行....是没办法了吗？

**Comment by xuejianxianzun** [comment]
不清楚，还是优先考虑更新chrome吧
