### ISSUE TITLE
可以添加一个下载自动点赞的功能按钮吗

### ISSUE THREAD

**Issue by SakamakiRane** [xuejianxianzun/PixivBatchDownloader#107]
白嫖感觉不舒服，一个一个点赞收藏又麻烦

**Comment by SakamakiRane** [comment]
啊 才发现已经有人问过了( ´_ゝ｀)

**Comment by SakamakiRane** [comment]
不过有时候看到很对我xp但点赞却都只有几百的画师，就只能批量下完一个一个点，插件就是为了方便嘛，拜托了请再考虑一下

**Comment by xuejianxianzun** [comment]
插件就是为了方便，说的是没错，但是添加新功能也需要花费时间啊。更何况有些功能我并不想加。
你可以在爱发电给我一些赞助吗

**Comment by SakamakiRane** [comment]
重打过好几遍看来语气还是不太对，白嫖还有所冒犯真的很抱歉 但确实是穷，这个问题就当做不存在吧
