### ISSUE TITLE
下载记录导入导出（备份恢复下载记录）

### ISSUE THREAD

**Issue by baibai92** [xuejianxianzun/PixivBatchDownloader#109]
我认为这是个不可或缺的功能，在一些场景下会有很大的帮助。比如 chrome崩溃卸载重装软件，电脑恢复重装系统，插件冲突（一键清理浏览器插件，cookie管理插件等），迁移电脑等场景，下载记录能够很好的帮助我不必下载重复的图片，节省硬盘资源，同时还可以本地查看历史记录（不可能每下载一次导出一次csv文件）。同时，对于一些重复的图片，倘若命名规则不同，连大批量覆盖都无法做到，占用双份空间，下载记录可以解决。希望作者大大考虑加下这个功能。

**Comment by xuejianxianzun** [comment]
1. 对于一些重复的图片，倘若命名规则不同就会重复下载……去重策略选择为宽松，则只判断 id，可以解决同一个文件但文件名不同的问题，不会重复下载。
2. 去重依赖于扩展自己的下载记录，并不是扫描硬盘文件，所以视具体情况，有时候可能不太准确。这也是为什么之前没有做导入导出功能的原因。
3. 此功能可能会在之后的一段时间内添加。

**Comment by baibai92** [comment]
1.假设我在两次下载的中间某一天发生上述场景（例2020.1.1---2020.10.1的某一天），即使去重规则为宽松，命名规则不同时不能覆盖，因为cookie被清除，导出历史记录就是为了这些时刻。因为使用插件跨度时间长，我们并不能保证上述场景不会发生
2.即使不太准确，也总比没有的好。

**Comment by xuejianxianzun** [comment]
7.9.0 版本增加了此功能，你试试
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.9.0

**Comment by baibai92** [comment]
great!!棒棒
