### ISSUE TITLE
能否做一个调用其他下载器的功能。。。

### ISSUE THREAD

**Issue by UNSCs117** [xuejianxianzun/PixivBatchDownloader#110]
RT，用的360浏览器，IDM接管了360的下载，但是这个脚本却只会调用浏览器自身的下载器下载，然后360下载一定要一个个点确定才行，要点死我的节奏啊

**Comment by xuejianxianzun** [comment]
1. 下载器左下角——常见问题里有提醒：
请不要在浏览器的下载选项里选中'总是询问每个文件的保存位置'。
2. 不要用 360 浏览器，用 chrome 浏览器
3. 用 idm 等第三方下载的话不能自定义文件名。所以下载器不会做直接调用第三方下载器的功能。
4. 如果要调用其他下载器，你可以利用复制url、复制文件名、导出csv、导出抓取结果等工具，选择合适的方式自己去第三方下载器里建立下载。

**Comment by UNSCs117** [comment]
OK,谢谢解答。。。的确是这个问题，关了就没事了
