### ISSUE TITLE
Request:Date Stamp Format

### ISSUE THREAD

**Issue by q36yznmh** [xuejianxianzun/PixivBatchDownloader#111]
Hello.

I would like the {date} tag to be subdivided by "yyyy " "yy" "mm" "dd".

For example, October 07, 2015
yyyy:2015
yy:15
mm:10
dd:07

I want it to be in yymmdd format.
2013-06-22 (yyyy-mm-dd) -> 130622 (yymmdd)

thx.

**Comment by xuejianxianzun** [comment]
Other users may require different formats, which is a troublesome problem. `yyyy-MM-dd` is more general.
If the user needs to customize the date format, I may need to add a separate setting item. I have no plans for this at present. You can try to rename the tool, or modify the source code.
Find `${y}-${m}-${d}` in `js/content.js` and modify it.

**Comment by xuejianxianzun** [comment]
In the next version, I will add a custom date format setting.

**Comment by q36yznmh** [comment]
Excellent!
Thank you very much.

谢谢你。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
I added a setting item in the "Other" tab, and the user can set the date format.
Because it has not been published to the extension store, it can only be installed offline.
