### ISSUE TITLE
请问下能否加入 **在抓取小说的同时抓取其简介** 的功能

### ISSUE THREAD

**Issue by wendao90** [xuejianxianzun/PixivBatchDownloader#113]
在使用时并未找到这个功能相关的设置，
请问下能否加入 **在抓取小说的同时抓取其简介** 的功能？

**Comment by xuejianxianzun** [comment]
抓取小说简介，可能会很长。我打算这样，开启“在小说里保存元数据”的话，会把简介也保存进去。
不想把简介单独保存成一个文件。

**Comment by wendao90** [comment]
> 抓取小说简介，可能会很长。我打算这样，开启“在小说里保存元数据”的话，会把简介也保存进去。
> 不想把简介单独保存成一个文件。

搜噶，多谢回复~

**Comment by xuejianxianzun** [comment]
不对啊，现在版本不就有这个功能了。你开启这个选项就会保存简介。

**Comment by wendao90** [comment]
> 不对啊，现在版本不就已经有这个功能了。你开启这个选项就会保存简介。

啊啊啊啊，抱歉才看到，我刚刚试了试，确实，我有罪！（拜谢
