### ISSUE TITLE
使用gif格式保存动图有色差

### ISSUE THREAD

**Issue by Realzhazha** [xuejianxianzun/PixivBatchDownloader#114]
大概好像是红色会偏暗点
![fb](https://user-images.githubusercontent.com/35806568/99162200-00332080-2736-11eb-89ba-697bcf4c9ca9.png)

**Comment by xuejianxianzun** [comment]
gif格式在颜色上存在很大的问题，这也可能是本程序使用的 gif 转换库有不完善的地方，这个问题我修不了。
