### ISSUE TITLE
支持多个转换

### ISSUE THREAD

**Issue by cmmdwl** [xuejianxianzun/PixivBatchDownloader#115]
![image](https://user-images.githubusercontent.com/21263352/99698927-56081f80-2acc-11eb-91d4-d2faabd25c77.png)
一次转一个有点偏慢了我的cpu占用率才不到百分之20，支持多个转换应该能够提升下载多张动图时候的速度

**Comment by xuejianxianzun** [comment]
“其他”选项，设置同时转换数量
