### ISSUE TITLE
建议：增加通过Aria RPC下载的选项

### ISSUE THREAD

**Issue by CNOwl** [xuejianxianzun/PixivBatchDownloader#116]
如题

**Comment by xuejianxianzun** [comment]
请先查看 readme 底部的友情链接里的另一个下载器。
我因为自己没有使用 aria，而且下载器用户里用aria的人也很少，所以没有进行相关的研究。

ps：简单的看了下 rpc 的调用方法，感觉难以处理小说的下载，因为 pixiv 并没有提供一个 url  下载小说文件，下载器是提取小说文本生成一个本地 blob url 来下载，这种 url 发送到远程电脑就无法下载了。

ps2：对于大批量的下载任务，比如一次几万个文件的任务，发送给 aria 不知道是否能顺利。因为我没有测试所以会有些担心。
