### ISSUE TITLE
升级后快速收藏无法关闭，建议将预览搜索结果放在抓取标签下。

### ISSUE THREAD

**Issue by zhaomma** [xuejianxianzun/PixivBatchDownloader#117]
升级8.2.0后快速收藏默认开启，没找到关闭选项。
建议将“预览搜索页面的筛选结果”开关放在抓取标签下，或者能为抓取添加停止功能？

**Comment by xuejianxianzun** [comment]
你可以设置“收藏设置”来控制快速收藏的效果，如果不想让它附带tag就设置不附带tag。
预览搜索页面这个放到抓取标签下有什么理由吗，它的分类可能不太好分。
停止抓取现在只能通过刷新页面，反正在pixiv刷新页面也没什么不良影响。如果要在下载器里添加这个功能的话就得添加一个按钮了，我还是希望按钮能少点，emmm 如果提的人多了在考虑添加吧

**Comment by zhaomma** [comment]
设置不添加tag后，虽然图标被替换了但功能就等同于原来的收藏是吧。
预览搜索介绍上说如果结果太多可能会崩溃，所以在抓取时如果数量过多会检查一下是否关闭，
减少按钮的话可否把手动删除作品替换为预览搜索，毕竟不开启预览搜索手动删除也无法使用。
停止功能主要是可惜已抓取文件，刷新后要重新抓取确也不是什么必要功能。
说来现在有导出搜索结果，以后是会有什么配套的使用方法吗？

**Comment by xuejianxianzun** [comment]
设置不添加tag等于pixiv原本的收藏。
预览结果这个，有时候要切换过去看一下是挺麻烦的。不过一般不会每次都抓取很多吧，所以不会每次都去看。抓取结果如果只有几千个的数量级别，开着也影响不大。这个选项在抓取途中随时关闭就行，关闭后新抓取的结果不会添加到页面上。关于它放在哪里，因为它只在搜索页面生效（但是“抓取”部分的选项是所有页面生效），所以把它放到“抓取”里感觉会有点不和谐。
导出抓取结果，主要是考虑到一些用户会想保存抓取数据，或者提取数据什么的。它也有可能被导入到这个pixiv下载器用来建立任务，这是一种可能性，但是这样的需求并不多，所以没有开始做。

**Comment by zhaomma** [comment]
通过文件体积跳过的文件会被记录为已下载，本想用来筛选过大文件不下载原图的

**Comment by xuejianxianzun** [comment]
8.3.0版本会始终显示pixiv原本的收藏按钮。

**Comment by xuejianxianzun** [comment]
跳过的下载不应该被保存到下载记录里，这是个bug，我发布了新版本进行修复:
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v8.3.1

**Comment by Realzhazha** [comment]
chrome商店上没有更新啊，还是8.3.0

**Comment by zhaomma** [comment]
> chrome商店上没有更新啊，还是8.3.0
Microsoft也没有，在意更新内容的话可以先用离线加载
