### ISSUE TITLE
Failed - Network Error

### ISSUE THREAD

**Issue by Emperor-Koto** [xuejianxianzun/PixivBatchDownloader#118]
我是用Chrome Version 87.0.4280.88 (Official Build) (x86_64)，然后Powerful Pixiv Downloader v8.2.0。“Crawling”是可以的，可不能下载。让它下载后Chrome说“Failed - Network Error。“ 应该是跟PPD的程序有关系，因为只用Chrome或者用”Pixiv Toolkit“ 的程序就能下载，没问题。

请教有什么办法？我的中文不太行。如果能用英文来帮我这个忙最好。用中文给我回复我当然也非常感谢！：）

**Comment by xuejianxianzun** [comment]
My chrome version number is the same as yours, but I can download it. So I am not sure why.
As an alternative, you can click the "Copy URL" button after the crawl is complete. Then use other download software to download these files.

**Comment by Emperor-Koto** [comment]
Thanks for the quick response! Just to share the information, I tried the following things _all at once_, and had no luck:

-disable all other extensions
-disable Chrome's "Safe Browsing" (set to "no protection")
-allowed pop-ups and redirects
-added pixiv.net to the list of sites where access to insecure content was allowed
-disabled Bitdefender Shield

Despite throwing the kitchen sink at it, from what I can tell, it's no good!

I also tried copying and pasting the download URLs into "Free Download Manager" but all I could get were HTTP errors 414 and 403. I'm going to just try uninstalling Chrome and reinstalling it again to see if that works. :/

**Comment by xuejianxianzun** [comment]
Maybe you can try this:
Right-click on this extension icon and select "Manage Extensions".
Make sure the following two settings are enabled:
1. Automatically allow access to the following websites
2. Allow access to file URL

**Comment by Emperor-Koto** [comment]
UPDATE: I'm now using Big Sur 11.0.1, still getting the "Failed" message.

Thanks for the suggestion! "Access to the following websites" has always been allowed, but I don't see an option to "allow access to file URL." I've attached screenshots of the extension settings menu. I looked through the rest of the Chrome settings menu to see if I could give extensions permission to access file URLs elsewhere, but didn't find anything.

Is this normal or is something wrong?

<img width="681" alt="Screen Shot 2020-12-09 at 11 30 30 AM" src="https://user-images.githubusercontent.com/75638030/101665783-09e93480-3a13-11eb-9cda-78f04b9a1e73.png">
<img width="677" alt="Screen Shot 2020-12-09 at 11 39 24 AM" src="https://user-images.githubusercontent.com/75638030/101666089-651b2700-3a13-11eb-8f62-c1fd7bed672f.png">

**Comment by xuejianxianzun** [comment]
Your screenshot is normal. I guess your problem may be related to Mac, but I only have Windows, so I cannot test it.
Try using "Copy URL" now, sorry.

**Comment by Emperor-Koto** [comment]
Thank you for helping out anyway. I'll post here if I manage to find anything!

**Comment by Dazzler-Boy** [comment]
> Hello! I was running into the same issue, I'm not sure if the reason is the same, but for me, the extension runs into the network failed error when in incognito. Running it on a normal window will work fine! Just wanted to mention what worked for me since I noticed you also turned on Allow in incognito!

OMG MAN ! Thank you so so much. I was running in this issue for weeks and tried everything. This simple fix worked. God bless you !!
