### ISSUE TITLE
可否增加浏览量和点赞量数据？

### ISSUE THREAD

**Issue by cxl0812** [xuejianxianzun/PixivBatchDownloader#119]
现在系统中有收藏数据的获取，但如果有图片的浏览量和点赞量的话可能可以进行更进一步的分析

**Comment by xuejianxianzun** [comment]
你的需求是把浏览和点赞输出到csv和抓取结果里吗？这样也不错。
似乎没有多大必要添加到文件名里，你觉得怎么样

**Comment by xuejianxianzun** [comment]
最新版本里已经添加了这个功能
https://github.com/xuejianxianzun/PixivBatchDownloader/releases

**Comment by cxl0812** [comment]
非常感谢您为我们提供了这个功能，这将极大的方便我们的研究工作。还有一个小提议：现在可以根据收藏数量对图片进行筛选，得到质量较好的图片，但是并不能通过图片浏览量来对图像进行一个过滤。我们认为图片被浏览次数应该也是筛选图片的一个重要方面。当然我们可以在您添加浏览量数据的csv文件中进行提取过滤，但如果在下载时能有这么一个条件设置将会很便捷~再次感谢！

**Comment by cxl0812** [comment]
> 最新版本里已经添加了这个功能
> https://github.com/xuejianxianzun/PixivBatchDownloader/releases
非常感谢您为我们提供了这个功能，这将极大的方便我们的研究工作。还有一个小提议：现在可以根据收藏数量对图片进行筛选，得到质量较好的图片，但是并不能通过图片浏览量来对图像进行一个过滤。我们认为图片被浏览次数应该也是筛选图片的一个重要方面。当然我们可以在您添加浏览量数据的csv文件中进行提取过滤，但如果在下载时能有这么一个条件设置将会很便捷~再次感谢！

**Comment by cxl0812** [comment]
非常感谢您为我们提供了这个功能，这将极大的方便我们的研究工作。还有一个小提议：现在可以根据收藏数量对图片进行筛选，得到质量较好的图片，但是并不能通过图片浏览量来对图像进行一个过滤。我们认为图片被浏览次数应该也是筛选图片的一个重要方面。当然我们可以在您添加浏览量数据的csv文件中进行提取过滤，但如果在下载时能有这么一个条件设置将会很便捷~再次感谢！

**Comment by xuejianxianzun** [comment]
浏览次数比起收藏数量来说平时不太被人注意，比如我觉得5000收藏的作品质量不错，10000以上的质量很高，但是却想不起来对应的浏览数量大致是多少。
所以我觉得使用浏览次数进行筛选对普通用户意义非常有限。
你们是用它做什么研究的呢？你也可以下载这个扩展的 release，在某些地方进行硬编码，然后离线安装。

**Comment by cxl0812** [comment]
好的~谢谢您的回复与帮助。我们的想应用的场景是找到一些浏览量比较大的图片，然后通过这些图片的点赞量来为这些图片分配一个类似于质量的tag，或许我们可以研究一下您的release，考虑硬编码~谢谢

**Comment by cxl0812** [comment]
好的谢谢您的回复与帮助。我们的想应用的场景是找到一些浏览量比较大的图片，然后通过这些图片的点赞量来为这些图片分配一个类似于质量的tag，或许我们可以研究一下您的release，考虑硬编码谢谢

**Comment by xuejianxianzun** [comment]
推荐修改的节点是搜索 release 里的 `js/content.js` 里的两处 
```// 检查通过```
在其前面插入检查浏览量的代码，如果不符合条件就直接 `return`。
第一处是检查图片作品，第二处是检查小说作品，根据需要修改即可。

你也可以在项目源文件（`src` 目录）里修改，代码更加清晰，不过需要编译才能用。

**Comment by cxl0812** [comment]
好的~谢谢您的指导
