### ISSUE TITLE
下载下来的gif文件变成黑白的了

### ISSUE THREAD

**Issue by Haocen2004** [xuejianxianzun/PixivBatchDownloader#12]
![75763097](https://user-images.githubusercontent.com/25221696/61365662-a1983100-a8ba-11e9-9783-8d207ef1d37d.gif)
下载到的图片
以及原网址
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=75763097

**Comment by xuejianxianzun** [comment]
转换 gif 使用的那个库可能有问题，以前也发现过一些图片颜色有偏差，这个这么厉害的还是第一次见到。
不过我对图像转换并不了解，也没有修复这个问题的计划。
本下载器下载的动图默认是 ugoira  文件，用软件 honeyview 可以查看动图效果（不过文件大了可能帧率低
