### ISSUE TITLE
8月份下载的图片和今天下载的不一致

### ISSUE THREAD

**Issue by ExilsZ** [xuejianxianzun/PixivBatchDownloader#120]
8月份下载过一次，今天又下一次，去重软件没有检测出重复。检查发现8月份下载的一个文件EXIF信息包含了软件、拍摄日期，而今天下载的文件中少了这两项；有文件8月版显示 （Jpeg,YUV444,sRGB），此次下载少了一项变成（Jpeg,YUV444）。这是扩展保存文件处理方式发生了变化还是P站对图片的改动呢？
最后感谢大佬的扩展😀

**Comment by xuejianxianzun** [comment]
扩展保存方式没有变化，可能是画师重新上传了该图片。
你可以提供这个图片的 id 让我看看。

**Comment by ExilsZ** [comment]
其他画师的作品出现同样的差异，相比几个月之前下载的文件，今天下载的缺少了部分文件信息，不过我有一段时间没有下载，不清楚具体是什么时候出现的变化，只是今天才发现。不同时间下载的[图片提取链接](https://ws28.cn/f/4d2smc4d8ng)
![文件信息变化](https://user-images.githubusercontent.com/20733948/103434484-dd54c100-4c3c-11eb-802f-7422cf02d446.jpg)

**Comment by ExilsZ** [comment]
如果确认是P站官方对图片做了处理，那我就优先保留原先信息更多的文件

**Comment by xuejianxianzun** [comment]
这件事情有点奇怪。
https://www.pixiv.net/artworks/58485664
用下载器下载的和手动保存是一样的，所以不是下载器的问题。
为什么和你以前保存的不一样呢？看作品信息也不是画师重新上传了图片。那有可能是 pixiv 自己做了什么修改吧。

**Comment by xuejianxianzun** [comment]
我对比了以前下载过的一些文件，可以确认现在 pixiv 去掉了所有图片的一些 exif 信息，如软件、拍摄日期、评价 等。
被处理过的图片的体积基本都发生了变化，大部分的体积有所减小，但少数会变大一些。

**Comment by xuejianxianzun** [comment]
> 如果确认是P站官方对图片做了处理，那我就优先保留原先信息更多的文件

你尽量保留之前下载的吧，没做过修改。

**Comment by ExilsZ** [comment]
感谢解答
