### ISSUE TITLE
新版收藏夹没有给未分类作品添加tag的选项了？

### ISSUE THREAD

**Issue by white3angel** [xuejianxianzun/PixivBatchDownloader#121]

**Comment by xuejianxianzun** [comment]
有。到你的收藏页面使用
https://www.pixiv.net/bookmark.php

**Comment by white3angel** [comment]
旧版收藏好像已经无了，我这里打开旧版的直接就转到新页面了。。

**Comment by white3angel** [comment]
旧版收藏夹好像已经无了，我这里打开旧版的直接就转到新页面了。。

**Comment by xuejianxianzun** [comment]
看来旧版本要完成历史使命了。
不过每次改版我都是最后一批的，别人不说我就不知道。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
你可以试试刚才发布的安装包

**Comment by white3angel** [comment]
试了一下，可以正常使用了
