### ISSUE TITLE
Search and Cut/Paste Issues 

### ISSUE THREAD

**Issue by slelmir** [xuejianxianzun/PixivBatchDownloader#122]
Hi, it looks like if I download a file without setting a file name length limit and the name goes over the Windows Explorer file character limit, when I try to search tags in the file name and cut and paste them to other folders, I get an error where windows can't find the file anymore and I have to skip them. I can cut and paste and move the files without searching their names though, but I guess the file is corrupted in some way. I can't rename the file, can't put them in the recycle bin only permanently delete, and I think some of them didn't show any file size, just 0 bytes. I don't know how specific this issue is, but I guess I can only fix it by setting a file length limit when downloading? I wish I had a hard set length number, but I checked the file name lengths of the corrupted files and they come out to different lengths. Maybe it's because when the program saves the file names, it doesn't stop naming in the middle of a tag, but only after a full tag name? If I set a name limit, it might not save some of the tags I would like to see on the file. I don't think I want to mess with my PC and extend the name limit, so I guess I'll just have to live with that.

**Comment by xuejianxianzun** [comment]
hi!

If you use Windows and the latest version of the Chrome browser, when the file name is too long, Chrome will automatically truncate some characters at the end. In Explorer, the file can be operated normally.

If your browser does not automatically handle this problem, you can use the downloader settings to limit the length of the file name.

Both of these methods trim the complete file name and discard the part that exceeds the limit. This may cause some tags to be truncated or discarded. Too long tags is the main reason that the file name exceeds the limit, so if you want to keep the complete tags, it is difficult.

You can click "Export CSV file" after the crawl is complete, so you can get the complete file name. This method is not convenient, but it may be helpful to you. When you want to search for the complete tags, you can open the csv file to search and get the image id.

In Windows Explorer, the length of file name is limited to 256 characters. But in fact, the length that can be used is smaller. The file name length limit in the downloader is 200 by default.

**Comment by slelmir** [comment]
All right, thanks for the info! Setting the limit to 200 fixes the naming error and still gets most of the tags I want to keep.
