### ISSUE TITLE
原图png格式，在设置图片尺寸后命名异常。

### ISSUE THREAD

**Issue by zhaomma** [xuejianxianzun/PixivBatchDownloader#124]
PID87215216，图片尺寸设置为 普通 (1200*1200) 下载后扩展名为jfif并提示，
如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。

能否考虑在文件名中体现图片尺寸的选择，如普通44920385_p0_m，小图44920385_p0_s

**Comment by xuejianxianzun** [comment]
1. 命名异常的问题： 禁用其他有下载功能的浏览器扩展。
2. 目前没有这个打算，你可以自行在命名规则里添加这些标记字符。

**Comment by zhaomma** [comment]
> 1. 命名异常的问题： 禁用其他有下载功能的浏览器扩展。
> 2. 目前没有这个打算，你可以自行在命名规则里添加这些标记字符。

已尝试过只启用本扩展。也试过其他浏览器。都是一样情况。
下载JPG格式的其他尺寸，或原图下载，命名都没有问题，貌似只有在原图为PNG格式的时候，下载其他尺寸会有异常。
暂时没有其他电脑测试，如果您那测试正常烦请告知一声。
