### ISSUE TITLE
A small legacy naming request (or work around) 

### ISSUE THREAD

**Issue by hoopsie** [xuejianxianzun/PixivBatchDownloader#127]
I was wondering, for a niche situation, if there is a way to use the old naming rule for "User ID" in latest version, which was changed after version 4.0.5. 
Currently {user_id} changes it to "uid_2222222" but before it was simply "2222222". The legacy rule on 4.0.5 is {p_uid} which excludes the "uid_" part. 

[When I use the pixiv mobile app, I don't always download them from my bookmarks collection later. So i'm relying on the old naming rule which will replace files of the same name as I download the ones I missed from the app. I'm doing this for a chunk of my bookmarks before moving to the latest version. unfortunately most old versions have stopped working.]

If there is a way to edit the parameters myself then I would love to do that temporarily to exclude the "uid_" part in filename.

**Comment by xuejianxianzun** [comment]
If you use `{user_id}` and don't need `uid_`, you can turn off this setting:
`Add named tag prefix`

**Comment by hoopsie** [comment]
Wow, i guess i had that option on the whole time, but now I know what it means... sorry about that... I was trying so many things to figure it out x'D.
