### ISSUE TITLE
标签全部为undefined

### ISSUE THREAD

**Issue by Double-Lie** [xuejianxianzun/PixivBatchDownloader#128]
edge浏览器,本来是好的,同步到另一台电脑上就标签全部为undefined,卸载重装亦是如此,还请大佬帮忙看看,谢谢

**Comment by Double-Lie** [comment]
还请大佬帮忙看看

**Comment by Double-Lie** [comment]
还请大佬帮忙看看,.谢谢

**Comment by xuejianxianzun** [comment]
如果您之前没有安装过这个扩展，那么当您新安装了 9.4.0 版本之后，下载器的文本可能无法正常显示。如果你遇到了这个问题，请按照下面的步骤修复：
在 Pixiv 的页面上按 F12，然后按 Esc，会显示控制台（Console）。把下面的代码粘贴进去，按 Enter 执行：
localStorage.setItem('xzSetting',{"userSetLang":"auto"})
然后刷新页面，问题就会解决。
在下个版本里会修复这个问题，你也可以现在就离线更新到最新版本。

**Comment by Double-Lie** [comment]
大佬请问我怎么离线安装谢谢

**Comment by Double-Lie** [comment]
release下载下来了不知道放哪

**Comment by SmiMi** [comment]
然而
localStorage.setItem('xzSetting',{"userSetLang":"auto"})
并没有解决

**Comment by xuejianxianzun** [comment]
> 然而
> localStorage.setItem('xzSetting',{"userSetLang":"auto"})
> 并没有解决

那你执行之后刷新页面，控制台有什么报错信息吗（右侧为 content.js 的）？
如果说什么 json token 的，那就是这次的错误。你重新执行一下试试，不行的话离线更新到最新版吧

**Comment by xuejianxianzun** [comment]
```
localStorage.setItem('xzSetting',`{"userSetLang":"auto"}`)
```
之前发的代码，反引号被 github 转义了。已更新。

**Comment by UNSCs117** [comment]
emmmm在9.7.3里还是这样子啊。。。目前还没试过手动加代码，但是无论在线更新还是离线更新，新版本的都会变成undefined，但是之前安装的旧版本(7.4.0)就没问题
