### ISSUE TITLE
can work on android kiwi browser?

### ISSUE THREAD

**Issue by youling257** [xuejianxianzun/PixivBatchDownloader#129]
android kiwi browser support chrome extension, how it work on android kiwi?

**Comment by youling257** [comment]
![Screenshot_20210219-140544](https://user-images.githubusercontent.com/16304724/108464798-ca18b600-72bb-11eb-9a3f-ef9e1ab53e92.png)

it stop at convert file.

**Comment by xuejianxianzun** [comment]
There may be some problems when using this extension on the kiwi browser, such as downloading stuck.
I recommend using the yandex browser, which can also use this extension.
It takes a certain amount of time to convert the file, but if it takes too long, it may be abnormal.

**Comment by xuejianxianzun** [comment]
看起来你是中国人呀，我也是，没必要装了（
