### ISSUE TITLE
excluding tags doesn't work

### ISSUE THREAD

**Issue by komaedalove** [xuejianxianzun/PixivBatchDownloader#13]
Including or excluding tags doesn't work. I blocked a tag and it still shows up.

包括和排除标签的功能不能用。我把某个标签遮了，可是有那个标签的发帖还是会出现

**Comment by xuejianxianzun** [comment]
On some pages, such as the page that searches for tags, it will take effect at the time of download.
Before downloading, if the top information does not display the setting of "Including or excluding tags", it does not take effect. It will take effect when the download starts.
If this setting is shown at the top, but it doesn't work, please let me know the details.

**Comment by xuejianxianzun** [comment]
I'm going to make some improvements in the near future, on the search tag page, it will take effect before downloading.

**Comment by komaedalove** [comment]
Thank you very much :)
