### ISSUE TITLE
chrome扩展失效

### ISSUE THREAD

**Issue by SmiMi** [xuejianxianzun/PixivBatchDownloader#130]
Chrome版本 88.0.4324.182（正式版本） （64 位）
Downloader版本：9.5.2

操作步骤：
1. 升级到9.5.2版本
2. 重启浏览器，打开Pixiv并登陆
3. 扩展下载页面均显示undifined
2. 在控制台输入localStorage.setItem('xzSetting',{"userSetLang":"auto"})，还是显示undifined
3. 移除扩展，重新安装9.5.2版本
4. 重启浏览器，打开Pixiv
5. 扩展下载页面无法打开

**Comment by xuejianxianzun** [comment]
localStorage.setItem('xzSetting',`{"userSetLang":"auto"}`)

**Comment by xuejianxianzun** [comment]
```
localStorage.setItem('xzSetting',`{"userSetLang":"auto"}`)
```

**Comment by xuejianxianzun** [comment]
发现问题了，我发在github上的代码，反引号被转义了。请执行第二个代码块里的代码。

**Comment by SmiMi** [comment]
执行第二个代码块解决了，谢谢
