### ISSUE TITLE
Exporting Crawl Results not working

### ISSUE THREAD

**Issue by Aergernis** [xuejianxianzun/PixivBatchDownloader#131]
When trying to export crawl results, an error occur

`https://www.pixiv.net/en/users/973675/following
Stacktrace
js/content.js:4343 (Anonyme Funktion)`

**Comment by xuejianxianzun** [comment]
Hello!
1. What version of your downloader?
2. Does this problem exist on all pages? Have this problem before?
3. Are there more error messages about "content.js"?
4. When you export, how many crawl results are there?

**Comment by xuejianxianzun** [comment]
I used the URL you provided for testing and crawled 353,098 files (results), and failed to export the crawled results.
The reason is that the string length exceeds the browser limit. I am thinking how to solve this problem.

**Comment by xuejianxianzun** [comment]
You can install the latest version offline:
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
Then close the previously installed version, refresh the page, and try to export again.

**Comment by Aergernis** [comment]
Wow, that was fast i didn't even had time to replay.
It's working now with so many Items to export. Also importing then seams to work correctly (the correct number of Imports is shown). So the Issue can be closed.
Thank you very much.
