### ISSUE TITLE
請問可否新增一項將已刪除或已鎖定的圖片篩選出來的功能?

### ISSUE THREAD

**Issue by cpio123** [xuejianxianzun/PixivBatchDownloader#132]
就是將收藏內被原繪師刪除或鎖定的圖片篩選出來
這樣將來要整理的時候能比較方便
不知道這種功能有無解法?
謝謝!!

**Comment by xuejianxianzun** [comment]
抓取到被删除的图片时，下载器会在日志输出提示，如：
```
35042974: 404 not found
42289515: 404 not found
47795400: 404 not found
```
被锁定的图片应该也会一样。你试试吧。

**Comment by cpio123** [comment]
> 抓取到被删除的图片时，下载器会在日志输出提示，如：
> 
> ```
> 35042974: 404 not found
> 42289515: 404 not found
> 47795400: 404 not found
> ```
> 
> 被锁定的图片应该也会一样。你试试吧。

這個方式我知道 
不過這樣需要從收藏庫裡面一個一個翻出來刪掉有點耗時
所以想請問有無其他更便利的方法
畢竟可能隔個幾天就有一堆圖被刪除或鎖住了 這樣刪有點累 ((我有點強迫症XD

**Comment by xuejianxianzun** [comment]
被锁定的图片是无法从pixiv的收藏库里删除的。
难道你的意思是从你下载的本地文件里删除？但是下载器无法操作本地硬盘上的文件。
所以我有点迷惑。

**Comment by cpio123** [comment]
> 被锁定的图片是无法从pixiv的收藏库里删除的。
> 难道你的意思是从你下载的本地文件里删除？但是下载器无法操作本地硬盘上的文件。
> 所以我有点迷惑。

抱歉 我用詞不精準
應該說pixiv收藏庫裡的圖片如果被原繪師刪除或鎖定的話
我看到後會"取消收藏" ((不喜歡收藏庫裡有空白的圖片
所以才會提問有沒有方法可以便利的將這些圖片篩選出來 方便日後取消收藏
給您造成困擾還真是不好意思!!

**Comment by xuejianxianzun** [comment]
现在大部分用户的收藏库都是新版了，里面被删除或锁定的图片是无法编辑的，也就无法取消收藏。
我不清楚旧版的收藏库是否能取消。不过你的需求似乎是要把它们筛选（汇总）出来，便于批量取消收藏？现在下载器无法实现。

**Comment by cpio123** [comment]
> 现在大部分用户的收藏库都是新版了，里面被删除或锁定的图片是无法编辑的，也就无法取消收藏。
> 我不清楚旧版的收藏库是否能取消。不过你的需求似乎是要把它们筛选（汇总）出来，便于批量取消收藏？现在下载器无法实现。

我是用以下方式取消收藏被刪除的圖片 
1.將收藏庫裡被刪除的圖片打勾
![擷取](https://user-images.githubusercontent.com/63335004/109381766-31b3ae80-7917-11eb-9a83-b582b791bb6a.PNG)
2.收藏庫裡每頁最下面有個取消收藏
![擷取1](https://user-images.githubusercontent.com/63335004/109381777-3f693400-7917-11eb-9f05-336d2080c9b8.PNG)
這樣圖片就能取消收藏了

然後目前下載器無法實現篩選功能我了解了 感謝您的解答!!

**Comment by xuejianxianzun** [comment]
不客气~
你的收藏库还是旧版的，你可以进入你的主页，里面的“收藏”选项卡就是新版的。Pixiv 正在逐步把所有用户的收藏页面切换到新版。
如果收藏的作品比较多，可能每天都会新增一些被删除的，所以不要太有强迫症了（笑
