### ISSUE TITLE
为每个作品创建单独的文件夹设置为1时无效

### ISSUE THREAD

**Issue by SmiMi** [xuejianxianzun/PixivBatchDownloader#133]
版本号：9.7.0

操作：
1. 在我的收藏中抓取
2. 设置命名规则：{user}/{title}{id}
![image](https://user-images.githubusercontent.com/6406966/109328574-8f52e700-7894-11eb-964e-dabb56c4650f.png)

2. 当"为每个作品创建单独的文件夹"设置为0时，每个作品都可保存至文件夹
![image](https://user-images.githubusercontent.com/6406966/109328695-b4475a00-7894-11eb-9253-9a131bed8bc1.png)

3. 当"为每个作品创建单独的文件夹"设置大于0时，有多图的作品都没有创建文件夹
![image](https://user-images.githubusercontent.com/6406966/109328655-a7c30180-7894-11eb-9002-71d198b4fb27.png)

**Comment by xuejianxianzun** [comment]
确实存在问题，请更新到 9.7.1 版本看问题是否解决。

**Comment by SmiMi** [comment]
> 确实存在问题，请更新到 9.7.1 版本看问题是否解决。

谢谢，已经解决了。
