### ISSUE TITLE
每打开一个网页显示两个报错，下载器界面没有文字说明

### ISSUE THREAD

**Issue by Nagisa-Koworu** [xuejianxianzun/PixivBatchDownloader#134]
postDateStart: Invalid value
postDateEnd: Invalid value

**Comment by xuejianxianzun** [comment]
这是因为“设置投稿时间”的起止时间有误，你可以打开这个选项，设置正确的时间。然后可以关闭这个选项，应该不会提示错误了。
在以后的版本里，发生这种情况时下载器会把错误的值替换为默认值，就不会出现这个错误了。

**Comment by xuejianxianzun** [comment]
你也可以离线更新到最新版本试试
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
