### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Nagisa-Koworu** [xuejianxianzun/PixivBatchDownloader#135]
抓取小说是显示：抓取完毕，但没有找到符合筛选条件的作品。
然而我没有任何限定
图片下载页下载数量设置为-1时会变成100个，这太少了

**Comment by xuejianxianzun** [comment]
1. 请把你当时抓取的页面网址发过来
2. 在某些页面里有最多页数限制，这是 Pixiv 的限制，下载器也不能突破限制。

**Comment by Nagisa-Koworu** [comment]
第二个问题已解决，9.7.2就已经解决了
第一个问题在各种小说页面都存在。

**Comment by xuejianxianzun** [comment]
在小说页面测试没有发现问题。
请使用最新版chrome，在下载器的设置里重置设置，然后尝试抓取。

**Comment by xuejianxianzun** [comment]
在小说详情页面里发现了这个问题，向前向后抓取无效，这是下载器内部的错误，在最新版本里已经修复
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
