### ISSUE TITLE
文件名称变成 UUID 后缀名是 jfif-其他扩展程序的影响

### ISSUE THREAD

**Issue by Stake18** [xuejianxianzun/PixivBatchDownloader#136]
近日出现下载的图片全部变成文件名为类似 “57d2f23d-726a-4c45-b879-ac25bd4bb284.jfif” 的jiff文件，已确认没有其他接管下载的扩展

**Comment by xuejianxianzun** [comment]
确认一下你的浏览器是不是Chrome浏览器最新版，有哪些其他扩展？
如果找不到原因可以加群让我看看。
