### ISSUE TITLE
以 . 开头的文件夹名称导致下载出错-Linux 隐藏文件夹

### ISSUE THREAD

**Issue by closetool** [xuejianxianzun/PixivBatchDownloader#137]
linux下以`.`开头的文件夹是隐藏文件夹, 将R18文件目录设为隐藏文件夹时, 文件下载完后卡住

**Comment by closetool** [comment]
![Uploading image.png…]()

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/110198028-72b54100-7e8a-11eb-802a-315b21892f2f.png)

**Comment by xuejianxianzun** [comment]
Chrome 的 downloads API 要求文件名**开头和结尾都不能使用 `.`**如果发生这种情况，Chrome 就会产生一个错误提示，并且这个文件不会被保存到硬盘上。这是 Chrome 的限制。
下载器会把开头和结尾的 `.` 替换为全角的 `．｀。（r18文件夹这里没有覆盖到，之后我会修复。）
目前看来你没办法下载到 `.` 开头的隐藏目录里。

**Comment by xuejianxianzun** [comment]
现在你可以手动把这个 `.` 去掉或者换成其他字符来继续下载。

**Comment by closetool** [comment]
多谢大佬
