### ISSUE TITLE
下载器的标签页/选项卡可以只允许鼠标点击进行切换吗？

### ISSUE THREAD

**Issue by UNSCs117** [xuejianxianzun/PixivBatchDownloader#138]
在pixiv网站打开PixivBatchDownloader的界面之后，上面的“抓取”“下载”“其他”三个标签能否变成仅在用户点击这个标签之后才会打开这个标签呢？现在的只要鼠标移过去就会打开那个标签的话，强迫症很难受，对于一直监视下载进度的我也是很难受。。。如果工作量大的话不该也没事，就是一个小的建议啦

**Comment by xuejianxianzun** [comment]
最新版本的下载器添加了此设置（是隐藏设置），目前你可以离线安装来使用：
https://github.com/xuejianxianzun/PixivBatchDownloader/releases

----------

下载器的选项卡可以用鼠标点击和鼠标经过两个事件来进行切换。

有的用户想要**只用鼠标点击**切换，不想用鼠标经过来切换。对此增加了一个隐藏设置：

`mouseEnterSwitchTabbar`

- 默认值为 `true`，允许鼠标经过切换选项卡。
- 如果为 `false`，不允许鼠标经过切换选项卡。

**使用方法**：在页面上输入口令 `mouseenter` 即可切换该选项的开启与关闭。
