### ISSUE TITLE
多图作品下方小图预览失效或许能修复下？

### ISSUE THREAD

**Issue by Franinc** [xuejianxianzun/PixivBatchDownloader#140]
![1112344](https://user-images.githubusercontent.com/26399054/111558820-77eb8780-87ca-11eb-9d4f-24a46686b356.jpg)
![22334559](https://user-images.githubusercontent.com/26399054/111559148-f9dbb080-87ca-11eb-9cc2-b3bd03fb4db5.jpg)
如图，加载失败的图片：
`https://i.pximg.net/c/250x250_80_a2/custom-thumb/img/2021/03/03/06/29/53/88179809_p1_custom1200.jpg`
我才发现官方有原版的多图预览，点开按钮提取的图2预览新地址（权限更严格，直接打开图片是403）：
`https://i.pximg.net/c/128x128/img-master/img/2021/03/03/06/29/53/88179809_p1_square1200.jpg`
来自：[artworks/88179809](https://www.pixiv.net/artworks/88179809)

**Comment by xuejianxianzun** [comment]
感谢你提出的解决方法，在稍后发布的新版本里我会应用这个修改。不过应用商店里还需要等待审核。
