### ISSUE TITLE
希望下载图片的命名规则限制可以宽松一些

### ISSUE THREAD

**Issue by a1oyss** [xuejianxianzun/PixivBatchDownloader#141]
`private checkNamingRule() {
    if (settings.userSetName.includes('{id}') || (settings.userSetName.includes('{id_num}') && settings.userSetName.includes('{p_num}'))) {
    }
  }`
感觉后面的id_num和p_num可以不用同时存在，之前使用的{bmk}_{title}/{title}_{p_num}规则也没有出现什么问题，现在就导致用以前规则下载不了图片。

**Comment by xuejianxianzun** [comment]
这个规则是为了防止重名，因为经常有人重名了然后来问我，所以最近才强制加上了这个限制。
你的这个规则因为 bmk 和 title 组合起来一般不会重名，所以问题不大。但是很多用户并没有这样的意识，甚至有人只用一个 title 做命名标记然后来找我。加上这个限制和提示会减少他们犯错的情况。
所以这个限制我是不打算修改的，你可以下载离线安装包，注释掉调用此函数的代码来使用（此调用应该只有一处）。
