### ISSUE TITLE
能否加个取消重试下载的判断

### ISSUE THREAD

**Issue by Franinc** [xuejianxianzun/PixivBatchDownloader#142]
你好，有时候因为某些原因想取消下载（比如手滑点错/图片以前下载过），点“确认下载”弹窗的取消按钮后，拓展会无限次数重试，也就无限次弹窗。
![Snipaste_2021-04-02_22-04-38](https://user-images.githubusercontent.com/26399054/113423364-ebafa600-9400-11eb-8ed3-1a47a7e8d16d.jpg)

**Comment by xuejianxianzun** [comment]
这个难以判断，因为用户也可能点错了，他其实还想要重试呢。
你这种情况就点保存吧，一张图而已，以后想起来了去删掉就行了。
ps：建议你在浏览器设置里关闭下载前确认弹窗，否则批量下载会弹出很多弹窗
ps2：建议使用 Chrome 或 Edge 浏览器
