### ISSUE TITLE
图片下载问题

### ISSUE THREAD

**Issue by kkvsda** [xuejianxianzun/PixivBatchDownloader#143]
有时候下载的图片是损坏的，只会显示一点，换了几次vpn下载都有这个问题，不知道是什么情况。
还有提取URL给idm和迅雷现在也下载不了，请问是有什么限制了么？
求解，谢谢。

**Comment by xuejianxianzun** [comment]
图片损坏是你的网络问题。
idm和迅雷下载不了？不知道p站有没有加什么新的限制，你用其他软件下就和下载器没有关系了。

**Comment by kkvsda** [comment]
试过好几个下载器都不行，显示http403，应该是p站的问题

**Comment by kkvsda** [comment]
> 图片损坏是你的网络问题。
> idm和迅雷下载不了？不知道p站有没有加什么新的限制，你用其他软件下就和下载器没有关系了。

换了几个下载器还是不行，显示http403，应该是p站的限制了
