### ISSUE TITLE
能否有个一键私密收藏功能？

### ISSUE THREAD

**Issue by fjqingyou** [xuejianxianzun/PixivBatchDownloader#144]
现在要私密收藏。还需要跳转一次界面，能否提供个一键支持？

**Comment by xuejianxianzun** [comment]
![QQ截图20210408102955.png](https://i.loli.net/2021/04/08/wiU7Nuv4DOJghzF.png)
不需要跳转啊，你可以点图片下方扩展菜单来进行私密收藏。
如果你点击下载器的五角星来收藏，可以先在下载器设置里，“收藏设置”设为“非公开”，这样点五角星都是私密收藏。
