### ISSUE TITLE
{tags_transl_only} New file name writing system?

### ISSUE THREAD

**Issue by slelmir** [xuejianxianzun/PixivBatchDownloader#145]
Did something change with how {tags_transl_only} works? I think it used to write all the tags in a post:
 1. japanese if the tag was only in japanese
 2. english instead of the japanese if both are available
 3. english if only english was available
It looks now like it only writes the english instead of the japanese if they're both available. It seems like now the only way to get all the tags is with {tags_translate}, which lists all the tags plus the translations. But with the 200 character file limit, I wouldn't be able to get most of the tags. 

I just double checked, and I'm pretty sure that it used to work that way, I would be able to get a file name with combinations of japanese and english like this:
55351678_p0 R-18,creation,original,large breasts,pubic hair,youkai,不可殺伊,large penis,shota,oneshota
If the file naming system for this could be reverted or if there's a workaround, please let me know, thank you!

**Comment by slelmir** [comment]
And then I also noticed that Ugoira posts file names are not written with "_p0" at the end of the id # by default. Which means that now I have to write it myself in the naming rule box, and that I actually have to download Ugoiras and pictures separately. Is there a simpler way to just download them all at once like before?

**Comment by slelmir** [comment]
It would just make it easier because then I could search my saved files by "p0" in Windows, and it would show me the number of works and I could compare it to the number pixiv shows when you search a tag, and compare to see how many I've saved.

**Comment by slelmir** [comment]
I did download Python, and it said something about being able to have file names that exceed the 200 character limit, but I tried it and it didn't work. Do you know anything about that? I'd love to have all the tags, translated and original language.

**Comment by xuejianxianzun** [comment]
1. There is a bug in {tags_transl_only}, I have fixed it and wait for the web store to review it. It will become the same as before.
2. Ugoira and Novel do not have a serial number, so there will be no `p0` for serial number. There may have been `p0` at some time before, but there is no more. If you want to count the number of downloads, you may need other methods.
3. I have also used Python's "Remove File Name Length Limitation". It seems to be useless for Windows Explorer.

**Comment by slelmir** [comment]
Ok cool, thank you! Do you know when the program will update the {tags_translate_only} after it's reviewed? Or will the program show that it's been updated in a message when I start it up? 
Ok, it's a little bit of a hassle to add in the p0, but it doesn't change much.
Darn, I wonder what situation the Python file limitation thing is good for then?
Thanks for answering, and thanks for your work!

**Comment by xuejianxianzun** [comment]
A new version 9.9.2 has been released in the Web store. You can check the installed version:
URL: `chrome://extensions/`
I don't know much about Python. Sorry.
