### ISSUE TITLE
插件右上角的放大镜有没有可能自定义在哪个角呀

### ISSUE THREAD

**Issue by SetoKaiba** [xuejianxianzun/PixivBatchDownloader#147]
插件右上角的放大镜有没有可能自定义在哪个角呀，比如说左上角，现在和pixiv downloader ex的放大镜重叠了，pixiv downloader ex的这种开iframe的有些时候还是会更方便，比如说动图会动起来，长图会显示得更好，漫画什么的有时候更方便。

**Comment by xuejianxianzun** [comment]
从 10.0.1 版本开始可以在设置里将其显示在左上角。
目前你可以离线安装，或者等待应用商店更新。

**Comment by SetoKaiba** [comment]
好的，谢谢。
