### ISSUE TITLE
無法下載

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#148]
![未命名](https://user-images.githubusercontent.com/82942914/115543557-142a1200-a2d4-11eb-9e14-aac1910571d6.png)
我不太清楚為甚麼按了下載後最上面出現工作開始就沒了，第一次用求解。

**Comment by xuejianxianzun** [comment]
看你是没有登录，先登录吧。

**Comment by e1e1111e1e** [comment]
謝謝
