### ISSUE TITLE
图片和动图都下载不了~

### ISSUE THREAD

**Issue by 664873568** [xuejianxianzun/PixivBatchDownloader#149]
![动图抓取失败](https://user-images.githubusercontent.com/50593310/116325564-07864c00-a7f5-11eb-8777-8a309aac6ee6.png)

前面的获取转换都没问题就是到调用浏览器下载时没反应（使用的QQ浏览器最新版）
试过旧版的插架是可以正常下载的https://greasyfork.org/zh-CN/scripts/24252

另外下载了谷歌浏览器的最新版测试是可以正常下载的
（两眼懵逼~搞不懂情况）

**Comment by xuejianxianzun** [comment]
为什么用 QQ 浏览器？这就是个垃圾
