### ISSUE TITLE
能不能增加一个下载图片简介的功能

### ISSUE THREAD

**Issue by Nagisa-Koworu** [xuejianxianzun/PixivBatchDownloader#151]
有些画师会把插图故事写在简介里，能不能在抓取的同时将这些简介收集起来

**Comment by Nagisa-Koworu** [comment]
这些实际上都不是很重要，可以每个作者ID一个TXT这样，里面存作品ID、标题、简介、TAG
和现在小说的正文之前的那段差不多

**Comment by 1286604964** [comment]
这个需求我也有，具体简介保存需求其实和fanbox下载器一样就可以。
希望您可以考虑一下。

**Comment by lybb001** [comment]
同求作品简介保存功能，简介和图片保存在一起方便查看就行

**Comment by Nagisa-Koworu** [comment]
> 这个需求我也有，具体简介保存需求其实和fanbox下载器一样就可以。
> 希望您可以考虑一下。

fanbox下载器就支持？

**Comment by xuejianxianzun** [comment]
> 这些实际上都不是很重要，可以每个作者ID一个TXT这样，里面存作品ID、标题、简介、TAG
> 和现在小说的正文之前的那段差不多

你在抓取之后导出csv文件，里面就有除了简介以外的数据。

**Comment by xuejianxianzun** [comment]
> 同求作品简介保存功能，简介和图片保存在一起方便查看就行

简介怎么保存是个问题。

1. 如果每个作品分别建立一个txt文件保存简介，那么 txt 文件的数量会很多。
2. 如果每个画师的作品简介集合到一个txt文件里，文件数量会少一些，不过查找简介不太方便。
3. 保存在 csv 文件里，一批任务只需要导出一个 csv 文件。

不过后两个方式也有缺点，由于图片的简介是集中存放的，如果把下载的图片分散到多个文件夹里，简介文件没办法跟文件图片一样分别移动。

**Comment by xuejianxianzun** [comment]
> 同求作品简介保存功能，简介和图片保存在一起方便查看就行

已经在做了，现在只是保存了简介，但是看上面的需求，感觉以后肯定有人要求再往里面加这加那的，我在想要不干脆把常用的数据全塞进去算了

**Comment by xuejianxianzun** [comment]
做的差不多了，下图的效果：
![20210829175822.jpg](https://i.loli.net/2021/08/29/DzptvIBRPiNfmQF.jpg)
![20210829175835.png](https://i.loli.net/2021/08/29/zshc7IB2Uo8DJM5.png)

**Comment by xuejianxianzun** [comment]
没人反馈啊，现在可以离线安装新版本进行尝试。过段时间会更新到谷歌商店。

**Comment by cpuopt** [comment]
好家伙，直接做成导入数据库得了:stuck_out_tongue_closed_eyes:

**Comment by xuejianxianzun** [comment]
> 好家伙，直接做成导入数据库得了😝

我也很无奈啊

**Comment by Nagisa-Koworu** [comment]
> 没人反馈啊，现在可以离线安装新版本进行尝试。过段时间会更新到谷歌商店。

不好意思，一直没上来，这个效果基本上就是我设想的。

**Comment by lybb001** [comment]
![无标题](https://user-images.githubusercontent.com/89398781/134767685-5a75f3fa-d829-48fa-9a41-80084a533cb8.jpg)
![无标题2](https://user-images.githubusercontent.com/89398781/134767689-20f1fb2e-80d1-4e9d-b0e1-757a6b037fc3.jpg)
感谢添加功能！但是文字格式跟你的效果不一样。很挤，没有换行。

**Comment by Reinford0** [comment]
@lybb001 该升级win10了，7以下的系统用notepad打开是不会换行，要么换打开方式比如word

**Comment by xuejianxianzun** [comment]
> ![无标题](https://user-images.githubusercontent.com/89398781/134767685-5a75f3fa-d829-48fa-9a41-80084a533cb8.jpg)
> ![无标题2](https://user-images.githubusercontent.com/89398781/134767689-20f1fb2e-80d1-4e9d-b0e1-757a6b037fc3.jpg)
> 感谢添加功能！但是文字格式跟你的效果不一样。很挤，没有换行。

因为下载器下载的小说的换行方式是 `\n`，win7 的记事本不支持。你可以换个软件打开试试。或者使用转换工具（linux换行转windows换行）对小说进行转换。

**Comment by lybb001** [comment]
> @lybb001 该升级win10了，7以下的系统用notepad打开是不会换行，要么换打开方式比如word

这样啊，我是好多旧游戏不兼容就没更新win10

> > ![无标题](https://user-images.githubusercontent.com/89398781/134767685-5a75f3fa-d829-48fa-9a41-80084a533cb8.jpg)
> > ![无标题2](https://user-images.githubusercontent.com/89398781/134767689-20f1fb2e-80d1-4e9d-b0e1-757a6b037fc3.jpg)
> > 感谢添加功能！但是文字格式跟你的效果不一样。很挤，没有换行。
> 
> 因为下载器保存的 txt 文件的换行方式是 `\n`，win7 的记事本不支持。你可以换个软件打开试试。或者使用转换工具（linux换行转windows换行）对小说进行转换。

那没办法了，Windows直接打开有日文乱码，虽然找到了转换工具，但感觉还不如手动复制。

**Comment by xuejianxianzun** [comment]
> > @lybb001 该升级win10了，7以下的系统用notepad打开是不会换行，要么换打开方式比如word
> 
> 这样啊，我是好多旧游戏不兼容就没更新win10
> 
> > > ![无标题](https://user-images.githubusercontent.com/89398781/134767685-5a75f3fa-d829-48fa-9a41-80084a533cb8.jpg)
> > > ![无标题2](https://user-images.githubusercontent.com/89398781/134767689-20f1fb2e-80d1-4e9d-b0e1-757a6b037fc3.jpg)
> > > 感谢添加功能！但是文字格式跟你的效果不一样。很挤，没有换行。
> > 
> > 
> > 因为下载器保存的 txt 文件的换行方式是 `\n`，win7 的记事本不支持。你可以换个软件打开试试。或者使用转换工具（linux换行转windows换行）对小说进行转换。
> 
> 那没办法了，Windows直接打开有日文乱码，虽然找到了转换工具，但感觉还不如手动复制。

你可以安装个轻量级的文本编辑器代替记事本来打开txt文件，例如 Notepad2，Notepad++ 等。
