### ISSUE TITLE
希望增加按下载大小筛选的功能

### ISSUE THREAD

**Issue by cHEnB0** [xuejianxianzun/PixivBatchDownloader#152]
如果图片大小小于2M，就跳过之类的功能。
还有默认下载位置可以修改吗？或者调用第三方下载工具(例IDM 啥的

**Comment by xuejianxianzun** [comment]
按下载大小筛选，这个功能有啊，在“其他”选项卡里，文件体积设置。你想跳过小于 2m 的，可以设置最小值为 2m，最大值随意。
默认下载位置你只能去浏览器设置里改。调用idm那也需要你浏览器插件支持。
