### ISSUE TITLE
能否支持导入到aria2下载

### ISSUE THREAD

**Issue by xiao-gy** [xuejianxianzun/PixivBatchDownloader#154]
Rt.
就是希望能够加入一个使用aria2下载的功能

**Comment by xuejianxianzun** [comment]
请参考 readme 底部的另一个下载器。
本下载器没有添加这个功能，是因为本下载器所下载的小说和动图是转换成 blob 对象然后保存到本地的，如何把 blob 对象数据发送给 aria2 下载，对我来说是个问题。

**Comment by xiao-gy** [comment]
哦哦，谢谢解释
