### ISSUE TITLE
使用命名规则为每个作品创建单独的文件夹导致每张图片创建一个文件夹

### ISSUE THREAD

**Issue by tio-plato** [xuejianxianzun/PixivBatchDownloader#155]
文档中说明
> 如果你使用命名规则作为目录名字，那么命名规则不要使用 {p_num}，它会导致每个图片都单独建立一个目录。可以考虑使用 {id} 替换 {p_num}

但是实际上即使仅使用`{id}`作为命名规则，也会导致每张图新建一个文件夹

**Comment by xuejianxianzun** [comment]
使用 id 作为命名规则，不是”每张图新建一个文件夹”，而是每个 id 建立一个文件夹。（一个 id 可能包含多个图片）（如果你下载的作品只有一张图片，可能看起来像是每张图新建一个文件夹。）
如果你使用了 id_num，才是每个图片一个文件夹。
如果你对此有异议，请提供你的设置截图，下载的作品 id。

**Comment by tio-plato** [comment]
命名规则：
```
{user}_{user_id}_{task_date}/{type}/{date}_{title}_{id}
```
![image](https://user-images.githubusercontent.com/60922756/120641325-0e644680-c4a6-11eb-9e08-038168f8c8d4.png)
下载结果：每张图单独一个文件夹
![image](https://user-images.githubusercontent.com/60922756/120641479-39e73100-c4a6-11eb-8312-57a9f41a2f75.png)

尝试仅使用{id} 作为命名规则，并换了另一个作品抓取：
![image](https://user-images.githubusercontent.com/60922756/120641697-7ca90900-c4a6-11eb-80bf-77821b067a06.png)
![image](https://user-images.githubusercontent.com/60922756/120641722-87fc3480-c4a6-11eb-9fef-dfe95f7418ac.png)
可以看到还是每张图片一个文件夹。

和下载作品无关，本次测试用的是https://www.pixiv.net/users/21047020 画师的最新两个作品，不过之前测试过多个不同画师不同作品结果一致

**Comment by tio-plato** [comment]
> 使用 id 作为命名规则，不是”每张图新建一个文件夹”，而是每个 id 建立一个文件夹。（一个 id 可能包含多个图片）（如果你下载的作品只有一张图片，可能看起来像是每张图新建一个文件夹。）
> 如果你使用了 id_num，才是每个图片一个文件夹。
> 如果你对此有异议，请提供你的设置截图，下载的作品 id。

您好，已提供设置和下载结果截图，请问可否确认一下是我设置的问题还是代码的问题
@xuejianxianzun
