### ISSUE TITLE
gif太多了好像会爆内存

### ISSUE THREAD

**Issue by xzxz520cs** [xuejianxianzun/PixivBatchDownloader#156]
昨天在下这位 https://www.pixiv.net/users/1167548 的图时内存占用越来越高，满了之后页面就崩溃了。

**Comment by xuejianxianzun** [comment]
这是因为下载的动图较多，动图转换时占用的内存较多，而且释放比较慢。目前没有好的办法，如果内存占用过高，或者页面崩溃，清关闭此页面，然后重新打开，下载器可以续传，继续未完成的下载。

**Comment by Nagisa-Koworu** [comment]
有没有什么办法增加Edge允许扩展占用的内存，我64G内存连四分之一都用不掉就跳内存不足了
