### ISSUE TITLE
大批量下载，从插件到实际存储的速度较慢

### ISSUE THREAD

**Issue by zjqwtm543** [xuejianxianzun/PixivBatchDownloader#157]
直接抓取画师的所有画作，插件UI中看到单个作品的下载进度条是满的。
但是到浏览器的下载界面显示 进度条满，速度仅有10K不到 且任务未完成，起码要几分钟后，近似理解为原画本身的内容以这个速度下载完的时间过去后才显示完成。

浏览器是vivaldi4.0.2312.33内核似乎基于Chrome/91.0.4472.114

**Comment by Nagisa-Koworu** [comment]
电脑到站点不够通畅，建议你自己优化一下网络

**Comment by xuejianxianzun** [comment]
下载器先下载文件（下载器的进度走完），然后浏览器保存文件（浏览器的下载管理里面会出现这个任务）。
如果下载器进度慢，是网络问题。如果浏览器保存文件很慢，那就不常见了，可能是你硬盘负载太高了之类的问题？

**Comment by zjqwtm543** [comment]
下载器进度很快，基本是后者的现象，有点像缓存爆了的现象。
现在做了三步处理，浏览器的chrome://settings的安全部分关掉了安全浏览
> 下载器先下载文件（下载器的进度走完），然后浏览器保存文件（浏览器的下载管理里面会出现这个任务）。
> 如果下载器进度慢，是网络问题。如果浏览器保存文件很慢，那就不常见了，可能是你硬盘负载太高了之类的问题？
