### ISSUE TITLE
能否增加一个命名文件夹的功能

### ISSUE THREAD

**Issue by br6008** [xuejianxianzun/PixivBatchDownloader#158]
下载图片添加的规则很多，然后用此规则去命名文件夹很长，文件夹本来想要个作者id 作品标题 作品id，只能手动修改文件夹名了。

**Comment by xuejianxianzun** [comment]
什么意思，你在命名规则里设置一个短的文件夹名字就可以了啊。就像这样：
`文件夹规则/文件名规则`

**Comment by Nagisa-Koworu** [comment]
我用的是：pixiv/_{type}/{user}/{series_title}/{id_num}_{title}_{p_num}
仅供参考
