### ISSUE TITLE
抓取量多过大时，抓取完不会弹出窗口，所有抓取内容化为飞灰，还浪费大量时间，不止一次了

### ISSUE THREAD

**Issue by 203saber** [xuejianxianzun/PixivBatchDownloader#160]
图片链接：file:///D:/%E4%B8%8B%E8%BD%BD/0.png

**Comment by 203saber** [comment]
http://r.photo.store.qq.com/psc?/V12PyLi73v6LNz/TmEUgtj9EK6.7V8ajmQrEFeS50jPdJZNDdsQ9Doxc9aptfQEFkCF1Vtc4UXEQr7PYKQDQmRzbwWG80CKaUlgKuZGHJyc8HD52on0he9PkYc!/r

**Comment by 203saber** [comment]
> 图片链接：file:///D:/%E4%B8%8B%E8%BD%BD/0.png

**Comment by xuejianxianzun** [comment]
我昨天在赛马娘抓了1000页60000个作品也没出问题，不是很清楚你的情况。
就算我用你抓取时的条件再试一次，大概率是我不能复现你的问题。
你可以试试抓取量太多的话关闭“预览搜索结果”，中途关闭也可以，这样可以减少网络使用率和内存使用量。
如果你有更多可以补充的细节欢迎补充。

**Comment by xuejianxianzun** [comment]
Reinford 认为这是下载器在判断图片颜色时，可能有一些缩略图加载失败了，所以导致了这个问题。
在后续更新的版本里我对这个地方进行了更合适的处理，或许这个问题能得到解决。
