### ISSUE TITLE
下载到一半就下不动了

### ISSUE THREAD

**Issue by TastyPlanet** [xuejianxianzun/PixivBatchDownloader#162]
一直暂停，又开始下载，暂停、下载、暂停、下载...来来回回好多次，网速都已经2M/s了，就是不下载
![2021-07-20 142151](https://user-images.githubusercontent.com/50004335/126272217-dab4cfb2-d91d-417a-a012-013133f48a04.png)
![2021-07-20 142236](https://user-images.githubusercontent.com/50004335/126272252-2a22e7a3-3b99-455e-bc6c-14ad1f425065.png)

**Comment by cpuopt** [comment]
遇到同样问题，下载列表里错误的一个一个出现，最后就全红了。但是clash里可以看见一直在从i.pximg下载，但是下载进度不动

**Comment by xuejianxianzun** [comment]
请尝试：
减少同时下载数量
关闭页面重新打开继续下载
清理C盘空间然后再下载

**Comment by xuejianxianzun** [comment]
你同时下载那么多，没必要，你网速是2M，而同时下载10张图可能总体积10-20M，你下载不还是2M吗，并不能提高速度。
如果图片更大还有可能超时。

**Comment by TastyPlanet** [comment]
好的我这就去试试

**Comment by TastyPlanet** [comment]
还有个问题，有些图是真的下载不了吗，手动切换到那张图，点击下载也不行，想弄清楚到底怎么回事

**Comment by xuejianxianzun** [comment]
下不动的原因比较复杂，你下不动让我试试也许我下得动。我是很少遇到这种问题，emmm

**Comment by TastyPlanet** [comment]
emmmm，要不这样，等我遇到下不动的图，我先收集起来，之后打包提交一下

**Comment by xuejianxianzun** [comment]
对于这种梯子还在正常下载（有正常的速度和流量），但是下载器却一直循环下载/暂停的情况，C盘空间不足应该是主要的原因。
尽量清理下C盘空间再试试。

**Comment by TastyPlanet** [comment]
谢谢，清理了C盘之后发现，之前下载一直循环暂停的，现在可以正常下载了！
另外问一句有没有方便清理的工具？

**Comment by xuejianxianzun** [comment]
Dism++
http://www.chuyu.me/zh-Hans/index.html
打开它，界面左侧有个空间回收功能，能清理出比较多的空间。
