### ISSUE TITLE
Is There a New Problem With Downloading and Converting to WebM?

### ISSUE THREAD

**Issue by slelmir** [xuejianxianzun/PixivBatchDownloader#163]
I started downloading webm's from Pixiv today with my usual settings, but after downloading, the webm files don't show any thumbnail and can't play in any of my video players. I tested the other webm videos I've downloaded before and they worked fine. When I tried playing in MPC-HC, it gave me this error:

File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {1AC0BEBD-4D2B-45AD-BCEB-F2C41C5E3788}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0

Do you know why this is happening? Thanks!

**Comment by xuejianxianzun** [comment]
Please try to drag and drop the webm file to the Chrome browser. If the Chrome browser can play, the file is normal.
If the file is normal, please consider installing Potplayer to play it (this may also solve the thumbnail problem).
If the file is not normal, please submit the pixiv URL of this work.

**Comment by slelmir** [comment]
I tried playing the webm's in chrome and in potplayer, neither of them work, just shows a black screen and the play bar in chrome. I also tried downloading from different artists, different tags, and none of them work.

**Comment by slelmir** [comment]
Just restarted my computer to see if that helps, I'm getting the same problem.

**Comment by xuejianxianzun** [comment]
I have no idea about this either.
Please submit the pixiv URL of this work. Let me try.

**Comment by slelmir** [comment]
https://www.pixiv.net/en/tags/%E7%8D%A3%E5%A7%A6/illustrations?s_mode=s_tag&type=ugoira
https://www.pixiv.net/en/tags/%E5%8E%9F%E7%A5%9E/illustrations?s_mode=s_tag&type=ugoira

These are the two pages I've tried, I just crawled the first page of each and tried downloading them. None of the files were working.

**Comment by xuejianxianzun** [comment]
There is a problem, and I am looking for the reason.

**Comment by xuejianxianzun** [comment]
This is most likely due to a problem caused by the new version of Chrome. Please try to install a browser with a Chrome kernel version not greater than 90（or Chrome v90）, which may be able to convert normally.

**Comment by xuejianxianzun** [comment]
The 10.2.0 version of the downloader will fix this problem, please wait for the automatic update, or manually update offline now.
