### ISSUE TITLE
系列小说下载建议

### ISSUE THREAD

**Issue by shangji666** [xuejianxianzun/PixivBatchDownloader#164]
对系列小说下载时能将它们合并为一个文件吗，这样会显得简洁很多

**Comment by xuejianxianzun** [comment]
我也觉得这样很好，但是下载器现有的下载流程设计导致这个功能并不容易做到。尤其是在系列、非系列小说混杂的情况下。

如果只是在系列小说的目录页面添加这个功能会简单些。也就是单独的去下载某个系列的小说，一次只下载一个系列。

**Comment by Nagisa-Koworu** [comment]
你可以将整个系列保存在以系列名为文件夹名的文件夹里

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
请尝试离线安装最新版本进行体验（安装后需要关闭在线安装的版本），欢迎反馈
