### ISSUE TITLE
功能请求：增加对 Firefox 浏览器的支持

### ISSUE THREAD

**Issue by ASC8384** [xuejianxianzun/PixivBatchDownloader#165]
功能请求：增加对 Firefox 浏览器的支持

**Comment by xuejianxianzun** [comment]
这个以前有人提过。因为下载流程中的 firefox 的一个策略会加重资源占用所以没有 firefox 版本了。
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/88

**Comment by xuejianxianzun** [comment]
Firefox version:
https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/
