### ISSUE TITLE
用不了，点击没弹出窗口

### ISSUE THREAD

**Issue by honey11155** [xuejianxianzun/PixivBatchDownloader#166]
除了https://www.pixiv.net/ranking.php?mode=daily这个网站能用其他的都没法用。
修改了permissions为所有网站也不能用

**Comment by xuejianxianzun** [comment]
https://www.pixiv.net
首页呢？下载器没这个问题，可能是你浏览器有问题。

**Comment by xuejianxianzun** [comment]
如果你没有补充更多信息，过段时间我会删除这个issues。
