### ISSUE TITLE
增加禁用上方“XXX users入り"的选项

### ISSUE THREAD

**Issue by fireattack** [xuejianxianzun/PixivBatchDownloader#168]
希望能提供增加禁用这条的选项。

这个有时候会有bug，导致挡住搜索框：

![image](https://user-images.githubusercontent.com/4130991/129459155-1fe71aa5-9afa-4fbf-ba55-018a212afe29.png)

而且我有premium，用不到这个。

谢谢！

**Comment by xuejianxianzun** [comment]
我试了一下没有发生这个 bug。在什么情况下会发生？以及你的浏览器版本号是多少？
![QQ截图20210815102320.jpg](https://i.loli.net/2021/08/15/PeL65yXFYlOwpTG.jpg)

**Comment by fireattack** [comment]
有很多情况会出现，一般是后有无这个条的界面来回切换时，就会出现。

比如以下STR：

1. 打开任意tag的页面，比如 https://www.pixiv.net/tags/%E6%B0%B4%E7%9D%80/artworks 
2. 点一下搜索框，让下面那一堆东西都预加载出来。←这步必需
2. 然后点击左边的Pixiv logo切换到主页，此时上面的条消失
3. 点击任意一个你的的お気に入りタグ（如果没有，先设置几个）
4. 再点搜索框，此BUG出现

<html>
<body>


Google Chrome | 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)
-- | --


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by xuejianxianzun** [comment]
在 10.4.0 版本里会添加一个开关（在“其他”选项卡里）：
增加了是否显示快捷搜索区域的开关。如果关闭了这个开关，就不会显示快速搜索区域。

这个版本需要一段时间才能发布到应用商店里。你也可以从 release 页面下载离线安装包使用。
[离线安装指南](https://xuejianxianzun.github.io/PBDWiki/#/zh-tw/%E9%9B%A2%E7%B7%9A%E5%AE%89%E8%A3%9D)

**Comment by fireattack** [comment]
谢谢
