### ISSUE TITLE
为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载

### ISSUE THREAD

**Issue by 1112yuzu** [xuejianxianzun/PixivBatchDownloader#169]

**Comment by xuejianxianzun** [comment]
你说的“下载log”是什么页面的？
下载器只有在下载动图时才会下载到 zip 压缩包，其他时候不会产生压缩包。

**Comment by 1112yuzu** [comment]
就是我点开log的时候下面会显示“下载页面”，我点击后会直接下载成压缩包的形式挺方便的，结果今天突然有些log点击后变成一张一张下载了……







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午11:06
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
你说的“下载log”是什么页面的？
 下载器只有在下载动图时才会下载到 zip 压缩包，其他时候不会产生压缩包。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuejianxianzun** [comment]
你点击的哪个按钮，你截个图？感觉你说的不是这个下载器啊

**Comment by 1112yuzu** [comment]
就是这个“下载页面”，点击的话就能直接抓取整个log的图并且以压缩包的形式保存，但今天有些log我点击的时候突然就一张一张下载了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午11:53
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
你点击的哪个按钮，你截个图？感觉你说的不是这个下载器啊
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1112yuzu** [comment]
然后那些变成一张一张下载的log里下载器是这样的界面，中间的“选择并下载”没有







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午11:53
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
你点击的哪个按钮，你截个图？感觉你说的不是这个下载器啊
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuejianxianzun** [comment]
你图没传上来啊，以及你这个下载器的名字是什么？

**Comment by 1112yuzu** [comment]
图没有传上来吗，我是以邮件的形式回复的（直接回复不知道怎么上传图……），然后下载器的名字是Powerful Pixiv Downloader




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午12:04
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
你图没传上来啊，以及你这个下载器的名字是什么？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1112yuzu** [comment]
我再试着发送一下图……？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午12:04
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
你图没传上来啊，以及你这个下载器的名字是什么？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuejianxianzun** [comment]
邮件里也看不到你的图啊，没有看到任何图片和附件。
你在扩展管理里禁用 Powerful Pixiv Downloader，然后刷新 pixiv 页面，如果你还能看到所谓 下载 log 的按钮，说明那是其他扩展的，不是这个扩展的、

**Comment by 1112yuzu** [comment]
！试了一下发现确实是其他扩展的，原来是别的插件吗，抱歉麻烦你了……



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 中午12:11
收件人: ***@***.***&gt;; 
抄送: "Morning ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PixivBatchDownloader] 为什么下载log的时候有些不能直接下载成压缩包了，会变成一张一张下载 (#169)





 
邮件里也看不到你的图啊，没有看到任何图片和附件。
 你在扩展管理里禁用 Powerful Pixiv Downloader，然后刷新 pixiv 页面，如果你还能看到所谓 下载 log 的按钮，说明那是其他扩展的，不是这个扩展的、
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
