### ISSUE TITLE
[建议]命名规则中添加投稿日期的选项

### ISSUE THREAD

**Issue by oweaF** [xuejianxianzun/PixivBatchDownloader#17]
有date这个tag的话下载下来的图片方便排序

**Comment by xuejianxianzun** [comment]
排序的话id排序就是同样的效果啊

**Comment by oweaF** [comment]
但是当你用多层文件夹的话，根据id来排序就不好用了
`{user}/{title}/{id}`这种就不能通过id来排

**Comment by xuejianxianzun** [comment]
那使用 date 的话是怎样设置命名规则和排序的？

**Comment by oweaF** [comment]
`{user}/{date}_{title}/{id}`像这样类似的，按画集时间排

**Comment by xuejianxianzun** [comment]
变通的说， `{user}/{id}_{title}/{id}` 也可以，除非你一定要用日期做文件名。
主要问题在于，date 命名规则有格式上的分歧。
比如源数据是 `uploadDate: "2019-08-26T04:12:03+00:00"`，是要分成 date 和 time 两部分，还是都包含在 date 里？
然后时间里的冒号不能做文件名，需要替换成某个字符。
日期是年月日还是月日年，又会有分歧。
如果把上面方方面面都照顾到，那么这部分的设置会变得非常繁琐，我不愿意做。但我如果预设一种规则，就又会有其他人问我怎么这样，怎么不那样。为了避免这个问题，我没有添加 date 标记。

**Comment by oweaF** [comment]
以排序为目的的话按date:yyyy-mm-dd就好了(好像也只能是ymd这个顺序)，目的是大致的线性，至于一天里面几点钟发了什么，我是不关心的。
`{user}/{id}_{title}/{id}`这种也行，就是难看了些😂

**Comment by xuejianxianzun** [comment]
这个问题我再研究下

**Comment by xuejianxianzun** [comment]
现在更新了，添加了 {date} 字段。
