### ISSUE TITLE
[功能建议]搜索结果按收藏数排序显示

### ISSUE THREAD

**Issue by TenmaSennpai** [xuejianxianzun/PixivBatchDownloader#170]
通过收藏数进行搜索，存在一个问题，在搜索之前，并不知道在某类图片下，什么收藏数以上是质量较好的
所以有没有可能让搜索结果按收藏数排序显示
也就是在抓取时进行排序或者在出现结果后再进行排序
有了此功能后，也可以直接进行排序

不知道是否可以实现

**Comment by xuejianxianzun** [comment]
默认开启的设置：预览搜索页面的筛选结果，会在搜索页面抓取完成后按收藏数量排序。
这是你需要的吗？

**Comment by TenmaSennpai** [comment]
是的，原来已经有这个功能了，我之前可能是没有让它抓取完，所以没发现，谢谢

另外，还有一个一个小BUG，供参考，这个BUG在刷新页面后会恢复正常
复现方法：点击开始筛选作品后点击搜索框，或在筛选作品完之后点击搜索框
图片：https://imgur.com/a/VMV4cy0

**Comment by xuejianxianzun** [comment]
这不是下载器的 bug，而是 pixiv 的 bug。
下载器在页面顶部输出日志之后，搜索框下移，但是这个悬浮窗口仍然使用一开始的位置，所以它就挡住了搜索框。
这个悬浮窗不是下载器控制的。你可以把浏览器窗口化，然后再恢复最大化，它会重新计算位置，这样就恢复正常了。
