### ISSUE TITLE
New Features Request

### ISSUE THREAD

**Issue by CyberSolutions8799** [xuejianxianzun/PixivBatchDownloader#173]
If possible please add these few features:

1. Display Original Image Dimensions (Eg: 640 x 640)
2. Display Ugoira Video Dimensions (Eg: 1920 x 1080)
3. Display Ugoira Duration (Eg: 3:45)
4. Seek Bar & Pause Ugoira
5. Block Ads (If Possible)

**Comment by xuejianxianzun** [comment]
Where is the image resolution displayed? I will think about it.

Is the "Seek Bar" used to control the playback of Ugoira? Realize the function of forward and backward? This is difficult for me to do.
If you use the downloader to save the Ugoira in webm format, you can use the video player to control it.

Block Ads: The downloader has blocked some ads, but it may not be comprehensive enough. It is recommended that you also use other extensions, such as Adblock plus.

**Comment by CyberSolutions8799** [comment]
> Where is the image resolution displayed?

Here: https://i.imgur.com/8MhxW9G.jpg (or maybe the lower-right corner)
Same for Ugoira Dimensions and Duration.

**Comment by xuejianxianzun** [comment]
I may add this feature in the future.

**Comment by xuejianxianzun** [comment]
In the next version, the "Preview Work" function will display the size of the image.
You can easily view the size of any image without even entering the page of this image.
So the downloader will not display the size of the image separately on the page.
Currently, the function of displaying Ugoira  information will not be added.
https://imgur.com/a/PQJiQpw
