### ISSUE TITLE
有大量重复文件时，下载速度变慢

### ISSUE THREAD

**Issue by telessa** [xuejianxianzun/PixivBatchDownloader#175]
先抓取100页 大概1万多结果 抓取越多 抓取就越慢
开始检测文件已下载过 以近乎一秒一个的速度跳过下载 2分钟才跳过111个已下载文件
1万多图 要6个小时才能执行完

如果在抓取完后 选择刷新网页 恢复抓取结果 此时
检测速度飞快  全部跳过 但在第9000个抓取结果开始 跳过速度越来越慢

希望能改进抓取速度和已下载文件检测速度

**Comment by xuejianxianzun** [comment]
1. 请提交你抓取的网址
2. 下载开始后才会检测重复文件。这些文件里你之前下载过多少？
3. “第9000个抓取结果开始 跳过速度越来越慢”，是指下载到第 9000 个文件的时候吗？

**Comment by telessa** [comment]
1
https://www.pixiv.net/tags/50000users%E5%85%A5%E3%82%8A/illustrations?s_mode=s_tag
2 
可能是全部  
3
检测到文件  已经下载过，跳过此次下载
是这步变慢

**Comment by xuejianxianzun** [comment]
可能确实有问题，但是大量测试需要比较多的时间，我明天处理下。

**Comment by xuejianxianzun** [comment]
你可以尝试先关闭这个扩展，然后从下面的网址下载我新发布的一个安装包，离线安装到扩展管理里面。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v11.3.30
安装之后打开网址重新抓取、下载，观察问题有没有解决（检查重复文件的速度是否能维持在一个比较快的水平 ）
https://www.pixiv.net/tags/50000users%E5%85%A5%E3%82%8A/illustrations?s_mode=s_tag

如果你不会离线安装，请参考：
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85?id=%e8%a7%a3%e5%8e%8b%e6%96%87%e4%bb%b6

**Comment by telessa** [comment]
快了8倍

**Comment by xuejianxianzun** [comment]
> 快了8倍

现在可以顺利下载完吗？

**Comment by telessa** [comment]
> > 快了8倍
> 
> 现在可以顺利下载完吗？

可以

**Comment by xuejianxianzun** [comment]
看起来你的问题解决了呢。还有另一个issues也有类似的问题，我等等他的反馈。
等过段时间发布了新版本的话，你可以删除这个离线安装的版本，从扩展商店安装新版本。

**Comment by telessa** [comment]
> 看起来你的问题解决了呢。还有另一个issues也有类似的问题，我等等他的反馈。 等过段时间发布了新版本的话，你可以删除这个离线安装的版本，从扩展商店安装新版本。

非常感谢
