### ISSUE TITLE
Randomly stopping downloading

### ISSUE THREAD

**Issue by Aergernis** [xuejianxianzun/PixivBatchDownloader#176]
Hi,
after updating from 11.2.0 to 11.3.3 the downloader just randomly stops downloading after a few 100 pictures. No Error or something, it just download any further.
I've tested Versions 11.3.0, 11.3.1  and 11.3.2 to with same result. 11.2.0 does not have this issue.

https://www.pixiv.net/en/users/973675/following

[Powerful Pixiv Downloader Settings.json.log](https://github.com/xuejianxianzun/PixivBatchDownloader/files/7446463/Powerful.Pixiv.Downloader.Settings.json.log)

**Comment by xuejianxianzun** [comment]
If the downloader stops downloading because of an exception, it will automatically pause the download, and then resume the download. Are you encountering this situation? Is there a screenshot?

**Comment by Aergernis** [comment]
I don't have a screenshot . I'll install 11.3.3 and take one. May take some time.

**Comment by Aergernis** [comment]
Here is the screenshot. No error or anything.

![stopping](https://user-images.githubusercontent.com/13299518/139542858-75988840-7b74-451e-af63-630b782e3a93.png)

**Comment by xuejianxianzun** [comment]
Perhaps the "don't download duplicate files" feature caused this problem.
I will try to solve this problem tomorrow. You can turn off "Don't download duplicate files" first and then continue downloading.

**Comment by Aergernis** [comment]
Seems to be true. I've paused and resume the download and it still didn't go any further. After disabling the "Don't download duplicate files" function, pausing and the resume and it's downloading.

**Comment by xuejianxianzun** [comment]
I didn't find the problem in the code of "check for duplicate files", so I still can't determine the cause.
Now I optimized the log function and reduced the memory usage. Please try to install the following version and try again.
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85?id=%e8%a7%a3%e5%8e%8b%e6%96%87%e4%bb%b6

**Comment by Aergernis** [comment]
Installed and testing.

**Comment by Aergernis** [comment]
It's still downloading, even after a lot of skipped pictures.

**Comment by xuejianxianzun** [comment]
It looks like the problem is solved. Thanks for the test.

**Comment by Aergernis** [comment]
No big deal. Thanks for your efforts and fast support
