### ISSUE TITLE
系统磁盘的剩余空间可能不足

### ISSUE THREAD

**Issue by Misaki4115** [xuejianxianzun/PixivBatchDownloader#177]
Error: 94009676_p0 Code: 0
下载时发生错误，可能的原因：
系统磁盘的剩余空间可能不足。请尝试清理系统磁盘空间，然后重新启动浏览器，继续未完成的下载。

但是我的硬盘空间还有100多g，而且用fanbox下载器也是正常的欸

**Comment by xuejianxianzun** [comment]
1. 系统盘空间不足。你说的100多G到底是不是系统盘？
2. fanbox 下载器和 pixiv 下载器的下载流程不同，不会出现这个问题。

**Comment by Misaki4115** [comment]
谢谢！
是开了跨域工具的问题
