### ISSUE TITLE
After update .txt metadata is not saved in the same folder as works.

### ISSUE THREAD

**Issue by As4shi** [xuejianxianzun/PixivBatchDownloader#178]
It all goes to the default Download folder set in my browser config and doesn't follow the naming rule, the works are being saved properly so this is exclusive to the "Save the metadata of the work ?" option.

I would be very thankful if this can be fixed since i was relying on it so far, besides that thanks for keeping up the good work :)
![explorer_Shc6eXbtOx](https://user-images.githubusercontent.com/24969000/141408539-baff9dd8-4dac-497e-a1aa-d226b19ca22e.png)

**Comment by xuejianxianzun** [comment]
This is a problem caused by version 11.4.2.
You can install the old version, or wait for the automatic update to the new version.
