### ISSUE TITLE
Uncaught (in promise) Error with v 11.4.3

### ISSUE THREAD

**Issue by Aergernis** [xuejianxianzun/PixivBatchDownloader#179]
I happend after crawling and saving results (autoimaticly). Download didn't start.

```
Uncaught (in promise) Error: Extension context invalidated.



Kontext

https://www.pixiv.net/en/users/973675/following

Stapelüberwachung

js/content.js:12766 (Anonyme Funktion)

` 12777       chrome.runtime.sendMessage(sendData);
`
```

**Comment by xuejianxianzun** [comment]
I guess you installed it offline.
After offline installation, you need to refresh the pixiv page, otherwise the page still uses the old version of the code, and this problem will occur.
