### ISSUE TITLE
Just A Question About Bookmarks

### ISSUE THREAD

**Issue by slelmir** [xuejianxianzun/PixivBatchDownloader#182]
Hi, are there any plans to crawl separately through public and private bookmarks? I think it would make it easier to sort through the works I haven't saved yet.

**Comment by xuejianxianzun** [comment]
You can switch the "Public" and "Private" categories of the bookmark page and start crawling.
![QQ截图20211201120111.png](https://i.loli.net/2021/12/01/GhSB4lYIen5FtJR.png)
