### ISSUE TITLE
Configuration Re-arrangement

### ISSUE THREAD

**Issue by CyberSolutions8799** [xuejianxianzun/PixivBatchDownloader#183]
Instead of _Crawl_, _Download_ and _Other_ tabs it'd be better if there is _Downloads_, _Enhancements_ and _Settings_.

**Downloads Tab =** Both Crawl and Download related settings.
**Enhancements Tab =** Settings related to the site directly (Eg: Preview Works, Replace square thumbnails, etc.)
**Settings Tab =** Settings related to the extension itself (Eg: How to switch tabs, Language, etc.)

**Comment by xuejianxianzun** [comment]
I think your suggestion makes sense, but the current layout of the downloader is also the result of a trade-off.
The downloader puts many options in the "Other" tab to make room for the "Crawl" and "Download" tabs.
If the downloader puts the grab and download options together, then when downloading, the user must scroll the mouse to see the download area.
In addition, there are many options that are not commonly used. These options do not necessarily occupy space all the time, so I use the "Advanced Settings" and "Other" tabs to hide them.

**Comment by CyberSolutions8799** [comment]
Then how about putting all the configuration related options under a parent tab, _Configuration_ and adding another tab called _Dashboard_.

**Dashboard Tab =** Every option that user uses to download, crawl or select images.
**Configuration Tab =** Downloads Sub-Tab, Enhancements Sub-Tab, Settings Sub-Tab.

**Comment by xuejianxianzun** [comment]
I think the "Download" tab should not be used alone, because there are some settings that are strongly related to downloads, and users may need to modify or pay attention to these settings frequently, for example:
Naming rules
Preview file name
Export crawl results
Start downloading automatically

Separating these settings from the download area will reduce the user experience.

**Comment by CyberSolutions8799** [comment]
Okay! Then it can't be helped. 👌
