### ISSUE TITLE
能做个浏览时的私密收藏功能不，不只是下载跟公开收藏按钮。

### ISSUE THREAD

**Issue by Naileon** [xuejianxianzun/PixivBatchDownloader#185]

**Comment by xuejianxianzun** [comment]
下载器的五角星收藏按钮是可以设置成进行私密收藏的。
在下载器的"收藏设置"选项里选择“不公开”就行了。

如果作品上的收藏按钮是pixiv原本的心形按钮，你可以在作品缩略图上点击放大镜图标，然后点击底部的收藏按钮，这个也是下载器的按钮。

**Comment by Naileon** [comment]
好 谢谢作者大大
