### ISSUE TITLE
[Help] How can I convert Ugoira animate file to Webm offline

### ISSUE THREAD

**Issue by Paper-Folding** [xuejianxianzun/PixivBatchDownloader#186]
### I have ugoira animate files stored locally, is there any way to convert them to webm file offline?  
(For some reason, some of ugoira files' source is set as private by artists, so I'm not able to download source and convert them to webm utilizing `PixivBatchDownloader` from Pixiv anymore, so I'm seeking a way to convert them offline.)

**Comment by xuejianxianzun** [comment]
Sorry, the downloader can't do it. It cannot let you select a zip file for conversion.
In addition, you also don't have frame delay data for the animation.
One method is to decompress the image and then use other software to synthesize the moving image. For example, use ffmpeg to generate MP4 video.
Another method is to change the file extension `zip` to `ugoira`, and then use the image viewing software honeyView to open it. HoneyView will automatically switch the pictures in the compressed file to form an animation effect. But if the file is relatively large, this software will take up more memory and the animation effect will become very slow.

**Comment by Paper-Folding** [comment]
Thank you for your reply! I seems ugoira is just a set of images when I change files' extension to zip. Your reply is helpful, I think I got my idea to convert them, thank you. I guess I can just close this help.
