### ISSUE TITLE
有{bmk_id} 的话，希望加一个下载前自动快速收藏的功能

### ISSUE THREAD

**Issue by acteds** [xuejianxianzun/PixivBatchDownloader#189]
或可分为
https://www.pixiv.net/artworks/*
这样的作品页,和其他页面做多选开启关闭

**Comment by acteds** [comment]
在下载前手动收藏后点下载{bmk} 依然取不到值，需要刷新页面

**Comment by xuejianxianzun** [comment]
为什么需要“下载前自动快速收藏”，没有懂。你可以开启“下载后自动收藏”。
{bmk} 怎么会获取不到值？{bmk} 和你收藏没收藏并无关系，你抓取这个作品就能获取到 {bmk}。

**Comment by acteds** [comment]
> 

说错了是｛bmk_id｝

**Comment by xuejianxianzun** [comment]
{bmk_id} 用于下载你收藏的作品。如果你用在没收藏的作品上，然后希望下载器在下载前收藏作品，这属于本末倒置了。
让下载器自动收藏，那收藏到了不喜欢的作品怎么办？

**Comment by acteds** [comment]
> {bmk_id} 用于下载你收藏的作品。如果你用在没收藏的作品上，然后希望下载器在下载前收藏作品，这属于本末倒置了。 让下载器自动收藏，那收藏到了不喜欢的作品怎么办？

在一个没有收藏的作品页(https://www.pixiv.net/artworks/*),
如果觉得插画可以那我就是收藏加下载
现在有{bmk_id}这个参数,我想取到这个参数,用来排序.
现在就是要先收藏该作品,然后刷新,最后下载.
所以有这个先收藏再下载的想法.

因此不存在下载器自动收藏到不喜欢的作品(仅限在我人工干预的作品页面)

**Comment by xuejianxianzun** [comment]
你这种情况我建议先手动收藏，过段时间累积了一定数量的收藏作品之后，去你的收藏页面进行批量下载。

**Comment by acteds** [comment]
> 你这种情况我建议先手动收藏，过段时间累积了一定数量的收藏作品之后，去你的收藏页面进行批量下载。
确实是一个好办法.
这个奇怪的需求大概和
**下载之后收藏作品**
差不多,只不过现在多了个字段取不到,而要取到则是要收藏

**Comment by xuejianxianzun** [comment]
{bmk_id}的设计意图就是解决在收藏页面下载时的排序问题，在其他页面没多少实际意义。
