### ISSUE TITLE
画师名称与画师id无法正常命名

### ISSUE THREAD

**Issue by wow646** [xuejianxianzun/PixivBatchDownloader#19]
下载到的文件名为{p_user}{p_uid}，其他命名正常

**Comment by wow646** [comment]
![批注 2019-09-04 210641](https://user-images.githubusercontent.com/54895293/64257600-37b21480-cf58-11e9-898a-862c29c6d48b.jpg)

**Comment by xuejianxianzun** [comment]
在某些页面，部分标记不可用。
{p_user}{p_uid} 是当前页面的画师信息，如果你想在每个文件里保存对应的画师信息，可以使用{user}{uid}

**Comment by xuejianxianzun** [comment]
今天我发现这地方确实是出了 bug，现在已经提交了新版本 2.4.1，大概半个小时后可以更新。
https://chrome.google.com/webstore/detail/pixiv-batch-downloader/hfgoikdmppghehigkckknikdgdcjbfpl

**Comment by xuejianxianzun** [comment]
现在提示在人工审核，可能要多等一段时间了
