### ISSUE TITLE
当选择“原图”以外的“图片尺寸”时，Powerful Pixiv Downloader插件不能以正确的格式下载图片

### ISSUE THREAD

**Issue by luoy804** [xuejianxianzun/PixivBatchDownloader#190]
问题描述：

**Comment by luoy804** [comment]
问题描述：

**Comment by xuejianxianzun** [comment]
“原图”以外的“图片尺寸”全都是jpg。
原图可能是png的，但是其他尺寸都是 pixiv 自动裁剪生成的 jpg 格式。

**Comment by xuejianxianzun** [comment]
既然你都不下原图了，还在意图片是 png 还是 jpg 没什么意义。

**Comment by luoy804** [comment]
首先，很抱歉因为不熟悉github网页的规则，在没有完成编辑前误发送。并且我还没找到删除帖子的选项。。。
@xuejianxianzun
问题描述：

- 我试图在“其他-图片尺寸”中选择其他尺寸，但发现下载的图片中有一部分变成了“jfif”格式。并且在下载过程中，网页报错“如果下载后的文件名异常，请禁用其他有下载功能的浏览器扩展。”；
- 因为jfif格式可以在windows直接查看，但在另外一下软件中无法识别，让我有些头痛；

使用环境与一些尝试：

- 用的是**chrome浏览器**；
- 是在画师主页中抓取图片并下载，抓取图片过程中一切正常，但在下载时报错并出现以上问题；
- 在网页报错后，根据提示重启浏览器并**禁用了所有其他插件/扩展程序**，问题仍未解决；
- 仅在选择“原图”以外的“图片尺寸“中，会出现这个问题，恢复选择”原图“后不会出现这个问题；
- **此问题仅在部分画师的主页中出现**，目前试验了三次，有两次出现图片格式变”jfif“的情况；

出现问题的画师为：
https://www.pixiv.net/users/3302692
https://www.pixiv.net/users/9038581
未出现此问题的的画师为：
https://www.pixiv.net/users/5232718

以下是部分截图（不清楚是否能正常上传至论坛），分别为：

- 网页报错的截图；
- 浏览器所使用的插件（均已禁用）；
- 文件夹中格式变为jfif的截图；

![image](https://user-images.githubusercontent.com/96585480/147405233-9c1f3efa-bd36-4fdf-bd92-6721aca4785c.png)

![image](https://user-images.githubusercontent.com/96585480/147405261-4fb9a75e-b0ea-44ee-a03f-6ba957bc3c67.png)

![image](https://user-images.githubusercontent.com/96585480/147405492-032a8f3b-14f6-43ad-a6a7-a91c2ca59098.png)

**Comment by luoy804** [comment]
> 既然你都不下原图了，还在意图片是 png 还是 jpg 没什么意义。

并不是PNG变为JPG，而是部分图片变为JFIF格式；
之前因为不熟悉github网页的规则，在没有完成编辑前误发送；
已经补充问题描述并附上部分图片，如需要其他信息我可以继续补充；
