### ISSUE TITLE
期望批量下载作者内容时保存作者简介等信息

### ISSUE THREAD

**Issue by yfdyh000** [xuejianxianzun/PixivBatchDownloader#193]
建议提供选项，在 /users/* 页面下抓取并下载时，用txt文件保存作者昵称、ID、简介等，乃至作品列表？以及自动下载用户头像、用户封面，记录去重数据更佳。txt文件名可以附上日期。

**Comment by xuejianxianzun** [comment]
- 用txt文件保存作者昵称、ID、简介等
- 保存作品发表日期
你可以在“其他”选项卡开启选项“保存作品的元数据”

- 自动下载用户头像、用户封面
你可以在“其他”选项卡手动下载

-记录去重数据
你可以在“其他”选项卡开启“不下载重复文件”

- 保存作品列表
你可以在抓取后导出抓取结果为 csv 来得到作品列表。

**Comment by xuejianxianzun** [comment]
我能理解你的想法，不过我感觉“在画师页面下载时自动保存头像和/或封面图”这个设置比较少会有人用到。而且下载器的设置太多了，这个还是你自己动下手吧，或者修改代码来实现自动保存。
至于自动导出csv的话有现成的设置可以使用。

**Comment by xuejianxianzun** [comment]
现在没有保存作者简介的功能，因为作者简介不是作品的一部分，作品数据里也没有作者简介。
下载器的功能是针对每个作品的，没有针对“用户”进行太多的优化。
目前没有计划实现保存作者简介的功能。
