### ISSUE TITLE
批量下载时，下载器会出现卡顿，能否调用外部下载器？

### ISSUE THREAD

**Issue by f59375543** [xuejianxianzun/PixivBatchDownloader#194]
比如说发送到Aria2，虽然可以直接复制url，但是这样会丢失命名规则

**Comment by xuejianxianzun** [comment]
正常来说不会很卡的，要么是有大量的动图要转换，要么是电脑配置太低了，才会卡顿。
至于 Aria2 没有支持，一部分原因是：动图和小说是下载器转换后生成的，其 URL 只能当前浏览器里使用，无法传递到外部进行下载。

**Comment by xuejianxianzun** [comment]
如果你希望使用 Aria2，你可以试试另一个下载器：
https://github.com/Mapaler/PixivUserBatchDownload/
