### ISSUE TITLE
期望在已关注用户新作品界面，添加一个分类：非r18作品，和其他类分开，用于正常的浏览。

### ISSUE THREAD

**Issue by duoluodeyouhei** [xuejianxianzun/PixivBatchDownloader#197]
发现界面都分成了三个类，搞不懂p站为什么把关注界面分两类。

**Comment by xuejianxianzun** [comment]
你的意思是只有“全部”和“R-18”分类，没有“全年龄”分类吗？
我之前也注意到过这个问题，目前粗略看了下，只有搜索页面有三种分类，其他的基本都是只有两种分类。
让下载器来弥补这个功能是舍近求远的，因为下载器无法介入  pixiv 原本的行为逻辑，只能模拟它的行为，这就会很费事。

其实“全年龄”的 API 已经有了，只是 pixiv 没加“全年龄”的按钮来让用户使用罢了。
所以还是期待 pixiv 来加这个功能吧。有这个需求的用户可以向 pixiv 提出反馈、建议，让 pixiv 加上这个功能，就一劳永逸了。

**Comment by xuejianxianzun** [comment]
全部：
https://www.pixiv.net/bookmark_new_illust.php
API：
https://www.pixiv.net/ajax/follow_latest/illust?p=1&mode=all&lang=zh

----------

R-18：
https://www.pixiv.net/bookmark_new_illust_r18.php
API：
https://www.pixiv.net/ajax/follow_latest/illust?p=1&mode=r18&lang=zh

----------

全年龄：
现在没有用于全年龄的网址
API：
https://www.pixiv.net/ajax/follow_latest/illust?p=1&mode=safe&lang=zh

--------------------------

三个 API 的区别只在于 mode 参数的值不同。

只获取（查看）全年龄作品的 API 已经有了，只是 pixiv 没让用户能够使用它。
