### ISSUE TITLE
“预览作品”功能的问题和“浏览图片”新功能

### ISSUE THREAD

**Issue by bai12123** [xuejianxianzun/PixivBatchDownloader#198]
作者你好，软件使用体验很棒，提3个建议，希望能对软件起到作用

1.预览作品的功能开启后，当我将鼠标放在图片上，界面弹出一个图层，鼠标不动，向下滑动滚轮，图层被遮挡（如图），移开鼠标再次放在图片上，图层复原。我希望是当鼠标指针未曾离开图片，滑动滚轮，图层始终保持完整显示，直到鼠标离开图片。（这个功能一般是在排行榜，作者主页，下方的缩略图还没有完全出现在界面，但是我鼠标已经放上去了，弹出了原图，我滑动滚轮查看完整缩略图，名字和作者，图层也能一直保持完整，体验更好）
![Snipaste_](https://user-images.githubusercontent.com/99849852/162471851-0724fc86-5dc2-424a-a080-dce7e7b49412.png)
2.预览图片功能，弹出的图片，希望能关闭左上角的图片尺寸和名字（只留一个框或者无框），带来极致的看图体验。

3.pixiv的浏览图片功能一直不是特别好，作者主页都是小图，排行榜也只有3列。希望能有一个这样的功能，图片能够铺满屏幕的宽度，并且能够改变图片大小。我找了4张图来说明这个功能
![Snipaste1_ (1)](https://user-images.githubusercontent.com/99849852/162474919-cd99b7db-d200-4464-bd94-b3bf31330a41.png)
![Snipaste2_ (1)](https://user-images.githubusercontent.com/99849852/162474973-849510bc-6247-49cc-9465-e8ef33b04836.png)
![Snipaste3_ (1)](https://user-images.githubusercontent.com/99849852/162475030-baa0907a-4563-498d-878f-616b3a209622.png)
![Snipaste4_ (1)](https://user-images.githubusercontent.com/99849852/162475086-8684209c-121f-4f94-b366-f1722ab79efa.png)

**Comment by xuejianxianzun** [comment]
1. 你说得对，我会优化一下这里
2. 我考虑加个开关，启用之后可以关闭作者等信息
3. 这个目前还不好说，因为不同页面的作品缩略图元素不是一样的，还需要调查下。顺利的话可以做一下。你可以先增大页面缩放凑合下。

**Comment by bai12123** [comment]
1.弹出图片如果加个过渡动画就更好了，现在的有点生硬
2.没有标题后希望边框宽度能细点
3.这个功能是我在sleazyfork.org/zh-CN/scripts/421970-yande-re-%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87看到的，看图体验很好，原作者很久没有更新了，可以参考下。

**Comment by xuejianxianzun** [comment]
1. 预览图的宽高、位置都是不固定的，为其添加动画太费事，我不打算添加，不过如果有人帮忙实现倒可以。
2. 可以
3. 我在研究了，先用画师主页试试，其他页面以后再说吧。我目前的打算是保持一行 6  个缩略图，但是其宽度会增加，图片显示的也会更大。没有计划设置放大倍数。

目前计划是这样的效果：
![20220409_183959.jpg](https://s2.loli.net/2022/04/09/iPj9os5HUaGCXpz.jpg)

**Comment by bai12123** [comment]
1.动画只是锦上添花，没有也无妨
3.好的，无敌。竖图一行6个可以，横图是否小了。横图宽度可以按竖图2个算，一行5个？
![Snipaste_](https://user-images.githubusercontent.com/99849852/162569015-1e0d93d1-3736-4a60-9b27-1fe90745c126.png)

**Comment by xuejianxianzun** [comment]
横图按 2 个算确实好看不少，只是这个地方很难处理，因为 pixiv 没有标志一个图片是横图还是竖图，要处理的话只能等图片加载完之后获取宽高一个个判断。
而且 pixiv 有时会动态加载新的缩略图。
这样还有个问题在于画面会抖动。因为列表刚加载出来的时候每个图片宽度一样，之后才能找出横图，改变它们的宽度，这样布局就会忽然一下子变了。
有点头疼

**Comment by bai12123** [comment]
横图这个还是要处理的。因为有的画师主页全是横图，一行6个横图就小了，跟原来没有太大区别。提供一个想法仅供参考：可以等主页的先加载完，添加一个按钮，再改变布局。

**Comment by xuejianxianzun** [comment]
每次都要点一下按钮也挺麻烦的，而且也不能很好的处理在之后才添加的缩略图。
在不同的页面里，缩略图的元素、缩略图的容器、缩略图列表容器的元素大多有所差别。这一块的功能做起来很麻烦。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v12.0.0
你可以离线安装试试怎么样，给我反馈下。
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85
另外，缩略图乱的问题，如果关闭“替换方形缩略图”，就是使用 pixiv 原本的方形缩略图，那样看起来就整齐了。

**Comment by bai12123** [comment]
来晚了，反馈几个问题。
1.长按鼠标右键弹出的大图，边框没有改细

2.在已有长按鼠标右键弹出的大图时，鼠标移到原图或者其他图，会再次弹出预览图，正确的做法是已有大图的情况下，拒绝弹出预览图，直至点击空白处取消大图。
![Snipaste_](https://user-images.githubusercontent.com/99849852/162592541-3c80fcce-a72e-4aeb-bf1f-1aba992795aa.png)

3.预览作品功能，原图和普通，我找了几组图片测试（大图小图都有），弹出来的大小都一样，不知道是不是我肉眼没分辨出来

4.（1080p屏，100%无缩放）排行榜一行4个，图与图间隙大，有空白（其他页面也受影响）。画师主页一行5个，宽图没有放大，有空白。如果关闭“替换方形缩略图”，虽然不乱了，“显示更大缩略图”功能失效（图3）。个人认为显示更大缩略图的目的就在于一次看完整大图，排版更加舒服，有了这个功能后，替换方形缩略图可以下线了。
![Snipaste3_](https://user-images.githubusercontent.com/99849852/162592903-08e200c9-bd15-4492-8a7a-75c510811840.png)
![Snipaste2_](https://user-images.githubusercontent.com/99849852/162592913-5cbdffd8-2714-40d4-87c9-b98c1fc27c14.png)
![Snipaste_4](https://user-images.githubusercontent.com/99849852/162592918-37ae4ab0-dbfe-4d1e-8f89-f57635d0bdbc.png)

**Comment by xuejianxianzun** [comment]
1. 这个忘记改了
2. 同时显示的情况还是比较少的，问题不大
3. 原图和普通图就是预览区域加载的图片。是有区别的，原图就是原图，普通是最大1200px的压缩过的图。但是由于预览图的大小也就那么大，所以原图和普通在视觉上基本看不出来差别。用默认的“普通”就行了。
4. 感觉你还是开了缩放，因为你每一排显示的数量都比我的少一个。你按  ctrl+0 重置下缩放吧。至于“一次看完整大图”，不开替换方形缩略图的话，你看到的缩略图是裁剪过的正方形，那也没看到完整的图呀。我还是喜欢开着。
