### ISSUE TITLE
关于是否能开发【一键下载所有关注画师】的功能

### ISSUE THREAD

**Issue by Ruo-bin** [xuejianxianzun/PixivBatchDownloader#199]
现在是可以在关注画师页面下载，可以把当前页面关注画师的作品全部下载，但是我关注比较多，有70多页，一页一页去下载就有点麻烦，所以不知作者能不能做下这个功能。
插件很棒，感谢作者

**Comment by xuejianxianzun** [comment]
你打开你的“关注”页面，直接开始抓取就行了啊

**Comment by xuejianxianzun** [comment]
![20220411_033618.jpg](https://s2.loli.net/2022/04/11/jSPNEyHkxf8W63s.jpg)
![20220411_033711.jpg](https://s2.loli.net/2022/04/11/FVQtdZ6InMavNo1.jpg)

**Comment by Ruo-bin** [comment]
原来如此，谢谢，不得不说你的关注是真的多啊，几乎是我的两倍
