### ISSUE TITLE
Corrupted filename

### ISSUE THREAD

**Issue by Menius8** [xuejianxianzun/PixivBatchDownloader#2]
Images saves as shown on screenshot
![default](https://user-images.githubusercontent.com/44773877/47998219-e53e7680-e141-11e8-9759-22a416509d08.JPG)

**Comment by xuejianxianzun** [comment]
我没有遇到这个问题，请问如何重现？
你可以尝试卸载这个扩展，然后重新安装。

**Comment by Menius8** [comment]
Tried this, no changes. Maybe I should turn off other extensions? Browser Chrome.

**Comment by xuejianxianzun** [comment]
What is your operating system and browser version?
It seems that chrome did not use the specified file name when downloading, but used url as the file name. I have not encountered this problem before.

**Comment by Menius8** [comment]
OS: Windows 10 Home 1803
Chrome version 70.0.3538.77
