### ISSUE TITLE
启用更大预览图会概率出现翻页异常

### ISSUE THREAD

**Issue by FishMagic** [xuejianxianzun/PixivBatchDownloader#201]
在点击向左或者向右翻页时，概率性会出现连续翻动两页（以大预览图的大小）

**Comment by xuejianxianzun** [comment]
因为缩略图的宽度增加了，但是 pixiv 仍然按照之前的方式滚动，所以会出现这个问题。
首页顶部的区域一次会切换5个作品，但是开启了更大的缩略图之后，可能同时只能显示 4 个作品，这样就会有一个看不到了。
除了这种情况，大部分横向滚动区域都会出现滚动不完的情况，目前尚无法解决。

**Comment by xuejianxianzun** [comment]
今天我尝试了很久，但是没能解决这个问题。
pixiv 原本在这里的缩略图是固定 184px 的，我的放大倍数对它来说太多了。
如果确实需要看这里的内容，现在只能点它右上角的 [查看全部](https://www.pixiv.net/bookmark_new_illust.php)，到单独的页面去查看。
