### ISSUE TITLE
建议: 希望添加设置: 关闭多图作品预览图的"鼠标滚轮切换图片"功能

### ISSUE THREAD

**Issue by Ricky2576** [xuejianxianzun/PixivBatchDownloader#202]
显示预览后 如果再想向下滚动网页 滚动了鼠标滚轮 就会切换图片 需要将鼠标从缩略图移开才能滚动网页
很不方便

希望添加这个设置 谢谢

**Comment by xuejianxianzun** [comment]
![20220419_165159.png](https://s2.loli.net/2022/04/19/FuQTrbI69RWSHyj.png)
从下个版本 12.1.0 开始会增加这个设置。到时候你关闭这个设置就可以了。
