### ISSUE TITLE
下载"发现"页面的图片时，不能选择下载多少页

### ISSUE THREAD

**Issue by liuzs** [xuejianxianzun/PixivBatchDownloader#203]
不像别的页面有翻页目录，发现页面是边滑动边加载下一页的，点一次只能抓取40张左右，然后需要手动划一下刷新再点抓取
这有什么办法吗

**Comment by xuejianxianzun** [comment]
"发现"页面没有页码。
你可以考虑多攒一些再下载试试。

**Comment by liuzs** [comment]
> "发现"页面没有页码。 你可以考虑多攒一些再下载试试。

发现了一个邪道办法，把浏览器缩放到最小（比如25%），这样一次可以抓取150张
100%缩放的话只有50张
差不多也够用了
