### ISSUE TITLE
关于命名规则的一个小问题

### ISSUE THREAD

**Issue by UNSCs117** [xuejianxianzun/PixivBatchDownloader#204]
前几个版本下载webm，并且在命名规则一栏里使用{p_num}后，webm文件全部都会有正常的0,1,2...的序号，但是最近发现所有webm的p_num全部消失了？目前还没碰到一个作品内2个动图的，所以不确定这样会不会文件名冲突。
![1](https://user-images.githubusercontent.com/39910838/165793735-7a6259f9-12cc-4429-a510-cca40576e550.png)
我使用的命名规则：{user}-{user_id}/{id_num}-{title}_{p_num}
“其他”选项卡下“命名”一栏的设置：
![2](https://user-images.githubusercontent.com/39910838/165793994-dcc98f9e-578b-47df-838d-c2d519245e2e.png)
这个命名规则对图片是完美运行的，但是就是webm文件出问题了。不知道这个是bug还是我设置问题？

**Comment by xuejianxianzun** [comment]
以前 webm 格式的 {p_num} 可能产生序号，但是现在不会有序号了。这是正常的，这个修改应该至少有几个月了吧。
因为动图作品是没有序号的，也不会冲突，所以没有必要为它们添加序号。

**Comment by xuejianxianzun** [comment]
现在你的命名规则会导致动图的文件名结尾是个横线，如果你介意的话，可能需要下载后用批量重命名软件自行修改文件名。

**Comment by UNSCs117** [comment]
明白了，不会产生冲突就放心了，谢谢回答
