### ISSUE TITLE
关于下载太大的动图时卡住的问题

### ISSUE THREAD

**Issue by UNSCs117** [xuejianxianzun/PixivBatchDownloader#205]
由于我前面从没下过很大的动图，所以不知道前几个版本会不会这样，不过最近碰到好几个超大的动图(40MB朝上的玩意儿)，结果无论动图转换线程调成1还是多少，都会在转换这个大动图上卡住，有时页面还会出崩溃报错(chrome内核浏览器)，甚至我下载线程和转换线程都在1的情况下，一个动图转webm花了3h都没转换成功。。。不知道这是bug，还是本身就不支持这么大的动图转换呢？

**Comment by xuejianxianzun** [comment]
这个作品的id是多少，另外你的浏览器是什么浏览器？报错的提示是 out of memory 吗？
“转webm花了3h都没转换成功”，转换时你是否切到别的程序去了？如果页面被完全遮挡住转换速度会变得很慢。

**Comment by UNSCs117** [comment]
作品id是89392904，大小31.9M，昨天也有几个大小40M朝上的。。。浏览器是360浏览器(别喷我，因为用得太习惯所以还换不掉了)，报错提示是“FACILITY_VISUALCPP/ERROR_MOD_NOT_FOUND”，非常容易在转换大体积的动图并且浏览器有除此页面外的其他标签存在时产生。
![1](https://user-images.githubusercontent.com/39910838/166006561-aaf83d6a-4998-40ff-8e40-c24a609f4c75.jpg)
花3h都没转换好那次是一直在前台的，我把它放在那里就离开了，回来发现还卡在那里。。。

**Comment by UNSCs117** [comment]
昨天下这个动图时放在前台等了10min(期间在玩手机)，结果还是卡在那里。。。话说啥时候能出一个在下载进度条旁加“跳过”按钮的小功能呢？有些图片实际上我通过其他方式下载了，但是在这个脚本内想要跳过目前只能编辑导出的抓取结果后再导入(我觉得的唯一一种跳过方式)。。。不过量太大的话说实话也不用添加，毕竟很少用 :)

**Comment by xuejianxianzun** [comment]
我下载并且转换成功了，大约花费一分钟。
请你尝试最新版本的Chrome来转换试试，如果能够成功则说明是 360 浏览器的问题。

**Comment by xuejianxianzun** [comment]
另外 VISUAL CPP 指的是 VC 运行库，如果你用 Chrome 也会出现这个错误，则可能是系统中缺失某些 dll。

**Comment by UNSCs117** [comment]
问题基本找到了，就是360本身的问题，那个FACILITY_VISUALCPP/ERROR_MOD_NOT_FOUND确实也是360浏览器的特色(虽然我也就这几天碰到)，用edge是没问题的

**Comment by xuejianxianzun** [comment]
ok，360黑料+1
