### ISSUE TITLE
Feature Request 10655385

### ISSUE THREAD

**Issue by squiddies0** [xuejianxianzun/PixivBatchDownloader#206]
Checkmark setting to add the user's id to the folder name. an example of that would be **User - Pixiv 1234567**.

I saw that you can manually change the user name incase the artist changes their name, but a itll be hard to do so for everyone cause anyone can change their name.

**Comment by xuejianxianzun** [comment]
do you mean `{user_id}` ?
![20220501_141114.png](https://s2.loli.net/2022/05/01/lhEA3j1eoI62i4r.png)
E.g: `pixiv/{user_id}/{id}`
