### ISSUE TITLE
[Feature Request] 增强功能菜单中 建议添加选项【过滤列表中已收藏的作品】

### ISSUE THREAD

**Issue by gylidian** [xuejianxianzun/PixivBatchDownloader#207]
#### case 1

平时在阅览搜索结果列表时，有大量的作品已经被收藏过了，人眼分辨倍感疲劳

#### case 2

可能有些用户会将收藏夹作为已阅列表使用，标记过“收藏”的作品代表已阅

### 功能

可以添加过滤器（后续可能添加其他过滤器也说不定，这里作为一个子功能 =>）将已收藏过的作品 过滤后展示

### 可参考对象

Pxder APP（某第三方客户端）

**Comment by xuejianxianzun** [comment]
你说的是在所有页面的作品里都隐藏收藏过的作品，还是只在搜索页面里？

**Comment by gylidian** [comment]
> 你说的是在所有页面的作品里都隐藏收藏过的作品，还是只在搜索页面里？

后者

**Comment by xuejianxianzun** [comment]
目前我没有这个打算，因为你列出的动机还是很少数人会遇到的情况。
