### ISSUE TITLE
如何定期运行抓取?

### ISSUE THREAD

**Issue by mcthp** [xuejianxianzun/PixivBatchDownloader#208]
有每日看一周前某个tag的图的习惯,想在服务器弄个定期任务实现自动化啥的,请教一下有无实现方法的建议.

**Comment by xuejianxianzun** [comment]
下载器没有定期抓取的功能，而且下载器必须在浏览器里使用，感觉不是很适合自动化的样子。
你可以通过 js 来模拟点击下载器的抓取按钮，开始抓取。
如果不想开着浏览器那就换成支持命令行的爬虫吧，我记得 github 上有 py 做的 pixiv 爬虫。

**Comment by mcthp** [comment]
谢答复
手上有个服务器带gui而且平常也是闲置所以倒没关系
在github搜过pixiv的爬虫,star数都不多,分辨不出哪个靠谱些
那我先试试模拟点击的方法
