### ISSUE TITLE
沒有下載鈕

### ISSUE THREAD

**Issue by OftenHsu** [xuejianxianzun/PixivBatchDownloader#21]
下載的按鈕不見了
https://imgur.com/95D6T0L
https://imgur.com/jfvmpGk

查詢/作者/tag頁面都沒有

**Comment by xuejianxianzun** [comment]
扩展被下架了。
目前新版本只能离线安装了。
https://github.com/xuejianxianzun/PixivBatchDownloader/wiki/2.-%E5%AE%89%E8%A3%85#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85
