### ISSUE TITLE
希望加个系列小说更新下载功能

### ISSUE THREAD

**Issue by wvwvwvwvw** [xuejianxianzun/PixivBatchDownloader#210]
我想把收藏里的系列小说检查一下有没有更新，然后下载更新或者没下载的部分，然后导出系列作品信息
另外系列作品名称有重复的情况，文件夹命名加一个系列id

**Comment by xuejianxianzun** [comment]
只下载更新或者没下载的部分，你可以开启“不下载重复文件”的设置。
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E8%AE%BE%E7%BD%AE-%E5%85%B6%E4%BB%96?id=%e4%b8%8d%e4%b8%8b%e8%bd%bd%e9%87%8d%e5%a4%8d%e6%96%87%e4%bb%b6

系列id以后我加一个吧。

**Comment by wvwvwvwvw** [comment]
因为有的小说系列里数量特别多收藏不过来，所以我把每个系列小说只收藏其中一个，但是下载的时候只能下载收藏的，所以想要个批量下载系列小说的功能

**Comment by xuejianxianzun** [comment]
“下载的时候只能下载收藏的”，你在你的收藏里下载肯定这样啊，要下载这个系列的所有小说的话，你需要到系列页面里下载才行。
“批量下载系列小说的功能”早就有了，在系列页面里下载就行。

**Comment by xuejianxianzun** [comment]
在下个版本里会添加新的命名标记：
`{series_id}` 系列 ID
预计几天内可以更新
