### ISSUE TITLE
下载标签建议添加描述或者详情

### ISSUE THREAD

**Issue by wjcwqc** [xuejianxianzun/PixivBatchDownloader#211]
https://www.pixiv.net/users/4325914
![image](https://user-images.githubusercontent.com/30833114/169765116-b8f702a8-b43f-482b-96ef-7a802a720cbf.png)

如上，我想下载妹红表情包，但是无法保存为”东方Project-藤原妹红-血压飙升“，此处”血压飙升“ 应该是描述详情，由于所有表情包实际名称都是详情，目前插件保存最后只有妹红和id，无法保存为表情包名称，建议添加{detail}的tag。

**Comment by xuejianxianzun** [comment]
描述信息可能会很长，并且可以包含超链接，所以不适合放到文件名里。
你这种情况可以在“其他”-“下载”里开启：
```
保存作品的元数据：  插画  漫画
```
这样可以保存描述信息。

**Comment by wjcwqc** [comment]
ok，多谢

**Comment by xuejianxianzun** [comment]
你也可以不启用`保存作品的元数据`，而是在抓取后 `导出 CSV 文件`，因为导出的文件里也含有摘要数据。
