### ISSUE TITLE
新改动导致的联动问题

### ISSUE THREAD

**Issue by Hakoyu** [xuejianxianzun/PixivBatchDownloader#212]
# 与 [Pixiv Previewer](https://greasyfork.org/zh-CN/scripts/30766-pixiv-previewer) 的联动问题
## 在5月12日时 同时使用PixivBatchDownloader和PixivPreviewer
PixivBatchDownloader可以做到在PixivPreviewer以收藏数重新排序的页面后 依旧显示下载按钮(就像期望中的那样)
![image](https://user-images.githubusercontent.com/48956359/170877715-38978115-0cbd-4da5-b65d-591116d1f31f.png)
此方法可以在**按最新排序**的页面下筛选出近期高收藏数的图并手动下载
(因为收藏数只是客观条件,并不代表此图片符合预期,所以选择手动下载,无脑抓取大可不必)
常规方法 比如使用**1000users入り**这种tag来筛选并没有任何用处
因为这只是一个tag 作者和读者可以随意添加 有些技术不高作者会手动添加此tag以期望获取更高的阅读量
## 但近期使用时 PixivBatchDownloader已经无法在PixivPreviewer排序后的页面上显示按钮
![image](https://user-images.githubusercontent.com/48956359/170878748-d1b89c68-ee0e-4253-80c9-b6b80388a5cc.png)
(左下角为PixivPreviewer排序后所显示的当前图片收藏数)
调查得知PixivPreviewer的最后一次更新在2022/4/7 所以猜测是此插件的问题

**Comment by xuejianxianzun** [comment]
下载器最近的一项修改是：

为了防止事件重复绑定，当下载器对一个作品缩略图元素绑定事件后，会在元素上添加一个标记：

```js
el.dataset.mouseover = '1'
```

下载器先绑定了事件，并添加了标记。然后 PixivPreviewer 对作品进行排序：

```js
imageElementTemplate.cloneNode(true)
```

根据 MND 的文档：

>克隆一个元素节点会拷贝它所有的属性以及属性值,当然也就包括了属性上绑定的事件(比如onclick="alert(1)"),但不会拷贝那些使用[addEventListener()](https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener)方法或者node.onclick = fn这种用JavaScript动态绑定的事件. 

所以，`cloneNode` 之后，下载器绑定的事件丢失了，所以不会显示右上角的两个按钮。

但是作品元素上的 `mouseover ` 标记没有丢失，下载器会认为它上面绑定过了事件，不会再给它绑定。

**Comment by xuejianxianzun** [comment]
在 PixivPreviewer 的代码里搜索

```js
let firstImageElement = Pages[PageType.Search].GetFirstImageElement();`
```

在这一行下面添加下面代码，保存：

```js
            const eventElement = firstImageElement.querySelector('[data-mouseover]')
            eventElement && eventElement.removeAttribute('data-mouseover')
```

问题可以解决。

**Comment by Hakoyu** [comment]
好的 以解决 非常感谢

**Comment by xuejianxianzun** [comment]
如果你想从下载器端修改，可以先从扩展管理中移除下载器，然后离线安装下载器。
并把 `content.js` 里的这一行注释掉：

```js
el.dataset.mouseover = '1';
```

ps：注释掉这一行可能会导致下载器自身的预览作品功能出现异常。

**Comment by xuejianxianzun** [comment]
下载器在搜索页面抓取时也可以对作品进行排序。不过两者的执行方式不同，下载器不会在打开页面后自动对这些作品进行排序。

这个事情只能说 `cloneNode` 太霸道了，会移除所有使用 `addEventListener` 绑定的事件。

如果能换成其他方法会更温和一些。毕竟这种方式也可能会误杀其他工具绑定的事件。

**Comment by Hakoyu** [comment]
行 我会尝试向 PixivPreviewer 那边报告这个问题

> 下载器在搜索页面抓取时也可以对作品进行排序。不过两者的执行方式不同，下载器不会在打开页面后自动对这些作品进行排序。
> 
> 这个事情只能说 `cloneNode` 太霸道了，会移除所有使用 `addEventListener` 绑定的事件。
> 
> 如果能换成其他方法会更温和一些。毕竟这种方式也可能会误杀其他工具绑定的事件。
> 
> 不过换个方法的话可能 PixivPreviewer 那边要改的代码会多一些，就先这样吧。

行 我会尝试向 PixivPreviewer 那边报告这个问题

**Comment by xuejianxianzun** [comment]
倒也不用报告，从代码来看那边要改起来的话估计会挺费事。

**Comment by Hakoyu** [comment]
那就先放着吧

**Comment by xuejianxianzun** [comment]
我想了想，如果他那边愿意把我上面的两行代码加进去倒是挺方便的，就是不知道他愿不愿意了。

```js
            const eventElement = firstImageElement.querySelector('[data-mouseover]')
            eventElement && eventElement.removeAttribute('data-mouseover')
```

你可以去提一下，附上这个 issues 链接。

**Comment by Hakoyu** [comment]
好的

**Comment by Ocrosoft** [comment]
感谢大佬提供的修改思路，cloneNode 还是为了尽可能保留别人添加的属性，避免其他脚本不能通过 class/attr 来查找元素，事件的丢失确实没啥办法。

**Comment by xuejianxianzun** [comment]
> 感谢大佬提供的修改思路，cloneNode 还是为了尽可能保留别人添加的属性，避免其他脚本不能通过 class/attr 来查找元素，事件的丢失确实没啥办法。

大佬不敢当。这种事情确实没有完美的办法，而且 cloneNode 还有个好处是不怕 pixiv 修改 className 之类的小变化。现在 pixiv 这种编译时生成的 className 太让人心烦了，不知道啥时候就会变，选择元素时提心吊胆的 /(ㄒoㄒ)/~~
