### ISSUE TITLE
可以添加浏览数下载限制吗？

### ISSUE THREAD

**Issue by telessa** [xuejianxianzun/PixivBatchDownloader#216]
收藏数下载限制用的并不顺手 还是有大量不用的图片被下载了 删除相当费时

**Comment by xuejianxianzun** [comment]
目前没有这个计划。

浏览数量高的，收藏数量（图片质量）不一定高。
如果你想筛选高质量的图片，浏览量还不如收藏量可靠。

**Comment by telessa** [comment]
> 目前没有这个计划。
> 
> 浏览数量高的，收藏数量（图片质量）不一定高。 如果你想筛选高质量的图片，浏览量还不如收藏量可靠。

好吧
