### ISSUE TITLE
手动选择的作品总是自动下载

### ISSUE THREAD

**Issue by 203saber** [xuejianxianzun/PixivBatchDownloader#217]
用谷歌让浏览器抓取后，我手动选责作品，然后抓取选择就会自动下载，抓取的数量在300左右，不知道是不是数量的问题，首先谷歌上的自动下载我是关过的，然后就是插件也没有选择自动下载，不知道是什么原因？

**Comment by 203saber** [comment]
300

**Comment by 203saber** [comment]
用谷歌让浏览器抓取后，我手动选责作品，然后抓取选择就会自动下载

**Comment by 203saber** [comment]
抓取的数量在300左右，不知道是不是数量的问题，

**Comment by xuejianxianzun** [comment]
通过某些方式建立的下载任务会自动开始下载，即使你关闭了“自动开始下载”。
