### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by juanhu6317** [xuejianxianzun/PixivBatchDownloader#218]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details
![微信图片_20220614133154](https://user-images.githubusercontent.com/94777126/173500580-f8694cb2-4c40-4a1e-85e5-12b2f8f38e1d.png)

**Comment by xuejianxianzun** [comment]
这是个警告信息，目前不用管。
之前因为手机上的 Yandex 浏览器不支持 Manifest version 3，所以下载器没升级。不知道现在它支持了没。

**Comment by xuejianxianzun** [comment]
2022/06/27
Yandex 浏览器 22.7.0 仍然不支持 Manifest version 3 的扩展程序。

下载器现在在等待 Yandex 浏览器支持 V3。如果在年底时它仍不支持，下载器只能抛弃它了。
