### ISSUE TITLE
特定的图片一直下载失败

### ISSUE THREAD

**Issue by JamesLearning** [xuejianxianzun/PixivBatchDownloader#22]
chrome和Tempermonkey是最新的
Pixiv Batch Downloader是2.5.4

在下载大批量图片时经常中断，经过排查发现有特定的一些图片一直下载失败
即使点进去这个图的页面去下载也会失败
重现例子：illust_id=73909676
开发者工具控制台显示：
`GET https://i.pximg.net/img-original/img/2019/03/28/02/11/57/73909676_p0.jpg net::ERR_FAILED 200    content.js:3526`
但是手动点开大图完全正常，在开发者工具Network对比手动打开的图和之前下载失败的图，请求头没有任何区别。

**Comment by xuejianxianzun** [comment]
我今天测试是可以正常下载的。
你用了扩展版的话就把 Tempermonkey 里的脚本版关闭，只用扩展版。
现在你把扩展版删掉，通过离线安装更新到最新版，再试试。如果还是不行，就让我给你远程看看吧。
离线安装：
https://github.com/xuejianxianzun/PixivBatchDownloader/wiki/2.-%E5%AE%89%E8%A3%85#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85
