### ISSUE TITLE
[Feature Request] An online version of the Pixiv Batch Downloader

### ISSUE THREAD

**Issue by pyramidjack** [xuejianxianzun/PixivBatchDownloader#220]
Hey. Ya think you can make an online version of the Pixiv Batch Downloader similar to Furarchiver?: https://furarchiver.net/

**Comment by xuejianxianzun** [comment]
no plan.

**Comment by pyramidjack** [comment]
Ah come on! There's literally no Archiver Site that downloads entire galleries from Pixiv. Perhaps you could do some actual justice by creating an online version of the Pixiv Batch Downloader similar to Furarchiver?
