### ISSUE TITLE
建议对每个画师记录上次抓取并下载作品的时间以避免重复抓取消耗时间

### ISSUE THREAD

**Issue by Jobove** [xuejianxianzun/PixivBatchDownloader#221]
如题, 可以尝试添加一个功能, 抓取并下载某画师的作品后记录最后抓取时间, 下次抓取时从该时间开始避免重复抓取.

**Comment by xuejianxianzun** [comment]
你这一设想的目的是想只下载新作品吧，不过这个方法只能在理想情况下使用，不能应对一些特殊情况。

所谓理想情况就是用户抓取了这个画师的所有作品，以后每次去抓取就只抓取更新的作品。

如果前后两次抓取的设置条件不同，假如今天有一个作品抓取了，但是被排除了。明天再次抓取，修改了筛选条件，应该抓取并下载它，但是按照这个时间段的设计，压根就不会再去抓取它。

再比如用户第一次下载时只保存多图作品的第一张图。过了一段时间后又抓取了一次，这次想全部保存全部的图片，这也会出问题。

再比如用户第一次只抓取了画师第一页的最新作品，后来想抓取更早期的作品，也会出问题。

还有其他一些情况也会因为这个设计而导致抓取结果出错，并且难以被用户察觉。

要解决这些问题，不是记录下载时的时间段能做到的，至少需要为每个作品单独生成记录。不过这依然不能解决所有问题。

除了上面这些特殊的情况，还有一个问题，那就是作品是可以被修改的。我在以前做“不下载重复文件”时就考虑过:

如果一个作品抓取并下载后，以后不再抓取它，那么假如画师修改了一个作品的话，例如添加了更多的图片，或者重新上传了高清图片，甚至删除了这个作品。不再去抓取一次怎么能获取它的最新数据呢？除此之外别无他法。

所以重复的抓取是有必要的，而且画师页面里的作品数量顶多也就几百个，花不了多长时间。

你可以打开“不下载重复文件”，它的适用范围更广，考虑的也更周全。
