### ISSUE TITLE
系列小说的"设定资料"的保存

### ISSUE THREAD

**Issue by yfdyh000** [xuejianxianzun/PixivBatchDownloader#223]
https://www.pixiv.help/hc/articles/900000361863-%E5%B0%8F%E8%AA%AA%E7%B3%BB%E5%88%97%E7%9A%84%E8%A8%AD%E5%AE%9A%E8%B3%87%E6%96%99%E6%98%AF%E4%BB%80%E9%BA%BC-
例：https://www.pixiv.net/novel/series/8913386/glossary
https://www.pixiv.net/novel/series/1387445/glossary

**Comment by xuejianxianzun** [comment]
原来还有设定资料啊，以前都没见到过。

**Comment by xuejianxianzun** [comment]
我看了看可以加上这个功能，现在的打算是添加一个按钮单独保存设定资料为一个 txt 文件。

**Comment by xuejianxianzun** [comment]
合并系列小说时，感觉可以把设定加到开头部分。
不过“抓取系列小说”由于是每个小说分别保存成一个文件，就不能在每个文件的开头都加入设定了，那样太重复了。如果只在第一部里加入设定感觉也可以。

这样处理的话就不需要把设定资料单独保存成 txt 了。

**Comment by xuejianxianzun** [comment]
已在下一个版本里添加此功能，只有在系列页面使用“合并系列小说”时，会在文件里保存设定资料。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v12.3.5

**Comment by yfdyh000** [comment]
尝试v12.3.8发现，“合并系列小说”只保存了设定资料的标题和简介，但点进去是有更多内容的，例如 https://www.pixiv.net/novel/series/8913386/glossary/149493 的内容。包括可能有插图，例如 https://www.pixiv.net/novel/series/1459120/glossary/58955
Google搜“novel/series /glossary/ site:pixiv.net”能找到一些“设定资料”作例。

如果下载时能检测并将“设定资料”视作小说章节来保存、去重，就更方便了。或者保存到单独一个txt也可以。

**Comment by yfdyh000** [comment]
另外，Edge版扩展没有更新，目前是12.3.0。

**Comment by xuejianxianzun** [comment]
原来如此，每条设定还会有更详细的内容。现在使用的 API 不包含这些详细内容，要获取的话必须每条设定分别请求一次详情。有点懒得去做。

现在就是把设定资料作为第一章节来存储的（仅限 epub 格式，因为 txt 格式只是纯文本没有任何结构）。

现在的去重系统不能支持对设定资料去重。

保存到单独一个txt 没有这个打算，依旧保存在小说文件内吧。

edge 审核很慢，有时候可能要一周，我无法控制。

**Comment by xuejianxianzun** [comment]
12.3.9 版本可以保存更详细的内容了。

不过不能保存设定资料的图片，因为在 epub 里用 img 标签加载不了 p 站的图片。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v12.3.9
