### ISSUE TITLE
下载去重，建议感知内容的变化

### ISSUE THREAD

**Issue by yfdyh000** [xuejianxianzun/PixivBatchDownloader#224]
不下载重复的文件-严格，只是基于文件路径，作品、作者名或保存设置变化会重新下载，作品修订内容不会重新下载。
也许，基于作品id和内容字节数（或者乃至CRC或hash）来下载去重也是不错的。

**Comment by xuejianxianzun** [comment]
对于图像作品，下载器会记录作品被修改的时间，加以对比。
小说作品没有记录修改时间，不过问题不大，因为小说体积小，下载很快。下载了新的去覆盖旧的就行了。

**Comment by yfdyh000** [comment]
如果作品名没变但新增/修改了内容，去重会导致不重新下载吧。如果记录和对比字数，感觉实现比较简单，不过错别字修改可能识别不到。

**Comment by xuejianxianzun** [comment]
小说确实可能会这样，要解决这个问题还是需要记录修改时间才行。

**Comment by xuejianxianzun** [comment]
12.3.6 版本记录了小说作品的修改日期用于去重。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v12.3.6
