### ISSUE TITLE
不公开的收藏作品通过批量收藏后变成公开收藏，希望批量收藏时跳过已收藏作品

### ISSUE THREAD

**Issue by WUHIM** [xuejianxianzun/PixivBatchDownloader#225]

**Comment by xuejianxianzun** [comment]
不公开的收藏作品通过批量收藏后变成公开收藏:

你可以打开高级设置，把下载器的“收藏设置”改为“不公开”，之后你再用下载器进行收藏就是非公开收藏。

---------

希望批量收藏时跳过已收藏作品：

目前没有这个计划。不过有一个曲折的办法来实现：

在你要批量收藏的页面进行抓取，排除“已收藏”作品，只抓取未收藏作品。然后打开“下载之后收藏作品”功能，最后开始下载。

如果你仅仅是为了收藏，而不是为了下载，可以把“图片尺寸”改为“ 方形缩略图 (250px)”，这样下载速度会很快。
