### ISSUE TITLE
小说封面下载与过度访问

### ISSUE THREAD

**Issue by yfdyh000** [xuejianxianzun/PixivBatchDownloader#228]
https://github.com/xuejianxianzun/PixivBatchDownloader/commit/92183b0b14cf7da64959f4857d858cfce4f68e6b 新增了自动下载小说封面。
使用线程=3下载若干小说后，pixiv发出“过度访问”警告。
下载任务近2000项，去重后实际下载800多个txt 约20MB，含封面图则约550MB。
目前猜测，是否下载封面图的请求没有计入线程控制（任务数），所以使请求数及频次翻倍了。

在之前版本中，调高线程数（大概=5）后下载若干，遇到过“过度访问”警告，更早则没有，似乎与请求频次非常相关。

如果能识别和避免保存空白、“朴素”或重复的封面图，可能更好。不过也能用第三方工具处理。

**Comment by xuejianxianzun** [comment]
对于过度访问的情况我缺乏数据，你是在哪个页面抓取的，我去试试。

下载封面图的请求其实是受下载进程数控制的，在下载小说的本体时会决定是否下载封面。
在下载时，小说本体不会发起网络请求，所以请求数量取决于封面数量。
但是因为小说下载很快，封面图体积也小，下载也很快，所以请求的间隔会比较短。

识别封面是很难的，因为下载器并不具备识别图像内容的能力，自然也无法识别出空白、朴素的封面。

重复的封面现在只能通过 URL 来识别，但是所有小说的封面图的 URL 都是不同的，没有重复的 URL。

首先，有很多小说用的系统默认的封面图片，但是 pixiv 会在图片上叠加标题文字，合成一张新的图片，所以它们的 URL 是不一样的。
就像这种，文字是在图片里的：
![20220716_153347.jpg](https://s2.loli.net/2022/07/16/3gZ1475JV9QioTl.jpg)

其次，如果你上传自己做的封面，那么 pixiv 不会叠加文字，但是同一个图片上传到两个小说里，上传了两次，会生成 2 个不同的 URL。

**Comment by xuejianxianzun** [comment]
小说的封面图片的 URL 里包含日期字符串、作品 id、还有一串随机字符。
所以同一张图片，上传到两个小说里，它们的 URL 也肯定是不同的。

```js
"https://i.pximg.net/c/600x600/novel-cover-master/img/2022/07/16/16/40/08/ci17967034_6f6b742681ac1ff7f0effbcb7f94a67a_master1200.jpg",
"https://i.pximg.net/c/600x600/novel-cover-master/img/2022/07/16/16/39/28/ci17967032_adbd09bd505b471af19e2bda9b5b0c36_master1200.jpg",
```

**Comment by yfdyh000** [comment]
在 https://www.pixiv.net/novel/bookmark_new.php 页面，抓100页。

关于识别封面，了解和理解难度，只是个愿望，看来目前只能外部方式解决。如果用Canvas解析识别，恐怕对浏览器和程序设计有不小压力。

**Comment by xuejianxianzun** [comment]
我在小说搜索页面抓取和下载了2400个小说，带封面，花了20多分钟才下载完，没有被警告。
可能有些人几分钟就下载完了，或者短期内其他页面也有大量下载，所以会被警告吧。
目前对如何触发警告还是不清楚。

**Comment by yfdyh000** [comment]
> 我在小说搜索页面抓取和下载了2400个小说，带封面，花了20多分钟才下载完，没有被警告。 可能有些人几分钟就下载完了，或者短期内其他页面也有大量下载，所以会被警告吧。 目前对如何触发警告还是不清楚。

确实不太清楚怎么判断。我之前下载花了28分钟左右，八百多个txt（去重后）和大约2000个封面。
我暂时调低线程数，再观察看看。

**Comment by xuejianxianzun** [comment]
呃呃，下载完过去20分钟了，我突然收到警告邮件

**Comment by yfdyh000** [comment]
> 呃呃，下载完过去20分钟了，我突然收到警告邮件。 ![20220717_032126.png](https://camo.githubusercontent.com/2efe8e3577efa0f2cd54ca4affa4cb6bda150fffb40e99bf7317f12202b97fb5/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f31372f64535876636879596e5a4a4d4837552e706e67)

一样的邮件。所以，可能需要某些优化。比如同类访问加些延迟。

**Comment by xuejianxianzun** [comment]
我又去下载了几十个小说，能正常下载。所以下载器不能从请求数据里发现用户是否被警告。
比较难办，加延迟的话对效率影响比较大。

**Comment by wvwvwvwvw** [comment]
今天爬收藏突然多出报错代码500不知道是不是加了新的机制还是梯子问题（单次爬120个小说，一半报错），根据我被封号2次的经验(第二次永久封号)，短时间内(半天?)不要超过500个，单次不要超过200(因为下载过程中出现停顿一下然后发现访问出现延迟)，爬虫超量估计是先被客服审核然后决定是否封号(因为警告延迟不稳定，第二天早上突然被封)

**Comment by xuejianxianzun** [comment]
我找到了 pixiv 获取用户对话的 api：
https://www.pixiv.net/rpc/index.php?mode=latest_message_threads2&num=10&offset=0
在 pixiv 发送警告邮件的同时，pixiv 官方账号也会给用户发警告消息，我可以获取消息来进行判断。

**Comment by xuejianxianzun** [comment]
> 今天爬收藏突然多出报错代码500不知道是不是加了新的机制还是梯子问题（单次爬120个小说，一半报错），根据我被封号2次的经验(第二次永久封号)，短时间内(半天?)不要超过500个，单次不要超过200(因为下载过程中出现停顿一下然后发现访问出现延迟)，爬虫超量估计是先被客服审核然后决定是否封号(因为警告延迟不稳定，第二天早上突然被封)

500（Internal Server Error），服务器内部错误，p 站很少会这样啊，我没啥印象，不止是否与封号有关。

**Comment by yfdyh000** [comment]
> 我找到了 pixiv 获取用户对话的 api： https://www.pixiv.net/rpc/index.php?mode=latest_message_threads2&num=10&offset=0 在 pixiv 发送警告邮件的同时，pixiv 官方账号也会给用户发警告消息，我可以获取消息来进行判断。

如果第二次警告就封号，获取消息不太有用吧。

**Comment by xuejianxianzun** [comment]
> > 我找到了 pixiv 获取用户对话的 api： https://www.pixiv.net/rpc/index.php?mode=latest_message_threads2&num=10&offset=0 在 pixiv 发送警告邮件的同时，pixiv 官方账号也会给用户发警告消息，我可以获取消息来进行判断。
> 
> 如果第二次警告就封号，获取消息不太有用吧。

第二次警告会发消息吗，是什么样的

**Comment by yfdyh000** [comment]
邮件写了“若此行为未能得到改善，我们可能会冻结此账号。”
六月份有一封邮件是“请停止过度访问。若此行为未得到改善，我们有可能停止或删除您的账号。”

以及上面的网友说第二次就永久封号，所以短期内二次触发，大概账号就没了。
还是要限制频次吧。感觉可能某些地方需要控制并发数量。

**Comment by xuejianxianzun** [comment]
我只有一次警告，是这个消息：
若此行为未能得到改善，我们可能会冻结此账号。

我感觉下载图片不太容易被警告，下载小说比较容易被警告。

**Comment by xuejianxianzun** [comment]
不过我遇到了个问题，消息数据里有个 `"modified_at": "1657999204",` 看起来像是日期相关，但不是日期或时间戳。
我还没搞明白怎么获取消息的日期。

**Comment by xuejianxianzun** [comment]
我添加了检测功能：
每当用户下载了 100 个文件，下载器就会检查一次最近消息，如果发现 1 小时内收到过警告信息，则自动停止下载。
![20220723_180928.png](https://s2.loli.net/2022/07/23/gPvcRVIbQtX7DBh.png)

**Comment by xuejianxianzun** [comment]
我的两个账号收到警告消息的时间都是 20 分整，你们的是这样吗？
2022年7月17日 3:20
2022年7月23日 17:20

**Comment by yfdyh000** [comment]
> 我的两个账号收到警告消息的时间都是 20 分整，你们的是这样吗？ 2022年7月17日 3:20 2022年7月23日 17:20

是的：
6月15日周三 05:20
7月16日周六 04:20

所以，是定期检查日志的程序？更可能只是定时发出警告消息。

> 我添加了检测功能： 每当用户下载了 100 个文件，下载器就会检查一次最近消息，如果发现 1 小时内收到过警告信息，则自动暂停下载。

我觉得，一天或一周内触发第二次，恐怕将凉。

从文件日期来看，我6月触发时是下载图片而非小说。估算，1分钟保存41个jpg 未触发，1分钟保存85个jpg 则触发。

**Comment by xuejianxianzun** [comment]
看来都是20分钟发的消息。
不知道第二次触发警告是否必定封号。
限制并发数量的话，我没想好什么时候应该限制，什么时候不限制。因为这有可能影响正常的下载。

**Comment by wvwvwvwvw** [comment]
封号流程是第一次先给你一个警告，第二次封号，给客服发邮件申请解封(估计需要不到一周的时间)，第三次直接封号，申请解封没有回复

**Comment by xuejianxianzun** [comment]
> 封号流程是第一次先给你一个警告，第二次封号，给客服发邮件申请解封(估计需要不到一周的时间)，第三次直接封号，申请解封没有回复

原来如此
