### ISSUE TITLE
扩展版Google应用商店已下架

### ISSUE THREAD

**Issue by oldking139** [xuejianxianzun/PixivBatchDownloader#23]
如题，今天想转移chrome扩展的时候发现已经404了
[https://s2.ax1x.com/2019/09/14/nsgNi6.gif](url)

**Comment by xuejianxianzun** [comment]
是的，目前只能离线安装。
https://github.com/xuejianxianzun/PixivBatchDownloader/wiki/2.-%E5%AE%89%E8%A3%85#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85
