### ISSUE TITLE
下載前先用zip打包

### ISSUE THREAD

**Issue by hospotho** [xuejianxianzun/PixivBatchDownloader#233]
因為一張圖一張圖下，每次都要開設定改不用確認位置，說實話多少有點不方便
如果忘了下載才開始改設定，慢了就一堆彈窗要確認
lib看到有jszip.min.js，應該可以在下載前先用zip打包

看source code現在是每次download都用sendMessage，發object url和file name等資料到background
現在大概想法是在SendToBackEndData 加上blob.size把fileSize也發過去
```ts
const sendData: SendToBackEndData = {
  msg: 'save_work_file',
  fileUrl: blobUrl,
  fileName: fileName,
  fileSize: number,
  id,
  taskBatch,
}
```
然後下載交給ZipWorker，onMessage收到後把上面的資料和tabId發給ZipWorker
```ts
//background都是用array，用tabID當index好像有點浪費空間，這邊都用map當數據結構
let dlZip = new Map<number, jszip>()
 
export async function pushZip(
  taskBatch: number,
  fileUrl: string,
  filename: string
) {
  if (!dlZip.has(taskBatch)) dlZip.set(taskBatch, new jszip())
  const blob = await fetch(fileUrl).then((res) => res.blob())
  dlZip.get(taskBatch).file(filename, blob)
}

export function closeZip(taskBatch: number, name: string) {
  if (!dlZip.has(taskBatch)) return
  let zip = dlZip.get(taskBatch)
  zip.generateAsync({ type: 'blob' }).then(function (blob) {
    //直接搬jszip例子的saveAs，正式應該用chrome.downloads.download
    saveAs(blob, `${name}.zip`)
  })
  dlZip.delete(taskBatch)
}
```

dlSize到了設定的額度(500MB-2GB？)就下載
```ts
const maxZipSize = option.maxZipSize || 500 * 1024 * 1024
let dlSize = new Map<number, number>()

const taskBatch = msg.taskBatch
if(msg.fileSize + dlSize.get(taskBatch) > maxZipSize){
  //zipName暫時沒方便的方法拿，先假裝有一個getZipName()
  //可能用regex或者直接在content script傳過來實現這個getZipName()？
  closeZip(taskBatch , getZipName(taskBatch))
  dlSize.set(taskBatch, msg.fileSize)
}
await pushZip(taskBatch, msg.fileUrl, msg.fileName)
dlSize.set(taskBatch, dlSize.get(taskBatch) + msg.fileSize)

//下載結束後content script要發一次'download_complete'來closeZip
if (msg.msg === 'download_complete'){
  closeZip(taskBatch , getZipName(taskBatch))
  dlSize.delete(taskBatch)
}
```

**Comment by xuejianxianzun** [comment]
你需要 zip 打包功能的出发点是我之前没想到的，就是用打包来避免频繁弹出另存为对话框。

我最近思考过添加 zip 打包功能，但是这需要修改很多下载逻辑，例如保存下载记录、断点续传、不下载重复文件等。
比如有一些文件下载之后，暂存在 zip 数据里，但是页面被错误的关闭了，那么这些文件就应该恢复成“未下载”的状态，重新下载。
对于 zip 模式和普通模式，有多个地方要做判断，分别处理。所以我没有着手去做这个功能。

此外 zip 也有一些不完美的地方，比如 500MB 的分包，双倍的内存占用等。
如果一次下载要创建多个分包，那么能创建连续的分包吗（.zip, .zip.001, .zip.002 这样）？我感觉可能做不到。如果不是连续的分包，那么每个压缩包都会解压出一个文件夹，这样的体验也不好。

**Comment by hospotho** [comment]
下载逻辑好像不用改，主要是Download已經用createObjectURL把資料存進內存了，在'save_work_file'發送到background的時侯，前面的逻辑包括下載都已經弄好了
```ts
let file: Blob = xhr.response
const blobUrl = URL.createObjectURL(file)
```
至於保存下载记录、断点续传、不下载重复文件是在background實現的，依靠dlData dlIndex dlBatch保存紀錄和檢查
```ts
// 如果开始了新一批的下载，重设批次编号，清空下载索引
if (dlBatch[tabId] !== msg.taskBatch) {
  dlBatch[tabId] = msg.taskBatch
  dlIndex[tabId] = []
}

// 检查任务是否重复，不重复则下载
if (!dlIndex[tabId].includes(msg.id)) {
  // 储存该任务的索引
  dlIndex[tabId].push(msg.id)
  .......
}

//chrome.downloads.download的callback
(id) => {
  // id 是 Chrome 新建立的下载任务的 id
   dlData[id] = {
     url: msg.fileUrl,
     id: msg.id,
     tabId: tabId,
     uuid: false,
   }
}
```
ZipWorker只會取代chrome.downloads.download那數行代碼，紀錄可以在相同位置更新
```ts
//要分別用zip 模式和普通模式可以在下面這位置加一個if 檢查msg/option的zipMode
//或者普通模式的msg.msg用一個新的'save_single_file'，下單張圖片才用這個
//if(msg.zipMode === false)
//現在的版本
chrome.downloads.download({data}, callback)
//else
//zip版
await pushZip(data)
callback()
```
zip應該是不怕雙倍的内存占用，可以及時釋放。但zip的佔用加上原來的多線程下載和動圖轉換，確實可能對低配置的電腦(4GB ram左右？)不太友好，這情況要改回用普通模式
```ts
//有必要的話可以用navigator.deviceMemory檢查一下ram的上限
//1GB以下自動用普通模式，2、4、8GB各自增加zip大小的上限
pushZip(...){
  .......
  //使用後馬上釋放
  URL.revokeObjectURL(fileUrl) 
}
```

创建连续的分包的需求應該沒有，最大的動圖應該也不會起過100MB，在超過maxZipSize前closeZip，圖片就不需要被分到兩個不同的zip
```ts
if(msg.fileSize + dlSize.get(taskBatch) > maxZipSize){
  closeZip(...)
  dlSize.set(taskBatch, msg.fileSize)
}
```

要命名分包我建議是直接畫師名加index，zip.001很少有支持全部解壓的軟件。而且zip的名稱不同，而內部的資料夾名稱相同(保證zip模式下命名規則是{p_title}/{xxx} fileName就會有folder name的prefix了)，解壓縮後也會自動合併(至少在window上是)
```
//解壓前
artist01.zip->artist/1.png
artist02.zip->artist/2.png
//解壓後
artist/1.png
       2.png
//zip內只有單資料夾，應該不會發生下面這種的情況
artist01/artist/1.png
artist02/artist/2.png
```

**Comment by xuejianxianzun** [comment]
>至於保存下载记录、断点续传、不下载重复文件是在background實現的，依靠 dlData dlIndex dlBatch保存紀錄和檢查

我感觉不行吧，现在这些操作是在前台完成的，抓取结果和任务状态、下载记录储存在 indexeddb 里，如果使用 background 里仅在运行时存在的  dlData dlIndex dlBatch 是不能完成持久化存储，以及浏览器异常关闭后恢复数据的功能。

**Comment by xuejianxianzun** [comment]
navigator.deviceMemory 作用有限，它最大只会返回 8，而且我们也无法得知用户剩余的可用内存，稳妥起见压缩包的体积还是用 500MB 算了。

**Comment by hospotho** [comment]
> 我感觉不行吧，现在这些操作是在前台完成的，抓取结果和任务状态、下载记录储存在 indexeddb 里，如果使用 background 里仅在运行时存在的 dlData dlIndex dlBatch 是不能完成持久化存储，以及浏览器异常关闭后恢复数据的功能。

翻了一下，把資料储存到indexedDB的code應該是在BG、Deduplication和Resume，能看到IDB.put等操作。那既然原來就不是在background和download更新indexedDB，那麼只改background的code對已有的持久化功能沒有影響才對

> navigator.deviceMemory 作用有限，它最大只会返回 8，而且我们也无法得知用户剩余的可用内存，稳妥起见压缩包的体积还是用 500MB 算了。

說實話現在的電腦的ram也沒那麼少，500MB放內存直接當沒問題好了。如果後續要支持更大的大小或者想消耗更少的內存，那時候再學mega的做法用a[download]、FileSystem API和IndexedDB吧

**Comment by xuejianxianzun** [comment]
非也，下载器原本的涉及是每当保存完一个文件，就把它的下载状态设置为“已下载”，保存到 indexeddb。并生成一条下载记录，也保存进去。
如果做打包下载，就只能暂存压缩包里的文件的这些状态，等到压缩包保存成功之后才能写入到 indexeddb。
如果中途用户停止下载，这些暂存的变化应该丢弃。
如果页面异常关闭，在重新打开之后，因为这些文件没有保存下载状态，就要重新下载。

------------

不下载重复文件功能也受到影响，之前如果一个文件保存完了，就保存它的下载记录。如果打包的话，在它所属的压缩包下载之前，它不会生成下载记录（因为它没有真的被下载到硬盘上），它也就不会被视为重复文件，从而可以重复下载。

**Comment by xuejianxianzun** [comment]
其实我还有一个疑惑，和你的习惯有关（每次都询问下载位置）：
如果有大量的下载任务（比如抓取自己的书签，或某个tag下的所有作品等），文件数量以万计。用现在的下载模式是可以挂机下载的，但如果是打包+手动选择保存位置，那么挂机下载是否会出问题？
比如说，一共会创建 10 个压缩包（每个 500MB），出现了 10 个另存为对话框，但是由于无人值守，对话框都不会消失，那么这 10 个压缩包（5GB 内存）一直在占用着内存，是否会导致页面崩溃呢？那么这次下载就完全的失败了。

**Comment by xuejianxianzun** [comment]
其实之前我设想的对于“打包下载”这个功能的需求是用于“归档”，或是打包后以便于上传到网盘、分享给别人等。但是我想，用户可以在下载后手动创建压缩包，这是一个很简单的事情，所以打包功能并不是一个必须的功能。
看了你提的这个 issues 之后我才意识到，打包这件事和“是否询问保存位置”竟然也会有关联。
不过，用打包来减少确认“另存为”对话框的出现次数，还是治标不治本。归根到底这是个批量下载器，就算打包，在大量下载时也可能产生多个打包。要解决你的问题，最好还是关闭“询问保存位置“的设置。
可惜的是，扩展程序无法检测和修改浏览器设置，否则下载器就可以在必要时发出提醒了。
我现在不太想为了打包功能去做一些代码和逻辑上的修改，打包功能先搁置吧。

**Comment by hospotho** [comment]
>比如说，一共会创建 10 个压缩包（每个 500MB），出现了 10 个另存为对话框，但是由于无人值守，对话框都不会消失，那么这 10 个压缩包（5GB 内存）一直在占用着内存，是否会导致页面崩溃呢？那么这次下载就完全的失败了。

原來想說普通設一個上限或者直接靠performance.memory檢查，但想想Chrome本來就不是等你點下去才開始下載，任務開始就已經在硬盤上暫存，Chrome用家應該多少有看過.crdownload這個副檔名吧。這情況還佔用内存應該是沒弄好閉包，GC以為還有用而沒回收内存

>其实之前我设想的对于“打包下载”这个功能的需求是用于“归档”，或是打包后以便于上传到网盘、分享给别人等。但是我想，用户可以在下载后手动创建压缩包，这是一个很简单的事情，所以打包功能并不是一个必须的功能。

簡單抄點jszip的例子和復用原有indexDB的code，就不用面對數以千甚至萬計的下載紀錄，還有大量持續彈出的下載任務阻礙你正常使用，也能順便提供一個空窗期避免錯誤下載等情況要額外的清理，加上打包自帶的好處(不產生檔案縮圖，移動檔案位置的速度更快等)。那麼多優點交換完全挂机這所謂優點也夠值得了吧，而且後續要弄完全挂机也不是沒辦法實現，用File System Access API就可以下一個十幾GB的zip了(但應該沒這必要吧，而且出錯重建還麻煩)

要掛機肯定不是常態，有3MB網速沒卡rate limit多線程下載10GB也不用1小時，普通畫師全下原畫尺寸不說1GB、500MB也已經算是多的了。要爬蟲幾百個畫師甚至要自動更新的人，就會直接寫個python腳本掛server上了

>可惜的是，扩展程序无法检测和修改浏览器设置，否则下载器就可以在必要时发出提醒了。
我现在不太想为了打包功能去做一些代码和逻辑上的修改，打包功能先搁置吧。

如果真的不打算弄打包一次改善那麼多問題，那至少暫時在開始下載前改一下[setShelfEnabled](https://developer.chrome.com/docs/extensions/reference/downloads/#method-setShelfEnabled)，下完改回來，禁用那煩人的下載ui和動畫

我等有空研究完那堆indexDB的code就弄一個zipWorker的branch，測試完內存甚麼的就發個pr給你

**Comment by xuejianxianzun** [comment]
内存占用问题以后再测试吧。

“大量持續彈出的下載任務阻礙你正常使用”，这是在每次下载都询问保存位置的前提下才会有的， 不是所有人都有此问题。

不产生缩略图、移动更快，但是你下载 zip 之后不解压出来查看吗？如果只是存档，确实可以避免这些问题，但是大部分情况下，下载下来还是要解压的，那么这些情况就依然会出现。

在广大用户中，会编程的人始终是很少数，你这有些理想化了。

在12.3.0版本里我会添加一个选项用于隐藏下载栏。

我确实不想做打包功能，不仅是因为它会增加一些下载逻辑，使代码更复杂，但更重要的原因是很少有人真的需要下载为 zip 文档。这 200 多个 issues 以及数个 QQ 群里都没有人提过这个需求。
你对打包的需求基本上是为了减少另存为对话框的次数，从这一点出发的人应该也是很少的。
不过下载了压缩包之后，通常还是要找到压缩包，解压出来，这反而增加了操作量。
其实我觉得手动选择保存位置没有那么方便，因为如果你有多个常用的目标位置，就需要经常在另存为对话框里跳转到不同位置。
如果自动下载到默认位置，其实操作量上也差不多。这样也可以先只管存放多次下载的文件，等有闲暇了再集中整理。
如果使用一些第三方资源管理器，可以把文件（夹）一键从默认下载位置移动到预设好的常用位置（而不需要打开目标文件夹窗口）。只需在默认下载文件夹里就可以直接进行操作，比如：
![20220729_031052.jpg](https://s2.loli.net/2022/07/29/uYZ5xbIncoX8ASW.jpg)
*（这个软件是 xyplorer） 仅仅是一点建议*

**Comment by hospotho** [comment]
>“大量持續彈出的下載任務阻礙你正常使用”，这是在每次下载都询问保存位置的前提下才会有的， 不是所有人都有此问题。

感覺你理解錯了，雖然忘關询问位置出視窗也很煩，但對我產生困擾的不是視窗
像這個隨便找的影片的1:05 https://youtu.be/AGmr2-nOTjk

![image](https://user-images.githubusercontent.com/50175140/181800382-f074dbca-58e3-4820-8732-7d78525e1d55.png)

這個箭頭動畫、新建任務動畫和下載任務列，即使已經不询问保存位置，每次下載也都會出現。而且並非固定在下載分頁的視窗，當前用那個視窗就會在那個視窗出現。幾百次下載每次都左一個動畫下一個動畫再加一個任務列，三個不能關閉一直在動比彈窗還煩的東西，沒人覺得困擾提需求也是奇怪

打包確實不是我主要的需求，但就是能同時解決很多其他需求所以才提的。話說要從常用的地方移动東西到常用的某處，感覺你直接用explorer的快速访问就夠快了，在下載ctrl+x資料，點一下pin在快速访问的資料夾ctrl+v就完了

>如果自动下载到默认位置

我用詢問位置其實就為了卡下載一下，不會被網站自動下垃圾。搜索引擎隨便送你進一個手機版網頁，突然就下一個apk也不免太多，還有甚麼圖片影片pdf連結你直接開就有機會偷下。就算不管甚麼安不安全，單是要自己刪就很煩。除了在不在意還有別的因素，但就當是個人的習慣不用展開了

**Comment by xuejianxianzun** [comment]
原来如此。
13.0.0 版本我已经送审了，如果速度快的话明天应该能通过，到时候你可以隐藏下载栏先凑合一下。

**Comment by hospotho** [comment]
那我先close issue了
