### ISSUE TITLE
抓取时能不能添加一个宽高比小于等于某个值的功能

### ISSUE THREAD

**Issue by qq772519864** [xuejianxianzun/PixivBatchDownloader#234]
批量下载恋活的人物卡都是竖图但是宽高总是各不相同。但是比值大概都是一个小于0.72的。

**Comment by xuejianxianzun** [comment]
还真是，现在只有大于等于，没有小于等于。
以后我加个吧。

**Comment by xuejianxianzun** [comment]
即将发布的13.0.0增加了此功能。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v13.0.0
