### ISSUE TITLE
抓取出错：Pixiv 返回了空数据

### ISSUE THREAD

**Issue by telessa** [xuejianxianzun/PixivBatchDownloader#236]
Powerful Pixiv Downloader
13.1.2

Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。 无权访问 56000180，跳过该作品。status: 500

诸如此类的提示 几分钟后确实会恢复抓取 但是只要几个就会继续提示500 也没有邮件提醒

请问这是节点问题 还是账户进了某种黑名单

**Comment by xuejianxianzun** [comment]
抓取太多被 Pixiv 限制了。
等待几分钟可以恢复正常，但如果继续大量抓取就会重复此过程。

**Comment by telessa** [comment]
> 抓取太多被 Pixiv 限制了。 等待几分钟可以恢复正常，但如果继续大量抓取就会重复此过程。

目前试了换小号 换节点 降低抓取并行为1 都不行 只能抓200多 就500了 
一个画师也就300多图 都要3分钟以上了

如果多注册几个账号 每扫描几十张就换自动账号扫描 会不会好呢

**Comment by xuejianxianzun** [comment]
让下载器来自动切换账号吗？没有这个打算。

**Comment by telessa** [comment]
> 让下载器来自动切换账号吗？没有这个打算。

好的
