### ISSUE TITLE
13.1.2导出的下载记录体积变小

### ISSUE THREAD

**Issue by hongsongshu** [xuejianxianzun/PixivBatchDownloader#237]
13.1.2读取8月1日及以前导出的下载记录数据会丢失部分数据,而且13.1.2生成的下载记录文件.json有点问题?editplus不能正常编辑了.13.1.3还未更新,不知道是否已修复.

**Comment by hongsongshu** [comment]
实测13.0.0读取13.0.0及以前版本生成的下载记录文件后再保存生成的文件是正常的,和读取的文件档一致,13.1.0及以后版本读取后生成的记录文件档变小了,可能是部分数据遗失了?

**Comment by xuejianxianzun** [comment]
你应该打开文件看一下内容是否有差异，比如某个 id 的记录，在前后两次导出的文件里有什么差别？

https://github.com/xuejianxianzun/PixivBatchDownloader/blob/master/CHANGELOG.md#%E4%BF%AE%E5%A4%8D%E4%BA%86%E5%AF%BC%E5%87%BA%E4%B8%8B%E8%BD%BD%E8%AE%B0%E5%BD%95%E6%97%B6%E5%8F%AF%E8%83%BD%E5%A4%B1%E8%B4%A5%E7%9A%84%E9%97%AE%E9%A2%98

```
ver 13.0.1

修复了导出下载记录时，可能失败的问题
如果下载记录的数据量太大（超过 512MB），之前的版本就无法导出下载记录。这是因为 JSON.stringify 生成的字符串如果长度大于 512MB，会产生内部错误。

现在修复了此问题。
```

这个修改会导致：同样的数据，从这个版本开始，导出的文件体积会比之前的体积小。
这是因为修改之后，文件内容在导出时不会格式化，以减少体积和导出时的内存占用。

**Comment by hongsongshu** [comment]
哦 估计就是没格式化导致editplus无法打开文件

**Comment by hongsongshu** [comment]
感谢您的回复,我也已找到处理用的软件.

2022-08-10 17:01 GMT+08:00, xuejianxianzun ***@***.***>:
