### ISSUE TITLE
出现多次status: 500

### ISSUE THREAD

**Issue by xyx017** [xuejianxianzun/PixivBatchDownloader#238]
不了解是否是pixiv服务器的问题。
在抓取过程中处理一部分作品就会产生较多的无权访问，跳过作品，并显示status: 500，然后停止抓取，一段时间之后继续抓取又会经历同样的问题
极大地延长了下载时间

**Comment by yotv2000tw** [comment]
是的，我這邊也是在剛剛稍微下載一些圖檔，結果才剛開始抓就跑出status: 500錯誤代碼

```
沒有權限存取 [Pixiv id](https://www.pixiv.net/i/Pixiv id)，跳過該作品。status: 500
Pixiv 返回了空資料。下載器已暫停抓取，並且會在等待幾分鐘後繼續抓取。
```

我最近是不常使用，但以前沒有發生過這種現象，而且這也才抓一下子
不知道原因是甚麼

**Comment by xuejianxianzun** [comment]
这是因为 Pixiv 的反爬取策略，以前没有这种策略，现在大规模应用了。

**Comment by xuejianxianzun** [comment]
#236
