### ISSUE TITLE
[ Error ] crawling bookmark_new_illust error

### ISSUE THREAD

**Issue by YuzuWiki** [xuejianxianzun/PixivBatchDownloader#239]
- Browser: **Microsoft Edge  103.0.1264.77 (64)**
- System : **Win11** 、 **Manjaro KDE 5.24**
- plugin version: **Powerful Pixiv Downloader**  **13.10**

- INFO:
  - 抓取页面: https://www.pixiv.net/bookmark_new_illust.php
  - 抓取页数：10 页
  - 信息： 
    - 界面可观测信息
      >  抓取完10页作品信息后， 如下提示：
      >     ......
      >     无权访问 [100223595](https://www.pixiv.net/i/100223595)，跳过该作品。status: 500
      >     Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。
      >     ......
      > 
       
      || 抓取前| 抓取后| 
      | --- | --- | --- |
      | 访问作品页面| ✔|✗ (短暂时间无法访问)|

    - 终端观测信息：
      - 请求信息： 

        - Url: https://www.pixiv.net/ajax/illust/100350327
        - Method: GET
        - HttpCode: 500
        - Response:
              {
                      "error": true,
                      "message": "出现错误。请稍后再试。",
                      "body": []
              }
         
    - 问题出现时间： 8.9 日起
  - 尝试解决手段：
    - 换帐号 （无效）
    - 换代理 （无效）
    - 清除cookie 等浏览器信息 （无效）： 未尝试无痕模式

**Comment by YuzuWiki** [comment]
#### remark
直接批量抓取某画师不会触发以上问题

**Comment by telessa** [comment]
> 

会不会是这个画师的图太少了 少于200 所以没触发

试试这个画师呢
https://www.pixiv.net/users/811927

**Comment by YuzuWiki** [comment]
> 

感谢你提供的画师  (≡^∇^≡)
测试后发现。。 也会触发 上述问题。。。_(°:з」∠)_ 麻了。。

**Comment by YuzuWiki** [comment]
> > 
> 
> 会不会是这个画师的图太少了 少于200 所以没触发
> 
> 试试这个画师呢 https://www.pixiv.net/users/811927

感谢你提供的画师  (≡^∇^≡)
测试后发现。。 也会触发 上述问题。。。_(°:з」∠)_ 麻了。。

**Comment by xuejianxianzun** [comment]
>获取需要爬取作品列表后，可直接进入下载阶段， 而不是获取作品详细信息后再下载呢？

不能。

另见： #236
