### ISSUE TITLE
“未分类”功能

### ISSUE THREAD

**Issue by AgMonk** [xuejianxianzun/PixivBatchDownloader#24]
https://www.pixiv.net/bookmark.php?untagged=1

使用该页面可以显示出当前未分类（直接点击爱心收藏）的图片，但是在该页面使用本扩展下载时并不会下载该页面显示的图片，而是收藏夹主页显示的图片。

该问题大概从2.4版本开始出现，我尝试使用油猴脚本发现没有这个问题。

**Comment by xuejianxianzun** [comment]
谢谢反馈，确实是有了bug，我将在下个版本更新，预计下午可以发布。到时候再回复你~

**Comment by xuejianxianzun** [comment]
已更新~
