### ISSUE TITLE
抓取能不能限速啊

### ISSUE THREAD

**Issue by huhaku** [xuejianxianzun/PixivBatchDownloader#240]
经常抓取到一半P站就返回500,抓取能不能限速,例如抓取一个作品暂停几百毫秒

**Comment by xuejianxianzun** [comment]
如果抓取几百、几千个作品，每次暂停几百毫秒就不会被限速了吗？我觉得不一定，还得试验过才能知道。
而且抓取的多了才会被限制，抓取的少就没有这个问题，所以限速的话也要分情况使用。

**Comment by YuzuWiki** [comment]
> 如果抓取几百、几千个作品，每次暂停几百毫秒就不会被限速了吗？我觉得不一定，还得试验过才能知道。 另外，大量抓取时，现在的等待方式与限速方式，哪种花的时间更少，也需要测试。
> 
> 抓取的多了才会被限制，抓取的少就没有这个问题，所以限速的话还得分情况使用。
> 
> 等我有空了试验下吧。

你好， 我想是因为抓取过程中调用作品信息部分频率太高导致的。。可参见下图
![image](https://user-images.githubusercontent.com/73649332/184647398-292fde48-6aff-4230-9d29-8f1da3a14e84.png)

这部分是不是我们能对其优化下呢？ 比如获取少批量作品信息后开始下载？ 下载途中再获取接下来需要爬取的作品信息数据？ 
> 当然这会影响到下载前保存抓取作品数据的问题。。

**Comment by xuejianxianzun** [comment]
> 漏桶算法

大量抓取时这样没用的，我同时只发送 1 个请求，并且每个请求后等待 1 秒钟，都依然会被限制，只是限制的次数少了。

**Comment by qiuqiumaomao** [comment]
你们抓那么多干啥呀，一般要抓的人不是用爬虫吗

**Comment by xuejianxianzun** [comment]
> 你们抓那么多干啥呀，一般要抓的人不是用爬虫吗

本工具也是爬虫来着。

不知道其他能够大量抓取的 pixiv 爬虫有没有受到此限制。

**Comment by huhaku** [comment]
> > 漏桶算法
> 
> 大量抓取时这样没用的，我同时只发送 1 个请求，并且每个请求后等待 1 秒钟，都依然会被限制，只是限制的次数少了。
> 
> 至于是什么算法我不知道。

估计你抓得太厉害了,我目前这样改之后就暂时没事了.可能是我抓得少,每天才爬万把页

**Comment by huhaku** [comment]
> > 你们抓那么多干啥呀，一般要抓的人不是用爬虫吗
> 
> 本工具也是爬虫来着。
> 
> 不知道其他能够大量抓取的 pixiv 爬虫有没有受到此限制。

一样有限制的,目前我试出来封是按IP去封,换个代理就好了,就是不知道封多了对账号有没有影响,商业级爬虫一般都是多IP多账号集群式去爬

关注的画师多了,自然抓的也多,就每天定时抓抓关注页都能封几十次

**Comment by xuejianxianzun** [comment]
从 13.4.0 版本开始增加了“减慢抓取速度”的设置。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v13.4.0

**Comment by xuejianxianzun** [comment]
几百毫秒的延迟时间是不够的，下载器现在设置的 1.2 秒是我多次测试后的出的，我使用此间隔不会被限制。（缩小至 1.1 秒就会被限制了）
不过我在 pixiv 的网络请求时间大约在 200-300 ms 之间，如果有人的请求时间特别少，即使 1.2 秒也有可能被限制，不过次数应该会减少。

**Comment by narugo1992** [comment]
@xuejianxianzun 

这边提供一条关于过度访问的情报。我的[爬虫项目](https://github.com/narugo1992/gchar)，需要对游戏角色的所有名字（中日英以及各种别称）在p站上的图片量数据进行统计，爬虫挂在github action上每日后半夜自动执行，五个游戏一共大约1w条请求，全程用时3h左右。这样的爬取行为昨天连着进行了两轮后，这边账号收到了【pixiv过度访问警告】。

希望对你们有用，以及也想了解一下各位关于p站过度访问检测的经验。

**Comment by xuejianxianzun** [comment]
> 

如果你爬取的是 pixiv 的搜索页面，那么遇到限制后返回的作品总数就是 0。对作品详情的请求会返回 429 状态码。

我的下载器在慢速抓取时，每隔 1.5 s 才会发出一个请求，这不会触发 429 限制。

如果不加以限制，大约每当连续抓取到 200 个左右的作品数据就会被限制。我的下载器在检测到限制后会等待 3 分钟后再继续抓取，你的爬虫可能持续不断的抓取才会触发过度访问警告。

**Comment by narugo1992** [comment]
> 如果不设置间隔的进行连续的抓取，大约每当连续抓取到 200 个左右的作品数据就会触发限制

我之前设置的间隔是0.2s，也基本上是这个数，差不多少。

> 等待 3 分钟后再继续抓取

我这边是等待30s，不过由于这边可能确实存在不少图片数真是0的情况，所以还不能直接retry，只能重新组织一轮。

现在我已经调整了爬虫策略，间隔3s，请求70次后强制暂停35s，明天看看效果如何。

**Comment by xuejianxianzun** [comment]
是的，搜索页面即使遇到限制，状态码也还是 200。如果有必要的话，可以请求随便一个作品的详情来判断状态码是不是 429。

你现在的间隔很久应该是不会触发限制的。star 了，嘿嘿。
