### ISSUE TITLE
功能添加请求：标记喜欢自动下载

### ISSUE THREAD

**Issue by Seele0oO** [xuejianxianzun/PixivBatchDownloader#241]
当用户对图片或者小说标记喜欢时，希望下载器可以自动按照抓取规则抓取并下载。

**Comment by xuejianxianzun** [comment]
锐意制作中。

**Comment by Seele0oO** [comment]
如果可以的话，在这里再增加一个发送aria2 rpc下载请求的功能就更好了。

**Comment by xuejianxianzun** [comment]
> 如果可以的话，在这里再增加一个发送aria2 rpc下载请求的功能就更好了。

重复的建议。

https://github.com/xuejianxianzun/PixivBatchDownloader/issues/154

**Comment by Seele0oO** [comment]
明白了，谢谢。
