### ISSUE TITLE
429 错误：下載器出現(沒有存取權限，跳過該作品)

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#242]
8/16日使用時很難成功下載大多被擋下

**Comment by benaify** [comment]
也是遇到这种情况，打开链接提示发生了错误。暂时不清楚是号因为抓取过度被黑了还是p站自己服务器问题。

**Comment by xuejianxianzun** [comment]
> 也是遇到这种情况，打开链接提示发生了错误。暂时不清楚是号因为抓取过度被黑了还是p站自己服务器问题。

短时间内大量的抓取导致了 Pixiv 暂时限制了你的账号。等待几分钟可以恢复正常。

在被限制期间你不能正常打开其他作品。

**Comment by xuejianxianzun** [comment]
13.3.1 版本开始，下载器对 429 错误的作品会重新抓取，请检查你的扩展版本是否符合要求。

**Comment by e1e1111e1e** [comment]
能夠讓抓取速度減慢嗎，因為我如果一張一張點下載的或張數不多時沒有出現被擋的情形。不過我不太懂程式不知有沒有用，這樣或許不會被暫時限制。

**Comment by xuejianxianzun** [comment]
减慢抓取速度是有用的，然而在不会被限制的前提下，每 1 秒最多只能抓取 1 个作品（即使这样，大量抓取时还是会被限制，稳妥起见需要至少 1.2 秒）。
这样花费的时间和目前的方式相比，并没有显著的减少。

**Comment by thanatul** [comment]
刚才连续触发限制到第十次出现了[No access **, skip.HTTP status code: 502]

**Comment by xuejianxianzun** [comment]
> 刚才连续触发限制到第十次出现了[No access **, skip.HTTP status code: 502]

502 Bad Gateway

这有可能是网络错误，也有可能是 Pixiv 的进一步限制措施，我尚不清楚。

**Comment by xuejianxianzun** [comment]
从 13.4.0 版本开始增加了“减慢抓取速度”的设置。
这可以避免出现 429 错误，代价是增加抓取所需的时间。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v13.4.0
