### ISSUE TITLE
What is the solution to error code 429?

### ISSUE THREAD

**Issue by GCUSCOCOa** [xuejianxianzun/PixivBatchDownloader#243]
When it starts crawling to download a bookmark, it gets an "Error code: 429 (too many requests).The downloader will re-crawl it. Pixiv returned empty data. The downloader will pause crawling and resume crawling in a few minutes.". 
And then it just quits.
I set the number of pages to crawl to 1 and it was the same. How can I solve this problem?

**Comment by xuejianxianzun** [comment]
Error code: 429.
Pixiv has recently implemented strict anti-crawling measures. It used to return a 500 error when crawling too many, now it's a 429.

**Comment by xuejianxianzun** [comment]
When this error occurs, the downloader will automatically pause and resume crawling after a few minutes.
Now can only wait.

**Comment by GCUSCOCOa** [comment]
If that's the case, I have hundreds of pages of bookmark illustrations I want to download, but for now I have to crawl through them one page at a time?

**Comment by xuejianxianzun** [comment]
Instead of scraping manually, you can use the downloader as usual, but it will take a lot of time. Keep this tab working in the background.
Pixiv is now limited to a maximum of 1 request per second when scraping in bulk. If you have tens of thousands of works to crawl, it will take tens of thousands of seconds or more.

**Comment by GCUSCOCOa** [comment]
What do you mean by "you can use the downloader as normal instead of manual scraping"? Does it mean that there is a way in the downloader settings to limit it to 1 request per second? And how can it be done?

**Comment by xuejianxianzun** [comment]
Start the crawl and wait for the crawl to complete.
There is no such setting now.

**Comment by GCUSCOCOa** [comment]
I understand. Thank you very much for your kind attention.
