### ISSUE TITLE
能不能自动保存抓取的结果

### ISSUE THREAD

**Issue by mcxuehu** [xuejianxianzun/PixivBatchDownloader#244]
是抓取过程中自动保存，不是抓取完后保存。（手动也行）
电脑挂了几天，待处理2万多（总数50万），看着停电公告，我陷入了沉思（希望Windows的休眠有用）

**Comment by xuejianxianzun** [comment]
额，虽然说可以应对停电，但是这需求理由属于极端情况啊。
休眠会把内存保存到硬盘里，正常来说应该是没问题的，只是我没试过。我经常用的是睡眠，内存不断电，这样肯定没问题。
