### ISSUE TITLE
 [Feature Request]抓取列表页时可手动设置抓取速度

### ISSUE THREAD

**Issue by thanatul** [xuejianxianzun/PixivBatchDownloader#245]
能否增加几个功能，可以设置：
读取列表页时，每读取[N]列表页停顿[N]毫秒再读取后继列表
抓取作品时，每抓取[N]个作品的下载地址停顿[N]毫秒再抓取后继作品
每抓取一个作品的下载地址后间隔[N]毫秒再抓取后继作品

这几天抓取的体验，抓取作品下载地址时一次达到140个左右就会被限制，读取列表页一次达到220个左右也会被限制。
手动选图抓取一次只抓100个左右作品肝了三个多小时没有遇到问题。
感觉似乎是针对不像人类能手动完成的请求设限。这几个选项的组合应该可以让使用者根据要抓取作品的数量设置自己可以接受的速度.

**Comment by xuejianxianzun** [comment]
我已经试验过了，每抓取 1 个作品就停顿 1 秒，又或者是抓取 100 个作品后停顿 60 秒，所花费的时间和现在差不多，甚至更久。
>手动选图抓取一次只抓100个左右作品肝了三个多小时
如果你让下载器去抓取，需要多久呢，未必会比你手动更久。

大量抓取时，每个请求之间至少间隔 1 秒（实际上还要再长一点）才不会触发限制。如果设置抓取的间隔，也不可能比这更快，因为如果你快了，抓取一多还是被限制。

**Comment by xuejianxianzun** [comment]
设置间隔的方法是行不通的，不过 discord 上有人提供了另一种思路，我接下来尝试一下。

**Comment by thanatul** [comment]
也许P站判断是否有爬取时监测的除了速度还有频率，毕竟普通的人类是不可能手动以完全相同的请求间隔进行查询的。也许可以给抓取作品的停顿间隔加个随机变量？ 

另外我觉得这里需要关注的不仅仅是速度，P站毕竟是有大量下载会被发警告邮件&封禁账号政策的，既然现在开始反爬取而且限制针对账号，那么将来过度爬取也变成封禁账号理由可能也只是个时间问题。所以对如我一样胆小的用户来说也许存在宁愿牺牲一点效率也不想频繁触发限制的需求(╥﹏╥)

**Comment by xuejianxianzun** [comment]
从 13.4.0 版本开始增加了“减慢抓取速度”的设置。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v13.4.0
