### ISSUE TITLE
[Feature Request] 发现页定时抓取，重复判断提前

### ISSUE THREAD

**Issue by mcxiaoke** [xuejianxianzun/PixivBatchDownloader#246]
1. https://www.pixiv.net/discovery 发现页每次刷新数据都不一样，根据个人偏好推荐的，能否支持定时抓取？

api应该是 https://www.pixiv.net/touch/ajax/recommender/illust?mode=all

还有个问题，发现页可以加载更多（和搜索页一样），目前好像是只抓取了第一页

3. 重复判断能否提前到获取作品详情前？而不是下载时判断，根据id即可，可以减少很多api请求

**Comment by xuejianxianzun** [comment]
1. 发现页面不支持定时抓取。定时抓取的应用范围是随着时间推移会有新作品出现的地方。发现页面上出现的作品比较随机，不适合定时抓取。
下载器并未使用这个 API，因为每次下载到的作品是不同的，并不是你在页面上看到的那些作品。
下载器在发现页面下载时，只会从页面上获取你现在看到的作品。

2. 重复下载不能仅根据 id 便提前判断，你这种想法的前提是作品自发布之后就不再变化了。然而一个作品发布后可能会有多种属性（包括图片）的修改，如果在下载前便因为 id 相同而排除了，那么就不能抓取到被修改的作品。
