### ISSUE TITLE
下载时，同时只有 1 个文件的进度在动

### ISSUE THREAD

**Issue by Ruo-bin** [xuejianxianzun/PixivBatchDownloader#247]
![Snipaste_2022-08-23_21-43-04](https://user-images.githubusercontent.com/39343596/186174115-8d55e142-8eb4-4180-80bd-3ac08a50a925.jpg)
始终只有其中一个在下载，只有一个在动

**Comment by xuejianxianzun** [comment]
你下载时梯子的下载速度是多少？
如果下载速度比较慢（例如 1MB/S），这些文件体积又都比较大（不能很短时间内下载完成），那么你看到同时只有 1 个文件在下载，这是正常的，因为这是 Chrome 内部的机制。

**Comment by Ruo-bin** [comment]
已经恢复正常了，可能刚刚梯子不稳定
