### ISSUE TITLE
请求更新可以一键收藏某个用户的收藏 

### ISSUE THREAD

**Issue by motian16** [xuejianxianzun/PixivBatchDownloader#250]
想着先抓取后下载选自动收藏 这样下次就不会重复抓取 重复下载 ，抓取下载都要用一个号，收藏能复制的话就不必只能用一个账号下载了 
不知道只是收藏的话会不会被pixiv限制

**Comment by xuejianxianzun** [comment]
你的意思是收藏过的作品，不再抓取和下载吗？

收藏某个作品，必须先抓取它的详细信息，所以“一键收藏某个用户的收藏”，其实就等于把他的收藏全部爬了一遍。

这没必要做新功能，你用你的新账号在旧账号的收藏页面全部抓取下载一遍，开启下载后自动收藏就行了。

不过下载时可以把图片尺寸设置为缩略图，以便加快下载速度。
