### ISSUE TITLE
手动选择作品支持一键选择整页

### ISSUE THREAD

**Issue by FishMagic** [xuejianxianzun/PixivBatchDownloader#251]
在 Pixiv 开始限制抓取速度之后，如果继续使用自动抓取下载收藏的图片会导致耗时过长，但是手动选择只能逐个作品的选择，请问是否可以在收藏页面实现一键整页的功能

**Comment by xuejianxianzun** [comment]
最快的抓取速度就是和以前一样，让下载器自动抓取完毕（不开启慢速抓取）。

你想手动一页一页下载吗？第一你这样没有下载器自动抓取快，第二你要想一次一页的话可以设置抓取页数为 1，然后开始抓取。
