### ISSUE TITLE
png的文件下载后文件名变成了xml

### ISSUE THREAD

**Issue by fjqingyou** [xuejianxianzun/PixivBatchDownloader#252]
不确定是什么因素导致的，是否还需要提供什么信息辅助定位？

OS
Windows 11 家庭中文版
22H2

Chrome 已是最新版本
版本 105.0.5195.102（正式版本） （64 位）

Powerful Pixiv Downloader
版本
13.6.0

**Comment by xuejianxianzun** [comment]
首先禁用其他扩展然后再下载试试。

如果问题仍然存在，请提供抓取时的网址，异常文件的截图。
也可以把抓取结果导出添加到附件。

**Comment by fjqingyou** [comment]
扩展中除了必要的代理，其他的都禁止掉了
然后两个截图，一个页面请求完整后清空网络请求结果，之后点击下载的截图。另一个则是控制台报错的截图，是否还需要提供什么？
[temp.zip](https://github.com/xuejianxianzun/PixivBatchDownloader/files/9541830/temp.zip)

**Comment by fjqingyou** [comment]
哦。控制台截图中，上面还有一小段
![image](https://user-images.githubusercontent.com/31087168/189514052-df3de809-9f09-499a-953c-efebba6835c6.png)

**Comment by xuejianxianzun** [comment]
异常文件的截图

**Comment by xuejianxianzun** [comment]
我可以正常下载，你下载所有作品都会这样吗？
你用的是什么梯子，换个路线试试？

**Comment by fjqingyou** [comment]
补充：文件是完整下载的。我只要重命名为.jpg什么的。是能够正常打开图片的。
![image](https://user-images.githubusercontent.com/31087168/189514187-7ac7d7c0-3697-4b87-8965-71f7e64e8a67.png)

**Comment by fjqingyou** [comment]
jpg和png会这样子，而gif不会。

**Comment by xuejianxianzun** [comment]
尝试更换梯子线路重新下载。

**Comment by xuejianxianzun** [comment]
![20220911_140448](https://user-images.githubusercontent.com/17283977/189514751-f7f1f6ee-ef56-407b-9866-e5159211100d.png)
当你下载这个图片时，查看响应标头里的 content-type，如果你的不是 image/jpeg，说明你的梯子存在问题，它篡改了响应标头。

**Comment by fjqingyou** [comment]
不是，不存在这个字段，应该是它的问题导致的了
![image](https://user-images.githubusercontent.com/31087168/189514615-13d2d3dd-8a0f-4c03-acbc-ccd1b18c8ea6.png)

**Comment by fjqingyou** [comment]
确认换到有这个content-type的环境下的，是能正常工作的！那么可以把这个issue关闭了？

**Comment by xuejianxianzun** [comment]
你这梯子挺离谱的，缓存信息也一概没有，建议换个梯子吧。

**Comment by fjqingyou** [comment]
嗯！感谢！
