### ISSUE TITLE
动图下载希望能转为webp格式

### ISSUE THREAD

**Issue by qteen1995** [xuejianxianzun/PixivBatchDownloader#253]
已有的webm基本只能用视频播放器浏览，webp兼容性好一点

**Comment by xuejianxianzun** [comment]
我没有添加webp的转换，是因为我没有找到合适的 js 库。
另外，你提 issues 时应该使用我预设的模板的。其中有一个步骤就是：
其他软件是否有此类功能？是否可以参考？

**Comment by xuejianxianzun** [comment]
长时间无回复，关闭此问题。
