### ISSUE TITLE
Translation to Ru/UA

### ISSUE THREAD

**Issue by bropines** [xuejianxianzun/PixivBatchDownloader#254]
I would like to translate the extension into Russian/Ukrainian, but I don't understand which files I have to edit.

**Comment by xuejianxianzun** [comment]
All text is in LangText.ts：
https://github.com/xuejianxianzun/PixivBatchDownloader/blob/master/src/ts/langText.ts

Each array stores a sentence and stores the translated text in a fixed order.
I don't know how many Russian and Ukrainian users the downloader has, but thanks for your help.

**Comment by bropines** [comment]
> All text is in LangText.ts： https://github.com/xuejianxianzun/PixivBatchDownloader/blob/master/src/ts/langText.ts
> 
> Each array stores a sentence and stores the translated text in a fixed order. I don't know how many Russian and Ukrainian users the downloader has, but thanks for your help.

Okay. Suppose I translate all the text in that file, how do I compile the program so that it has a setting for my language?
Or I can translate and make a pool requester, and you do the rest.

**Comment by xuejianxianzun** [comment]
You can modify this file and submit a PR, I will add the corresponding switch.

**Comment by bropines** [comment]
Is it possible to change fonts somehow? The current one in Russian looks sooooo painful
