### ISSUE TITLE
Layout issue on Dark Theme

### ISSUE THREAD

**Issue by zeppelin8101** [xuejianxianzun/PixivBatchDownloader#259]
**Describe the bug**
"show larger thumbnails" doesn't work well with Dark Theme on, some tall images will overlap with other images above them because the images lose a class that contains `height: auto !important` and `max-height: 540px` with Dark Theme on.

**To Reproduce**
Turn on these options in the extension settings
- show larger thumbnails
- Horizontal image takes up double the width
- Replace square thumbnails to show image ratio

Visit artist's Pixiv with tall vertical pictures, for example this artist [https://www.pixiv.net/en/users/1878082](https://www.pixiv.net/en/users/1878082) and turn on Dark Theme on Pixiv, not extension.

**Screenshots**
![chrome_2022-10_2217](https://user-images.githubusercontent.com/105969445/193416848-e6341688-b3e9-4075-ac66-d13615902a9f.png)

![chrome_2022-10_2216](https://user-images.githubusercontent.com/105969445/193416854-370c6b00-fc31-4f9d-88da-bdadd58b449b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Google Chrome
 - Version: 106.0.5249.91

**Comment by xuejianxianzun** [comment]
This issue has been confirmed and I will fix it in a future update

**Comment by xuejianxianzun** [comment]
fixed.
