### ISSUE TITLE
在移动端页面使用插件时会出现重复抓取且不下载的情况

### ISSUE THREAD

**Issue by Khvar** [xuejianxianzun/PixivBatchDownloader#26]
我是使用kiwi来实现在手机端也使用chrome插件的
在2.4版本中，该插件是可以正常使用的，即点击快速下载按键之后能够正确的抓取到链接并下载
今天更新到了最新版本的插件后，点击快速下载之后，插件会先抓取一个网址，然后并不执行下载，而是抓取第二次，也无法继续下载程序
![Screenshot_20190922_154455_com kiwibrowser browse](https://user-images.githubusercontent.com/55649731/65384082-96e19880-dd50-11e9-866f-2c564b64e6e6.jpg)
![Screenshot_20190922_154530_com kiwibrowser browse](https://user-images.githubusercontent.com/55649731/65384085-9ea13d00-dd50-11e9-8184-86af003e8032.jpg)

**Comment by xuejianxianzun** [comment]
我没在手机上用过，而且在手机上也很难调试。
我记得 pc 上没问题，手机上的话，如果你有时间，可以用 yandex 浏览器安装扩展试试，看能不能正常用。这样可以弄清楚是下载器的原因还是浏览器的原因。如果是下载器的原因的话，我看能不能找出来原因。
其实最近因为节日将近，我的梯子也不好用了，所以有时候我也没办法测试。

**Comment by Khvar** [comment]
> 我没在手机上用过，而且在手机上也很难调试。
> 我记得 pc 上没问题，手机上的话，如果你有时间，可以用 yandex 浏览器安装扩展试试，看能不能正常用。这样可以弄清楚是下载器的原因还是浏览器的原因。如果是下载器的原因的话，我看能不能找出来原因。
> 其实最近因为节日将近，我的梯子也不好用了，所以有时候我也没办法测试。

换了yandex也是同样的，还是连续两次抓取图片，第一次抓取到一个地址，第二次抓取到两个重复的地址，也都不会下载

毕竟过节了， 不着急hhhhh

**Comment by xuejianxianzun** [comment]
抓取两次之后，点击开始下载，能下载码
现在我对这个问题没什么头绪

**Comment by Khvar** [comment]
> 抓取两次之后，点击开始下载，能下载码
> 现在我对这个问题没什么头绪

不能下载，点击也不行，url那里是读到了，但是下面的下载进度那里既不会显示读到的id，状态也只是停在未开始下载，就像一楼的图二那样

**Comment by Khvar** [comment]
上面这些都是基于p站的手机页面
如果选择了桌面版网站，那一切都是正常的

**Comment by xuejianxianzun** [comment]
已修复
请更新到2.6.4
