### ISSUE TITLE
能否添加对Firefox的兼容

### ISSUE THREAD

**Issue by Seele0oO** [xuejianxianzun/PixivBatchDownloader#260]
**What functionality do you want?**
*你想要什么功能？*
对Firefox的兼容
**What is the purpose to solve?**
*目的是解决什么问题？*
Firefox上没有好用的类似插件
**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*
有类似但不参考
**Additional context**
*附加描述*
firefox 上传附加组件
https://addons.mozilla.org/zh-CN/developers/addon/submit/upload-unlisted

**Comment by Kairi5431** [comment]
Just wanted to chime in I also came here to find out if support for firefox would be possible.

**Comment by xuejianxianzun** [comment]
重复的问题。
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/88

**Comment by xuejianxianzun** [comment]
Firefox version:
https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/
