### ISSUE TITLE
Can't download images in novels

### ISSUE THREAD

**Issue by SubBarrierSystem** [xuejianxianzun/PixivBatchDownloader#262]
Sorry, I'm not good at englisg.So my grammar is may broken.
**Describe the bug**
*请描述你遇到的问题。*
When Try download novel "Download embedded images in novels".
Can't download images in novels.

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*
1.Enable "Download embedded images in novels"
2.Download specific novel
3.Can download novel and meta data.But can't download images in novels

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

1.ExportFile
![Download_Error](https://user-images.githubusercontent.com/115947520/196051867-1a5219a7-ccd4-4b34-8fbc-6eeb3cf82980.png)

2.https://www.pixiv.net/novel/show.php?id=17968738
3.ExportFile
[Powerful Pixiv Downloader Settings.zip](https://github.com/xuejianxianzun/PixivBatchDownloader/files/9795409/Powerful.Pixiv.Downloader.Settings.zip)

4.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows10
 - Browser Chrome
 - Version 106.0.5249.119（Official Build） （64 bit）

**Additional context**
This novel is nsfw, if it's probrem, i will find other novel.

**Comment by xuejianxianzun** [comment]
This problem has been reproduced, it should be because this novel is special, I will solve it later.

**Comment by xuejianxianzun** [comment]
The upcoming 13.9.0 release fixes this bug.
