### ISSUE TITLE
{question} How to create a folder to put the images?

### ISSUE THREAD

**Issue by SIREN587** [xuejianxianzun/PixivBatchDownloader#263]
Hello, i would like to know if there is a way to make a folder to put the images eg downloads/pixiv also, is there a way to make subfolders like this? downloads/pixiv/1

**Comment by xuejianxianzun** [comment]
Prepend your custom path to the naming rule, e.g. `downloads/pixiv/1/{user}/{id}`

**Comment by SIREN587** [comment]
Thank you very much xueji!
