### ISSUE TITLE
Changing font 

### ISSUE THREAD

**Issue by bropines** [xuejianxianzun/PixivBatchDownloader#264]
**What functionality do you want?**
*你想要什么功能？*

I would like a font-changing function. In Russian, for example, the current font looks awful.
![image](https://user-images.githubusercontent.com/57861007/197386375-ed17e5f2-db0d-40ef-aca3-99fe8111de5f.png)

**What is the purpose to solve?**
*目的是解决什么问题？*
Change the strange font to your own, or at least any font from google fonts

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*
I haven't seen any open source programs, and I haven't really looked for them

**Additional context**
*附加描述*

**Comment by xuejianxianzun** [comment]
What font is commonly used for Russian text?

**Comment by bropines** [comment]
I think this one's okay.
https://fonts.google.com/specimen/Comfortaa

**Comment by xuejianxianzun** [comment]
> I think this one's okay. https://fonts.google.com/specimen/Comfortaa

This font is more rounded and it is not suitable for everyone.

**Comment by xuejianxianzun** [comment]
![20221028_143655](https://user-images.githubusercontent.com/17283977/198519753-1061ef4e-65f1-4930-b3e9-4e71e67575f3.png)
On my system the russian font looks appropriate as my OS default font is Microsoft Yahei.
It looks like your system font is not appropriate.
I looked at a Russian website, how about using its fonts?
https://ria.ru/
```font-family: "NotoSans",Arial,sans-serif;```

**Comment by xuejianxianzun** [comment]
![20221028_144110](https://user-images.githubusercontent.com/17283977/198520479-6251cff6-97b7-4517-9578-b03ad8f9f1a9.png)
I see this, how about you?

**Comment by xuejianxianzun** [comment]
NotoSans doesn't seem to be a system built-in font, it needs to be loaded over the network. So it's easier to use `Arial`.
But I have a question, do other Russian users see the same downloader font as your screenshot? Is this representative?

**Comment by bropines** [comment]
This is a screenshot of my friend:
![image](https://user-images.githubusercontent.com/57861007/198689060-81716d14-c5d0-4fd9-9653-6e70bcb7efa4.png)
This is my screenshot: 
![image](https://user-images.githubusercontent.com/57861007/198689215-4609422d-5d88-4962-b9eb-34931d66744a.png)

The fact is that we support this font, even now on the same ria.ru
![image](https://user-images.githubusercontent.com/57861007/198689403-5caa24c0-cd1c-45aa-a06e-7a98ce5dbd62.png)

I sin that the browser is buggy, but not for two different people.

I thought it was possible to change the font, because there is such a feature in the extension for VK.

https://user-images.githubusercontent.com/57861007/198690116-105b752a-7ac5-4e5d-bc99-fd89693c3c57.mp4

https://chrome.google.com/webstore/detail/vk-styles-themes-for-vkco/ceibjdigmfbbgcpkkdpmjokkokklodmc?hl=ru

**Comment by xuejianxianzun** [comment]
ok, i will set the font for russian to `font-family: Arial,sans-serif;` in the next update.

**Comment by xuejianxianzun** [comment]
Since version 14.0.0, the downloader will set the Russian font to `sans-serif`.
