### ISSUE TITLE
多图里排序第一位直接是1可以吗

### ISSUE THREAD

**Issue by 1686565568** [xuejianxianzun/PixivBatchDownloader#265]
多图第一个和另一个插件第一位是01有冲突，会重复下载图，可以选择页数（第一张图就是01第二张图就是02）而不是默认的图片在作品的序号吗(p0 p1这种）

**Comment by xuejianxianzun** [comment]
我没有理解为什么这会导致重复下图。
目前没有此计划。

**Comment by 1686565568** [comment]
第一张就是01而非00

**Comment by xuejianxianzun** [comment]
为什么会重复，你会同时用这两个工具下载相同的作品吗？

**Comment by xuejianxianzun** [comment]
到现在我也没搞懂你的问题所在，下载器的第一张图片的文件名可能是 `102275107_p0`，另一个是 `102275107_01` 还是什么，难不成是 `102275107_p1` ？
就算名字不一样，只要不用两种下载器去下载相同的文件不就没有问题吗？
以前用那个工具下载的就用以前的名字，以后用另一种名字会如何呢？

**Comment by 1686565568** [comment]
定好的是id 标题 页数 按照文件p0排就不对，手动改很麻烦，算了，不麻烦了，谢谢大佬
