### ISSUE TITLE
希望增加一个可输入指定页数或数个作品的且能记住上一个设置的功能（设有页或作品数量单位选择）

### ISSUE THREAD

**Issue by benaify** [xuejianxianzun/PixivBatchDownloader#266]
因为有关注画师之后抓取全部作品的习惯，之前Pixiv没有抓取限制的时候还好，但是现在增加了限制手段无法快速抓取更新的作品。如果画师只更新几个（少量）作品，自己又不记得抓取了那些（应该从哪个作品开始抓取更新），就不得意再次抓取全部。虽然扩展内有可以输入抓取数量的功能，但是不便捷。我抓取一页就得把-1改成1，完事还要记得改回去-1，免得关注新画师的时候要抓取全部又只抓取了一页。

**Comment by xuejianxianzun** [comment]
那这个功能要以什么形式实现呢？
就算实现了，每次抓取前不还是要手动选择一下吗，没感觉好到那里去。

**Comment by benaify** [comment]
![Snipaste_2022-10-26_17-47-19](https://user-images.githubusercontent.com/56367786/197999280-d1eed733-2388-46cb-97cc-fd85204a5511.png)
你看这样是否可行，行不通的话就算了，不折腾。

**Comment by xuejianxianzun** [comment]
第一个抓取按钮总是全抓，第二个才使用之前设置的页数吗？感觉有点增加理解成本。
而且就算记忆上一个设置，但是需要变动时还是还是自己手动选择，意义有限。

**Comment by xuejianxianzun** [comment]
下载器会记忆你在不同页面类型里最后一次输入的页数。所以现在也不至于每次都要修改，还行吧。抓取前自己确认下抓取数量还是有必要的。

**Comment by kenshin000003** [comment]
抓取前自己确认是很重要，
但是不需要输入就可以在-1和1之间跳转，对于单手逛P站的情况也很必要😇。

我想了几个可能可行的实现方法，
方法3、方法4实现简单，但是不知道怎么跳过0。
所以 方法2 应该是目前我想到的最容易实现的方法。

![插件负1设置](https://user-images.githubusercontent.com/80815506/216242107-be3ac014-61ac-4b3a-8614-dd8421fc7bde.png)
