### ISSUE TITLE
收藏作品遇到 429 错误时重试

### ISSUE THREAD

**Issue by Lancercmd** [xuejianxianzun/PixivBatchDownloader#267]
**Describe the bug**
*请描述你遇到的问题。*

只有抓取会等待 `429`。
对于下载，当对应插画未下载时，下载的速度受网络和线程数限制；当对应插画已下载时，会直接跳过。
但如果启用下载后自动收藏，当对应插画未下载时效果同上，当对应插画已下载时就会尝试秒收藏，然后遇到 `429`，但不会停止。

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*

（尝试为已完成下载的插图添加收藏）
导入一个已完成下载的抓取结果，勾选下载后自动收藏的情况下，开始下载，在~200个操作时便会失败，但它会继续尝试之后的收藏。

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version 106.0.1370.52

**Additional context**

希望在下载时的自动收藏也能等待 `429` 即使这会导致用时大大增加。另外不知道失败的收藏会不会重试？

**Comment by xuejianxianzun** [comment]
从 14.0.0 版本开始，添加收藏失败时，下载器将会重试。
