### ISSUE TITLE
429错误

### ISSUE THREAD

**Issue by 203saber** [xuejianxianzun/PixivBatchDownloader#269]
之前，抓取下载的时候，几千个文件，没有过卡顿，现在抓取一两百个就要返空数据，不知道什么原因？望告知

**Comment by 203saber** [comment]
错误代码：429（请求数量过多）。下载器会重新抓取它。
Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。

**Comment by xuejianxianzun** [comment]
抓取时遇到 429 错误：
短时间内抓取太多作品就会这样。
即使发生了 429 错误，下载器依然可以完成抓取，只是需要的时间比以前更多。（下载器会重新抓取发生 429 错误的作品，所以你不用担心有作品被遗漏。）
发生 429 错误时，你无法正常浏览 Pixiv 的作品，这是因为你的账户被临时限制了，所以更换你的 IP 是无法解决此问题的。
如果你不想遇到 429 错误，可以在下载器的设置中启用“减慢抓取速度”。（但是这无法 100% 避免此问题）
