### ISSUE TITLE
建议：从收藏下载时可以选择特定id或者收藏顺序之后下载

### ISSUE THREAD

**Issue by ZhangPeiJiun** [xuejianxianzun/PixivBatchDownloader#27]
之前下载都是全部下载，可以开发一个设置项指向特定图片ID后开始下载或者按收藏时间顺序下载吗，加多一个TAG就行

**Comment by xuejianxianzun** [comment]
1.下载收藏可以指定页数
2.指向特定图片ID后开始下载的意思是想只下载新加入收藏的吗？
3.现在下载收藏就是按收藏时间的顺序下载的
4.如果你说的增加tag是为了上一条，那么没必要

**Comment by xuejianxianzun** [comment]
如果是想为了下载某个id之后收藏的作品，一般来说，你可以向后翻页，比如翻到第20页觉得到这里为止是还没下载过的，那么可以回到第一页，设置下载页数为 20.
也可以通过数量来计算页数，例如你上次下载的收藏是 1000 个，现在共有收藏 1200 个，可以计算出需要下载 10 页。
如果可以输入一个 id 往后下载，这需要单独增加一行设置，但这个功能使用的人又很少，我没什么动力去做。
