### ISSUE TITLE
抓取作品限制投稿时间时，有时抓取不到任何作品

### ISSUE THREAD

**Issue by tpexa** [xuejianxianzun/PixivBatchDownloader#270]
在“已关注用户的作品”和特定作者的作品页中抓取时都会遇到，但不是一直都能成功复现，例如限定起始时间是2010年1月1日0点0分，结束时间是2022年11月8日20点0分（比当前时间稍晚），有时会遇到抓取不到任何作品的情况，即使点进作品详情，确认投稿时间在设定的时间范围内也抓取不到。但是关闭限制投稿时间的选项后，就可以稳定成功抓取。
请帮忙看看可能是什么问题，谢谢

**Comment by xuejianxianzun** [comment]
出现问题时抓取的哪个作者，把页面 URL 发给我试试。

**Comment by tpexa** [comment]
> 

我最开始是在已关注的作者页面，发现这个情况后点击了其中一个作者作品页（https://www.pixiv.net/users/228427/artworks），发现上述问题也会出现。刚才试了一下，设定时间2021/1/1 00:00:00 - 2022/11/9 19:59:00，会有部分在此时间段内的作品抓取不到

**Comment by xuejianxianzun** [comment]
已确认问题，稍后我会排查原因。

**Comment by xuejianxianzun** [comment]
之前我搞错了，设置错了时间，导致有些作品没抓取到。
在 https://www.pixiv.net/users/228427/artworks 设置时间范围为 `2021/1/1 00:00:00` - `2022/11/9 19:59:00`，共抓取到 23 个作品，确认没有问题。
你抓取到多少个？如果少于此数量，请检查是否是因为其他过滤条件导致一些作品没有被抓取。

**Comment by tpexa** [comment]
> 这位作者的作品页确实如此，我也是抓取到23个。但是我测试了另一个页面，即已关注用户的作品（https://www.pixiv.net/bookmark_new_illust.php），限定时间范围: 2022/11/8 00:00:00 - 2022/11/9 18:00:00，抓取第1页（当前页），这时即使手动点开作品确认都是在这个时间范围内，也没办法抓取到任何作品。这个情况不知道您能不能复现？

**Comment by xuejianxianzun** [comment]
上个版本添加的优化措施导致了在时间范围间隔很小时可能存在问题。我会尽快发布新版本解决此问题。

**Comment by tpexa** [comment]
> 明白了，多谢

**Comment by xuejianxianzun** [comment]
14.0.1 版本了修复此问题。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v14.0.1
