### ISSUE TITLE
请问能不能提供下载记录导出和导入功能？

### ISSUE THREAD

**Issue by Duangex** [xuejianxianzun/PixivBatchDownloader#271]
**What functionality do you want?**
*你想要什么功能？*
把下载记录导出成TXT，并且可以导入TXT当下载记录

**What is the purpose to solve?**
*目的是解决什么问题？*
1.清除浏览器Cookie时会把下载记录删了
2.本地文件夹已经存在的图片可以把文件名批量输入到TXT里，然后导入到插件当成下载记录，避免下载到重复文件

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*

**Additional context**
*附加描述*

**Comment by xuejianxianzun** [comment]
在下载器的 [不下载重复文件](https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E8%AE%BE%E7%BD%AE-%E6%9B%B4%E5%A4%9A-%E4%B8%8B%E8%BD%BD?id=%e4%b8%8d%e4%b8%8b%e8%bd%bd%e9%87%8d%e5%a4%8d%e6%96%87%e4%bb%b6) 功能里，可以导出与导入下载记录（JSON格式）。

如果你需要自己制作 txt 格式的下载记录，参见：[导入 id 列表](https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E8%AE%BE%E7%BD%AE-%E6%9B%B4%E5%A4%9A-%E4%B8%8B%E8%BD%BD?id=%e5%af%bc%e5%85%a5-id-%e5%88%97%e8%a1%a8)

**Comment by Duangex** [comment]
好的了解，这个隐藏功能太实用了，非常感谢
