### ISSUE TITLE
想請問要如何解決GIF動圖轉換時電腦CPU會使用過度

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#272]
**What functionality do you want?**
*你想要什么功能？*

**What is the purpose to solve?**
*目的是解决什么问题？*

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*

**Additional context**
*附加描述*

**Comment by xuejianxianzun** [comment]
转换 GIF 时，CPU 的占用率和文件的体积、图像尺寸有关。这些指标越大，占用的内存和 CPU 可能越多。
这个问题无法解决。

**Comment by xuejianxianzun** [comment]
是这样的，不过下载器转换动图时会使用作品的帧延迟数据，如果下载 zip 压缩包在转换的话，你没有帧延迟数据就会与原图的速度不一致。

**Comment by kenshin000003** [comment]
帧延迟数据 是否可以导出？
放在 `meta.txt` 文件里，但是非动图的这里就会是空。
或者如果判断是动图，新开一个 `帧延迟数据.txt` 文件放在相同文件夹里？
没想出哪个更好。

另外，能否初始设定设置为：zip 压缩包，然后悬停在其他三种文件类型的时候，提示”容易造成卡顿“。这样做对高端电脑没什么改变，但是对老电脑就很有用了。
