### ISSUE TITLE
关于特殊类型的字符下载后的转换

### ISSUE THREAD

**Issue by scybbq** [xuejianxianzun/PixivBatchDownloader#273]
![2022-11-21_173456](https://user-images.githubusercontent.com/80437613/203016512-47814204-4ece-4b17-bdf4-1d1fffb45583.jpg)
可以将下载后转换的结果由这种
![2022-11-21_175310](https://user-images.githubusercontent.com/80437613/203020050-ae8ea275-29e4-47dd-9dad-d12ebb94d426.jpg)
改变成这种
![2022-11-21_175026](https://user-images.githubusercontent.com/80437613/203019688-dab8c664-cff0-4d7c-b92f-6c304e007bc6.jpg)
或者这种
![2022-11-21_174544](https://user-images.githubusercontent.com/80437613/203018771-a9ea1722-b7c3-43be-af4f-a003ebc56184.jpg)
吗？这样批量删除的时候方便一点

**Comment by xuejianxianzun** [comment]
上图中文字的文字是 pixiv 小说里面的吗？
请提供这个小说页面的 URL，以便我进行测试。

**Comment by xuejianxianzun** [comment]
你所希望转换的格式（后两张图片）虽然可以方便你进行删除，但是并非所有用户都会删除上标的文字。对于直接阅读小说的用户，后两种格式会影响阅读。

**Comment by scybbq** [comment]
是的，https://www.pixiv.net/novel/show.php?id=7501715

**Comment by scybbq** [comment]
那么可以通过增加一个选择项来决定是否删除上标的文字来解决吗？

**Comment by xuejianxianzun** [comment]
https://afdian.net/a/xuejianxianzun
赞助 200 元的档位可以让我增加这个新功能。不过对于这个功能来说，价格似乎比较贵。

**Comment by scybbq** [comment]
好的，谢谢
