### ISSUE TITLE
抓取中收藏状态的问题

### ISSUE THREAD

**Issue by Shinyo1** [xuejianxianzun/PixivBatchDownloader#274]
*请描述你遇到的问题。*

在勾选了抓取已收藏图片选项时后，在界面点击红心后立即进行抓取下载会提示

*如何重现这个问题？*

![SAZ_}1~~JTBPEV6M_XM{KD](https://user-images.githubusercontent.com/38732721/204041985-6d0bd99e-56c7-40bf-afc8-307f60e87f92.png)

![QQ图片20221126025107](https://user-images.githubusercontent.com/38732721/204041660-dfe2d5b9-715f-44fa-a627-ff2728982914.png)

**Screenshots**
If applicable, add screenshots to help explain your problem
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]     win10
 - Browser [e.g. chrome, safari]    chrome
 - Version [e.g. 22]   107.0.5304.121

**Comment by xuejianxianzun** [comment]
这个页面的网址呢？

**Comment by Shinyo1** [comment]
https://www.pixiv.net/artworks/96226913

**Comment by xuejianxianzun** [comment]
你这网址是一个作品，你点红心的是另一个作品，你到底要抓哪个作品？
https://www.pixiv.net/artworks/89797335

**Comment by Shinyo1** [comment]
![image](https://user-images.githubusercontent.com/38732721/204042412-25a3d41b-5022-4c62-b991-10d9b313cd0e.png)
从这一排你任选一个作品点红心，然后抓取就会出现提示

**Comment by xuejianxianzun** [comment]
你收藏一个作品，然后抓取另一个没收藏的作品（本页面显示大图的作品）？

**Comment by Shinyo1** [comment]
收藏和抓取的是同一个

**Comment by Shinyo1** [comment]
你操作一遍嘛

**Comment by xuejianxianzun** [comment]
你点的哪个抓取按钮，截图

**Comment by Shinyo1** [comment]
![~V 3R70WGS%(BZLR }1P2WQ](https://user-images.githubusercontent.com/38732721/204042860-fd425635-3dec-4a35-b0e2-31055548ccc8.png)

**Comment by xuejianxianzun** [comment]
我试了，可以抓取到

**Comment by Shinyo1** [comment]
你的设置和我一样吗

**Comment by xuejianxianzun** [comment]
你的设置呢？怎么不截全

**Comment by Shinyo1** [comment]
![08S30K8()E7S`U DP_KA~58](https://user-images.githubusercontent.com/38732721/204043075-f8d03e77-7490-491b-8237-8718d05e1a68.png)

**Comment by Shinyo1** [comment]
![$R6`@ KWP%P})S@DCNRYUV0](https://user-images.githubusercontent.com/38732721/204043112-f688dc27-e23c-48c8-be37-85a72aa40493.png)

**Comment by xuejianxianzun** [comment]
![20221126_030836](https://user-images.githubusercontent.com/17283977/204043221-600e74ca-4e99-45df-bd54-74c92fb2def7.jpg)
没有此问题，可以抓取下载

**Comment by Shinyo1** [comment]
我换了其他的作者页面现在也变正常了，但是这个Slience Girl作者的界面依旧有问题，不知道是怎么触发的

**Comment by Shinyo1** [comment]
这个问题我出现不止一次

**Comment by Shinyo1** [comment]
我知道怎么触发了····

**Comment by Shinyo1** [comment]
![@)98O83RBQ~P 7{O_07 UZN](https://user-images.githubusercontent.com/38732721/204043817-fe30e7f2-0e6f-454d-b455-8750bdc3b8f5.png)

**Comment by Shinyo1** [comment]
![47DI$~A)$JC9% UOI U99T](https://user-images.githubusercontent.com/38732721/204043906-1f5d07ad-d829-4742-92a5-7a8d987c7128.png)

**Comment by xuejianxianzun** [comment]
在新标签页里收藏作品吗？
那么抓取时是哪个标签页？

**Comment by Shinyo1** [comment]
是的，是在新标签页里收藏作品，抓取在新标签页里，比如我右键点击”在新标签页中打开链接“打开玉子的页面，然后收藏一个作品并抓取，就会提示弹窗

**Comment by xuejianxianzun** [comment]
无法复现。我使用和你一样的设置依然能够抓取。
