### ISSUE TITLE
Edge 可安装但无法启动/弹出展示窗

### ISSUE THREAD

**Issue by JosQiLow** [xuejianxianzun/PixivBatchDownloader#275]
**Describe the bug**
*Edge 可安装但无法弹出展示窗。Version 107.0.1418.56 (Official build) (64-bit)*

**To Reproduce**
How to reproduce this problem?
*第一次下载使用, 安装完后, 点了图标却没反应. 移除再安装也还是一样.*

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

**Screenshots**
[https://drive.google.com/drive/folders/1mQirRvZz7x9eYEmvFFXdnQH_2y-y25As?usp=share_link](url)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 22H2 19045.2311]
 - Browser [Version 107.0.1418.56 (Official build) (64-bit)]
 - Version [14.0.1]

**Additional context**
still need to say Thanks to you :)

**Comment by xuejianxianzun** [comment]
安装之后，刷新你已打开的 pixiv 页面才能使用。因为页面没刷新时，扩展的代码并未被注入到页面中。
你的问题是这个吗？

**Comment by xuejianxianzun** [comment]
请回复
