### ISSUE TITLE
Disable Quick bookmarks and Album viewer

### ISSUE THREAD

**Issue by HTOdinTH** [xuejianxianzun/PixivBatchDownloader#276]
**What functionality do you want?**
*你想要什么功能？*
Like preview and quick search, I want to be able to turn off the quick bookmark button and the album viewer so they will not appear on any pages.

**What is the purpose to solve?**
*目的是解决什么问题？*
I want my computer to be lazy, and not do unnecessary work. I also don't want to scroll so far to read the description.

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*
This extension has this functionality for preview and quick search.

**Additional context**
*附加描述*
I want to turn off the star button and the album view that appear here:
![The buttons and viewer above the work title](https://i.imgur.com/utzgZK8.png)

**Comment by xuejianxianzun** [comment]
I don't plan to add these two switches at this time, because most users will not need to turn them off.
You can use an ad blocking extension for this purpose, for example ABP allows you to manually select elements on the page to block. Or you can add the following rules in ABP:
```
pixiv.net###quickBookmarkEl
pixiv.net###viewerWarpper
```
