### ISSUE TITLE
【建议】跳过重复下载的基准是否能增加一项"作品最后更新时间"呢

### ISSUE THREAD

**Issue by kurokawaTK** [xuejianxianzun/PixivBatchDownloader#277]
发现有部分作者会在元小说的基础上更新作品，但是在这之前下载过作品后面再扒取会因为id相同而跳过，因此想问下作者有没有意愿优化一下这个判断基准呢

**Comment by xuejianxianzun** [comment]
你试过不下载重复文件的“严格”模式吗？就是你说的这个功能。

**Comment by xuejianxianzun** [comment]
现在就可以啊，修改小说正文后，下载器会检测到日期变化， 再次下载它。
你自己去创建小说试一下。
