### ISSUE TITLE
請問能增加偵測pixiv圖檔出錯的功能嗎?

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#279]
我發現pixiv偶爾會出現如下圖無法載入的情形，圖片會只跑出部分。
![79261328_p0](https://user-images.githubusercontent.com/82942914/208233742-37fe058d-a133-485d-9d62-f32fe747cba8.jpg)
有辦法偵測出錯的檔案嗎?

**Comment by xuejianxianzun** [comment]
这种图像在正常浏览 pixiv 时（而非下载时）也会出现吗？

**Comment by e1e1111e1e** [comment]
會。有時過幾天才會好不之為何

**Comment by xuejianxianzun** [comment]
我保存了你上传的这张图片，体积 640 KB (655,360 字节)，分辨率 1400*1750 像素。
虽然图片的下半部分是损坏的，但是用十六进制查看器可以看到这些部分依然是有值的，而非全是 0 或有其他明显特征。
如果这张图片是发生此问题时的原图（而非截屏，或者被转换过），那么我觉得是很难检测这种特定问题的。
![20221218_160726](https://user-images.githubusercontent.com/17283977/208287933-8fe85c1e-60b2-4e09-8ea7-0666be6ccff0.png)

**Comment by e1e1111e1e** [comment]
好的了解。圖的話是下載器載下來是這樣子右鍵下載也是。
