### ISSUE TITLE
能否提供crx文件

### ISSUE THREAD

**Issue by NTDLX** [xuejianxianzun/PixivBatchDownloader#28]
![image](https://user-images.githubusercontent.com/34884072/65576540-c25cc100-dfa4-11e9-9264-72662f3f2047.png)
以开发者模式导入，每次打开谷歌浏览器都会弹出这个提示

**Comment by xuejianxianzun** [comment]
这个问题好像无解

**Comment by xuejianxianzun** [comment]
crx 文件用不了的，安装进去会提示这不是商店里的应用，然后强制停用
