### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by catcafeman** [xuejianxianzun/PixivBatchDownloader#281]
![image](https://user-images.githubusercontent.com/97942184/209447945-2890ec77-a70e-4e15-824e-b7921194a3d0.png)
请问为什么需要这个新的权限呢？

**Comment by xuejianxianzun** [comment]
由于下载器更换了修改网络请求标头的方式，使用了 `declarativeNetRequest` 权限，这应该是出现此提示的原因。
这个权限确实有能力阻止网络请求，但并不代表下载器会这么做。

**Comment by catcafeman** [comment]
> 由于下载器更换了修改网络请求标头的方式，使用了 权限，这应该是出现此提示的原因。 这个权限确实有能力阻止网络请求，但并不代表下载器会这么做。`declarativeNetRequest`

![image](https://user-images.githubusercontent.com/97942184/209448123-4d94e304-eb57-4626-8f34-1f2ba7651059.png)
感谢回复！我关注到此扩展可以阻止【任何】页面上的内容，这是我的解决方案。

**Comment by xuejianxianzun** [comment]
这个担心是多余的，下载器只会在“允许的站点”上运行。
