### ISSUE TITLE
无法合并小说并下载

### ISSUE THREAD

**Issue by smoblk** [xuejianxianzun/PixivBatchDownloader#282]
**Describe the bug**
*请描述你遇到的问题。*

在系列小说页面，打开下载器页面 选择合并系列小说 只会显示抓取成功 但不会开始下载

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*

选择部分多项目系列小说页面 以小说下载为EPUB方式 点击合并系列小说

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xuejianxianzun** [comment]
此为已知问题，请等待扩展自动更新到 15.0.1，或者使用离线安装包自行更新。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.0.1

**Comment by smoblk** [comment]
抱歉 我之前单独下载github的 那个全文件压缩包 解压后 无法加载 且 扩展程序内无法更新至15.0.1 （使用VPN情况下）


现已完成更新 可以删除问题回报了


感谢制作者


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuejianxianzun/PixivBatchDownloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月27日(星期二) 凌晨5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuejianxianzun/PixivBatchDownloader] 无法合并小说并下载 (Issue #282)





 
此为已知问题，请等待扩展自动更新到 15.0.1，或者使用离线安装包自行更新。
 https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.0.1

**Comment by xuejianxianzun** [comment]
扩展已经更新到新版本了，你可以换回在线安装：
https://chrome.google.com/webstore/detail/powerful-pixiv-downloader/dkndmhgdcmjdmkdonmbgjpijejdcilfh
