### ISSUE TITLE
429错误

### ISSUE THREAD

**Issue by 203saber** [xuejianxianzun/PixivBatchDownloader#283]
我不知道文字是否会发生改变，问题是抓取，抓取出现的问题越来越严重，我记得上半年还没有这个问题，现在不管是抓取周榜，或者抓取任何标签，超过500数量以上的都会出现问题

如下:
错误代码：429（请求数量过多）。下载器会重新抓取它。
Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。(429)

不是一次，是每次，我不知道是服务器难以负荷，或者代码出现的问题，或者P站本身的更新，希望能够改善，望重视！
图片我暂存在了公共图书馆，可查看
https://ibb.co/R0BDvgM

**Comment by xuejianxianzun** [comment]
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?id=_429-%E9%94%99%E8%AF%AF

请在常见问题页面搜索 429 自行查看。
