### ISSUE TITLE
错误代码：429（请求数量过多）。下载器会重新抓取它。 Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。

### ISSUE THREAD

**Issue by geniuslm** [xuejianxianzun/PixivBatchDownloader#284]
错误代码：429（请求数量过多）。下载器会重新抓取它。 Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取

遇到这种情况 兄弟们等着就行了  ( ╯□╰ )

**Comment by xuejianxianzun** [comment]
重复的问题
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/283
