### ISSUE TITLE
商店安装错误:Invalid manifest

### ISSUE THREAD

**Issue by belkahorry** [xuejianxianzun/PixivBatchDownloader#285]
其他扩展安装正常,代理换过无效
![搜狗截图20230105151905](https://user-images.githubusercontent.com/29267562/210724301-e97749a2-b6a6-42b7-8668-3e973a3170f3.png)

**Comment by xuejianxianzun** [comment]
你用的是什么浏览器，版本号多少

**Comment by xuejianxianzun** [comment]
太久没有回复，关闭问题。

**Comment by z134git** [comment]
我也是一样，360极速，内核95
