### ISSUE TITLE
需要跳过p站新加入的跳转链接设置

### ISSUE THREAD

**Issue by SoudayoWwww** [xuejianxianzun/PixivBatchDownloader#286]
**What functionality do you want?**
*你想要什么功能？*
希望能够跳过p站目前的站点跳转链接。

**What is the purpose to solve?**
*目的是解决什么问题？*
p站点击作者简介下方关联的主页、twitter图标等会弹出新的跳转链接，非常影响日常使用。

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*
N/A

**Additional context**
*附加描述*
![GZF7DW`JQU054B77% @C_`T](https://user-images.githubusercontent.com/52328223/211809876-e955bdbf-bc4f-4883-b74e-a76154e9af49.png)

![B9KQM$R E}VKNDALX4F283D](https://user-images.githubusercontent.com/52328223/211809058-bfa2fb92-806e-44b3-972e-5a8346907d4b.png)

**Comment by xuejianxianzun** [comment]
我还没想好做不做这个功能，我记得已经有油猴脚本有此类功能了，你去脚本站搜 pixiv 看看吧。
