### ISSUE TITLE
“不下载重复文件功能” 有一定的问题

### ISSUE THREAD

**Issue by Seele0oO** [xuejianxianzun/PixivBatchDownloader#288]
**Describe the bug**
*请描述你遇到的问题。*

我开启了另一个具有下载功能的插件，它会与本插件冲突导致下载失败，并且会记录该作品已被下载。
在收到提示后我将其他下载插件关闭，但该作品已经被记录为已下载，只能去设置临时关闭“不重复下载文件”

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*

见描述

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

```
正在下载中
正在保存抓取结果
检测到文件 [104884282_p0](https://www.pixiv.net/i/104884282) 已经下载过，跳过此次下载
检测到文件 [104884282_p1](https://www.pixiv.net/i/104884282) 已经下载过，跳过此次下载
2 / 2

✓ 下载完毕
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Linux arch 6.1.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 18 Jan 2023 19:54:38 +0000 x86_64 GNU/Linux`
 - Browser: `chromium`
 - Version: `Version 109.0.5414.74 (Official Build) Arch Linux (64-bit)`

**Additional context**

我认为应该根据**现有命名规则**来查找下载文件夹对应位置是否有将要下载的文件名同名文件。
如果没有就应认为该作品没有被下载。
当收藏数量很多的时候，插件中的json就会很大，效率可能不如读取下载文件夹的信息。

**Comment by xuejianxianzun** [comment]
1. “查找下载文件夹对应位置”做不到，因为浏览器扩展没有权限读取硬盘。
2. 根据命名规则判断是可以的，使用严格模式即可。
3. 下载记录不是 json，而是储存在 indexedDB 里的记录。
4. 哪个插件会导致它的下载被下载器记录？我觉得这不可能，让我来试试。

**Comment by Seele0oO** [comment]
https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn
aria2下载插件。

**Comment by xuejianxianzun** [comment]
emmm 你的意思是下载器发起的下载被这个扩展接管，然后下载器把这个文件标记为已下载？
如果这样的话是正常的啊

**Comment by Seele0oO** [comment]
但是下载并没有成功，且被标记为成功下载。

**Comment by Seele0oO** [comment]
但是下载并没有成功，且被标记为成功下载。

**Comment by xuejianxianzun** [comment]
下载没有成功可能因为下载器传递的是 Blob URL，所以第三方软件无法下载。
所以这个下载器不能搭配 aria2 使用。
但这个不是 bug。

**Comment by xuejianxianzun** [comment]
你用的那个 aria2 下载插件应该是接管了浏览器的下载，并直接把这个下载标记为已完成，所以下载器才会生成对应的下载记录。
