### ISSUE TITLE
bookmark tag problem

### ISSUE THREAD

**Issue by komaedalove** [xuejianxianzun/PixivBatchDownloader#29]
I use "bkm" before every image downloaded, but the order is not correct. When downloaded, the images with most bookmarks are on the bottom and I want to change that. I would like for images with more bookmarks to be on top.

![Screenshot - 2019-10-02 , 06_53_26](https://user-images.githubusercontent.com/52548608/66018953-79939380-e4e1-11e9-9320-5bc0a0415c6e.png)

**Comment by xuejianxianzun** [comment]
You can change the way the file manager sorts. For example, Windows explorer can be arranged in reverse order to achieve the desired effect. I am not clear about the software you use, please try it yourself.

**Comment by komaedalove** [comment]
Hello! When I try to reverse arrrange in windows explorer, the last pages of most bookmarked works are first. it is like:

```
bmk_2005 75604702_p2.jpg
bmk_2005 75604702_p1.jpg
bmk_2005 75604702_p0.jpg
bmk_103 73098348_p2.jpg
bmk_103 73098348_p1.jpg
bmk_103 73098348_p0.jpg
```

and I want it to be like

```
bmk_2005 75604702_p0.jpg
bmk_2005 75604702_p1.jpg
bmk_2005 75604702_p2.jpg
bmk_103 73098348_p0.jpg
bmk_103 73098348_p1.jpg
bmk_103 73098348_p2.jpg
```
