### ISSUE TITLE
能否添加一个功能，就下载时自动新建一个txt文件用于保存当前作品的信息

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#291]
**What functionality do you want?**
*你想要什么功能？*
下载时自动新建一个txt文件保存当前作品的信息

**What is the purpose to solve?**
*目的是解决什么问题？*
作品定位，分析

**Additional context**
*附加描述*
txt内容主要是作品链接，作者，tag之类的

**Comment by xuejianxianzun** [comment]
已有此功能：
更多选项卡-下载-保存作品的元数据
勾选作品类型，即可在下载时保存数据到 txt 文件
