### ISSUE TITLE
【改进】删除已下载文件列表、重置设置的时候，弹出提示框询问是否删除

### ISSUE THREAD

**Issue by kenshin000003** [xuejianxianzun/PixivBatchDownloader#292]
**What functionality do you want?**
*你想要什么功能？*

在
【不下载重复文件 ?    策略：  严格  宽松 导出 导入 清除】
【管理设置 导出设置 导入设置 重置设置】
这些设定中，
删除已下载文件列表、重置设置的时候，弹出提示框询问是否删除。

**What is the purpose to solve?**
*目的是解决什么问题？*

防止用户的误操作。

**Comment by xuejianxianzun** [comment]
重置设置是会询问的。

清除下载记录确实没有询问，以后可以加上。
