### ISSUE TITLE
【GUI改进建议】希望一些下载相关的按钮和设定可以和下载按钮放在一起

### ISSUE THREAD

**Issue by kenshin000003** [xuejianxianzun/PixivBatchDownloader#294]
拼了个图片，黑色字体代表添加文字。但是还是用文本描述一下，方便交流，也方便别人在反馈之前搜索，“【】”代表按钮。

虽然说得有些多了，但都是与 需求1 相关的需求，就放在一起说了。
需求：
1. 希望一些下载相关的按钮和设定可以和下载按钮放在一起，按照操作顺序进行排布。
2. 希望“导出抓取结果.json”“导出抓取结果.csv”“导出文件名List.txt”“导出 URLList.txt”可以用户自定义文件夹和文件名，用户自定义是否自动导出。
3. 希望：添加【暂停抓取】【停止抓取】按钮。
4. 希望：添加定时导出已下载文件列表的功能。
5. 【开始抓取/继续抓取】【暂停抓取】【停止抓取】可以显示固定文本也可以切换显示，切换显示的话比较掉头发，固定的话编写比较简单。
6. 希望“手动选择作品”的相关按钮可以显示出来，点完之后闪现总觉得怪怪的，如果是固定的按钮，会节省找按钮的时间，我知道HTML可以禁用按钮，不太清楚js行不行。

目的：逻辑清晰，用户看一眼就知道怎么操作；操作简便，免得来回翻页更改必要的设置。

```
----- 管理设置 -----
【管理设置】
----- STEP1 抓取 -----
抓取多少页面 ? __页
【开始抓取/继续抓取】【暂停抓取】【停止抓取】
【定时抓取】
【手动选择作品/继续选择】【清空选择的作品】
【导入抓取结果】
----- STEP2 导出抓取结果（可选项） -----
爬取后自动导出抓取日志？【】
【导出抓取结果（导出抓取结果.json）】文件名：__ 自动导出？【】
【导出 CSV 文件（导出抓取结果.csv）】文件名：__ 自动导出？【】
【预览文件名（导出文件名List.txt）】文件名：__ 自动导出？【】
【复制 URL（导出 URLList.txt）】文件名：__ 自动导出？【】
----- STEP3 下载 -----
抓取完毕后自动开始下载？【】
不下载重复文件？【】
已下载的文件列表 导出 导入 清除 文件名：__ 自动导出？【】
定时导出？【】定时导出时间间隔__
下载之后收藏作品？【】
【开始下载/继续下载】【暂停下载】【停止下载】
```

![2023-01-11-GUI优化建议](https://user-images.githubusercontent.com/80815506/216510354-009673e3-e3ce-4934-99d0-9cafd99c0cd8.png)

**Comment by xuejianxianzun** [comment]
1. 希望一些下载相关的按钮和设定可以和下载按钮放在一起，按照操作顺序进行排布。

我看了图片，我觉得管理设置没有必要放到顶部。

几乎涉及导出的功能都要自定义文件名，这样的设置究竟对多少用户有必要？我认为多数用户应该是偶尔才需要导出抓取结果或者 URL，而不是经常或默认这样做。这种只对少数人有用的设置我是不愿意加的，不然现在下载器的设置数量怕是已经翻了一番了。

另外你图中的工作流程 抓取 - 导出 -下载，我不认可，导出功能占据中间的黄金位置，有多大的意义需要这样做呢？

你在图上只显示了少量的设置，问题是哪些设置应该显示出来？（而且我觉得你对于哪些选项是“重要”的，想法和我有很大的不同）

没有在你图上显示出来的设置你又打算如何处理？

2. 希望“导出抓取结果.json”“导出抓取结果.csv”“导出文件名List.txt”“导出 URLList.txt”可以用户自定义文件夹和文件名，用户自定义是否自动导出。

这需要增加多个设置。这属于可以做但结合使用频率来看，我觉得没有多大必要的设置。我不想加。

自动导出抓取结果的功能现在已经有了。

没有自动导出文件名和 URL 的功能，我也不想添加。

3. 希望：添加【暂停抓取】【停止抓取】按钮。

请说明什么情况下有暂停抓取的需求？使用频率有多少？

停止抓取可以直接刷新页面，不需要单独添加一个按钮。

4. 希望：添加定时导出已下载文件列表的功能。

不打算添加，因为有此需求的用户应该占比很少。

5. 等决定添加这个功能了再说。

6. 希望“手动选择作品”的相关按钮可以显示出来，点完之后闪现总觉得怪怪的，如果是固定的按钮，会节省找按钮的时间，我知道HTML可以禁用按钮，不太清楚js行不行。

快捷键 Alt + S 切换手动选择和暂停手动选择。

![image](https://user-images.githubusercontent.com/17283977/217012621-e522e582-da62-41e8-b204-23697984f9dc.png)

**Comment by xuejianxianzun** [comment]
长时间未回复，关闭此问题。

**Comment by kenshin000003** [comment]
抱歉这几天太忙了……😥

1. “管理设置”确实不需要一定放在顶部，也可以放在底部。
  
2. 关于“少数多数人的操作”，毕竟：
  
  1. 能上网的人是少数
    
  2. 能上网的人里，能上互联网的人就是少数
    
  3. 能上互联网的人里，能上P站的是少数
    
  4. 能上P站的人里，能找插件的是少数
    
  5. 能找插件的人里，能找到这个插件的是少数
    
  6. 能找到这个插件的人里，能来到 GitHub 的是少数
    
  7. 能来到 GitHub 的人里，愿意注册并且提出建议的是少数
    
  
  所以，这个下载器的使用者就是少数。
  
  而且，能在 GitHub 反馈中看见的，一定是少数中的少数，最极端的例子，最特殊的需求。极端的情况满足了，通常情况也就满足了。
  
  况且每个人都有他的需求，或许十年之后，看到某个需求的反馈变多了，也就加上了这个功能。也许百年后会有人，扒出这个好东西，但是就是用不舒服，然后他还是需要改进才能用得舒服。
  
  或许也可以这样，在QQ群里新建投票，问对于新增某功能的意见，然后根据投票结果来决定要不要添加这个功能。
  
3. 仔细想想，文件列表比URL更有用一些。
  
  文件列表：我有时候需要获取以前下载了的文件的列表，然后重新下载。
  
  URL：sankaku 网站中有很多图片是这种 URL 的格式，所以搜图用得到。
  
  我需要 文件列表 和 URL 的导出可以设置文件名，是因为
  
  1. 我不希望导出的 文件列表 和 URL 全生成在下载文件夹的根目录，至少能像这样： `\下载根目录\FileList\` 放在文件夹里面。
    
  2. 或者有时候希望不同页面的下载可以做分类，比如： `\下载根目录\{page_title}\` （`{page_title} 当前页面的标题`）。
    
  3. 完整性，说白了，好看。
    
  4. 用户有可能有其他文件夹名的需求。
    
  
  而加上的。这一点看程序的复杂度了，如果大到电脑无法运行就算了。
  
4. “用户也不需要知道下载器的运行逻辑，应该以用户体验为第一位。”
  
  对于我这个稍微懂一点软件操作、懂一点 win10 操作别扭特性的人而言，从开始用这个下载器，到慢慢看懂这个下载器的处理顺序，也用了大概一周，期间也频繁测试设置才能明白，我相信不只是我会是这样。
  
  所以我觉得按操作顺序，可以更方便新用户的操作，对老用户的使用体验也会更好。
  
  并且作为程序设计者是感受不到新用户的操作不便的。所以游戏发行之前才需要有玩家来测试；所以电影上映前会需要很多人来看试映。
  
  我之前设计了一个 TAG 统计小程序，刚刚做完的时候，我也觉得挺牛逼的，等到1年之后，再打开，发现都不知道怎么用了。
  
5. “没有在你图上显示出来的设置你又打算如何处理？”
  
  我能想到的解决方法：
  
  1. 方法1：图中的设置放在 `【抓取】【下载】【更多】` 三页中的 `【下载】` 页。
    
  2. 方法2：图中的设置放在 `【抓取/下载】【更多】` 三页中的 `【抓取/下载】` 页。`【抓取/下载】`合并，这样有2页，用户更改设置，只需要翻找两页设置。`【抓取】【下载】` 页中的其余设置，放在图中设置的下方。
    
6. “只抓取和下载两部分就可能会导致下载面板出现滚动条了，一眼看不完整，这是很影响使用体验和效率的问题。”
  
  对于我而言，我会频繁操作：
  
  操作1：
  
  - 【翻页】【下载之后收藏作品 ?】 ON
    
  - 【翻页】【开始抓取】
    
  - 【翻页】【下载之后收藏作品 ?】 OFF
    
  - 【翻页】【开始抓取】
    
  
  操作2：
  
  - 【翻页】【不下载重复文件 ?】 ON
    
  - 【翻页】【开始抓取】
    
  - 【翻页】【不下载重复文件 ?】 OFF
    
  - 【翻页】【开始抓取】
    
  
  操作3，因为下载器的设计，新改变的设置与其他页面不同，这样很好，避免了正在下载页面的错误。但是有些时候，我仍然需要同步所有页面设置：
  
  - 修改设置
    
  - 【翻页】【导出设置】
    
  - 转到其他标签页
    
  - 【翻页】【导入设置】
    
  - 【翻页】【开始抓取】
    
  
  所以我会频繁翻页，但是翻页的时候，鼠标选取的操作是【最上边的小块空间】；但是如果是一页，只需要在【下载器页面】中进行滚轮操作，这样操作起来势必会舒适很多。
  
  另外也是因为滚轮操作空间更大，所以2页一定比3页舒服得多。（我猜 `【抓取/下载】` 合并后长度，比 `【更多】` 页短吧。）
  
  我觉得用电脑的人中，鼠标滚轮坏了的人也不少，这点就见仁见智了。
  
7. “请说明什么情况下有暂停抓取的需求？”，“停止抓取可以直接刷新页面”。
  
  我刷新过啊，下载器自动继续抓取了啊，所以才有这个需求的啊。当然我知道自动继续抓取很好就是了，有时候也很有必要，所以添加 `【暂停抓取】【停止抓取】` 应该是个更好的解决方案。
  
8. “希望：添加定时导出已下载文件列表的功能。”
  
  这个需求这个对于我个人而言很必要的，这一点等别人再反馈，反馈多了就需要加了。也可以投个票看看大家意见。
  
9. “【开始抓取/继续抓取】【暂停抓取】【停止抓取】可以显示固定文本也可以切换显示”
  
  这里我可能没说明白，再解释一下。
  
  - 方法1： `【开始抓取/继续抓取】` 固定文本。`【开始下载/继续下载】` 固定文本。
    
  - 方法2：一开始，显示 `【开始抓取】` ，点击 `【暂停抓取】` 后，`【开始抓取】` 变为 `【继续抓取】` 。
    
    这个需求是因为：
    
    - 第一次用下载器的人，看不懂怎么继续下载；
      
    - 即使用久了，看着也不舒服；
      
10. “希望【手动选择作品】的相关按钮可以显示出来，点完之后闪现总觉得怪怪的，如果是固定的按钮，会节省找按钮的时间，我知道HTML可以禁用按钮，不太清楚js行不行。”
  
  我说的是这三个按钮的闪现： `【暂停选择】【清空选择的作品】【抓取选择的作品】` ，希望：如果这个地方有按钮，就直接显示出来。
  
  另外忘了说了： `【不下载重复文件 ?    策略：  严格  宽松 导出 导入 清除】` 这个设置也是闪现的。
  
  我觉得这两个地方，没必要闪现，因为：
  
  1. 点开了，设置显示出来了，用户还需要用眼寻找按钮在哪，一方面不舒服，一方面一定程度上降低了操作效率。如果原本按钮就在，就会减轻这种现象。
    
  2. 我觉得更能方便用户的理解。

**Comment by xuejianxianzun** [comment]
我不打算按你说的修改。只回复部分问题：

-------

下载器的使用者就是少数没错，但在讨论对下载器的修改时，应该将下载器用户视为一个整体，而不是因为下载器的使用者在所有网民中是少数就代表下载器要按照小众软件的思路去做，就仿佛要做的很极致很极客。

“极端的情况满足了，通常情况也就满足了”，这句话有一定道理，但是我觉得不必如此做。因为你所说的要满足极端情况的做法对我来说有 2 个因素使我不能接受：
1.  一些多数人不常用的设置的位置被放在显眼的位置
2. 添加许多很少会被使用的功能/设置。这会使得下载器臃肿不堪，而我认为作为一个面向许多人使用的软件，适度的简洁和功能上的取舍是有必要的。

--------------

你需要“ 文件列表 和 URL 的导出可以设置文件名”。首先，导出的 URL 不能用下载器下载，而是只能用第三方软件下载，所以无法附带文件名路径。
如果你使用下载器里的“导出抓取结果”，并希望导入时能设置对应的文件路径，那么你应该启用“在不同的页面类型中使用不同的命名规则”的功能，那么在不同类型页面里就可以使用不同的命名规则和保存路径。这也对应你说的“有时候希望不同页面的下载可以做分类”。

---------

你说你用了一周才明白下载器的使用逻辑，我认为没有这么复杂。用户只需要点一个“开始抓取”就完事了。如果你是指其他功能，通常附带帮助，而且你可以在使用手册（Wiki）里查看更详细的说明。
唯一困难的地方我觉得在于命名时多个设置的互相影响会导致出现一些不太直观的结果。不过这我也没有办法。这么多设置都是应用户需要逐渐添加上去的，必然会导致系统变得约来越复杂。

---------

你觉得“2页一定比3页舒服得多”，但是现在下载器的第三页“更多”特意只放了不需要被频繁修改的设置，所以一般来说用户只需要关注前两页。
当然总有人例外，具体情况可能就多种多样了。从你的说法来看你对于导出和导入设置的使用频率较高。实际上我觉得必要性不大，因为下载器会持久保存设置。如果你的意思是针对不同的使用场景导出不同的设置，那么确实会感到麻烦。
针对此情况，你可以考虑用油猴脚本做辅助，因为下载器的导出设置按钮的 id 为 exportSettings，导入设置的按钮的 id 为 importSettings，你可以自行编写 JS 脚本获取对应元素，然后绑定自定义快捷键，按下对应快捷键则点击对应按钮。这样你可以无需切换到“更多”页面就能使用这两个功能。

例如在 Pixiv 页面上执行如下 JS 代码，可以按 E 导出设置，按 I 导入设置：

```js
const exportBtn = document.getElementById('exportSettings')
const importBtn = document.getElementById('importSettings')

window.addEventListener('keydown', (ev) => {
  if (ev.code === 'KeyE') {
    exportBtn.click()
  }
  if (ev.code === 'KeyI') {
    importBtn.click()
  }
})
```

-------------

"滚轮操作空间更大"，但问题的关键是如果把许多设置放在一起，会难以辨别，很难找到自己所需要的设置。
即使是我，想在“更多”页面里找到某个设置，有时候还得反复寻找。
所以我把“抓取”和“下载”分开，正是为了缓解这个问题。
下载器的“高亮显示关键字”功能也是为了缓解这个问题。

你想把抓取和下载的设置放在一页里，有考虑过这个问题吗？
虽说“先在下载里面开启某个设置，然后转到抓取里面再开始抓取”显得有些麻烦，但是用鼠标经过来切换两个标签页在我看来并不麻烦，而且容易找到对应设置，这并不比你所想的方法效率更低。


----------

至于你说的“刷新页面后下载器自动继续抓取了”，没有这个功能。刷新后会继续的是下载流程，而不是抓取。
不过我有想法添加这个按钮。等以后看吧，但我只计划用它来停止抓取（并保存抓取结果），没有“暂停/继续”的功能。

------------

“添加定时导出已下载文件列表的功能”：
除非用户喜欢三天两头频繁清理浏览器缓存，否则下载记录不会丢失，也就没有这个必要。所以我也不打算添加此功能。
如果你实在需要，请参考上面的 JS 代码，对导出按钮设置快捷键，或用 JS 代码来定时点击它。

---------

按钮闪现的问题：
点击“手动选择作品”后会多出 3 个按钮，如果把它们始终显示，版面会变得怎样臃肿？而且这对于用户来说增加了认知负担，会觉得这个软件好复杂好难搞懂。而且这三个按钮依赖于“手动选择作品”的先决条件，这是个逻辑问题。
至于“不下载重复文件”开启之后才会显示的子选项，下载器里有很多设置都是这样设计的。如果不开启设置却始终显示子选项，版面会变得何等杂乱？你可以把所有“蓝色开关按钮”的设置都开启，再对比一下关闭的状态，差别很大。

----------

总之，很多时候你的设计和使用理念不符合我对这个下载器的设计理念。用笼统的话说你是“高级用户”，然而不管什么软件，大多数人都会是普通用户，为高级用户做一些高级功能和不会被大众经常用到的功能属于边际效用递减。
能满足多数人在多数情况下的需求即可，其他的需求我是看心情或看必要性做。对于我很不想做的功能我就不会做，当然如果你会写代码的话可以 fork 本仓库自行构建属于你自己的定制版本。你也考虑让我为你定做专属版本，但这是需要视功能需求额外收费的。
