### ISSUE TITLE
Could you please make it compatible with Firefox?

### ISSUE THREAD

**Issue by lunae-f** [xuejianxianzun/PixivBatchDownloader#295]
I like this extension very much. However, I use MS-Edge "just" to use this extension. Please make it compatible with Firefox.
Thanks.

**Comment by xuejianxianzun** [comment]
The downloader used to have a Firefox version, but the downloader no longer supports Firefox because Firefox uses more CPU and memory when saving files.
see:
https://github.com/xuejianxianzun/PixivBatchDownloader/blob/master/CHANGELOG.md#183-2019-7-29

**Comment by lunae-f** [comment]
Understood. Have a good day. ; )

**Comment by xuejianxianzun** [comment]
Firefox version:
https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/
