### ISSUE TITLE
I translated to Japanese. But I can't use Git...

### ISSUE THREAD

**Issue by lunae-f** [xuejianxianzun/PixivBatchDownloader#296]
Japanese version of README.md (README-JA.md) has been created. In addition, the reciprocal links to README (README-EN.md, README-KO.md, README-RU.md, README-ZH-TW.md, README.md ) have been corrected.
The above fix is available at [my repo](https://github.com/lunae-f/PixivBatchDownloader) but I am not sure how to use Git. I would like to see it applied to this repository if possible.
Thank you.

**Comment by xuejianxianzun** [comment]
Thank you for your help! I've added it to this repository. 😊

https://github.com/xuejianxianzun/PixivBatchDownloader/blob/master/README-JA.md

**Comment by lunae-f** [comment]
thank you♥️
