### ISSUE TITLE
【P站抓取图片后无法自动下载】在正常抓取并筛选图片后，无法自动下载

### ISSUE THREAD

**Issue by luoy804** [xuejianxianzun/PixivBatchDownloader#297]
**Describe the bug**
在正常抓取并筛选画师作品后，一直卡在下载界面（下载进度一直为0/***），无法完成自动下载。

在多个画师主页尝试抓取，均会遇到这个问题。
（https://www.pixiv.net/users/4357504；https://www.pixiv.net/users/279599）

浏览器版本：Chrome 版本 109.0.5414.120（正式版本） （64 位）
插件版本：Powerful Pixiv Downloader 版本15.2.0
网络情况：使用了VPN翻墙，可以正常浏览P站图片

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*
1.在画师主页启动插件抓取图片；
2.正常完成抓取与筛选；
3.自动跳转至下载界面；
4.下载进度一直为0/***，无法完成自动下载；

*诊断信息*
1. 问题截图
![QQ截图20230205193623](https://user-images.githubusercontent.com/96585480/216816679-32aacfd6-fb0c-4809-a2b9-ee6c7129c67c.png)

2. 抓取时的页面 URL
[复制 URL.txt](https://github.com/xuejianxianzun/PixivBatchDownloader/files/10610876/URL.txt)

3. 如果需要，导出下载器的设置，并添加到附件。
[Powerful Pixiv Downloader Settings.zip](https://github.com/xuejianxianzun/PixivBatchDownloader/files/10610863/Powerful.Pixiv.Downloader.Settings.zip)

4. 如果需要，导出抓取结果，并添加到附件。
[result-ねこてゐ - pixiv-1675595954839.zip](https://github.com/xuejianxianzun/PixivBatchDownloader/files/10610867/result-.-.pixiv-1675595954839.zip)

**Comment by xuejianxianzun** [comment]
我使用你的设置没有遇到下载问题。
你重启浏览器试试，或者换edge浏览器试试。
这个问题时不时有人会遇到，但不是下载器的bug，通常都是浏览器或其他因素导致的。

**Comment by luoy804** [comment]
> 我使用你的设置没有遇到下载问题。 你重启浏览器试试，或者换edge浏览器试试。 这个问题时不时有人会遇到，但不是下载器的bug，通常都是浏览器或其他因素导致的。

感谢您的回复。
今天重启浏览器后，已经可以正常抓取并下载。
