### ISSUE TITLE
多图作品能够选择下载特定某张

### ISSUE THREAD

**Issue by ayanami-desu** [xuejianxianzun/PixivBatchDownloader#298]
**What functionality do you want?**
*你想要什么功能？*

**What is the purpose to solve?**
*目的是解决什么问题？*
有些画师上传本子的封面及部分内容，有时只想要封面，却不得不买椟还珠，多下载不想要的图片。
**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*

**Additional context**
*附加描述*

**Comment by xuejianxianzun** [comment]
你在 Chrome Web Store 里搜一下其他的 pixiv 下载器，我记得 pixiv 工具箱的还是啥有这个功能。你可以安装那个试试。

**Comment by xuejianxianzun** [comment]
你说的“只想要封面”应该指的是只下载第一张图片吧，你可以启用“多图作品只下载前几张图片”并设置为 1，就可以只下载第一张图片。

过几天我会增加一个新功能，不需要启用上面的设置，而是在预览作品时按快捷键 `C` 可以只下载预览的这张图片。这样你想单独下载第几张都可以。

**Comment by ayanami-desu** [comment]
非常感谢！
