### ISSUE TITLE
不打开页面,下载标题只能是页面标题吗?

### ISSUE THREAD

**Issue by NaixHw** [xuejianxianzun/PixivBatchDownloader#299]
在排榜和预览下载的时候,下回来的标题还是标签页上面的标题不是自定义的标题.

**Comment by xuejianxianzun** [comment]
什么叫“不打开页面”，不打开页面你是怎么用下载器下载的？
你的自定义标题是什么，页面标题又是什么，下载的文件名是什么，有没有截图？别让我在这儿猜

**Comment by NaixHw** [comment]
就是排行榜，不点进去单个作品,鼠标停上面预览下载.下载标题都是［pixiv]综合本周排行榜 2023年2月2日...

**Comment by xuejianxianzun** [comment]
你是否知道下载器可以修改命名规则来控制生成的文件名？你有没有修改过命名规则，下载的文件名和你的命名规则是否对应？
