### ISSUE TITLE
求助，无法下载的问题

### ISSUE THREAD

**Issue by neptunehs** [xuejianxianzun/PixivBatchDownloader#3]
我碰上了无法下载的问题（上个月还行的）
问题类似
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/2
不同的是 他下载成功而我失败了

在下载内容页面里显示的是这样的内容
3fd9548b-1ec3-42a5-b3e9-1952a32ac0b1 失败 - 网络错误
blob:https://www.pixiv.net/3fd9548b-1ec3-42a5-b3e9-1952a32ac0b1
由Pixiv Batch Downloader下载

顺便将blob:https://www.pixiv.net/3fd9548b-1ec3-42a5-b3e9-1952a32ac0b1 直接复制进地址栏是可以看得到图的
而且用copy urls能得到正确的地址（但就没办法用模板命名了。。。）
然而自带下载就是失败

希望作者能指导下是不是哪里设置有问题

win10 1607（14393.2551）
Chrome 70.0.3538.77
已关闭switchyomega以外的所有扩展并且已重装过

**Comment by xuejianxianzun** [comment]
不太清楚，你可以尝试在扩展详情里开启“允许访问文件网址”，如图：

![示例](https://s1.ax1x.com/2018/11/11/iqJ5TO.png)

如果不能解决，可以加 QQ 群让我远程看下。

**Comment by neptunehs** [comment]
![12351](https://user-images.githubusercontent.com/27727785/48314012-7c9e4080-e5fe-11e8-862a-b413660623f5.jpg)
没有该选项啊

**Comment by neptunehs** [comment]
突然可以了

**Comment by AYiXi** [comment]
果然把允许访问文件网址打开就行了
