### ISSUE TITLE
小说无法保存

### ISSUE THREAD

**Issue by Nagisa-Koworu** [xuejianxianzun/PixivBatchDownloader#300]
[18636392](https://www.pixiv.net/i/18636392) 保存失败，code：FILE_BLOCKED。下载器将会重试下载这个文件。
只有小说，插图和漫画正常

**Comment by xuejianxianzun** [comment]
所有小说都无法保存吗？
FILE_BLOCKED 是浏览器保存文件到硬盘时遇到的错误代码，与下载器无关。

**Comment by xuejianxianzun** [comment]
https://www.pixiv.net/novel/show.php?id=18636392
这个小说吗？下载没问题。可能是你的硬盘问题或者文件系统问题。
![image](https://user-images.githubusercontent.com/17283977/218240913-7da43fd2-8800-4e82-bd11-218a35edd7f0.png)

**Comment by xuejianxianzun** [comment]
无回复，关闭此问题。
