### ISSUE TITLE
下载中不能新建特殊名称的文件夹导致下载无法继续的问题

### ISSUE THREAD

**Issue by yaoyueweiyang** [xuejianxianzun/PixivBatchDownloader#301]
如题，当命名规则为{user}/{title}/{id} {tags}时，下载到一个作者名为“con.fundo_”的作品时，因为无法新建这个名称的文件夹，导致下载卡死，无法继续下载。
![image](https://user-images.githubusercontent.com/20874466/219600235-0987250f-34fb-43f0-8650-5fe3f4bbc064.png)

**Comment by xuejianxianzun** [comment]
下个版本修复了此问题。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.3.1
