### ISSUE TITLE
关于在设置-不下载重复文件处增加“定期导出下载记录”功能的建议

### ISSUE THREAD

**Issue by FrostNova67204** [xuejianxianzun/PixivBatchDownloader#302]
_**What functionality do you want?**
*你想要什么功能？*_
-我希望可以在下载-不下载重复文件处增加“定期导出下载记录”的功能，比如：
✅每___次完成下载时自动导出（本次或此前全部）下载记录
✅每___天后，在第___次完成下载时自动导出（本次或此前全部）下载记录
_**What is the purpose to solve?**
*目的是解决什么问题？*_
-有时会因为某些原因清除浏览器或单个网站（比如Pixiv）的cookies，这个操作会导致插件记录的下载记录丢失从而无法识别重复下载，有时会比较麻烦（因为上次备份的文件可能在数个月以前，在此期间可能下载大量图片）
_**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*_
-目前尚无其他此类参考。
_**Additional context**
Add any other context or screenshots about the feature request here._
*附加描述*
-因为平时有较为重度的Pixiv图片下载需求（因为经历过画师被封、退站等因素导致的其所有作品删除事件），所以十分依赖此功能，如果可以添加一个自动导出功能就好了。

**Comment by xuejianxianzun** [comment]
我不想添加此功能，因为这个功能只有少数重度用户才会需要，而大多数用户甚至不会每天都去 pixiv，更不会有这个需求了。
（ps：我不太清楚为什么会经常清理 cookies，即使切换 pixiv 账号也不需要清理 cookies 呀）

但是要做到这件事也不难，你可以在 pixiv 的页面上打开控制台，执行 JavaScript 代码来模拟点击“导出”按钮：

```js
document.querySelector('#exportDownloadRecord').click()
```

要达到自动化的目的，你可以使用 Tampermonkey 等“油猴脚本”类扩展来做一个在 pixiv.net 运行的脚本，定期或者在特定时机点击导出按钮。
