### ISSUE TITLE
小说标题出现奇怪字符导致文件命名的错误

### ISSUE THREAD

**Issue by yaoyueweiyang** [xuejianxianzun/PixivBatchDownloader#306]
https://www.pixiv.net/novel/show.php?id=15066191
标题括号中的上后面是一个奇怪的长方形字符，有显示却无法复制，导致其后的内容失效，该作者另有几个作品也是同样的问题。
命名规则为 {series_title} {title} 【作者：{user} pixiv{id}】
实际文件名为“澜江怪异 澜江怪异（11）恶魔之馆（上” ，且没有文件类型。

**Comment by xuejianxianzun** [comment]
已确认问题，这个特殊字符是 `\u0000`，下次更新将会修复此问题。

**Comment by xuejianxianzun** [comment]
15.5.0 版本已提交审核，将会修复此问题。
