### ISSUE TITLE
能否使用第三方下载器下载，如 aira2，IDM？

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#307]
比如 aira2 Motrix

**Comment by xuejianxianzun** [comment]
不能。准确地说，只有部分图像作品可以发送到其他软件进行下载，有些文件则不行。
1. 图像文件有固定的 URL 可以发送到其他下载软件进行下载，但小说没有固定的 URL，它是下载器在浏览器内动态生成的文件，没有可供其他软件使用的 URL。
2. 动图作品的源文件（Zip）有固定的 URL，但如果需要转换成其他格式（如 WebM），那么同样是下载器动态生成的，没有可供其他软件使用的 URL。
3. 还有其他一些动态生成的文件（虽然可能只有少数用户会用到），例如保存作品的元数据到单独的文件、保存作品简介的文件。

PS：你可以尝试使用另一个 Pixiv 下载器，它可以把图像文件发送到指定的 Aria2 下载器下载。
https://github.com/Mapaler/PixivUserBatchDownload/
