### ISSUE TITLE
给未分类作品添加标签时频繁出现429错误

### ISSUE THREAD

**Issue by Wshine233** [xuejianxianzun/PixivBatchDownloader#308]
设置中似乎没有限制添加标签时的处理速度的功能，导致我在处理大量收藏图片时，经常出现429错误。
大概在处理**200张**图片后就会出现429错误：
`XXXXXXXX 添加收藏失败. 错误代码：429. 下载器会在几分钟后重试`
重试可用。

希望能支持 _给未分类作品添加标签_ 时，限制抓取速度的功能。
（虽然说重试可用吧，不过我看文档里提到频繁触发错误会收到警告，所以我认为可以像下载一样限制抓取速度）

**Comment by xuejianxianzun** [comment]
即将发布的 15.8.0 版本会在批量收藏时慢速收藏，以减少 429 错误的概率。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.8.0
