### ISSUE TITLE
下载漫画需要一个图片点击一次下载太麻烦，不能改成直接一次下载一个压缩包吗？

### ISSUE THREAD

**Issue by wycstc353** [xuejianxianzun/PixivBatchDownloader#311]
下载漫画需要一个图片点击一次下载太麻烦，不能改成直接一次下载一个压缩包吗？一个漫画一画要几百章图，现在每张图都要点击一次下载，希望可以改成全部缓存，然后电脑上只要点击一次，下载个压缩包

**Comment by xuejianxianzun** [comment]
我没有懂你的意思。现在下载器的确不会下载压缩包，但是为什么会“一个图片点击一次下载”？你是怎么下载的呢？

在作品页面内，你可以点击快速下载按钮来一键下载所有图片。
当你把鼠标放在作品缩略图上时，缩略图右上角也有一键下载按钮。
当你预览作品时，按快捷键 `D` 也可以一键下载。

**Comment by wycstc353** [comment]
> 我没有懂你的意思。现在下载器的确不会下载压缩包，但是为什么会“一个图片点击一次下载”？你是怎么下载的呢？
> 
> 在作品页面内，你可以点击快速下载按钮来一键下载所有图片。 当你把鼠标放在作品缩略图上时，缩略图右上角也有一键下载按钮。 当你预览作品时，按快捷键 `D` 也可以一键下载。

今天发现原因了，因为我google浏览器下载设置的时候设的是每次下载前询问每个文件的保存位置开了，关了就不用点了，所以几百个文件我要点几百次

**Comment by xuejianxianzun** [comment]
呃呃，下载器在安装后会显示提示的。左下角常见问题里也有提示，你都不看。
