### ISSUE TITLE
下载有卡顿并且弹窗的现象

### ISSUE THREAD

**Issue by kurokawaTK** [xuejianxianzun/PixivBatchDownloader#312]
没有勾选不下载重复文件，浏览器也没有设置下载前询问，偶尔会下载卡住，然后弹窗让我保存，保存后会出现一个未保存的提示，下载变成只有一个线程的并且依旧卡顿

导出了设置和抓取记录等供参考

https://files.catbox.moe/2wwpvo.zip

**Comment by xuejianxianzun** [comment]
你好，我使用你的设置和抓取结果下载了所有文件，没有出现下载卡住和弹窗的问题。
所以你的问题并不典型，或者说导致你出现弹窗的原因并不典型。虽然有一些原因会导致弹窗，但是那些常见的原因都不会在你的这个下载情景中出现。
我猜测可能是硬盘频繁读写细碎文件导致繁忙所致，尤其是如果你使用的是机械硬盘，那么这个可能性就值得考虑了。

我在下载完成之后重新导入抓取结果，开始下载并掐表，在 1 分钟的时间里下载了约 404 个小说，产生了  1182 个文件，共 83 MB。平均每秒会产生 20 个小文件，每个文件平均体积为 70KB。
小说的封面图体积较大，很多都超过了 100 KB。
小说本体很多在 20 KB 左右。
meta 文件大部分都小于 1KB。

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/3e1857e0-c838-46ee-bc7d-1f117e2f6259)

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/7bd0be3c-f2d5-4361-8689-fe16cc468a8b)

**Comment by xuejianxianzun** [comment]
一些 “下载时弹出另存为对话框” 的常见原因：
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?id=%e4%b8%8b%e8%bd%bd%e6%97%b6%e5%bc%b9%e5%87%ba%e5%8f%a6%e5%ad%98%e4%b8%ba%e5%af%b9%e8%af%9d%e6%a1%86
不过这不符合你的情况。
