### ISSUE TITLE
关于图片保存时tag的建议

### ISSUE THREAD

**Issue by LZTSGS** [xuejianxianzun/PixivBatchDownloader#313]
保存图片并在文件名中加入tag时，有三种模式「翻译前」「翻译前附带翻译后」「翻译后」

如果使用「翻译前」保存会直接写入日语标签，由于标签里日语片假名过多，会导致后续图片查看时图片标签不好理解，分类查找不方便。

使用「翻译前附带翻译后」保存时，很容易出现由于文件名过长出现硬截断的问题。

使用第三种「翻译后」时也会有一个问题如下图标签

![Screenshot_20230409235831](https://user-images.githubusercontent.com/67962258/230783326-939b4e92-6c54-4c28-9778-2346372369ae.png)

由于日语汉字和中文一样，翻译结果默认会变成英语。所以当使用第三种保存该图时会出现标签全是英文的情况。

不知道能不能实现保存标签时给标签分优先级，比如给想要语言的标签优先级，要中文时就给带汉字的标签分为优先级，对比翻译前和翻译后，哪个优先级高就保存哪个，从而避免中文标签翻译成英文保存的情况，如没有中文标签则通过优先级的方式使用其他标签，来解决这个问题。

之前我用一款安卓第三方版本的P站软件，它标签保存规则用着挺好的，默认会保存带汉字的。还能实现一些比较明显重复的标签去重复。
下图中的「柯莱」「柯莱（原神）」这两个标签
![Screenshot_20230410000017](https://user-images.githubusercontent.com/67962258/230783483-0ce1d8db-48c6-4dc0-99c7-4bef1892f17c.png)

在保存后会省略前者来减小文件长度。
![Screenshot_20230410000321](https://user-images.githubusercontent.com/67962258/230783527-8f48740b-5db4-41bc-b516-258c16ff5182.png)

不知道这样的标签规则在插件中能够实现，如果能实现的话作者大大能否考虑加入一下。

**Comment by xuejianxianzun** [comment]
你说的是两个功能，第一个功能是当翻译后的标签全部为英文时，使用原始标签。
我找了一些作品看了看，应该不会有什么副作用， 可以试一试。

第二个功能是合并相似标签，这个我觉得不合适，比如你举例的那个文件名里没有出现单独的“原神”，但“安柏（原神）”是“原神”的子项，从分类的角度考虑，它不能取代原神。下载器内部有一些功能会依赖标签来建立文件夹，或者排除作品，这可能会导致错误的结果。一些高级用户会使用下载器生成的文件名或抓取结果来优化他们的文件分类管理，所以这个功能我觉得不行。
而且有时候当一个标签包含另一个标签时，两个标签的含义实际上是不同的。这实际上应该被视为错误。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/43e041cb-a734-44df-8623-e4e4cc71770f)

**Comment by xuejianxianzun** [comment]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/42a8eb58-d107-4998-ab59-231fabcc46e0)
P 站的翻译真的有病，同样是括号里的碧蓝航线，有的翻译为英文有的翻译为中文。

**Comment by xuejianxianzun** [comment]
https://www.pixiv.net/artworks/106130169
フラミンゴ flamingo
P 站翻译的什么玩意，火烈鸟不是有中文吗，用户使用中文，结果它整个日译英。

**Comment by xuejianxianzun** [comment]
即将发布的 15.8.0 版本应用了此优化。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.8.0
