### ISSUE TITLE
360极速浏览器不能安装15.2.0及以上的版本

### ISSUE THREAD

**Issue by 610364023** [xuejianxianzun/PixivBatchDownloader#314]
360极速浏览器不能安装15.2.0及以上的版本
一个一个试，15.1.0可以，之后就不行了
![2023-04-13_14-13-04](https://user-images.githubusercontent.com/45279039/231669581-b2faa5a1-0be2-43c9-9da6-b63de47752f5.jpg)

![2023-04-13_14-10-56](https://user-images.githubusercontent.com/45279039/231669409-9df03475-f9ee-4f2e-9475-75f7f2be9c84.jpg)
![2023-04-13_14-11-10](https://user-images.githubusercontent.com/45279039/231669414-f365008c-6e3a-4242-a4bf-5269431fd9aa.jpg)

**Comment by xuejianxianzun** [comment]
这不是 bug。
国产浏览器的内核版本落后，甚至经过魔改。不要提问相关问题。
