### ISSUE TITLE
需要更明显的下载完成通知

### ISSUE THREAD

**Issue by Jeggedrock** [xuejianxianzun/PixivBatchDownloader#318]
想要个比较明显的下载完成通知，比如声音报警，需要点击的弹窗，带闪瞎眼gif的弹出页面

由于抓取时间经常要几分钟，又有多屏幕，经常没法知道什么时候下载完成。目前的下载完成提示从来没看到过。

从网络蚂蚁到迅雷都有完成提示音

**Comment by xuejianxianzun** [comment]
未经确认的提示音通常认为是对用户不友好的，所以下载器没有加提示音。
不过你可以开启“下载完成后显示通知”，这会在屏幕右下角显示一条通知消息（卡片），通常带有系统提示音。

**Comment by xuejianxianzun** [comment]
![image](https://user-images.githubusercontent.com/17283977/236637854-1cf1cfa2-a9f1-4ab6-8aad-bb598e7d6593.png)
多屏幕会导致你看不到下载完成通知吗？
不过应该依然能听到系统提示音的。

**Comment by Jeggedrock** [comment]
> ![image](https://user-images.githubusercontent.com/17283977/236637854-1cf1cfa2-a9f1-4ab6-8aad-bb598e7d6593.png) 多屏幕会导致你看不到下载完成通知吗？ 不过应该依然能听到系统提示音的。

chrome网站提示音一般都是全局关掉的，每个网站都来问一遍实在是太烦了
