### ISSUE TITLE
Folder creation doesn't works

### ISSUE THREAD

**Issue by UniverseCodex01** [xuejianxianzun/PixivBatchDownloader#320]
**What functionality do you want?

Downloader can create artist folders and artworks folders.

**What is the purpose to solve?

Every picture will be stored in their Artis folder with  the correspondent artwork folder name

**Do other software have such functionality? Is it possible to refer to?**

I don't know.

**Additional context**

On kiwi browser(android browser based on chromium with support for chromium extensions) creation of folders doesn't works, I enabled the option to save artworks with multiple pictures in folders with artwork id and title and also I added {user}/{user_id} to file name to save all artworks in ArtistName/ArtworkID_ArtworkName/filename. But images still stored in Storage emulated0/Downloads/filename.jpg

**Comment by xuejianxianzun** [comment]
This is Kiwi browser`s bug.

**Comment by UniverseCodex01** [comment]
> This is Kiwi browser`s bug.

It's not possible to be fixed on future updates?

**Comment by xuejianxianzun** [comment]
> > This is Kiwi browser`s bug.
> 
> It's not possible to be fixed on future updates?

The downloader cannot fix this issue. This can only be fixed by Kiwi Browser.

**Comment by UniverseCodex01** [comment]
> > > This is Kiwi browser`s bug.
> > 
> > It's not possible to be fixed on future updates?
> 
> The downloader cannot fix this issue. This can only be fixed by Kiwi Browser.

Wrong comment form my side, sorry. I confused this issue with my issue on kiwi repo. Sorry
