### ISSUE TITLE
关于线程的问题

### ISSUE THREAD

**Issue by UNSCs117** [xuejianxianzun/PixivBatchDownloader#322]
emmm目前使用了近2年了，目前是同类里最好用的，不过观察下来发现下载线程貌似只是同时下载几张图片而已，并非代表像IDM那样一个文件有多少个线程。当网络带宽很高或者网络很好的情况下这样没啥差别，但是在网络有些问题的情况下却会导致下载速度及其慢。目前人在德国，用的edge，网速100M，实测在70-80M左右，IDM线程拉满一张图只需要几秒就能下载完，但是用这个脚本时每张图只有几至几十K的下载速度，半小时过去了还是那几张正在下载的图，而IDM批量下载35张只花了3分钟就结束了。所以啥时候考虑把下载线程转向类似IDM下载策略那样的单文件多线程？再考虑到转webm之类的动图文件下载，这种单文件多线程的反而会加快总体下载速度。。。

**Comment by xuejianxianzun** [comment]
下载器使用的是 JS 的 XHR 来加载图片，约等于浏览器内置的下载功能，不支持多线程，目前我也没有这个打算。

真正的多线程下载通过指定 Range 把文件分为多个区块进行下载，这不仅会使下载管理和错误重试等代码更加复杂，而且浏览器本身就不适合太多线程请求，因为浏览器有连接数限制，通常对同一网站只支持 6 个并发请求，这也是为什么下载器限制了最大同时下载数量为 6。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/d02361da-36c7-4031-929e-f695ee14e524)
假如同时下载 5 个文件，每个文件 4 线程，总共 20 个请求，那么无疑会有很多在排队，等前面的请求完成了才会执行后面的请求，并不能实现 IDM 那样的效果。因为 IDM 不是浏览器，它没有同时请求数量为 6 的限制。

另外你说的 `网速100M，实测在70-80M左右`，测速结果不代表在任何网站你都有这个下载速度，就像以前在国内如果你是联通宽带，去下载只有移动或电信线路的资源会很慢。而 pixiv 是个外国网站，或许没有良好的接入你的网络运营商，才会只有几十K。从你的描述来看，即使你用 IDM 提高了速度，其实下载速度依然不算很快。
我建议你尝试改善网络环境，例如试试梯子，如果有效果的话那么你直接在浏览器里下载也会比较快。不行的话就用 IDM 下载吧，浏览器难以实现 IDM 的效果。
