### ISSUE TITLE
Protect Download History

### ISSUE THREAD

**Issue by LittleBenjiBoy** [xuejianxianzun/PixivBatchDownloader#323]
**What functionality do you want?**
*你想要什么功能？*
I want the ability to backup and restore download history.

**What is the purpose to solve?**
*目的是解决什么问题？*
To prevent losing download history. To never download duplicate images.

**Do other software have such functionality? Is it possible to refer to?**
*其他软件是否有此类功能？是否可以参考？*
Yes, [Pixiv Downloader](https://chrome.google.com/webstore/detail/pixiv-downloader/fnbkeopcpjainobjebddfcnnknmfipid).

**Additional context**
*附加描述*
This is how it looks for the extension [Pixiv Downloader](https://chrome.google.com/webstore/detail/pixiv-downloader/fnbkeopcpjainobjebddfcnnknmfipid):
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/43734617/39b82727-ac4f-4fd9-8610-ced0862ae70c)

**Comment by xuejianxianzun** [comment]
Already have this feature.
First enable `Don`t download duplicate files`, after that you can export or import downloader records.
The exported record can be imported (appended) to the download record of the downloader.

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/5576ba68-8eee-4ef8-b24c-86422b1ccce7)
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/15740411-27ae-49a6-89c1-c7e46e6748b0)

**Comment by LittleBenjiBoy** [comment]
Thank you. I did not try enabling `Don't download duplicate files`, so I did not know. I did not know that the history gets appended. This is good to know.

Thank you for making such a nice extension and for maintaining it.
