### ISSUE TITLE
请问怎么只下载新的内容？

### ISSUE THREAD

**Issue by faker1708** [xuejianxianzun/PixivBatchDownloader#324]
比如之前 已经下载800张了，然后作者新增了100张，我应当怎么只下载这新的100张？

**Comment by xuejianxianzun** [comment]
打开画师的作品列表页面，找到上次下载到的最后一个作品，进入这个作品的页面，使用按钮“从本页开始抓取新作品”，这样也会只下载新的作品。

你也可以使用 “设置 id 范围” 或 “设置投稿时间” 选项。

**Comment by faker1708** [comment]
这有点麻烦啊，还得我来一个一个看下载到哪了。这种功能不应该全自动么，可能你们需求不大吧。

**Comment by xuejianxianzun** [comment]
你即世界，所有人的需求应该和你一样？
不过你可以开启 不下载重复文件，但这也不是万能的。因为下载器没有权限检测你硬盘上是否存在对应文件，否则你想要的效果并不难做。
