### ISSUE TITLE
下载时发生错误，状态码为 0，请求未成功。

### ISSUE THREAD

**Issue by xuruixiang2008** [xuejianxianzun/PixivBatchDownloader#325]
**Describe the bug**
在抓取作品时使用慢速抓取避免限制，但这导致有些画师删除作品，当下载器准备下载被删除的作品时会报错。

**To Reproduce**
如果抓取时间较久，有些画师会删除自己的作品，这导致了报错。

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/119653652/8f71a2f7-a052-41f6-8b09-970fcd1edf0d)
[2. 抓取时的页面 URL](https://www.pixiv.net/tags/%E3%82%B9%E3%82%AB%E3%83%A9%E3%83%9E%E3%82%B7%E3%83%A5/artworks?s_mode=s_tag)
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。
[下载器设置及抓取结果.zip](https://github.com/xuejianxianzun/PixivBatchDownloader/files/11781361/default.zip)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
如果无法解决的话，可以增加一个忽略报错的功能。

**Comment by xuejianxianzun** [comment]
我表示怀疑，尝试下载被删除的文件应该显示 404 错误，而不是状态码 0.

**Comment by xuruixiang2008** [comment]
我发现那些作品并没有被删除，但是我重启了浏览器和代理服务器依然错误，并且还会出现另存为弹窗

**Comment by xuejianxianzun** [comment]
那系统盘剩余空间呢？
提示里的三个可能性是从高到低的，你试试吧，如果都不行的话我也没办法。

**Comment by xuruixiang2008** [comment]
系统盘剩余空间7GB，可是依然报错，如果无法解决可以加一个忽略报错的开关吗

**Comment by xuejianxianzun** [comment]
忽略的话下载失败的怎么办，不管了

**Comment by xuruixiang2008** [comment]
我试试能否记录日志，但我发现如果访问请求未成功的页面并不关闭标签页再点击下载却是正常的。

**Comment by xuejianxianzun** [comment]
可能是网络问题？或者除了我列出的 3 种情况外还有未知原因？那还挺少见的，我不知道为什么。
目前不打算添加这样的开关。
