### ISSUE TITLE
能否让下载后收藏这个功能也能慢速完成

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#327]
慢速抓取可以有效防止被限制，但是下载后收藏是并发的

**Comment by xuejianxianzun** [comment]
可以考虑，之后我看看

**Comment by xuejianxianzun** [comment]
即将发布的 15.8.0 版本会在批量收藏时慢速收藏，以减少 429 错误的概率。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v15.8.0
