### ISSUE TITLE
请问快捷键功能可以关闭吗

### ISSUE THREAD

**Issue by Dream5366** [xuejianxianzun/PixivBatchDownloader#328]
或者是否可以修改快捷键？我只看到对快捷键的说明，没看到怎么关闭这个功能，考虑到这个会跟别的软件和应用的快捷键冲突，而别的软件应用可能无法修改快捷键，以及还有误操作导致快捷键变成慢捷键的问题

**Comment by xuejianxianzun** [comment]
目前不能关闭。
虽然确实可能会出现快捷键冲突的问题，不过几率很小，因为下载器的快捷键已经避免了与浏览器快捷键的冲突。所以冲突应该只能是其他软件导致的，而且它（们）还得启用了全局快捷键，不然影响不到浏览器内的页面。
虽然确实可以添加关闭快捷键的设置，但是很少有人遇到冲突问题（在我印象里你是第一个反馈此问题的人），所以目前我不打算添加此设置。
你目前已经遇到冲突了吗？可以对你遇到的情况加以说明吗？

**Comment by xuejianxianzun** [comment]
长时间未回复，关闭此问题。
