### ISSUE TITLE
Tag bug 

### ISSUE THREAD

**Issue by DABnoREGRET** [xuejianxianzun/PixivBatchDownloader#329]
Found a bug that make tag separator (or the entire tagging) stop working. It is because the tag list accept character that break lines, for example: My Youth Romantic Comedy Is Wrong, As I Expected broke the list resulting in [this](https://pastecode.io/s/ude7kd33)

**Comment by DABnoREGRET** [comment]
I have to change it like [this](https://pastecode.io/) for it to work

**Comment by DABnoREGRET** [comment]
Maybe I misunderstood the tag separation function, but the problem remains in tags that have "," in them, jeopardizing the list.

**Comment by xuejianxianzun** [comment]
The "Tag separation symbol" feature only affects separators in the characters generated by these tags:
- `{tags}`
- `{tags_translate}`
- `{tags_transl_only}`

"Create a folder with the first matched tag" must use `,` as delimiter.

**Comment by xuejianxianzun** [comment]
I will add a note in the next version:
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/09718d6a-287f-48c0-aea0-648e17a6f3c2)

**Comment by DABnoREGRET** [comment]
Thanks, but still, tag that have `,` make the tag list broken too, please address that as well.

What it should be
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/57186199/21da3686-8d32-48cd-a850-021f9e43ed19)

What it is currently
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/57186199/7d9dee4b-6ab5-4ce6-8990-204fdf9f65fa)

**Comment by xuejianxianzun** [comment]
No, pixiv's tags don't contain `,`, I don't know where your tag came from.

**Comment by DABnoREGRET** [comment]
> No, pixiv's tags don't contain `,`, I don't know where your tag came from.

I think it's the translation of tag
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/57186199/3a68ef28-92bd-4589-9d57-1c55a0873bd9)
Which is what I use for my tag list

**Comment by DABnoREGRET** [comment]
Also, in some very rare case there are `,` in actual tag as well,
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/57186199/5637cbef-8104-4439-a34d-b894ba897a2f)

**Comment by xuejianxianzun** [comment]
The rare cases you've listed are all bad, and I can't fix this. See the example below:
`少女,女孩子,碧蓝航线,斗罗大陆,小舞,朱竹清,宁荣荣,千仞雪,比比东,波赛西,公主连结Re:Dive`
How to tell which tags are exceptions? There is no way, unless additional means are taken.
For this problem, I suggest you use tags without `,` instead, like:
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/ca3645e6-f763-4a4a-aa45-dc04c4e29a28)
