### ISSUE TITLE
抓取结果为0

### ISSUE THREAD

**Issue by timk-lalala** [xuejianxianzun/PixivBatchDownloader#330]
我不知道为什么在抓取的时候提示没有符合的图片，我所有设置已经还原。并且重新安装过插件。

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17139396/fa39d665-221b-4cc4-ae16-8037a532591c)

我抓取这这位画师的就不能抓取      https://www.pixiv.net/users/89469319
但是其他画师好像没有问题

**Comment by timk-lalala** [comment]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17139396/3052f420-1a2e-46e3-a845-04c35f4aa8d3)
在这里屏蔽的标签会导致无法抓取，能否忽略屏蔽标签。因为观看可以正常观看，但是抓取就会提示无符合要求的图片

**Comment by xuejianxianzun** [comment]
你屏蔽了怎么说能正常观看呢？

**Comment by xuejianxianzun** [comment]
我知道了，你屏蔽了 `AI生成`，作品的标签列表如下：
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/2d87af10-0b28-4fcb-b067-1c0fc4708372)
pixiv 给它显示了个  `AI生成` 的标记，下载器把它视为一个标签处理，所以你能看到这个作品，但下载器却会排除它。
你取消屏蔽  `AI生成` 即可，因为这个屏蔽是没什么作用的。

---------

### 对于 AI 生成的作品，下载器会在抓取结果的标签列表里添加特定标记

在 AI 生成的作品页面里，标签列表处会显示 `AI生成` 的标记。实际上这个 `AI生成` 并不是作品的标签，只是 pixiv 显示的一个标记。但是因为它和作品的标签显示在一起，所以很多人以为这是作品的标签里的，进而疑惑为什么下载器抓取不到这个“标签”。

所以现在下载器干脆把这个标记添加到了作品的标签列表里。

**提示：**根据用户在 pixiv 使用的不同语言，`AI生成` 这个标记也字会随语言变化。下载器会根据语言来添加对应的标记，比如英文时添加的标记是 `AI-generated`。

**Comment by timk-lalala** [comment]
这个屏蔽方式有用的，如果设置后排行榜里或者搜索的里面是看不到AI标签的作品的。

**Comment by raeka21** [comment]
English lang here. For those who's having the same problem, you could just check that box for "unknown". It works for me at least.
