### ISSUE TITLE
这个屏蔽方式有用的，如果设置后排行榜里或者搜索的里面是看不到AI标签的作品的。

### ISSUE THREAD

**Issue by timk-lalala** [xuejianxianzun/PixivBatchDownloader#331]
这个屏蔽方式有用的，如果设置后排行榜里或者搜索的里面是看不到AI标签的作品的。

_Originally posted by @timk-lalala in https://github.com/xuejianxianzun/PixivBatchDownloader/issues/330#issuecomment-1626960051_

**Comment by xuejianxianzun** [comment]
你在p站的设置里也可以屏蔽AI作品的
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/e06fa6c3-bb36-4268-8dcb-9fb2241ea55c)

**Comment by timk-lalala** [comment]
我试过了，最后把屏蔽标签关掉之后就好了。但是带着个标签的作品是可以正常观看的，只是某些场景下不会显示而已。

**Comment by xuejianxianzun** [comment]
设置里隐藏AI作品需要画师 在 发布作品时指定这个作品是AI产生的，这样 P 站才知道 它是 AI 的，才能屏蔽它。
而屏蔽“AI生成”的标签则需要这个作品的标签列表里含有“AI生成”。
这是两种不同原理的屏蔽方式，没有完美的。
