### ISSUE TITLE
错误代码：429（请求数量过多），Pixiv 返回了空数据。下载器已暂停抓取

### ISSUE THREAD

**Issue by CodeEngieer** [xuejianxianzun/PixivBatchDownloader#332]
**Describe the bug**
在爬取300张图片的时候会报错429，表示
（请求数量过多）。下载器会重新抓取它。
Pixiv 返回了空数据。下载器已暂停抓取，并且会在等待几分钟后继续抓取。(429)
**To Reproduce**
How to reproduce this problem?
爬取超过一定数量的图片，就会报这个错误

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

在爬取这个画师时报错，其实之前爬取很多画师的时候也报这个错误。https://www.pixiv.net/users/57536037/artworks?p=7
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/75971727/e7a66372-8cb5-4544-a3f5-e6fc5c47942b)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xuejianxianzun** [comment]
老生常谈了，这是p站的限制，高频抓取就会这样，你开启下载器的慢速抓取功能。
