### ISSUE TITLE
very slow download after crawling.

### ISSUE THREAD

**Issue by 96neko22** [xuejianxianzun/PixivBatchDownloader#333]
**Describe the bug**

It might be a bug, or may be a change in the system of pixiv.
Currently, the speed of download has become very slow.
Before a few days, it downloaded 30-40 pictures per 5 seconds.
Now it downloads 4-6 pictures per 20 seconds. 

I do not have knowledge of programing, but I feel the pixiv has introduced some anti-scraping system or regulation for sending request in a short term, whatever. 

**To Reproduce**
Sorry, I do not have an idea.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: very current.

**Additional context**
I cleared cache and cookies to try to fix problem, but it did not work.

Thanks for everything you made.
I love to use Powerful Downloader.

**Comment by xuejianxianzun** [comment]
How many files were downloaded when this problem occurred? Do you have any screenshots?

**Comment by xuejianxianzun** [comment]
This is not a typical problem, if you can reproduce the problem, please let me know how to do it.

**Comment by 96neko22** [comment]
Total downloaded files may be around 200,000 from I started to use. Now, I feel the problem is not in the pixiv website. Very slow download problem is possibly due to a large amount of cache or cookies ( I guess ). 
I uninstalled Google chrome to reset my browser, and I do not know what was changed, but now I can download very quickly as usual. So, I should clear cache or cookies regularly to reduce pressure of something in the PC.
Sorry for unclear information !

**Comment by xuejianxianzun** [comment]
Ok.

There is a specific phenomenon: if the browser freezes for a while when you start it, it means that you need to clear the download history of the browser.
Not sure if your problem has anything to do with this.

Another possibility is: if tens of thousands of files are downloaded in a page, for example, the download progress is `150000/200000`, it may cause the download to become slower and slower. But this should not affect other pages.
