### ISSUE TITLE
Pixiv小说插图问题

### ISSUE THREAD

**Issue by FErDaiif** [xuejianxianzun/PixivBatchDownloader#334]
**Describe the bug**
*请描述你遇到的问题。*

在文本里面多个重复的[uploadedimage:]，在epub里面只有第一个出现的[uploadedimage:]能够作为图片显示

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*

https://www.pixiv.net/novel/show.php?id=20211870
可以自行实验

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xuejianxianzun** [comment]
已确认问题。
之前没预料到会有这种情况，下个版本我会修复此问题。

**Comment by xuejianxianzun** [comment]
15.9.0 版本会修复此问题，审核中。
