### ISSUE TITLE
考虑下火狐版的扩展呗？

### ISSUE THREAD

**Issue by SteveYu000** [xuejianxianzun/PixivBatchDownloader#335]
**What functionality do you want?**
*你想要什么功能？*
希望做一个火狐版的扩展

**Comment by xuejianxianzun** [comment]
重复的问题。
https://github.com/xuejianxianzun/PixivBatchDownloader/issues/295

提 issue 之前先搜索是个好习惯。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/0d1c1a1e-5977-4498-80f6-3e96823d88bf)
