### ISSUE TITLE
一个功能建议

### ISSUE THREAD

**Issue by moxue128** [xuejianxianzun/PixivBatchDownloader#337]
请问能否加一个批量收藏的功能，而不是下载后收藏。有些收藏过了，但是换号之后又要重新收藏很麻烦

**Comment by xuejianxianzun** [comment]
没什么麻烦的，收藏作品前本来就要获取作品数据。下载后收藏只不过多了个下载的步骤，你可以把下载的图片尺寸设置为小图，这样下载很快，不耗什么时间。
