### ISSUE TITLE
偶發性下載停滯

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#338]
**Describe the bug**
*请描述你遇到的问题。*
偶爾會有下載到一半就停下來了，跟空間無關我桌面還有數十G的空間。這時就要重新整理頁面才可繼續。
**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*
下載時
**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xuejianxianzun** [comment]
发生此问题时，下载器有显示提示吗？例如：
>發生錯誤，原因：xxx 請重新整理頁面。
如果有此提示，说明下载器检查到了这种情况，但无法自动修复。无法进一步对此进行优化。

**Comment by e1e1111e1e** [comment]
沒有就突然載不了。還是是chrome的問題，因為發生這情況後我的chrome關掉後就打不開必須重開電腦。

**Comment by xuejianxianzun** [comment]
我以前遇到过类似的情况，可能是 Chrome 的下载管理崩溃了。
此时 Chrome 关掉后打不开，但是在任务管理器里应该还有一个 chrome.exe 的进程。结束它之后就可以重新打开 Chrome 了。

**Comment by xuejianxianzun** [comment]
下次更新我会尝试检测这种情况：向浏览器发送下载后 3 秒如果没有收到回应，就提示刷新页面重试。

**Comment by zhaomma** [comment]
edge一次浏览器更新后，也遇到了这个问题。
面板下载显示中全是已完成的，但总下载进度未完成。
暂停下载后再开始下载一般一次就解决了。
通常是最后几张才出现这种情况。
看起来就像不再向浏览器提交新的下载任务。

下载线程设置为1后，基本不再出现该情况。

**Comment by xuejianxianzun** [comment]
我刚才试了同时下载3个，下载了 4436 个文件，没有卡住。所以这个问题难以复现和调试。

**Comment by xuejianxianzun** [comment]
> 下次更新我会尝试检测这种情况：向浏览器发送下载后 3 秒如果没有收到回应，就提示刷新页面重试。

现在你们还会出现下载卡住的问题吗？出现问题时是否会显示这个提示？

**Comment by e1e1111e1e** [comment]
有看到了

**Comment by xuejianxianzun** [comment]
能看到这个提示就好。至于真正的原因和解决方法我还没有头绪。最近我下载了上万个图片也没遇到中途卡住的情况。
