### ISSUE TITLE
发现页 相关作品展示不完全

### ISSUE THREAD

**Issue by duoluodeyouhei** [xuejianxianzun/PixivBatchDownloader#339]
bug1: 在发现页面，点击某一作品收藏，会在下方弹出相关作品。此时如果开启了显示原始比例图片功能，那么弹出的相关作品没有办完全展示。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/40574965/3004c9d1-7261-4ad2-b30a-f789068a228b)

bug2: 好像p站更新了版本，给图片增加了固定的宽度和最大高度，导致显示原始比例图片功能不正常，望尽快修复。

**Comment by xuejianxianzun** [comment]
1. 点击收藏后，下方显示的相关作品的左右两侧有箭头，可以点击箭头查看其余作品。
2. 下个版本会修复“显示更大的缩略图”失效的问题，等会儿就提交到谷歌商店审核。

**Comment by duoluodeyouhei** [comment]
> 1. 点击收藏后，下方显示的相关作品的左右两侧有箭头，可以点击箭头查看其余作品。
> 2. 下个版本会修复“显示更大的缩略图”失效的问题，等会儿就提交到谷歌商店审核。

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/40574965/b325e2b2-9d63-4265-b3e9-22c829a981e8)
箭头是有的，但是还是显示不完全，一般相关作品是推荐十个，开启了显示原始比例图片功能，推荐作品少而且最后一个通常显示半张画。好像箭头左右移动距离是固定的。

**Comment by xuejianxianzun** [comment]
有时会有这个问题，因为下载器没能修改横向滚动区域的大小和滚动逻辑。
首页的第一排横向滚动区域也有类似问题，因为 p 站原本的缩略图每个大小都是一致的，一次滚动固定距离。
下载器把作品改为更大的缩略图后，每个缩略图的宽度都可能不同，此时按照原本的逻辑就会产生一些错乱。
现在我也没法修复此问题。
