### ISSUE TITLE
希望增加小说下载的功能

### ISSUE THREAD

**Issue by YuhangSco** [xuejianxianzun/PixivBatchDownloader#34]
特别是直接下载系列小说，如果能加上自动简繁转换或者翻译就更好了。

**Comment by xuejianxianzun** [comment]
小说有其他扩展可以下载，你去谷歌商店搜 pixiv 看下。
因为用户对小说的需求比较小，我自己也不看，所以还没有计划增加这个功能。

**Comment by YuhangSco** [comment]
嗯，我发现了两个插件，不过是日文的😂看不懂，装了之后点download也没反应 。

**Comment by xuejianxianzun** [comment]
我也不清楚，我没怎么用过其他的下载扩展
