### ISSUE TITLE
No animation.json from downloaded ugoira zip files

### ISSUE THREAD

**Issue by basic2004** [xuejianxianzun/PixivBatchDownloader#340]
**Describe the bug**
I downloaded pixiv artworks, ugoira files are downloaded zip type.
but this is not ugoira type, there is no animation.json from downloaded zip files.

**To Reproduce**
Just download ugoira artwork as ZIP file and open it with image viewer support ugoira (ex. HoneyView)
but currently this is detected multi image files, not animated.
If contains animation.json within ZIP file, this will be animated.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Microsoft Edge
 - Version: 115.0.1901.188

**Comment by xuejianxianzun** [comment]
Using animation.json to play zip animation is not a standard solution, and the downloader will not support it.
You can change the zip extension to ugoira, and honeyView can also play it. But since there is no frame delay information, the delay is incorrect.
