### ISSUE TITLE
可能发生了错误。请刷新页面重试。

### ISSUE THREAD

**Issue by Jaassa** [xuejianxianzun/PixivBatchDownloader#341]
**Describe the bug**
更新到最新版本后，下载时会刷很多“可能发生了错误。请刷新页面重试。”的提示，但测试了一下下载没有发现什么实际影响。

**To Reproduce**
在任何画师的主页开始下载都会触发

**Diagnostic information**
打开“收集错误”看了下控制台，没有看到什么报错。log里也就是和截图一样大量地在刷“可能发生了错误。请刷新页面重试。”

**Screenshots**
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/81044437/b437eee8-1d70-403a-8ff7-869381eaef6e)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2 22621.2070
 - Browser Edge Dev
 - Version 117.0.2007.0 (正式版本) dev (64 位)

**Comment by xuejianxianzun** [comment]
这个提示是上次更新增加的，代码有些问题，导致它可能意外出现（并不总是如此）。我更新 16.0.4 版本修复一下。
