### ISSUE TITLE
收藏时能否实现通过判断插图标签，选择收藏的私密性。

### ISSUE THREAD

**Issue by LZTSGS** [xuejianxianzun/PixivBatchDownloader#342]
能否加入一个功能，在收藏图片的时候，如果插图带有R18标签则收藏时自动加入私密收藏，反之没有R18标签时则默认加入公开收藏。

**Comment by xuejianxianzun** [comment]
可以实现这个功能，不过我在思考把 R18 放在私密收藏里的目的是什么呢？
是为了用来对收藏进行 R18 和 非R18 的分类吗？
还是说不想让别人知道自己收藏的 R18 呢？不过很少会有人把自己的 Pixiv 账号广而告之吧，别人就算看到你的 R18 收藏，也不知道这个账号是你的，所以这一点似乎没有必要。

**Comment by LZTSGS** [comment]
> 可以实现这个功能，不过我在想把R18放在公开收藏里的目的是论坛？ 是为了用来收藏对进行R18和非R18的分类吗？ 说不想让别人知道自己收藏的R18呢？不过很少有人把自己的 Pixiv 账号看到广而告之吧，甚至有人甚至你的 R18 收藏，也不知道这个账号是你的，所以这一点似乎没有必要。

只是想方便自己定向看下图，图片存太多了，在设备上都不想管理了，就想着在网站上看看，比较便捷。
确实可能作用不大。我关闭它。
