### ISSUE TITLE
關注用戶的最新作品擷取卡住

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#344]
**Describe the bug**
*请描述你遇到的问题。*
關注用戶的最新作品頁面擷取卡住，我設定排除插畫、漫畫只留動圖小說。擷取完後並未出現開始下載就卡住了。
但沒排除的話則不會出現，不確定是不是偶然。過去兩個月都沒遇過今天才出現。

只出現下面文字

清單頁面擷取完成
目前有 29 個作品
開始取得作品資訊
待處理 0, 共擷取到 4 個作品

**To Reproduce**
How to reproduce this problem?
*如何重现这个问题？*

**Diagnostic information**
1. Screenshot of the problem
2. The URL of the page when crawling
3. Export the settings of the downloader and add to the attachment if needed.
4. Export crawl results and add to attachments if needed.

*诊断信息*
1. 问题截图
2. 抓取时的页面 URL
3. 如果需要，导出下载器的设置，并添加到附件。
4. 如果需要，导出抓取结果，并添加到附件。

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by xuejianxianzun** [comment]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/0d14a450-b20d-4ea1-b68b-39d0584c8e91)
我试了没问题，可以自动抓取并下载。
你刷新页面重试一下看看。

**Comment by Gavin1937** [comment]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/71205842/7937bac1-ef9d-460c-b9d6-fcc96af82909)

我也遇上了类似的问题，在选择按照ID范围抓取后，点击 `开始抓取` 就卡住了
```
开始抓取
排除作品类型：AI 生成
id > 105670260
下载所有页面
正在抓取，请等待……
当前有 63 个作品
开始获取作品信息
待处理 0, 共抓取到 2 个作品
```

不过通过 `手动选择作品` 来抓取就没问题

这是点击 `开始抓取` 后 console 的报错

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/71205842/7663baab-827c-4bc3-9a60-98ded23fb8ce)

版本号：16.1.2

**Comment by xuejianxianzun** [comment]
已确认此问题，基本上是开启 ID 范围并且符合条件的作品少于 10 个时，才会发生此错误。
下次更新 16.1.3 会修复此问题。
离线版本已发布：https://github.com/xuejianxianzun/PixivBatchDownloader/releases
