### ISSUE TITLE
希望在edge上也能正常使用

### ISSUE THREAD

**Issue by player99963** [xuejianxianzun/PixivBatchDownloader#345]
edge瀏覽器可以直接使用chrome的擴充功能，但這個卻不行，我覺得非常可惜，使用上也比較困擾。
我想可能是哪裡出了問題，導致它無法在edge上適用，做一些調整應該就可以了？

**Comment by xuejianxianzun** [comment]
这个在 Edge 上怎么“不行”和“困扰”？我测试了并无问题，请详细说明。

**Comment by player99963** [comment]
> 这个在 Edge 上怎么“不行”和“困扰”？我测试了并无问题，请详细说明。

正常是可以使用的？我在edge上完全看不到可操作的按鍵

**Comment by xuejianxianzun** [comment]
你首先在 Edge 的扩展管理里看有没有安装好。然后打开 pixiv 页面看看。

**Comment by player99963** [comment]
> 你首先在 Edge 的扩展管理里看有没有安装好。然后打开 pixiv 页面看看。

![擷取](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/36121614/533c76ea-0645-48fc-8476-06833da9d6c6)
看起來正常
我關閉其他擴展也沒用，所以應該不是跟其他擴展有衝突
我最近剛重灌，重灌前後都是這個樣子，所以應該也不是我的電腦有什麼問題

**Comment by xuejianxianzun** [comment]
呃呃，你这是 fanbox 的下载器，不是  pixiv 的。

**Comment by xuejianxianzun** [comment]
pixiv 的是这个
https://chrome.google.com/webstore/detail/powerful-pixiv-downloader/dkndmhgdcmjdmkdonmbgjpijejdcilfh
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/02dccf33-2b0c-414a-a833-610a059e3c21)

**Comment by player99963** [comment]
> 呃呃，你这是 fanbox 的下载器，不是 pixiv 的。

噢，看來是我轉移擴充時出什麼差錯
用了之後沒有問題，感謝
