### ISSUE TITLE
请问可以出个支持火狐浏览器的版本吗

### ISSUE THREAD

**Issue by huoying57** [xuejianxianzun/PixivBatchDownloader#346]
主力是火狐浏览器，为了这个插件一直在火狐和edge之间切换，想询问下是否可以出个支持火狐的版本

**Comment by xuejianxianzun** [comment]
好像很多人提 issues 前好像都不会先搜索已有 issues。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/389e196d-ce7c-42db-b886-0484bb6a5871)
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/3c5c08a4-7119-4dbc-952e-cc1d613e12c4)
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/21bd961e-f570-4946-9835-59c3ade4e815)

**Comment by xuejianxianzun** [comment]
Firefox version:
https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/
