### ISSUE TITLE
希望添加图片放大和关注者高亮功能的开关

### ISSUE THREAD

**Issue by SuSWhW** [xuejianxianzun/PixivBatchDownloader#349]
1.目前的图片放大功能会使pixiv首页的滚动图显示不全，希望能添加个开关让用户自行选择是否开启此功能
2.关注者高亮的黄标有点丑（，希望也能加个开关

**Comment by xuejianxianzun** [comment]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/9197ae3c-4ed7-48f5-bf00-3e529bc97209)
