### ISSUE TITLE
下載後的文件命名問題

### ISSUE THREAD

**Issue by cmcmcmcm2** [xuejianxianzun/PixivBatchDownloader#35]
在網頁中的擴充元件下載頁面中 是正常命名
但是到了目的地文件卻是維持原本的編碼命名
例如1f9a6a68-a345-4518-8360-5111829d3a90.jfif
請問要怎麼解決

**Comment by xuejianxianzun** [comment]
关闭其他与下载有关的浏览器扩展试试

**Comment by cmcmcmcm2** [comment]
有了 正常顯示了 感謝大大協助^^

**Comment by xuejianxianzun** [comment]
ok

**Comment by cmcmcmcm2** [comment]
另外想問一下 怎麼切換語言的部份
有勞了

**Comment by xuejianxianzun** [comment]
p站首页底部可以设置语言
下载器与这里的语言保持一致

**Comment by cmcmcmcm2** [comment]
了解 謝謝

**Comment by miracleyoo** [comment]
遇到了相同问题，提供一个参考：我试错后关闭的插件是 Image Downloader
![image](https://user-images.githubusercontent.com/15561716/127743377-cf34d5c7-2d0d-454d-8a46-5aa7593eb949.png)
