### ISSUE TITLE
[BUG]首页瀑布流图片不会自动填充图片空隙

### ISSUE THREAD

**Issue by SuSWhW** [xuejianxianzun/PixivBatchDownloader#350]
在目前的版本中，图片会放大，但是放大后的图片不会自动填充其他图片的空隙，这样会使整个界面比较凌乱，如果能像瀑布流那样有一个判断逻辑，自行微调图片的大小并自动填充图片之间的缝隙会更好

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/120356642/17287d75-0e90-4845-8ad5-66381ee8c885)
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/120356642/473fb405-5530-49eb-8d96-c734ea63213b)

**Comment by xuejianxianzun** [comment]
1. 我不打算做瀑布流，因为这比较复杂，而且 Pixiv 一些元素的 className 经常会变，这会导致此功能经常出问题。事实上现在的“显示更大的缩略图”就经常因为 Pixiv 的改版而出现问题、
2. 你应该开启“横图显示2倍宽度”，这个功能就是为了解决横图在竖图中间看着很奇怪的问题。开启后你看着下面空了一截的横图会变成 2  倍宽度，以弥补空隙，平衡视觉感受。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/f6aa1334-eae5-44ac-9db9-7a0ccfa505f7)
开启的效果：
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/06f6a29a-8a3e-4c5e-8113-b2d80e1de499)
3. 我看到你同时使用了其他脚本（显示收藏数量的），不知道它是否与下载器的这个增强功能冲突。
