### ISSUE TITLE
擷取跟下載

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#351]
**你需要什么功能？**

避免禁帳警告

**目的是解决什么问题？**

現在連慢速下載都會被擋解取數大概180個(在關注用戶最新作品)
擷取後下載到一定數量後會出現禁帳警告(大概100張圖)

**其他软件是否有此类功能可以参考？**

**附加描述**

**Comment by xuejianxianzun** [comment]
我无法解决。要想不被封禁，只能自己少下。
