### ISSUE TITLE
能否加个定时保存抓取结果的功能？

### ISSUE THREAD

**Issue by greenhand10086** [xuejianxianzun/PixivBatchDownloader#352]
**你需要什么功能？**
定时保存抓取结果
**目的是解决什么问题？**
有时候浏览器会突然崩溃，或者忘了还在抓取，把浏览器或电脑关了，抓取进度就全部丢失了。

**Comment by xuejianxianzun** [comment]
目前不打算加，因为下载器现有的功能不好处理一些额外考虑到的情况。

1. 进度不好处理。
比如要抓取1000个作品，因为过滤器，会剩下 400 个。
然后页面被意外关闭了，重新打开，看到恢复了 233 个抓取结果，那么你下载这 233 个之后，是否还要抓取之前没抓取到的？
我想通常是需要的，但此时你并不能确定上次抓取到了哪里，现在该从哪里继续抓取。如果要避免遗漏，那只能全部再抓取一次。这就使得“保存一部分抓取结果”变得没那么有意义。

此外还有些相对少见的情况：

2. 很久以来，下载器是没有“停止抓取“功能的，用户必须通过关闭或刷新页面来达到停止抓取的目的（并且这不会保存关闭页面时已经抓取到的结果）。如果有人想和以前一样，通过关闭页面来放弃这次抓取，那么“定时保存抓取结果”就和预期的“放弃抓取”不符。

3. 打开同一个网址的多个页面同时抓取时，保存的结果会互相替换掉（顶掉）。如果页面保持打开，这不会影响正常下载。但是如果是关闭页面后再次打开，恢复数据，就会出现问题。
不只是“定时保存”会这样，现在的抓取完之后保存也存在这个问题。例如我同时打开三个 Pixiv 首页，然后让它们同时抓取一部分 ID 范围（我筛选壁纸时就是这样操作的）。在长时间的执行中，如果它们三个都定时保存抓取结果（或者是抓取完之后保存的结果），那么最后一次保存的会覆盖掉之前的。
这是因为下载器目前是用网址来区分保存的数据，所以一个网址只有一份保存的抓取结果。如果一个网址打开了多个页面，保存了多个结果，那么其实只会保存最后一次的数据。如果页面或浏览器被意外关闭，再次打开后，恢复抓取结果时，这三个页面都会恢复成最后一次保存的结果，也就是恢复了相同的抓取结果，而不是各自的结果。
如果定时保存抓取结果，那么相比现在只在抓取完成后保存结果，保存的次数会增加，出现上面这个问题的概率也会增加。

以上这些问题可以通过编写相应的功能代码来解决，但是这些问题都属于发生概率不高的意外情况，而且会使一些机制的复杂度增加，所以我不是很有动力去花时间解决这些问题。

----------------

为了避免发生意外，我的个人习惯或许可供参考：
1. 浏览器常开不关。现在 Chrome 会自行释放不活动的标签页，所以通常用不掉那么多内存。我 16 G 内存在日常使用中没有必须关闭浏览器来腾出内存的情况。
2. 关闭电脑时，用睡眠来代替关机。睡眠很快速，而且可以保存所有打开的软件的状态。在开着浏览器的情况下睡眠，那么唤醒之后，下载器会继续抓取。
3. 如果怕自己意外关闭了某个标签页，可以右键它，选择“固定“。它会排在所有标签页的前面，并且不显示关闭按钮。它是特殊的，这可以大大减少意外关闭它的几率。
4. 减少浏览器崩溃的可能。如果浏览器经常崩溃，尝试解决导致崩溃的问题。在我的电脑上，浏览器是极少自己崩溃的，基本上只有一种可能，就是抓取时网页使用的内存超出一定值，那么这个页面会崩溃。
5. 在大量抓取时，最好将任务分成多批，例如要抓取 1000 页时，将其分成两个 500 页依次抓取。通常十万个结果的情况不会导致页面崩溃。再多就难说了，有些电脑上可能会页面崩溃，有的可能没事。
