### ISSUE TITLE
its about FB not about this one - this one is perfect - ty

### ISSUE THREAD

**Issue by dante25** [xuejianxianzun/PixivBatchDownloader#353]
Hi my friend, i dont know other way to contact you but this. Could you make batch downloader for facebook too just like this one? I have one extension which was free a couple months ago but than dude decided to set a paywall and now u have to pay monthly to use all features and as free version its soooo limited that is unusable anymore. If you are interested, i have latest version on my hdd, i can send it to you so you can take a look how it works, what it has of features, where is that paywall in the code and remove it if possible etc. if you redesign this extension ive mentioned i believe you will have even more patreons, because lots of users including me started complaining about paywall and atleast 40% of them gave up on that extension.

let me know if you are interested so i can send this extension to you. cheers

**Comment by xuejianxianzun** [comment]
I'm not going to make a downloader for Facebook
