### ISSUE TITLE
有办法一键扒取作品底下的推荐作品吗？

### ISSUE THREAD

**Issue by kurokawaTK** [xuejianxianzun/PixivBatchDownloader#355]
有没有办法一键扒取呢，手动选择一个个点有点折磨

**Comment by xuejianxianzun** [comment]
我正在做这个功能，遇到了个头疼的事情，推荐作品通常来自多个画师，有些命名规则例如 `{user}/{id}` 会为每个画师生成一个文件夹，这样的话推荐作品会建立很多个作者文件夹。
我现在还没想好怎么处理：
1. 不处理
2. 在最外层套一个文件夹，名字例如 ‘’‘xxxx的推荐作品’
3. 单独做一个设置可以让用户设置“推荐作品”的命名规则

**Comment by xuejianxianzun** [comment]
16.5.0 版本已添加此功能。
