### ISSUE TITLE
关于 仅下载新图片 功能的申请

### ISSUE THREAD

**Issue by alongw** [xuejianxianzun/PixivBatchDownloader#356]
**你需要什么功能？**
仅下载 “历史抓取记录” 以外的资源

**目的是解决什么问题？**
解决每次都要重复下载大量图片的功能（比如在下载已收藏图片或画师主页图片）

**附加描述**
软件中，有 “导入抓取记录” 的功能，但是他仅仅能导入并下载。
是否能在正常抓取完毕的基础上再次导入抓取记录，然后下载原有抓取记录中没有的。并且可以生成新的完整抓取（原有的加上筛选之后的，不能直接用新抓取的，因为画师可能会删除作品导致数据不完整）记录和筛选过的抓取记录。

**详细说明**

- 第一次抓取，保存抓取记录。下文称该抓取记录为 `原有抓取记录`
- 一段时间后，第二次抓取，保存抓取记录（需要允许用户保存），下文称该抓取记录为 `新的抓取记录`
- 用户可以选择完整下载，或是仅下载 `原有抓取记录` 中没有的，如果用户选择了仅下载 `原有记录中没有的` 那就生成 `筛选过的抓取记录` ，允许用户保存 `筛选过的抓取记录` 和 `完整抓取记录（原有抓取记录 + 筛选过的抓取记录。不能直接是新的抓取记录）`

**Comment by xuejianxianzun** [comment]
已有此功能
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7?id=%e5%a2%9e%e9%87%8f%e6%9b%b4%e6%96%b0
