### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by philipsljh** [xuejianxianzun/PixivBatchDownloader#359]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**
在线安装显示Invalid manifest 离线安装没反应
**如何重现这个问题？**
未知
**诊断信息**
Invalid manifest
发生问题时，页面的 URL：（必须）
https://chrome.google.com/webstore/detail/powerful-pixiv-downloader/dkndmhgdcmjdmkdonmbgjpijejdcilfh
问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**
360X 版本号 21.0.1216.0

**Comment by xuejianxianzun** [comment]
360浏览器左转不送

**Comment by xuejianxianzun** [comment]
1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
