### ISSUE TITLE
[FR] 在导出直链时增加一个替换自定义域名的功能

### ISSUE THREAD

**Issue by AlphonseZetta10** [xuejianxianzun/PixivBatchDownloader#360]
**你需要什么功能？**

在导出直链时增加一个替换自定义域名的功能

**目的是解决什么问题？**

> pixiv 的圖片伺服器網域為 i.pximg.net，因為有盜連保護，只要 Referer 是空值或不是來自 pixiv 的網域就會返回403。[参考](https://pixiv.cat/reverseproxy.html)

故将原始直链复制到aria2下载会报错。为了将操作简单化，希望在导出直链（如`复制URI`）时增加一个自动替换自定义域名的功能。

**其他软件是否有此类功能可以参考？**

无

**附加描述**

无

**Comment by xuejianxianzun** [comment]
1. 虽然不知道你要替换成什么域名，但是这不属于 pixiv.net 本身的功能请求，所以我不打算处理。你可以复制 URL 之后自行用文本编辑器批量替换。
2. 用 IDM 可以下载  i.pximg.net 的 URL。
