### ISSUE TITLE
Duplicate downloads 

### ISSUE THREAD

**Issue by Vagh-s** [xuejianxianzun/PixivBatchDownloader#361]
**What functionality do you want?**
The downloader relies on its download record to ensure no duplicated files. But for example if i switch browsers or i accidently cleared record it gets frustrating to make another download record by redownloading everything again or manually selecting what you want to download. Can you instead do it by filename? because what happens now are there are multiple redundant filenames on the same folder that would just be an easy catch for duplicate files without relying on the download record. You can jus tmake it as an option. Download records are not good on its own 

**What is the purpose to solve?**
To solve duplicate files 

**Does other software have such functions for reference?**

**Additional context**

**Comment by Vagh-s** [comment]
add in the fact that with the reliance on download record, lets say an image was deleted and you tried redownloading it, it will think you are downloading a duplicate file.

**Comment by xuejianxianzun** [comment]
The downloader doesn't have permission to check the files on your hard drive, so it has to keep a copy of the download itself. 

If you change browsers, you can export downloads from the downloader on your old browser and import them into your new browser.

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/a450f5ba-dd9c-4c4d-b2d5-b5f2da1dbe75)

**Comment by Vagh-s** [comment]
but what if you accidently cleared download record? does that mean you have to redownload everything you have downloaded to redo the download record?

**Comment by xuejianxianzun** [comment]
There is a way to generate download records locally and then import them into the downloader. refer to:
https://xuejianxianzun.github.io/PBDWiki/#/zh-cn/%E8%AE%BE%E7%BD%AE-%E6%9B%B4%E5%A4%9A-%E4%B8%8B%E8%BD%BD?id=%e5%af%bc%e5%85%a5-id-%e5%88%97%e8%a1%a8

**Comment by Vagh-s** [comment]
im sorry but i cannot understand chinese. I tried translator but it still seems confusing
