### ISSUE TITLE
关于文件名称长度限制

### ISSUE THREAD

**Issue by LZTSGS** [xuejianxianzun/PixivBatchDownloader#362]
<img width="132" alt="屏幕截图 2023-11-07 211106" src="https://github.com/xuejianxianzun/PixivBatchDownloader/assets/67962258/de45dd3b-f837-4212-8beb-a9279a8f29fc">
这个功能目前好像只能限制文件的字符总数而不是占位字符，占位长度的话，中文会占2字符，很多安卓手机文件名称上线比较严格，尤其是在从电脑移动文件到手机上的时候，很多文件大于170占位字符左右后就无法移动（因手机系统不同限制也可能不同），我在移动占位有170的图片时会出现无法正常移动卡死的现象。所以限制文件名称长度很重要，但是目前插件我测试时貌似限制文件长度只是通过文件字符总数来算的，没考虑到中文字符占位的情况，所以想作者大大能不能优化一下这点。

**Comment by xuejianxianzun** [comment]
是的，在某些场景里一个中文字符算 2 个长度，但是在 Windows 上，文件名长度上只把中文算作 1 个字符。而这个下载器是为 Windows 设计的，因此不会因为你说的 **安卓** 系统的区别便修改这个功能。针对你的情况，你可以把数值设置的更小，直至它不会在你的安卓系统上产生问题。

-----------

Windows 限制的文件名长度是 255（实际可用长度会更少一些） ，我在桌面建立一个中文名的 txt 测试，当文件名超长时，Windows 会自动截断，最后实际文件路径如下：

"C:\desktop\新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建文本文档一二三四新建.txt"

路径全长 245 字符，如果只算文件名，则是 232 个中文字符。显然，“文件名称长度限制”功能在 Windows 上是没有问题的。
