### ISSUE TITLE
我觉得算不上是bug吧,但抓取速度似乎还能优化一下

### ISSUE THREAD

**Issue by Restore000** [xuejianxianzun/PixivBatchDownloader#364]
**Bug 详情**
我观察到抓取作品的时候只勾选小说,依然会对其他类型的作品发起抓取请求,从请求链接可以看出小说和插画的链接是不同的
小说: https://www.pixiv.net/ajax/novel/*
插画: https://www.pixiv.net/ajax/illust/*
这导致发送大量多余的请求,我建议在发起请求之前先通过链接区分一下内容,然后跳过不需要发起的请求

能不能上架edge商店呢?

**如何重现这个问题？**
在抓取类型中任意勾选一项,其余取消勾选

**诊断信息**

发生问题时，页面的 URL：（必须）
https://www.pixiv.net/users/*/following
问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**
win10
edge119

**Comment by xuejianxianzun** [comment]
16.5.1 版本添加了这个优化措施，将会在近期更新。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v16.5.1

至于 Edge 纯粹是因为审核太慢了，Google 商店通常需要一两天，但是 Edge 是一周到半个月。这对于需要紧急更新的情况非常致命。所以我从 Edge 商店下架了。

**Comment by Restore000** [comment]
大佬效率真高啊.
