### ISSUE TITLE
[BUG] “显示更大的缩略图”功能把横图识别竖图 

### ISSUE THREAD

**Issue by Franinc** [xuejianxianzun/PixivBatchDownloader#365]
**Bug 详情**

“显示更大的缩略图”功能最近失效，横图也识别为竖图，如下图1

**如何重现这个问题？**

见图2

发生问题时，页面的 URL：（必须）

https://www.pixiv.net/users/4346254

问题截图：（可选）

![Snipaste_2023-11-12_02-03-10](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/26399054/171af241-f92c-4cd4-9eca-e3f9e53da8f7)
![Snipaste_2023-11-12_02-03-57](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/26399054/e0aeefd0-0abd-4827-952f-e939d27ed493)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**

win 10
chrome 102
edge 119.0.2151.58 全新下载扩展也重现问题

**Comment by xuejianxianzun** [comment]
Pixiv 变化导致的这个问题，下载器新版本会修复这个问题，已经在审核了，这次审核的慢。
