### ISSUE TITLE
[BUG] 11月12日更新之后，下载器收藏按钮不能把作品收藏状态设置为不公开

### ISSUE THREAD

**Issue by cyanlamp247** [xuejianxianzun/PixivBatchDownloader#367]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**

**如何重现这个问题？**
在高级设置里的“下载器的收藏按钮 (✩)”选择“添加标签”和“不公开”，在作品页面里点击按钮“✩”，然后进入收藏列表中发现该作品被放在公开收藏里
**诊断信息**
无
发生问题时，页面的 URL：（必须）
https://www.pixiv.net/artworks/113379041
只是举例，实际上好像更新之后所有我点了收藏的图都有这个问题。。
问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**
Windows 11 家庭中文版 22H2
chrome 119.0.6045.124（正式版本） （64 位）

**Comment by xuejianxianzun** [comment]
是的，添加下载推荐作品功能的时候导致了这个问题。
下个版本 16.5.2 会修复这个问题。
