### ISSUE TITLE
[BUG] 出现了部分动图无法下载的情况

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#369]
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/69134831/4f289903-a509-461e-a020-5f22d190cbcc)
一直卡着不动

**Comment by xuejianxianzun** [comment]
提 issues 时有模板，为什么不用模板呢？
卡主的这两个文件的 id 是什么？

**Comment by yehuoshun** [comment]
> 提 issues 时有模板，为什么不用模板呢？ 卡主的这两个文件的 id 是什么？

抱歉没注意看，习惯性的这样发issues。

出问题的作品id是 99839025和 95901031

**Comment by xuejianxianzun** [comment]
对于这个作品
https://www.pixiv.net/artworks/99839025
转换为 webm 格式时报错：
` Frame 500 has a weird duration (must be between 0 and 32767)`
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/ffb7ddd6-2870-4841-b356-5ec189dc4a1f)
导出抓取结果，查看最后一帧的数据
`{"file":"000499.jpg","delay":47730}`
延迟时间为 47730 ms，也就是 47.73 秒，超出了下载器所使用的 webm 编码库的操作范围。所以该问题无法修复。

你可以将其保存为其他格式，比如 GIF、APNG 等。

**Comment by xuejianxianzun** [comment]
从下个版本 16.5.3 开始，下载器会自动处理此问题，并显示一条警告消息。

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/01d4d293-0c76-4db4-a41c-877184686f0d)
