### ISSUE TITLE
Missing Crawl and Download Buttons

### ISSUE THREAD

**Issue by Katsudon96** [xuejianxianzun/PixivBatchDownloader#37]
After Pixiv decided to update the look of their website, when looking at a tag it will not show any buttons to screen, crawl, download, pause etc. making it useless.

**Comment by xuejianxianzun** [comment]
This tool has not been adapted to the new search page. The next version update will support the new search page.

**Comment by Katsudon96** [comment]
> This tool has not been adapted to the new search page. The next version update will support the new search page.

Oh thought so. thank you for the quick reply

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v3.0.0
