### ISSUE TITLE
由插件储存的“喜欢的标签”功能

### ISSUE THREAD

**Issue by cpuopt** [xuejianxianzun/PixivBatchDownloader#370]
**你需要什么功能？**
由插件储存的“喜欢的标签”功能
**目的是解决什么问题？**
pixiv“喜欢的标签”最多只能设置10个，完全不够用
![img](https://p.inari.site/usr/369/655b68083727e.png)
**其他软件是否有此类功能可以参考？**
无
**附加描述**
##### 可能的标签添加方式
在https://www.pixiv.net/tags/* 页面添加另一个“添加进喜欢的标签”按钮
![img](https://p.inari.site/usr/369/655b6af56856b.png)
##### 展示的位置
可以在点击搜索框后打开的界面中展示，在原有的“喜欢的标签”div内追加或新增一个栏目，或在其他适合的位置显示
![img](https://p.inari.site/usr/369/655b68d181515.png)

**Comment by xuejianxianzun** [comment]
关于收藏这方面的功能需求各种各样，可能一共都有10种了，从添加收藏到整理收藏到下载收藏，都有各种需求。满足大家的需求是很难的。关于你这个问题，我建议你向p站反馈，让官方增加数量上限。
