### ISSUE TITLE
建议：命名规则可以新增一个作者标签

### ISSUE THREAD

**Issue by mmmjie** [xuejianxianzun/PixivBatchDownloader#371]
当我要下载数量很多的时候，在阅览时，可以选择排列顺序为文件名称，在这种情况下，作者标签在前面的话，同一个作者的会自动归类在一起

**Comment by xuejianxianzun** [comment]
啊？不是有 `{user}` 吗？

**Comment by mmmjie** [comment]
> 啊？不是有 `{user}` 吗？

灰溜溜的关闭了
