### ISSUE TITLE
对手机版kiwi浏览器的支持

### ISSUE THREAD

**Issue by WeisanEarl** [xuejianxianzun/PixivBatchDownloader#372]
**你需要什么功能？**
支持手机版kiwi浏览器
**目的是解决什么问题？**
其实在手机版kiwi上面也可以正常使用，毕竟kiwi浏览器用的也是chromeium内核。
但是手机版kiwi还是出现了一点小问题。即：下载得到的文件的名称不是按照插件里定义的{page_title}/{id}名称样式，而是类似于06a95754-2ace-4a19-9b47-aafed740936b.png这样的文件名称。
**其他软件是否有此类功能可以参考？**

**附加描述**

**Comment by xuejianxianzun** [comment]
这是kiwi浏览器的bug，不是我能解决的。
