### ISSUE TITLE
在抓取图片时是否能够增加“不展示抓取到的图片”的选项？

### ISSUE THREAD

**Issue by Keleton-Y** [xuejianxianzun/PixivBatchDownloader#373]
使用本工具时，被抓取到的图片会出现在当前页面下，方便用户查看预览、收藏或进行其它操作。虽然很方便，但是当抓取到的图片较多时，会占用比较高的内存（因为每张图片都有缩略图，同一个页面放的图片太多了）。目前连续两次在抓取到几千张图片后Chrome内存不足崩溃，所以我希望可以选择不用展示被抓取的图片，只需要看到当前的进度就行。

**Comment by xuejianxianzun** [comment]
你可以关闭此功能：
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/072196a1-a97a-4357-987d-7938ef85aa3f)
