### ISSUE TITLE
希望上架Edge扩展商店

### ISSUE THREAD

**Issue by ghg6666678** [xuejianxianzun/PixivBatchDownloader#375]
**你需要什么功能？**
希望上架Edge扩展商店
**目的是解决什么问题？**
解决安装扩展要翻墙的问题（虽然看p也要）
**其他软件是否有此类功能可以参考？**

**附加描述**

**Comment by xuejianxianzun** [comment]
目前不会考虑。
以前上架过 Edge，但是它审核特别慢，动不动一周到半个月，当 P 站改版导致下载器某些功能异常需要修复的时候，Edge 用户会很久都更新不了，因为卡审核了。有时候审核还会给我打回来，所以我将其下架了。
