### ISSUE TITLE
[BUG]保存失败，code：FILE_FAILED。

### ISSUE THREAD

**Issue by mhdy2233** [xuejianxianzun/PixivBatchDownloader#378]
下载一些图片时弹出保存失败，code：FILE_FAILED。下载器将会重试下载这个文件。
可能是文件名太长，或是其他原因导致文件保存失败。你可以尝试启用高级设置里的“文件名长度限制”。

目前只在碧蓝航线关键词的一些图片中弹出包括但不限于107486755、106165021...

**诊断信息**
文件名长度限制并没有作用

发生问题时，页面的 URL：任何页面都会弹出https://www.pixiv.net/tags/%E3%82%A2%E3%82%BA%E3%83%BC%E3%83%AB%E3%83%AC%E3%83%BC%E3%83%B3/artworks?s_mode=s_tag（必须）

问题截图：
![QQ截图20231229003256](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/128962709/a77aae6e-9c60-4c57-b691-f4a2227207d5)
![QQ截图20231229003422](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/128962709/5aca3710-675d-4bd6-b397-9051310b8809)
（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。
[Powerful Pixiv Downloader Settings.json](https://github.com/xuejianxianzun/PixivBatchDownloader/files/13788087/Powerful.Pixiv.Downloader.Settings.json)
文件太大了https://7s6rnj-my.sharepoint.com/:u:/g/personal/tuchuang_mhdyapp_buzz/ER81qv_LwnNJswV8E_XGhEoBFrByARhSth_Mys7-7oCcqw?e=CBQWFB
**你的操作系统和浏览器版本号**
操作系统windows server
浏览器Chrome120.0.6099.130

常见问题也都看过了并没有找到解决办法，图片手动点开也没有问题。
如果可以添加一个多次无法下载自动跳过就好了

**Comment by xuejianxianzun** [comment]
我找到了你图中第一个报错的作品 106165021：
https://www.pixiv.net/tags/%E3%82%A2%E3%82%BA%E3%83%BC%E3%83%AB%E3%83%AC%E3%83%BC%E3%83%B3%2010000users%E5%85%A5%E3%82%8A/artworks?p=4&s_mode=s_tag
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/a671624f-048a-4fe9-83bb-ad3206346175)

导入你的设置，并仅抓取此页，下载，没有任何报错，文件也确实保存下来了。（跳过了一些重复文件）
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/56c62dfd-f379-44d4-ab8a-a68a40499e4d)

此文件名为 121 个字符，正常情况下也不应该会超长：
```
106165021_p001，uid_20627147，tags_R-18,碧蓝航线,インプラカブル(アズールレーン),アズールレーン,極上の乳,爆乳,母乳,陥没乳首,淫紋,アズールレーン10000users入り，2023-03-12.jpg
```

所以你遇到的错误是非典型问题，属于“其他原因”。这不是下载器内部原因。你可以尝试单独下载此作品：
https://www.pixiv.net/artworks/106165021
如果可以正常下载，那么便可以确认此问题属于偶然。我无法对此提供任何解决办法。

**Comment by mhdy2233** [comment]
是的，这不是下载器的问题。这似乎是Windows系统的问题，我目前并没有找的好的解决办法，只能通过更改文件夹的形式跳过这个bug
