### ISSUE TITLE
【功能增强】以pixiv自带搜索语法屏蔽tag

### ISSUE THREAD

**Issue by yige-yigeren** [xuejianxianzun/PixivBatchDownloader#379]
**你需要什么功能？**
自动在搜索时加入pixiv自带忽略tag标签，可以在功能设置中加强选项中选用
**目的是解决什么问题？**
解决ai推荐、群推广、语c、不明生物、不喜欢的tag
**其他软件是否有此类功能可以参考？**
有一篇文章，实测有用
https://www.pixiv.net/novel/show.php?id=21302515
**附加描述**

**Comment by xuejianxianzun** [comment]
你的意思是在下载器里设置这些标签，然后在搜索时自动添加到搜索词后面？
emmm 感觉会用到这个功能的人不多

**Comment by yige-yigeren** [comment]
> 你的意思是在下载器里设置这些标签，然后在搜索时自动添加到搜索词后面？ emmm 感觉会用到这个功能的人不多，你搜索时手动添加吧

是的，这个可以部分取代原版的屏蔽标签功能，也算个加强。
如果没有打算的话那么我就关issue了
