### ISSUE TITLE
Why not keep the virtual search results show?

### ISSUE THREAD

**Issue by YumeMienai** [xuejianxianzun/PixivBatchDownloader#38]
In v3.0.0, it cut down the virtual search results show, just provide to download the filter artwork images.
But i think it is a good feature to filter favor number of search results, and find out a favorite artist rather than just to download. Sometimes it also can filter again to get the better artwork we want, not download first then check it.

**Comment by xuejianxianzun** [comment]
The point is that "filter favor numbe" is hard to do on new search pages.
In the new search page, the search results do not include the number of favorites. This makes the downloader's related features unusable. Now, if the downloader wants to get the number of collections for each piece of work, it needs to request its details separately for each piece. This method is not operative, so I had to remove the relevant features.
I also like the old search page, but unfortunately, unless pixiv shows the number of favorites, the downloader won't work as before.

chinese：
重点在于，”过滤收藏数量”在新的搜索页很难做到。
在新的搜索页，搜索结果里不包含收藏数。这使得下载器的相关功能无法应用。现在，如果下载器要获取每个作品的收藏数，需要对每个作品单独请求一次它的详细信息。这个方法不具有可操作性，所以我只好去掉了相关功能。
我也喜欢旧的搜索页，但很遗憾，除非 pixiv 显示收藏数，否则下载器无法像以前那样工作。

**Comment by YumeMienai** [comment]
Why not keep the old api as a standalone module for maintaining this feature until it is dropped?
It is still work in v2.7.6.

**Comment by xuejianxianzun** [comment]
Can you still use the old version v2.7.6 on the new search page? I think this is impossible.
One possibility is that your search page is still old. However, Pixiv will gradually update all users.
Old API? This does not exist. The downloader can only use the information provided by Pixiv, whether it is page content or API. In the old search page, Pixiv provides the number of favorites, so the downloader can be used.
The downloader can only adapt to changes in Pixiv and cannot get information that it does not provide.
-----
在新的搜索页面上，你依然能使用旧版本 v2.7.6  吗？我觉得这不可能。
有一个可能，就是你的搜索页面仍然是旧版的。但是 Pixiv 会逐步对所有用户进行更新。
旧的 API？这不存在。下载器只能使用 Pixiv 提供的信息，不管是页面内容，还是 API。在旧版搜索页里，Pixiv 提供了收藏数信息，所以下载器可以使用。
下载器只能适应 Pixiv 的改变，不能获取它不提供的信息。
