### ISSUE TITLE
[BUG]时不时出现下载器提示,导致图片名乱码

### ISSUE THREAD

**Issue by NaixHw** [xuejianxianzun/PixivBatchDownloader#380]
chrome Version 120.0.6099.130 (Official Build)
win 11

经常出现装了别的下载器 导致名字错乱. 电脑睡眠过后就偶尔出现了,把chrome重启又好了.

**Comment by xuejianxianzun** [comment]
这不是下载器的 bug，我就这么跟你说吧，有的扩展把下载器要下载的文件从它手里过了一遍，这个过程导致丢失了文件名，这不是下载器的锅。

**Comment by NaixHw** [comment]
我几个月都没动过扩展，就这几天时不时出现，重启又好了。

**Comment by xuejianxianzun** [comment]
那你下载到的文件名是什么样呢

**Comment by NaixHw** [comment]
dc4fe8b0-4882-97f1-06d94c483c1e.png

**Comment by xuejianxianzun** [comment]
这就是其他扩展导致的。

**Comment by NaixHw** [comment]
和去广告的冲突吗？最近就去广告的自动更新。

**Comment by xuejianxianzun** [comment]
一般是有下载功能的扩展，你挨个禁用再下载，排查一下

**Comment by NaixHw** [comment]
只有个twitter下图的，下视频的。不同网站也影响？

**Comment by xuejianxianzun** [comment]
是的

**Comment by NaixHw** [comment]
OK，谢谢
