### ISSUE TITLE
Add an option to private or unprivate all bookmarks

### ISSUE THREAD

**Issue by EverydayAden** [xuejianxianzun/PixivBatchDownloader#382]
Hi, I'm someone who frequently uses Pixiv and I have thousands of bookmarks, a lot of which I'd rather others not see because of NSFW, and Pixiv doesn't have an option to private all of your bookmarks at once. I think it would be very nice if this tool had an option to private everything for you, as well as unprivate if you wanted to.

Thanks!

**Comment by xuejianxianzun** [comment]
Pixiv's bookmark management lacks a lot of features, and the best thing to do is ask the officials to make changes, but they haven't done anything yet.

**Comment by EverydayAden** [comment]
> There is already a solution for this feature.
> 
> 1. Enable bookmarking after downloading:
>    ![image](https://private-user-images.githubusercontent.com/17283977/297672250-3e1360ed-f6ec-48c7-b24e-f1e9e0437f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njc0NDcsIm5iZiI6MTcwNTU2NzE0NywicGF0aCI6Ii8xNzI4Mzk3Ny8yOTc2NzIyNTAtM2UxMzYwZWQtZjZlYy00OGM3LWIyNGUtZjFlOWUwNDM3Zjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMjY1ZjRmNGYyY2ZlM2Y0NTQ0ZDQ5ZWMxZWZiOTMwYzlkN2UxNTI4YmYzZTEyOWNkOWJjODc1Zjk5ZjQxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0VFLEVR_TlU2A26rRINMBYQJH0ddO64EYFWUChncCoQ)
> 2. Set the downloader’s bookmark behavior to private:
>    ![image](https://private-user-images.githubusercontent.com/17283977/297672121-e9b50bd3-946c-4a46-bb5c-100d6d455a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njc0NDcsIm5iZiI6MTcwNTU2NzE0NywicGF0aCI6Ii8xNzI4Mzk3Ny8yOTc2NzIxMjEtZTliNTBiZDMtOTQ2Yy00YTQ2LWJiNWMtMTAwZDZkNDU1YTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTllYTM5M2U2YzNiNzQ5ZmUwODQ4NDQwNjQ0N2FkMTAwNGUxYTFiMDNkZTg4ZGQxZGY4MDc1Y2U1NWNkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9bYNizu7z5lfxg4AYcFSXKopAx-aWvcYiU0-WYr0VLM)
> 3. Crawl and download all your bookmarks.
> 
> In addition, since our purpose is not actually to download the image, you can set the image size to small to speed up the download. You can also set up multi-image works to only download the first image.
> 
> ![image](https://private-user-images.githubusercontent.com/17283977/297672391-6aab1bf4-81aa-4ab8-9e66-86b47615c712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njc0NDcsIm5iZiI6MTcwNTU2NzE0NywicGF0aCI6Ii8xNzI4Mzk3Ny8yOTc2NzIzOTEtNmFhYjFiZjQtODFhYS00YWI4LTllNjYtODZiNDc2MTVjNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjhjYjJjNWY3M2NiOTc5ZWVhN2IzMWI1NmJjYTc5ZDk5Y2E5ZDc5MmE2MGUwNTAyMzQwNWE4NGQxN2QwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCut6yLO93Y6Rx6CFEZ1R-79iAjY8TznBN3q5Jscu00)



> Pixiv's bookmark management lacks a lot of features, and the best thing to do is ask the officials to make changes, but they haven't done anything yet.

Thank you so much for letting me know about this! Didn't think to do this at all. I still think it would be convenient to have a dedicated option to private your bookmarks though because I have over 60k bookmarks and it would take a very long time to crawl everything. I know this because I've used that in the past and had to leave my laptop on overnight to crawl everything. If making an option to private everything is anything similar to the "Add tag to uncategorized work" option, then that's something I can just leave running in the background and conveniently stop whenever I want, because I was able to do that when adding tags to uncategorized works.

Still, definitely nice to know that it's still possible, so thank you!

And yeah, I'm surprised Pixiv hasn't just added an option to private bookmarks entirely. Seems like it would be a very basic feature that any website would have.

**Comment by xuejianxianzun** [comment]
I didn't add a button specifically to make the bookmark private because it wouldn't be perfect.
Some users may only want to modify a subset of their bookmarks. By crawling first and then downloading, they can filter the target works. For example, set the number of pages to crawl, or set the tags that must be included.

But regardless of the method, each work must be processed (send a request) individually. This becomes a problem when the number of works is high, and unfortunately this cannot be solved unless Pixiv officially rolls out this feature.

**Comment by EverydayAden** [comment]
> I didn't add a button specifically to make the bookmark private because it wouldn't be perfect. Some users may only want to modify a subset of their bookmarks. By crawling first and then downloading, they can filter the target works. For example, set the number of pages to crawl, or set the tags that must be included.
> 
> But regardless of the method, each work must be processed (send a request) individually. This becomes a problem when the number of works is high, and unfortunately this cannot be solved unless Pixiv officially rolls out this feature.

Got it. Thanks so much for your input on this! I'd also like to mention that I love this extension and it's been incredibly useful for art hoarding, so thanks a ton.

**Comment by EverydayAden** [comment]
> I didn't add a button specifically to make the bookmark private because it wouldn't be perfect. Some users may only want to modify a subset of their bookmarks. By crawling first and then downloading, they can filter the target works. For example, set the number of pages to crawl, or set the tags that must be included.
> 
> But regardless of the method, each work must be processed (send a request) individually. This becomes a problem when the number of works is high, and unfortunately this cannot be solved unless Pixiv officially rolls out this feature.

Hi, sorry to bother again. So I ended up using this feature but came across some problems. As there were thousands of downloads to go through, Chrome kept running out of RAM and closing the tab after awhile, but eventually I was able to download everything after resuming a few times. However, because of the page being closed, the downloader only started bookmarking illustrations from the point I resumed, meaning there were big gaps between what it was able to bookmark. I turned on the option to not download duplicates so that the downloader would go through and queue everything again without actually downloading everything, which worked, but it still rapidly builds up RAM for whatever reason when it's not actually downloading any files, which of course results in the page eventually closing. Is there any way to fix this? I don't see any reason for Chrome to need so much RAM while doing this because it's not downloading anything. I also tried pausing to see if my RAM usage would stop or go back down, but it still keeps climbing fast.

![Screenshot 2024-01-23 211628](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/157001381/3bc5d2aa-614e-4e92-b738-02e75fc65ad0)
![Screenshot 2024-01-23 211700](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/157001381/c4ed9498-3df1-4c85-b3d8-a584acccd13e)

Here's some screenshots. The one in Task Manager that's taking up 9,000 mbs is Chrome

**Comment by xuejianxianzun** [comment]
When you need to download a large number of works, you can divide them into multiple batches for processing.
For example, set the number of crawled pages to 50 and crawl from page 1. This allows you to control the number of downloaded works.
After the download is complete, jump to page 51 and start scraping again.

**Comment by EverydayAden** [comment]
> When you need to download a large number of works, you can divide them into multiple batches for processing. For example, set the number of crawled pages to 50 and crawl from page 1. This allows you to control the number of downloaded works. After the download is complete, jump to page 51 and start scraping again.

Sorry, I never mentioned that I'm importing results from a crawl file I have from the past when I first grabbed all my bookmarks.

**Comment by EverydayAden** [comment]
> When you need to download a large number of works, you can divide them into multiple batches for processing. For example, set the number of crawled pages to 50 and crawl from page 1. This allows you to control the number of downloaded works. After the download is complete, jump to page 51 and start scraping again.

Quick update because I didn't want to leave this off without telling you that this is working for me. I limited the page number and I've just been leaving the downloader to do it's thing when I can, and that's been working perfectly fine for me. I'm about two thirds of the way through privating everything now. Thanks so much for your help, I genuinely really appreciate it because I know I've been bugging you a lot on here.

**Comment by xuejianxianzun** [comment]
Happy to help.
