### ISSUE TITLE
Add an option to crawl without country/region limitations/check every country/region while crawling

### ISSUE THREAD

**Issue by EverydayAden** [xuejianxianzun/PixivBatchDownloader#383]
Not sure how difficult it would be to do something like this, but because of Pixiv's new limitations for different countries and regions, I think it would be great if this tool could crawl based on what it can see in every region, that way you're not limited to the content only visible in your country. Basically bypassing the region limitations.

And I know you can see more content (and I'm pretty sure all of it in most places) if you just select different places in Pixiv settings, but this would still be a great feature if Pixiv ever changes anything for specific places. I'm someone who likes to have everything from the artists I like, so being rest-assured that I'm squeezing out everything I possibly can would be amazing.

**Comment by xuejianxianzun** [comment]
There are no plans for this feature at this time.
At the moment I don't know how this works. Maybe it's by carrying parameters or flags in the request (but I'm not observing that right now), or maybe the results you're seeing are handled by Pixiv's servers and don't require the frontend to specify a region.
If it is specified by the front desk, assuming that each region has a corresponding request parameter, then multiple requests need to be sent to obtain all works.
If it is handled directly by the server (according to your region in pixiv settings), then the downloader will not be able to do anything.

-----------

现在没有针对此功能的计划。
目前我并不清楚这个措施是如何运作的。也许它是通过在请求中携带参数或者标记（但我现在没有观察到），或者你所看到的结果是由 Pixiv 的服务器处理的，不需要前台指定一个地区。
如果是由前台指定，设想每个地区都有一个对应的请求参数，那么要获得所有作品就需要发送多个请求。
如果是由服务器直接处理（根据你在 pixiv 设置里的地区），那么下载器将无能为力。

**Comment by xuejianxianzun** [comment]
You can change your region in Pixiv’s account settings, I think Hong Kong might be better.

-----------

你可以在 Pixiv 的账户设置里修改你的地区，我想香港可能会好一些。
