### ISSUE TITLE
不知能否增加一个批量删除已收藏作品的功能

### ISSUE THREAD

**Issue by wy0682109523** [xuejianxianzun/PixivBatchDownloader#384]
**你需要什么功能？**

1. 根据作品ID列表批量删除已收藏作品

**目的是解决什么问题？**

1. Pixiv收藏夹中有七八千张作品，批量下载到本地后，经过筛选与整理，需要取消收藏某些作品，取消数量达到几千张。手动操作取消的话，需要进行大量重复操作，如复制本地作品ID，根据作品ID找到作品详情，点击爱心取消，跳转编辑页面，点击“取消收藏”按钮，点击确认，再跳转页面

**其他软件是否有此类功能可以参考？**

1. 不知道

**附加描述**
1. 可以让用户提供一个包含作品ID列表的JSON文件，根据JSON文件，批量取消收藏作品
2. 示例
`{
    "bookmarkIds": [
        "19773944720",
        "19774022167",
        "19773955643"
    ]
}`

**Comment by xuejianxianzun** [comment]
感觉有这个需求的用户比例应该很少吧，所以我没什么动力去做。

**Comment by xuejianxianzun** [comment]
你能直接提供 bookmarkID 挺好的，可以直接删除作品。但是这个功能如果要给其他人用的话，可能有的人只会提供作品 ID，就得多一个步骤去获取 bookmarkID。
而且考虑多数人应该不了解 JSON 结构，所以改为提交一个 txt 文件，里面每一行一个 ID 比较简单些（对用户而言）。

如果你考虑给我赞助一个 200 元档的话我可以加急制作此功能哦~
https://afdian.net/a/xuejianxianzun
不赞助的话，因为这个功能用到的人会很少，所以花时间做没什么意义。

如果你会编程也可以自己解决，下面是删除一个收藏的 API：
```ts
static async deleteBookmark(
  bookmarkID: number | string,
  type: 'illusts' | 'novels',
  token: string
) {
  const bodyStr =
    type === 'illusts'
      ? `bookmark_id=${bookmarkID}`
      : `del=1&book_id=${bookmarkID}`

  return fetch(`https://www.pixiv.net/ajax/${type}/bookmarks/delete`, {
    method: 'POST',
    credentials: 'same-origin', // 附带 cookie
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
      'x-csrf-token': token,
    },
    body: bodyStr,
  })
}
```
考虑到你要删除几千个收藏，应该在每次请求之间设置间隔时间（3 秒），因为收藏请求也会触发 Pixiv 的 429 限制。

**Comment by wy0682109523** [comment]
好的，感谢大佬指点，那我自己先试试看，如果不行的话，再赞助大佬制作。

**Comment by wy0682109523** [comment]
好的，感谢大佬指点，那我自己先试试看，如果不行的话，再赞助大佬制作。 @xuejianxianzun

**Comment by xuejianxianzun** [comment]
在下个版本倒是有个反向操作：
你可以启用一个新的 pixiv 账号，然后制作一个只包含要保留的收藏数据的列表。
你可以手动制作，或者导出你的所有收藏列表，然后去掉需要删除的那些。
最后在收藏页面里使用“导入收藏列表（批量添加收藏）”功能来收藏它们。

数据格式如下，是个对象数组：
```json
{
  id: string
  tags: string[]
  restrict: boolean
  type: 'illusts' | 'novels'
}[]
```

示例：
```json
[
  {
    "id": "106494017",
    "type": "illusts",
    "tags": [
      "オリジナル",
      "一之瀬アスナ",
      "美甘ネル",
      "角楯カリン",
      "室笠アカネ",
      "ブルーアーカイブ",
      "二次創作",
      "長手袋",
      "Cleaning&Clearing",
      "ブルーアーカイブ10000users入り"
    ],
    "restrict": false
  }
]
```
tags 可以留空，这样只需要修改每一项的 id 即可。

**Comment by wy0682109523** [comment]
> 至于批量删除功能，我还是没打算做，因为这算是个高危操作，如果用户操作不当的话可能我要背黑锅。 现在下载器有个“取消收藏本页面中的所有作品”，一次只能操作一页，现在就只能这样。不能选择更大的范围，或者像你的需求一样更自由的操作（当然这个门槛也比较高了）。
> 
> 其实打开思路，一个普通 pixiv 账号最重要的只有两点（如果你不是创作者的话），就是收藏（的作品）和关注（的画师）。 下版本的话这两个数据都可以同步到新账号上了，所以遇到麻烦的事情（主要就是收藏管理，这个大家的需求各种各样，至少有 10 个不同需求了吧，但是呢 P 站又摆烂，我则是不想做一些除了提问者几乎没人会用到的功能），直接开个新账号算了，换账号没啥负担。

理解，我自己用Java简单实现了查询和删除的操作，解决了问题，感谢大佬制作的优秀工具。

**Comment by xuejianxianzun** [comment]
收到

**Comment by piter34964-cmd** [comment]
@wy0682109523 宝能把脚本分享给我一下吗，我也需要太感谢你了
