### ISSUE TITLE
（仅限收藏页面）预览启动条件判定异常

### ISSUE THREAD

**Issue by cyfxzh** [xuejianxianzun/PixivBatchDownloader#385]
**Bug 详情**
1.在收藏页面预览横向图片时，一些超宽预览图的一部份会出现在光标下方，此时光标不再被视为停留在略缩图上因此预览图消失，但停止预览后光标再次落在略缩图上开启预览，反复循环导致预览图不停闪烁。
2.光标经过略缩图后即使快速移动到空白区域也会显示预览，这导致阅览收藏时经常闪出不需要的预览图。
**如何重现这个问题？**
1.在用户自己的收藏界面（其他用户的收藏没有这个问题），挑选一张足够宽的横向图片，确保光标会出现在预览图上方即可。
2.光标移动到任意收藏作品略缩图后快速移到空白区域，即可看到异常显示的预览图
问题截图：（可选）
https://github.com/xuejianxianzun/PixivBatchDownloader/assets/49647320/24c68142-7f5a-4038-b9cd-e1cd25b0917c
https://github.com/xuejianxianzun/PixivBatchDownloader/assets/49647320/00a270fc-57b7-4022-a584-f17a7ac54833
**你的操作系统和浏览器版本号**
windows 11 chrome 121.0.6167.140 (Official Build) (64-bit)

**Comment by xuejianxianzun** [comment]
确实，只在收藏页面有这个问题，奇怪。

**Comment by xuejianxianzun** [comment]
上次更新添加了一个作品缩略图的选择器，导致在收藏页面里产生了重复绑定。下次更新修复。

**Comment by xuejianxianzun** [comment]
16.7.1 版本已发布。
