### ISSUE TITLE
能否为快捷键功能加上开关

### ISSUE THREAD

**Issue by Hisou** [xuejianxianzun/PixivBatchDownloader#386]
**你需要什么功能？**
我希望按C和D下载原图的功能可以开关。
**目的是解决什么问题？**
因为和我现在使用的其他插件功能冲突了。使用了ctrl+c复制链接的插件，但是现在在p站这么操作会自动下载图片。
**其他软件是否有此类功能可以参考？**

**附加描述**

**Comment by xuejianxianzun** [comment]
问题不大，以后更新我判断下用户有没有按下 Ctrl，按下就不下载。
你现在可以先从右键菜单复制链接。

**Comment by Hisou** [comment]
谢谢答复。

**Comment by xuejianxianzun** [comment]
This issue has been fixed in version 16.8.0.
