### ISSUE TITLE
收藏夹的“未分类”功能下抓取不到图片

### ISSUE THREAD

**Issue by AgMonk** [xuejianxianzun/PixivBatchDownloader#39]
https://www.pixiv.net/bookmark.php?untagged=1

会提示：抓取完毕，但没有找到符合筛选条件的作品。

![image](https://user-images.githubusercontent.com/31527430/68541142-db93c280-03d6-11ea-8f6f-4fdbee28efc9.png)

**Comment by xuejianxianzun** [comment]
感谢反馈，请到 releases 页面更新。
