### ISSUE TITLE
Brave Browser compatibility fix

### ISSUE THREAD

**Issue by 50Assassin** [xuejianxianzun/PixivBatchDownloader#393]
Hello, can you make it 100% compatible with Brave Browser? I have to refresh the browser over and over again to download with Powerful Pixiv Downloader compared to Chrome, and Chrome these days is acting finicky with my machine.

**Comment by xuejianxianzun** [comment]
I know this problem exists, but I can't solve it because it seems to be caused by browser behavior. I think this is caused by some modifications made to the Chromium core by the Brave browser, so I can't fix it.
