### ISSUE TITLE
我的 Pixiv 网站版无法显示收藏的小说

### ISSUE THREAD

**Issue by caiweihan** [xuejianxianzun/PixivBatchDownloader#394]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**
为什么我pixiv网页版点击收藏的小说显示一片空白，但点击“未分类”的标签后显示“有未分类标签的作品161”，说明有161个小说，但小说显示不出来。我关闭了广告拦截器，换了不同浏览器都没用（在 iOS 的 Safari 也没用），收藏的图片显示正常，在移动端app上也能看到收藏的小说。
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/29276271/aa851dab-f7cd-4093-b777-ef3be6b4cbe7)
请问这是 Pixiv 的一个 bug 吗？我的账号似乎被限制了，与这个问题有关系吗？
假如这个问题无法解决，怎样导出我之前收藏的小说？我尝试在收藏的小说页面使用 Powerful Pixiv Downloader，但会一直卡在抓取环节：
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/29276271/7f18a796-af43-4173-8b37-adec98be4c13)

**如何重现这个问题？**
点击收藏 -> 小说

**诊断信息**

发生问题时，页面的 URL：（必须）
https://www.pixiv.net/users/38391264/bookmarks/novels

问题截图：（可选）
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/29276271/34268b56-070b-40b3-b0e0-0d687c2b011f)

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/29276271/3c42a4f3-546f-48dc-9eb8-7c32b8122e54)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**
Windows 上的 Edge, Chrome
iOS 上的 Safari

**Comment by xuejianxianzun** [comment]
这不是下载器的 bug，而是你的账号被封禁导致的。这种情况下确实无法导出你的收藏列表。

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/93c78ea3-1f25-4c80-a517-73708fe7b2d4)

之前一些被封禁的用户只是不能添加收藏和关注画师，但是他的账号没有变成彻底的不存在，所以他依旧可以照常下载，收藏的作品也依旧存在。不清楚现在是不是都变成你这样了，还是说同时存在不彻底的封禁和彻底的封禁两种情况。
