### ISSUE TITLE
Brave Browser support

### ISSUE THREAD

**Issue by 50Assassin** [xuejianxianzun/PixivBatchDownloader#395]
Hello, would you be able to increase support for Brave Browser? Chrome isn't working properly these days. Brave Browser using Powerful Pixiv Downloader often times gave errors to "Insufficient storage" when downloading.

**Comment by xuejianxianzun** [comment]
There are no plans for this. I'm not sure what "Insufficient storage" issue you're talking about, but there are other issues with Brave Browser that I can't resolve.
