### ISSUE TITLE
关于抓取系列小说

### ISSUE THREAD

**Issue by fatecyx** [xuejianxianzun/PixivBatchDownloader#396]
1. 合并系列小说使用epub格式的问题
目前把图片直接嵌入到文本里，而且所有章节共用一个xhtml文件，然后比较大的、带有图的小说，导出的epub就根本打不开

2.合并系列小说时希望也能抓一下各章节的meta数据，比较需要的也就是Description部分

**Comment by xuejianxianzun** [comment]
1. 打不开的小说体积有多大呢？有没有具体作品让我测试下
2. 主要是每个章节开头都加 meta 的话看着会比较乱，影响阅读体验。我再考虑下

**Comment by fatecyx** [comment]
https://www.pixiv.net/novel/series/10513084

**Comment by fatecyx** [comment]
meta建议epub里面可以用其他格式来写，比如斜体或者设个style之类的
txt里面，如果只留下Description，只加个分割线应该也不会很乱
没有合并的时候，meta.txt里面重复内容就很多，只有url,Thumbnail,Title,Date这几个不同

**Comment by xuejianxianzun** [comment]
下载器生成 epub 使用的是一个库，它不一定有设置斜体（以及每个章节生成单独的 xhtml）功能。有空了我再看下。
