### ISSUE TITLE
[BUG]动图保存为GIF色彩失真比较严重

### ISSUE THREAD

**Issue by GornBear** [xuejianxianzun/PixivBatchDownloader#399]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**
在擷取動圖時如果選擇存為gif，經常有色彩失真的情況，存成webM或apng則不會發生
gif支援色彩較apng少我可以理解，但有時失真還是差異過大

**如何重现这个问题？**
在動圖頁面點擊快速下載

**诊断信息**

发生问题时，页面的 URL：https://www.pixiv.net/artworks/114246118
隨意選了一個動圖的網址，但不僅限於此

问题截图：
![114246118](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/74359835/396c357c-3ba8-4709-bb8b-2ea2869267a5)
![114246118](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/74359835/90da7969-4cb5-4ce5-aec1-dd7ac718d15c)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。
[Powerful Pixiv Downloader Settings.json](https://github.com/xuejianxianzun/PixivBatchDownloader/files/14912208/Powerful.Pixiv.Downloader.Settings.json)

**你的操作系统和浏览器版本号**
Windows 10
Chrome 123.0.6312.106

**Comment by xuejianxianzun** [comment]
这个问题不好解决，因为下载器转换 gif 是用的一个库，不是我自己写的代码。所以现在我没有能力修复它，除非找到个更好的库。

**Comment by xuejianxianzun** [comment]
现在用的是这个库：
https://github.com/jnordberg/gif.js

**Comment by xuejianxianzun** [comment]
我找到了解决办法，该工具有一个参数 `quality` 控制 gif 图像的量化质量，越低越好，从默认的 10 改为 1，质量好了很多。

![1](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/5d535de0-2c1e-4678-a8bc-894e2b4bd4a5)

不过这导致了转换时间变成了原来的 3 倍，我测试了一个源文件有 20 多 MB 的动图，转换时间从 10 秒变成了 30 秒。看来只适合对较小的动图使用高质量。

**Comment by xuejianxianzun** [comment]
我需要测试更多动图在不同质量下的画质和转换速度表现，再决定怎么设置质量。

**Comment by xuejianxianzun** [comment]
这个问题以前我也遇到过，基本都是这种手绘风格+画面剧烈抖动的动图才会出现明显的色差问题。

我进行了一些测试：
[转换动图为 GIF 格式时，不同质量的调查.md](https://github.com/xuejianxianzun/PixivBatchDownloader/blob/dev/notes/%E8%BD%AC%E6%8D%A2%E5%8A%A8%E5%9B%BE%E4%B8%BA%20GIF%20%E6%A0%BC%E5%BC%8F%E6%97%B6%EF%BC%8C%E4%B8%8D%E5%90%8C%E8%B4%A8%E9%87%8F%E7%9A%84%E8%B0%83%E6%9F%A5.md)

之前下载器转换 GIF 固定使用质量 10，我打算改为动态设置质量，动图的原文件体积越小，就使用越好的质量，这可以有效解决某些手绘动图保存为 GIF 时，色差过大的问题。

虽然有时使用最佳质量依然无法完全避免色差，但是比之前还是要好很多。
