### ISSUE TITLE
想在下载的文本的开头加上作品，作者的信息

### ISSUE THREAD

**Issue by qhrmwx** [xuejianxianzun/PixivBatchDownloader#400]
**你需要什么功能？**
想要下载的文本的开头加上作品，作者的信息，如id，字数，tag，收藏量之类
**目的是解决什么问题？**
不想让文件名搞的那么长又不想放弃这些信息
**其他软件是否有此类功能可以参考？**
油猴的pixiv小说下载器
https://update.greasyfork.org/scripts/439918/Pixiv Novel Downloader.user.js
**附加描述**
还有一个小问题，文件下载顺序这个功能，虽然下载是按顺序下载，但因为文件大小不同，下载完成的顺序并不统一，最后只能得到一个大概的顺序

**Comment by xuejianxianzun** [comment]
下载的文本，你指的是小说吗？
“更多”里面有个设置，在小说里保存元数据，会保存一些信息，不过没有字数。

按顺序下载不能保证下载顺序吗？我觉得有点奇怪。而且你可以按作品 id 排序。

**Comment by xuejianxianzun** [comment]
需要回复。
