### ISSUE TITLE
对书签超过一定数量的插图进行排序。

### ISSUE THREAD

**Issue by aqua1202** [xuejianxianzun/PixivBatchDownloader#403]
是否可以只对书签数超过一定数量的插图进行排序，而不是在搜索结果排序功能中对所有插图进行排序？换句话说，我们能否减少不必要的分类？ 这意味着

**Comment by xuejianxianzun** [comment]
那你为什么不设置收藏数量条件呢？
![Uploading image.png…]()

**Comment by aqua1202** [comment]
我想要的是缩短搜索时间。
尽管该功能可以根据书签数量过滤显示图片，但图片显示前的等待时间与未设置书签数量上限和下限时的等待时间相同。
毕竟，由于 pixiv 的限制，实现这样的功能是否很困难？

**Comment by xuejianxianzun** [comment]
是的，下载器本身无法做到直接按收藏数量从高到低排列，因为必须先抓取才能获得收藏数量，然后才能排序。
不过有个办法，你开 Pixiv 会员，可以按热门度排序，那个就是官方的按收藏数量从高到低排序的功能。

**Comment by xuejianxianzun** [comment]
无法实现此功能，如果你只想要收藏数量大于指定数量的作品，建议开通 Pixiv 会员。
