### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by Hell0Earth** [xuejianxianzun/PixivBatchDownloader#404]
**What functionality do you want?**

Use PixiVBatchDownloader on Firefox for pc and android(now Firefox mobile has full extensions support).

**What is the purpose to solve?**

Firefox is love.

**Does other software have such functions for reference?**

None.

**Additional context**

None.

**Comment by xuejianxianzun** [comment]
see https://github.com/xuejianxianzun/PixivBatchDownloader/issues/295

**Comment by Hell0Earth** [comment]
> see https://github.com/xuejianxianzun/PixivBatchDownloader/issues/295

Sad time 😔

**Comment by Yet-another-NPC-guy** [comment]
> Firefox version:
> https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/

Amazing 🤩, also Firefox and forks are pushing extensions on mobile devices, probably this will be the most useful version on mobile. Why you changed your position about Firefox support?

**Comment by xuejianxianzun** [comment]
Because of the constant requests, I decided to take some time to make a Firefox version.
I just installed Firefox on my phone and found that it doesn't install this extension directly, and it looks like it needs to be adapted to the mobile terminal to install it.
