### ISSUE TITLE
在浏览器默认下载位置增加一个专门给插件使用的文件夹

### ISSUE THREAD

**Issue by minecraftyusei** [xuejianxianzun/PixivBatchDownloader#405]
**你需要什么功能？**
增加一个将所有下载文件/文件夹置于其中的总文件夹
**目的是解决什么问题？**
浏览器默认下载路径下存在大量的文件夹/零散图片堆积，在保存的文件超过一定数量时，打开文件夹会变得耗时。
**其他软件是否有此类功能可以参考？**
google插件twitter media harvest。该插件可以下载twitter上的图片，在初次下载时它会在浏览器默认下载路径创建一个twitter media harvest文件夹，然后把所有下载的图片/短视频全存进去。举例来说我的google下载文件夹为googledownload，那么这个插件能做到将自身的下载路径改为googledownload/twitter media harvest，这样我可以不必在文件数量浩如烟海的googledownload里寻找从twitter上保存的图片。
**附加描述**

**Comment by xuejianxianzun** [comment]
你设置命名规则即可，例如 `Pixiv/{user}/{id}`  之类的，自己在前面加一个总文件夹就行。

**Comment by minecraftyusei** [comment]
> 你设置命名规则即可，例如 `Pixiv/{user}/{id}` 之类的，自己在前面加一个总文件夹就行。

感谢回复，我刚打完这条建议就想到了这个方法，但是命名规则里并没有提到可以使用字符，于是尝试了一下发现可行。是否可以考虑在插件控制面板命名规则的帮助那里加上“可以使用字符来创建文件夹，如Pixiv/{user}/{id}”？

**Comment by xuejianxianzun** [comment]
好的，以后我加个提示。
