### ISSUE TITLE
抓取到的作品数量少于预期的问题

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#406]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**

**如何重现这个问题？**

**诊断信息**

发生问题时，页面的 URL：（必须）

问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**

我下載已關注用戶的新作品時偶爾會出現少於設定的作品數量。像是我設定下載十頁本該是抓取600個作品，但有時會少於600少了幾個。請問這是作品刪除了或是改了權限嗎?

**Comment by xuejianxianzun** [comment]
通常是有作品被删除了。

**Comment by wvwvwvwvw** [comment]
小说收藏页面，一页是30个小说，爬取一页是24本小说

**Comment by xuejianxianzun** [comment]
> 小说收藏页面，一页是30个小说，爬取一页是24本小说

以前是24个，不知何时p站改成了30个。我下次更新修复这个问题。

**Comment by xuejianxianzun** [comment]
17.1.0 版本已添加此提示。
