### ISSUE TITLE
[BUG]抓取的地址全部403了（下载时发生错误，状态码为 0）需要加Referer

### ISSUE THREAD

**Issue by yll690** [xuejianxianzun/PixivBatchDownloader#408]
好像是pixiv加了防盗链的机制，比如直接打开下面这张图是打不开的
https://i.pximg.net/img-original/img/2024/07/15/00/24/37/120537101_p0.jpg
但如果从 https://www.pixiv.net/artworks/120537101 这个页面点开就可以打开
![image](https://github.com/user-attachments/assets/baa7f0ed-25a9-43bc-a96d-a90183c619ac)
对比请求头之后用Postman测了，只要设置`Referer`为`https://www.pixiv.net/`就可以请求了

**Comment by xuejianxianzun** [comment]
你说的设置 referer ，下载器从第一版就有这个措施。

**Comment by yll690** [comment]
好的，因为我之前是能用的，然后这几天用不了了，试了错误提示中的办法也不行所以研究了下请求，但刚才删除扩展后再重装就好了，确实不是扩展的问题。工具很好用，感谢作者。
