### ISSUE TITLE
一点功能建议

### ISSUE THREAD

**Issue by Auroradanica** [xuejianxianzun/PixivBatchDownloader#409]
· 能否添加修改扩展主题颜色的功能：想修改这个扩展的蓝色主色调
· 能否自定义扩展的快捷键：目前有些快捷键会冲突
非常感谢您的开发与付出！

**Comment by xuejianxianzun** [comment]
其实几个地方的蓝色值是不一样的，不好修改，你可以从 release 下载文件，修改里面的 css 实现。
冲突的是哪个快捷键呢？与哪个扩展冲突？

**Comment by Auroradanica** [comment]
冲突的是我自己设置的一些快捷键，如果太麻烦就没必要了，非常感谢您的付出！
