### ISSUE TITLE
下载部分作品时会不断地在开始和暂停状态间切换，而且下载进度不动

### ISSUE THREAD

**Issue by AgMonk** [xuejianxianzun/PixivBatchDownloader#41]
这是其中一幅
https://www.pixiv.net/artworks/77800848

![GIF](https://user-images.githubusercontent.com/31527430/68920730-161fa580-07b1-11ea-864e-7a62231c59d7.gif)

**Comment by xuejianxianzun** [comment]
我尝试快速下载这个作品没有异常。
下载文件时发生错误会重试，你应该是网络的异常导致无法下载。请改善访问 p 站的网络环境，也可以加群寻魂。
