### ISSUE TITLE
需要增加延遲圖片下載秒數或是限制網路封包機制

### ISSUE THREAD

**Issue by azeinhantai** [xuejianxianzun/PixivBatchDownloader#410]
**你需要什么功能？**
需要增加延遲圖片下載毫秒數(ms)或是限制網路封包機制

**目的是解决什么问题？**
避免官方偵測過度訪問

**其他软件是否有此类功能可以参考？**

**附加描述**
比照**減慢抓取速度**機制追加下載限制

**Comment by xuejianxianzun** [comment]
最近我会添加这个功能。

**Comment by xuejianxianzun** [comment]
17.2.0 已增加“下载间隔”设置。
