### ISSUE TITLE
建議有擷取結果時再按下「開始截取」會彈出警告視窗的防呆機制

### ISSUE THREAD

**Issue by azeinhantai** [xuejianxianzun/PixivBatchDownloader#411]
**你需要什么功能？**
如標題所示，最好是有「警告：先前的結果將會清空，是否重新抓取？」的訊息

**目的是解决什么问题？**
解決已有大量結果時，按下開始抓取就會重新抓取，將先前的結果清零的BUG

**其他软件是否有此类功能可以参考？**

**附加描述**
前幾天我掛了一整晚擷取特定標籤的作品，然後經過篩選完畢後要準備下載時，因為沒仔細看又按下了「開始擷取」，結果又讓外掛從頭開始抓取，之前的結果全部都被清空，我掛整晚的資源全都功虧一簣，我心裡滿是髒話，搞到最後心態不好把慢速擷取關掉讓外掛全速抓取，還被官方吃了過度訪問的警告通知

**Comment by xuejianxianzun** [comment]
好的，最近我更新这个功能。

**Comment by xuejianxianzun** [comment]
17.1.0 版本已添加此提示。
