### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZhuGeKongBo** [xuejianxianzun/PixivBatchDownloader#412]
在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**
下载的图片名称突然变成只有五个字符
比如，设定下载规则是{page_title}/{id}，在预览中显示是92134573_p0.png的图片变成了92134.png

**如何重现这个问题？**
我也不知道为什么，从8月7日中午开始就突然是这样了，似乎是由于我设定的tag太多导致{page_title}页面名字过长？

**诊断信息**

发生问题时，页面的 URL：（必须）

问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**

**Comment by ZhuGeKongBo** [comment]
验证了一下确实如此，文件夹的名字太长导致图片文件名字无法正常显示，只能设定保存在指定名字的文件夹才正常

**Comment by xuejianxianzun** [comment]
你的命名规则是什么？
是否是 {id} 放在了最后面，而前面的规则生成的字数太多，导致 {id} 被截断了？
如果是这样，那么“自动截断”是浏览器的操作，否则文件名超长就无法保存文件。你应该把 {id} 放在前面。

**Comment by ZhuGeKongBo** [comment]
@xuejianxianzun 规则就是{page_title}/{id}，page_title是以搜索页面的tag来命名，我输入了包含200个字符，35个tag，应该是这个导致图片输出的时候自动截断了文件名。
之所以输入这么多是因为想消除的tag类型太多，不过我换了个方式保存短文件名就没事了

**Comment by xuejianxianzun** [comment]
截断超长文件名不属于 bug。
