### ISSUE TITLE
允许在小说正文的最前面部分加入{title}并换行

### ISSUE THREAD

**Issue by ZhuGeKongBo** [xuejianxianzun/PixivBatchDownloader#413]
**你需要什么功能？**
允许在小说正文的最前面部分加入{title}并换行.
**目的是解决什么问题？**
下载小说的时候发现没有将小说标题加在正文中的规则，标题被作为txt文件名保存
譬如现有的小说现在是：
title.txt
打开txt后看到就是正文内容
————
希望以后的形式是
title.txt
打开txt后看到title
/换行
正文
这样的话就可以把小说集成到一个txt里不用手动挨个修改了

**其他软件是否有此类功能可以参考？**

**附加描述**
如果有可能的话，希望还可以加入自动生成章节的功能，在title加入规则，让合并成一个txt的小说在各自的title前生成第X章或者chapter X。类似于word【编号库】的作用

**Comment by xuejianxianzun** [comment]
你可以开启“在小说里保存元数据”的功能，这样会在开头保存标题。
![image](https://github.com/user-attachments/assets/9c7726f9-bee0-4b31-83f5-a305d62bd582)

而且你说的在合并的小说里加入章节，现在就是这样的啊，在系列小说页面可以合并小说：
![image](https://github.com/user-attachments/assets/a5a1a961-70bd-4e73-b2f2-787b8c0410ac)
没懂你是不是没试过就来提问了。

**Comment by ZhuGeKongBo** [comment]
@xuejianxianzun OK谢谢，因为功能太多没看懂保存元数据什么意思就没尝试
然后章节功能的话不是说系列生成，是不同的小说保存到同一txt时能否依然为其生成章节排序？

**Comment by xuejianxianzun** [comment]
“不同的小说保存到同一txt时”，下载器没有这样的功能，你要是手动合并的话就手动加吧。
