### ISSUE TITLE
每个网页首次打开“复制URL”功能后显示图片

### ISSUE THREAD

**Issue by sakura6264** [xuejianxianzun/PixivBatchDownloader#415]
如题，仅首次打开该功能后出现，第二次打开后正常。
![2024-8-13 10-17-11](https://github.com/user-attachments/assets/3dc12352-781d-4fb2-b0e8-88c468d4d225)
浏览器为Chromium 118.0.5993.159  
插件版本为17.0.0

**Comment by xuejianxianzun** [comment]
以前从来没有人报告过此问题，我认为这不是下载器的 bug。
请检查一下是否是其他扩展或脚本引起的。你可以禁用其他扩展和油猴脚本，然后刷新页面重新抓取，再点“复制URL”试一试问题是否会复现。

**Comment by sakura6264** [comment]
禁用包括油猴(我这里是暴力猴)在内的其他扩展并未能解决问题，bug依然可以稳定复现。  
但是在因为其他原因重装浏览器并清空所有用户数据之后bug消失了。重装后我使用google同步重新安装了所有拓展，并通过备份恢复了所有油猴脚本，bug依然不出现，此过程浏览器版本没有变化。  
虽然我的问题解决了，但这可能确实是下载器的某个跟扩展存储到浏览器本地的数据有关的bug，希望这些信息能有助于定位bug。

**Comment by xuejianxianzun** [comment]
我认为这不是下载器的 bug，复制 URL 的时候只是单纯的输出一个网址，纯字符串，在这个过程中浏览器也不会加载和下载这个图片。
