### ISSUE TITLE
[疑问]不知道是否是p站限速，我这边下载图片速度很慢

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#416]
我浏览器是谷歌浏览器版本 127.0.6533.120（正式版本） （64 位）
可以排除是魔法的问题，我在其他网站下载文件很快

**Comment by xuejianxianzun** [comment]
其他网站下载快不代表p站快，其他网站是p站吗？你p站下的慢就是下的慢，不要扯其他网站。
不可能是下载器的问题，因为下载器没有任何限速措施，只是使用浏览器的内置下载功能而已。
