### ISSUE TITLE
[Question] Pixiv enhancements

### ISSUE THREAD

**Issue by UnfortunateLiama** [xuejianxianzun/PixivBatchDownloader#417]
Would a pixiv enhancements only version (without download funtions) work on a non chromium based browser ?

**Comment by xuejianxianzun** [comment]
No, because those browsers cannot install this extension.
Although some enhancements do not rely on browser APIs, these codes are not isolated and cannot be used separately.

**Comment by xuejianxianzun** [comment]
Do you mean Firefox by non-Chromium browser? This extension can be modified to run on Firefox, but I would not do that.
