### ISSUE TITLE
显示AI图片的参数元数据

### ISSUE THREAD

**Issue by Hono373** [xuejianxianzun/PixivBatchDownloader#418]
显示图片元数据的功能

ai绘图如果是原图上传的话，会存在元数据保存tag 模型 等信息，pixiv存在大量ai图，但实际上存有初始元数据的图片需要大量的点开详情后再点击图片打开原图后用专门软件查看元数据才能确认是否有元数据，没有就是白跑一趟，十分麻烦

bandiview中，元数据功能是在显示图片的左上角，通过按钮开启关闭，并且叠加显示在图片上

感谢

**附加描述**
![image](https://github.com/user-attachments/assets/6f088d8d-173f-4e4e-b084-ce9fd1f16b28)

**Comment by xuejianxianzun** [comment]
我不打算做这个功能。
1. Pixiv 上的 AI 图有多少比例含有这些参数信息？我没什么印象，感觉很少。有这方面的数据吗？
2. 953610385 该作品已不存在 https://www.pixiv.net/artworks/953610385 我无法对这个图片进行研究，请再提供一个例子
3. 有多少下载器的用户会用到这个功能？炼丹的用户的比例有没有达到 1%？我觉得很难说。
4. 在哪里显示，何时显示？是否需要单独加一个开关来控制？你只要提出一个需求，而程序员要考虑的就很多了。
5. 如果有这项数据，应该是必须加载原图才能获得，开销太大。特别是有些原图一张几 MB 的，网络请求会造成明显的时间延迟。

我认为该功能不具有普适性，而且很少有用户需要，所以我不打算做。

**Comment by Hono373** [comment]
关于2 4 我展示的图片是bandiview 软件查看图片的时候，同时在图片上层的左上角显示元数据的功能展示
并不是存在一张id为9536.....的图片
关于5 确实是需要加载原图才能获得
确实属于是过于小众且大开销的功能，是我小看了实现与资源的权衡，感谢您的回复与解答

**Comment by xuejianxianzun** [comment]
我用的图片查看器是 HoneyView，它也会显示一些元数据，比如相机拍的照片里的经纬度、快门信息等。至于 AI 绘图的这些参数，我不知道 HoneyView 能否显示，反正我是从没看到过，所以从我的角度，不知道 Pixiv 上的 AI 图是有多少是包含了参数的。
