### ISSUE TITLE
发现页的预览好像挂了

### ISSUE THREAD

**Issue by lin65254154** [xuejianxianzun/PixivBatchDownloader#423]
不知道是不是账号问题,我的另一个账号发现页面可以出发预览

![image](https://github.com/user-attachments/assets/e3e72ce1-e14d-4988-97e9-e3a417332e9d)

**Comment by lin65254154** [comment]
我一直有用sandboxie多开账号,之前一直可以正常,今天就无法使用了

**Comment by xuejianxianzun** [comment]
我刚试了可以预览啊。至于你的是什么原因，是不是 sandboxie 引起的我不清楚，我没用 sandboxie。

**Comment by lin65254154** [comment]
刚刚做了一个测试，我不用sandbox，更换成edge浏览器，登录主账号，发现页预览可以使用，切换其他账号就用不了😂，很奇怪。反复对比好像我两个账号的设置没啥区别。

**Comment by lin65254154** [comment]
然后其他页面预览全部都正常😂

**Comment by lin65254154** [comment]
应该不是当前插件问题，我用其他的带预览功能的pixiv插件也无法生效，耽误您时间了，我这边在自己看看是不是有其他设置影响了。
