### ISSUE TITLE
[BUG]发现页面扩展失效

### ISSUE THREAD

**Issue by zlqd123** [xuejianxianzun/PixivBatchDownloader#426]
**Bug 详情**
发现页面缩略图不会放大，鼠标移到上面不会展示大图，也没有下载按钮
**如何重现这个问题？**
访问该页面即可 https://www.pixiv.net/discovery
**诊断信息**

发生问题时，页面的 URL：（必须）
https://www.pixiv.net/discovery
问题截图：（可选）
![QQ20240920-214325](https://github.com/user-attachments/assets/23f0b5fa-dfc3-4aba-bd8c-1660a8b46127)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**
Win11专业版23H2
Microsoft Edge 版本 128.0.2739.54 (正式版本) (64 位)
Chrome 已是最新版本版本 129.0.6668.59（正式版本） （64 位）

**Comment by cherishxinhua** [comment]
我也出现了上述问题

**Comment by xuejianxianzun** [comment]
Pixiv 的变化导致了此问题，我已经提交了新版本 17.1.4 修复此问题，正在审核中。
