### ISSUE TITLE
[BUG] It's not working on the discovery page

### ISSUE THREAD

**Issue by BrunoDutch** [xuejianxianzun/PixivBatchDownloader#429]
It doesn't appear to download directly from the discovery page, on other pages or directly on the image it works normally
I'm using the Brave browser

**Comment by xuejianxianzun** [comment]
A change in Pixiv caused this issue. I have submitted a new version to fix this issue and it is under review.

**Comment by BrunoDutch** [comment]
I installed the latest version that was released a little while ago, the download is working, but the images are not in large scale when I place the mouse over them.

**Comment by BrunoDutch** [comment]
I installed the latest version that was released a little while ago, the download is working, but the images are not in large scale when I place the mouse over them.

**Comment by xuejianxianzun** [comment]
I think it's fine, what do you see?
![20240926_083132](https://github.com/user-attachments/assets/936a0aa6-40f4-4d08-9947-c4e4e40a5137)

**Comment by BrunoDutch** [comment]
I think my connection to the site is a little slow, the image takes a while, but after a while it appears
