### ISSUE TITLE
a lot of options broken in new version

### ISSUE THREAD

**Issue by komaedalove** [xuejianxianzun/PixivBatchDownloader#43]
"remove multiple image works" is gone, it was a very useful feature, could you please bring it back?

when filtering by number of bookmarks, works with low bookmarks still show on the search page

when filtering, the works are no longer sorted by highest bookmarks to lowest bookmarks

**Comment by xuejianxianzun** [comment]
[The Search page is about to be renewed](https://www.pixiv.net/info.php?id=5371&lang=en)

The search interface has been redesigned and the number of favorites is no longer displayed in the new search page. So it is not possible to sort by number of favorites. It is also impossible to display the filtered results of the work.
Some users still see the old version, but will become a new version in the future. So I canceled these buttons.
