### ISSUE TITLE
能否增加按字数筛选小说的功能？

### ISSUE THREAD

**Issue by ZhuGeKongBo** [xuejianxianzun/PixivBatchDownloader#430]
**你需要什么功能？**
按字数筛选小说，虽然可以填写小说文件大小限制，但不是很直观
**目的是解决什么问题？**
筛选一些不必要的文件，比如小说问卷调查这些超短篇内容
**其他软件是否有此类功能可以参考？**
P站自带字数筛选，但自定义需要付费
**附加描述**

**Comment by xuejianxianzun** [comment]
这个需求比较少，不想做。
你可以下载后删除体积很小的小说文件。可以在资源管理器里切换到详细视图，按文件大小排序，看哪些文件体积比较小。
