### ISSUE TITLE
EPUB正文部分使用<p> </p>代替现有的<br/>

### ISSUE THREAD

**Issue by ccchan49** [xuejianxianzun/PixivBatchDownloader#433]
现在保存EPUB小说的时候，小说正文分段使用的是<br/>，而不是正常EPUB里会看到的<p>.....</p>

这导致了某些软件处理不过来生成的EPUB，尤其是一些提取小说进行翻译的软件

能否更改一下保存小说的时候的逻辑，使用<p>...</p>进行分段/换行

万分感谢！

附参考：
《ePub指南——从入门到放弃》编著：赤霓（第2版）

![image](https://github.com/user-attachments/assets/9d985774-fe6e-4d8d-8dce-5da313e91ebd)

**Comment by xuejianxianzun** [comment]
可以，以后我优化下这个地方

**Comment by xuejianxianzun** [comment]
感谢 PR，17.3.0 版本已应用此优化。
