### ISSUE TITLE
[BUG]下载器被其他扩展影响，导致下载文件不成功，一直暂停重试

### ISSUE THREAD

**Issue by hongsongshu** [xuejianxianzun/PixivBatchDownloader#434]
扩展版本17.1.4
问题现象是出现这个,无限循环暂停
正在下載
下載已暫停

正在下載
下載已暫停

停止并刷新网页后重新下载会提示
这个标签页已经有抓取结果了,重新开始抓取会清空这些抓取结果

卸载本扩展并清空浏览数据和重启浏览器后重新安装本扩展,不能解决问题,求解.
浏览器为chrome 版本 129.0.6668.101（正式版本） （64 位）
下载的网址 https://www.pixiv.net/artworks/123264026

**Comment by xuejianxianzun** [comment]
我未能复现问题
![image](https://github.com/user-attachments/assets/815ae1c7-800e-45b8-86f9-7d7d40d2961e)

**Comment by hongsongshu** [comment]
这个问题会不会是我在下载的时候点赞造成的...貌似就是下载此图的时候我点赞后就出问题了,真是奇怪的问题

**Comment by xuejianxianzun** [comment]
下载器以前没出现过这种问题，原来是被其他扩展影响了。估计那个扩展接管下载的行为不太规范吧，心累
