### ISSUE TITLE
【能否提供第三方下载器推送】默认下载方式存在卡住的情况

### ISSUE THREAD

**Issue by f59375543** [xuejianxianzun/PixivBatchDownloader#435]
不知道为什么，我这边每下一张图都要确定一遍，明明已经给了自动保存权限了
![20241017000424](https://github.com/user-attachments/assets/50886d7e-ce5a-4f39-b6bd-92bc47e97e98)

并且这样下载的话对浏览器负载很大，图片数量一多就经常崩溃，请问能否和其他下载工具一样，可以通过RPC推送等方式，调用第三方下载器，比如说aira2进行下载吗？

我试过复制下载地址然后手动输入aira2进行下载，但是一次性提交过多请求会导致卡死，可能使用RPC一点点发送会好很多

类似的工具有如下这些

https://greasyfork.org/zh-CN/scripts/17879-pixivuserbatchdownload

https://greasyfork.org/zh-CN/scripts/449291-%E6%94%B9-%E7%BD%91%E7%9B%98%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B

**Comment by xuejianxianzun** [comment]
给的“自动保存权限”是给浏览器的，你这是迅雷啊
你关掉迅雷的浏览器监听，或者禁用它的浏览器扩展就好了
我用IDM就不会接管p站的下载，迅雷屁事真多。

至于 aria2 的推送功能目前没有考虑。
