### ISSUE TITLE
下载时发生错误，状态码为 0，请求未成功。

### ISSUE THREAD

**Issue by Lambda-D3L7A** [xuejianxianzun/PixivBatchDownloader#436]
**Bug 详情**
下载停止
**如何重现这个问题？**
抓取完成自动下载
**诊断信息**
下载时发生错误，状态码为 0
发生问题时，页面的 URL：（必须）
https://www.pixiv.net/
问题截图：（可选）
![屏幕截图 2024-10-21 020921](https://github.com/user-attachments/assets/a2fa77bc-5b2c-4c63-b075-e4fff9e006ba)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。
[result-total 280-祝く月 - pixiv-2024／10／21 01：17：59.json](https://github.com/user-attachments/files/17451350/result-total.280-.-.pixiv-2024.10.21.01.17.59.json)

**你的操作系统和浏览器版本号**
操作系统：Windows 11 家庭中文版
Chrome版本 129.0.6668.101（正式版本） （64 位）

**Comment by xuejianxianzun** [comment]
你是否检查了截图顶部显示的红色日志提示？

**Comment by Lambda-D3L7A** [comment]
自检过了

**Comment by xuejianxianzun** [comment]
C 盘剩余多少空间？

**Comment by Lambda-D3L7A** [comment]
足够下完所有图片
没有使用反代理
重启浏览器会好一会然后又停了

**Comment by xuejianxianzun** [comment]
什么叫足够下完所有图片，你把第一条提示复制过来仔细看看

**Comment by Lambda-D3L7A** [comment]
![Uploading 屏幕截图 2024-10-21 022005.png…]()

**Comment by xuejianxianzun** [comment]
你截图没传上来

**Comment by Lambda-D3L7A** [comment]
![屏幕截图 2024-10-21 022005](https://github.com/user-attachments/assets/1cf2901d-8f85-4875-87ff-61e17eabc763)

**Comment by xuejianxianzun** [comment]
是之前就有5G空间，还是刚清理的？如果是清理的话需要重启下浏览器

**Comment by Lambda-D3L7A** [comment]
改了默认下载位置就好了

**Comment by xuejianxianzun** [comment]
![image](https://github.com/user-attachments/assets/6305958b-2477-4821-ba3e-265eea0a4f71)
我导入你的结果试了下没有遇到问题。
这个问题最大的可能性还是空间问题，之所以写大于4G，是因为浏览器的机制。但如果确实不是这个原因，那我也不知道具体的原因了。
