### ISSUE TITLE
可以增加下载选项--下载到eagle吗？（素材管理软件）

### ISSUE THREAD

**Issue by homjie123** [xuejianxianzun/PixivBatchDownloader#439]
直接下载到eagle，节约了下载-拖入导入eagle的步骤，直接从网页保留的图片有图片的来源链接，以便于图片溯源

还希望加入图片加入eagle时，自动保存文章标签功能 ，感谢

**Comment by xuejianxianzun** [comment]
怎么算“下载到eagle”呢？
如果它可以指定一个文件夹，下载到里面就可以自动导入，那你可以把浏览器的下载目录设置为那个目录。
否则的话，我不知道怎样自动导入进去
