### ISSUE TITLE
一次性下载过多会出现CPU和内存占用过高

### ISSUE THREAD

**Issue by Younsion** [xuejianxianzun/PixivBatchDownloader#44]
一次性下载过多一段时间后会出现CPU和内存占用过高，然后导致下载一直暂停/开始切换（网络正常），初步估计是页面outputArea过大导致的。我尝试F12删除这个元素，但是删除的时候CPU和内存会飙高，然后删除失败，可能是内存不够导致失败

**Comment by xuejianxianzun** [comment]
电脑配置如何？我有时一次下载几千个也没问题，我遇到的出错导致重试基本只有“网络错误”这一个原因。

outputArea 应该不是问题所在。建议你暂停，把线程调小，等会儿再继续下载。或者一开始就把线程调小。

**Comment by Younsion** [comment]
i5 4210h,8g
下载时开了6线程，然后第二天早上起来发现一直暂停/开始不停切换，然后电脑cpu占用很高，内存也很高，打开F12想把outputArea删除的时候就开始有卡死现象了...
我下次试试把线程数调小看看

**Comment by xuejianxianzun** [comment]
下载器现在限制只能同时下载5个啊
如果要下载和转换动图的话也会比较占资源，最好把同时下载数减小一些。
按说资源占用高也不应该出现 暂停/继续 的现象，我还是怀疑是网络有问题。
