### ISSUE TITLE
新增抓取作品下的作者文字

### ISSUE THREAD

**Issue by sivor0811** [xuejianxianzun/PixivBatchDownloader#440]
**你需要什么功能？**
可以新增抓取圖片的同時也抓取這個作品作者下面寫的文字嗎
**目的是解决什么问题？**
有些圖片搭配文字會更有效果
**其他软件是否有此类功能可以参考？**

**附加描述**

**Comment by xuejianxianzun** [comment]
试试这个功能：
![image](https://github.com/user-attachments/assets/48912191-c727-4730-9286-7591f72c1390)
