### ISSUE TITLE
咨询同志们账号被冻结要多久恢复正常使用

### ISSUE THREAD

**Issue by Hibiki-22** [xuejianxianzun/PixivBatchDownloader#441]
有没有哪位同志因为过度访问被冻结账号的经历？看另一个帖子我这里是第二个阶段（第一次冻结第二次永封），一般会冻结多久啊，我这里从3号开始申诉，截止发这条帖子的时候还没恢复账号的正常使用。
我这里关注大概接近1700，总共有接近27万图，被干掉的时候大概抓取了3万左右，抓取时间3秒，也许设置5秒或者以上会更好？
才想起来插件好像有导出关注列表的功能，等解冻了导出来下次用小号挂着下(╬▔皿▔)╯
![微信截图_20241109023750](https://github.com/user-attachments/assets/0856e080-083a-4d2e-b1b4-cae3fea6e540)

**Comment by Hibiki-22** [comment]
目前就是处于用户不存在的状态，也没法登录。这算是基本稳死了吧

**Comment by xuejianxianzun** [comment]
是的

**Comment by Hibiki-22** [comment]
这下安详的似了，谢谢同志啦
