### ISSUE TITLE
[BUG]在线版本是不是太低了，然后在线版本的高亮关注的功能是不是没用了

### ISSUE THREAD

**Issue by wycstc353** [xuejianxianzun/PixivBatchDownloader#442]
[BUG]在线版本是不是太低了，然后在线版本的高亮关注的功能是不是没用了，现在看不到关注用户的黄色了，都是原本的颜色，我记得上周还行的

**Comment by xuejianxianzun** [comment]
在哪里看不到，是所有页面看不到还是？

**Comment by xuejianxianzun** [comment]
提bug我不是设置了模板吗，包括要求描述如何复现问题。非得让我再问。

**Comment by wycstc353** [comment]
> 在哪里看不到，是所有页面看不到还是？

搜索后看不到，然后我今天试了一下又看得到了，真奇怪，算了，反正现在没问题了

**Comment by wycstc353** [comment]
![image](https://github.com/user-attachments/assets/f38118fc-5e5a-429b-bad5-f7254bac7d50)
昨天这样搜索后，关注的都没黄，今天又好了
