### ISSUE TITLE
发送ajax请求时机问题

### ISSUE THREAD

**Issue by yorutsuki123** [xuejianxianzun/PixivBatchDownloader#444]
很喜欢你的插件，但每当滑鼠经过作品时，插件都会发送该作品的ajax请求，导致该作品出现再浏览记录内

想问能不能改成当对于该作品有实际动作（例如显示预览、看大图或下载）时再发送ajax请求呢？

不然每次在浏览记录里面找图时都看到好多不相关的（哭哭

拜托了，非常感谢～～

**Comment by xuejianxianzun** [comment]
我试了不点进去作品页面是不会出现在历史记录里的。
仅仅鼠标划过，包括预览，都不会使作品出现在历史记录里。
难道你的可会吗？

**Comment by yorutsuki123** [comment]
[https://youtu.be/rgO87I88wxs](https://youtu.be/rgO87I88wxs)
我会耶，您看看

**Comment by xuejianxianzun** [comment]
我的情况和你不一样，仅预览过的不会显示在历史记录里。刷新后也没有。
不过我的历史记录页面显示“尝试版”，不知道是不是在尝试版里面不会显示，在你的版本里会显示？
![image](https://github.com/user-attachments/assets/23a42dd7-194a-4de1-abe2-97108fb5b716)

**Comment by yorutsuki123** [comment]
看来您是使用免费会员，因此不会出现

我在相同环境开了免费会员的小帐也跟您同一样没有出现

但是付费会员帐号的浏览记录是会出现的（与免费会员的「尝试版」是同个网址，但不是「尝试版」）

**Comment by xuejianxianzun** [comment]
我现在没有Pixiv会员，之前用PayPal支付开启过，但现在Pixiv不让我使用PayPal支付了。

**Comment by yorutsuki123** [comment]
唉，难过了，国际政策越来越烦，我是之前办了JCB卡才能订阅

**Comment by xuejianxianzun** [comment]
现在鼠标经过作品时，下载器会立即获取作品数据并缓存起来，这是为了让其他一些功能在使用时可以立即响应，比如预览图片、快速下载、打开图片查看器等。
你说的等到使用时再获取，也可以，只是某些功能的反应会慢一些，因为用户选择操作后，会有一个获取数据的过程。

**Comment by xuejianxianzun** [comment]
晚些我改改看吧，如果影响不大就按你说的来。

**Comment by xuejianxianzun** [comment]
应该问题不大，到时候我试试吧

**Comment by xuejianxianzun** [comment]
最新版本已经改成了预览时才会发起请求。
