### ISSUE TITLE
每次下载都会弹出另存为窗口

### ISSUE THREAD

**Issue by 1027690140** [xuejianxianzun/PixivBatchDownloader#446]
**可以把图片一次性下载完到压缩包里面吗？**

**对于一次性下载大量图片的情况，每次下载一张图片，浏览器都要弹出一个窗口，很麻烦**

**就是这种窗口**
![image](https://github.com/user-attachments/assets/aacf4a9a-d83c-4f31-b2d6-480424f5949b)

**Comment by xuejianxianzun** [comment]
安装完之后会提示一次
常见问题里也有提示
为什么不看呢
![image](https://github.com/user-attachments/assets/47c403c7-50af-4e72-a0c0-a2aff25f6648)
