### ISSUE TITLE
[Feat Request] 下载产生状态码为 0 的错误时，跳过出错的任务。

### ISSUE THREAD

**Issue by huzpsb** [xuejianxianzun/PixivBatchDownloader#447]
**你需要什么功能？**
在保存文件遇到错误时不暂停全部任务的下载；而是只暂停（严格来说是跳过？）出错的任务。

**目的是解决什么问题？**
我的网络连接不是很好。每当出现一个小错误时，都会收到提示
Download is paused
这使得我不得不在电脑前不停地刷线页面，非常的繁琐。

**其他软件是否有此类功能可以参考？**
这是常见的下载软件的默认行为，例如迅雷、FDM等。

**附加描述**

**Comment by xuejianxianzun** [comment]
我记得下载器不会因为错误而暂停吧，不是无限重试吗？
你可以截个图吗？

**Comment by huzpsb** [comment]
好的....让我复现一下

**Comment by huzpsb** [comment]
<img width="312" alt="image" src="https://github.com/user-attachments/assets/5f546e6b-19af-477d-b917-53c87a4e7b5e">

**Comment by huzpsb** [comment]
在出现此日志前有弹窗，内容为 _状态码为0的错误提示...

**Comment by xuejianxianzun** [comment]
状态码为 0 不是普通的下载错误，而是一种特殊的状态，有时并非是网络问题导致的。

**Comment by huzpsb** [comment]
> 如果是普通的下载错误，通常是下载一个文件的途中产生了错误，下载器会无限重试，不会暂停下载。 状态码为 0 通常没有实际开始下载。

我能够理解您的意思。但是在HTTP-Proxy环境下，客户端软件通常会返回Connection-established状态码，再发现事实上出现了错误。导致请求开始了，但是响应体的长度为0。我理解这不是常见情况，但是这的确对我构成了困扰。我所请求的，是您可以考虑加入一个开关并设置为非默认开启状态。与此同时，您也可以参考对429的处理方法（sleep一段时间并重试）

**Comment by xuejianxianzun** [comment]
我不清楚你说的情况。我也使用代理来访问 Pixiv，但没有遇到这种错误。

**Comment by huzpsb** [comment]
一种稳定的复现方法是，将代理模式设置为HTTP(s)，使用命令行（而不是虚拟网卡）设置浏览器代理，然后在下载过程中重启代理程序。

**Comment by xuejianxianzun** [comment]
我的代理软件没有添加虚拟网卡，是 HTTP 模式。它自动配置了系统代理。
下载时，在 Chrome 开发者工具的 Network 里不会产生额外的请求。

![image](https://github.com/user-attachments/assets/cf1ce6b6-575b-4381-b9b5-f26aa627ae3d)

![image](https://github.com/user-attachments/assets/391dde0b-e045-45ef-88a4-f07a445919ac)

**Comment by huzpsb** [comment]
> 我的代理软件没有添加虚拟网卡，是 HTTP 模式。它自动配置了系统代理。 下载时，在 Chrome 开发者工具的 Network 里不会产生额外的请求。
> 
> ![image](https://private-user-images.githubusercontent.com/17283977/389204607-cf1ce6b6-575b-4381-b9b5-f26aa627ae3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzMzNjMsIm5iZiI6MTczMjM3MzA2MywicGF0aCI6Ii8xNzI4Mzk3Ny8zODkyMDQ2MDctY2YxY2U2YjYtNTc1Yi00MzgxLWI5YjUtZjI2YWE2MjdhZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Y2Y2ZGVhMzgwYWNiZGQzZTMxMmE0ZjM0NjhlM2NlMjg5ZTE4ZTllMjQxYzQ0MzVmYjI4MzU5ZDE2OGY0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jkRpvBe_bQALsxYq1tR4wpaCU5mGarBuEsLCfHi9Sog)
> 
> ![image](https://private-user-images.githubusercontent.com/17283977/389204570-391dde0b-e045-45ef-88a4-f07a445919ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzMzNjMsIm5iZiI6MTczMjM3MzA2MywicGF0aCI6Ii8xNzI4Mzk3Ny8zODkyMDQ1NzAtMzkxZGRlMGItZTA0NS00NWVmLTg4YTQtZjA3YTQ0NTkxOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE0NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYzZhNmJjNTFkMzhiZmQzYmZjZTI2YjliNWIwOWFiNDlhZDQxYjUxNjRmNzhkNTQzODJkZWExZDBiNmU2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5IZUjdDHnbjdLgBVQl6NmTTepq2Otqw5qr8WJLJF3JU)

非常抱歉我没有阐述清楚。浏览器会在一个连接中收到两次2XX响应；其中一次来源于您的V2客户端；另一个才是真正的、来自Pixiv的、经过了TLS的2XX响应。
参见
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT
````text
The request target is unique to this method in that it consists of only the host and port number of the tunnel destination, separated by a colon (see Syntax for details). Any 2XX successful response status code means that the proxy will switch to 'tunnel mode' and any data in the success response body is from the server identified by the request target.
````

在浏览器的控制台看来，的确只有一个请求....
以及，至少在我的机器上，我的确遇到了这个问题...虽然我理解它可能很罕见，但是请相信~~我不会吃饱了撑的来提一个不存在的issue~~

**Comment by xuejianxianzun** [comment]
我可以看到请求发送给了代理服务器，你的呢？
![image](https://github.com/user-attachments/assets/5b73b3b6-04c2-4794-8755-012aff4bc44d)

**Comment by huzpsb** [comment]
我可以看到请求被代理服务器响应了2xx后代理服务器失去了响应（x）
但是事实的确如此...然后连接在浏览器里面红了 显示Response not available

**Comment by xuejianxianzun** [comment]
我不认为让下载器等待一会儿就会“跳过错误代码 0 的状态”从而解决问题。
因为当下载器接收到状态码为 0 的消息时，该请求已经完成。此时等待是无意义的，因为下载器不知道后面是否会有另一个请求，以及如何接管（监听）那个请求的状态。
```
 // 文件加载完毕，或者加载出错
    xhr.addEventListener('loadend',
```

**Comment by huzpsb** [comment]
因此我在最初的设想中提到的是放弃这个任务。我非常同意这个观点：状态码0意味着这个文件任务很有可能已经不可恢复地失效。我只是不希望这个失效影响到其他文件任务...

**Comment by xuejianxianzun** [comment]
> 我可以看到请求被代理服务器响应了2xx后代理服务器失去了响应（x） 但是事实的确如此...然后连接在浏览器里面红了 显示Response not available

看起来是代理软件在处理请求上存在差异。你的代理软件或许没有把真实的请求数据发送给浏览器？浏览器也不知道你的代理服务器有没有完成请求。

**Comment by huzpsb** [comment]
我的网络环境确实非常差，我对此感到抱歉....

**Comment by xuejianxianzun** [comment]
> 因此我在最初的设想中提到的是放弃这个任务。我非常同意这个观点：状态码0意味着这个文件任务很有可能已经不可恢复地失效。我只是不希望这个失效影响到其他文件任务...

对于因网络代理而产生的错误状态码 0，所有请求都会这样，所以跳过的话就会跳过所有文件。

**Comment by huzpsb** [comment]
> > 因此我在最初的设想中提到的是放弃这个任务。我非常同意这个观点：状态码0意味着这个文件任务很有可能已经不可恢复地失效。我只是不希望这个失效影响到其他文件任务...
> 
> 对于因网络代理而产生的错误状态码 0，所有请求都会这样，所以跳过的话就会跳过所有文件。

唔 为什么...因为代理是可以被界面程序重启的（想必您操作代理也不是直接打命令行吧）

**Comment by xuejianxianzun** [comment]
我不知道你是如何设置代理的，但根本的解决办法就是解决代理引起的这个问题。
你说”连接在浏览器里面红了 显示Response not available“，显然你的代理软件（或代理方式）没有正确处理与浏览器之间的对接，这对于依赖浏览器的下载器而言是难以解决的问题。

**Comment by huzpsb** [comment]
唔....无论如何....我相信我已经提供了足够的信息。
我理解并尊重您可能因为此种情况实在罕见而拒绝在主分支中解决此问题。若如此，我会开启一个分支来自行解决。
但是我仍然希望呼吁您，为此（的确不是您的插件带来的问题...）特殊情况加一个（哪怕是藏在高级选项里面的）（默认关闭的）开关。
这将有助于解决在非典型网络下的（不合理）（但是客观存在）的需求。
感谢您的时间，祝您生活愉快。

**Comment by xuejianxianzun** [comment]
你可以尝试自己解决，但我觉得这很难。
至于这个 issue 提出的请求我认为意义不大，因为下载器通常不会暂停，而会暂停的情况又无法通过”跳过出错的文件“来解决问题。
这样做很可能只是从暂停变成跳过所有文件，没有实际意义。

**Comment by huzpsb** [comment]
To those who may concern:
> @See https://github.com/huzpsb/PixivBatchDownloader/releases/tag/z
