### ISSUE TITLE
关于pixiv的过度访问警告

### ISSUE THREAD

**Issue by yehuoshun** [xuejianxianzun/PixivBatchDownloader#454]
抓取速度和下载速度应该怎么设置才能有效避免封号，目前已收到过度访问警告

**Comment by xuejianxianzun** [comment]
这个问题似乎没有固定的答案。
有时候虽然抓取和下载比较频繁，但总量少，就不会有问题。反过来说，即使抓取和下载的限制比较严格，但总量多了也可能会被警告。

**Comment by xuejianxianzun** [comment]
唯一可行的似乎就是避免大量抓取和下载，但如果需要这样做，你可以考虑使用小号。
而且小号也可以下载大号上的收藏作品（只要是公开地收藏），这样大号就不会被封禁。
对于特别大的任务，你可以考虑使用多个浏览器或无痕模式窗口，登录多个小号，分批抓取和下载。

**Comment by yehuoshun** [comment]
> 唯一可行的似乎就是避免大量抓取和下载，但如果需要这样做，你可以考虑使用小号。 而且小号也可以下载大号上的收藏作品（只要是公开地收藏），这样大号就不会被封禁。 对于特别大的任务，你可以考虑使用多个浏览器或无痕模式窗口，登录多个小号，分批抓取和下载。

好的  感谢
