### ISSUE TITLE
[BUG]命名规则中包含了数字 ID{id_num}但还是弹出警告，保存后依旧以默认规则下载

### ISSUE THREAD

**Issue by shanweixxy** [xuejianxianzun/PixivBatchDownloader#455]
**Bug 详情**
命名规则中包含了数字 ID{id_num}但还是弹出警告，无视警告后抓取作品保存后依旧是以默认规则下载
**如何重现这个问题？**
将默认规则全部删掉，只选择数字 ID{id_num}，再打开选择框便会弹出警告。如果无视警告后以命名规则：{id_num}{user_id}
进行下载，下载下来的文件命名格式还是以默认规则命名
**诊断信息**

发生问题时，页面的 URL：（必须）
复制url的按钮显示 没有可用的抓取结果。
问题截图：（可选）
![Quicker_20241204_192815](https://github.com/user-attachments/assets/dc391228-92bd-400f-8925-7488d6a55f5c)
![Quicker_20241204_193936](https://github.com/user-attachments/assets/d9284918-064d-4b62-ba9a-1b54a54524a5)

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**版本	
win11 23h2
Microsoft Edge
版本 131.0.2903.70 (正式版本) (64 位)

**Comment by shanweixxy** [comment]
我的问题原来是{id_num}要和{p num}一起用

**Comment by xuejianxianzun** [comment]
这不是 bug。
必须包含 {id_num}{p num} 指的是这两个必须同时使用，而不能只使用其中之一。
如果只使用一个，在下载插画作品时非常容易出现文件名相同的问题。

对于小说来说，因为没有序号，所以 {id} 等价于 {id_num} 或 {id_num}{p num}。你没有必要在这种情况下纠结。

**Comment by shanweixxy** [comment]
{

**Comment by shanweixxy** [comment]
对不起我是猪鼻

**Comment by shanweixxy** [comment]
麻烦了
