### ISSUE TITLE
[需要优化] 减慢抓取 作品数量判断 应使用条件筛选后数量

### ISSUE THREAD

**Issue by yfdyh000** [xuejianxianzun/PixivBatchDownloader#457]
**Bug 详情**
例如【当前有 149 个作品
开始获取作品信息
慢速抓取，以避免触发 429 限制】【待处理 71, 共抓取到 2 个作品】
**如何重现这个问题？**
更多-减慢抓取速度 启用。当作品数量超过指定数量时启用：100。
投稿时间（或其他条件?）适当设置，使准备抓取作品详情的数量（例如70个）小于当前场景及 抓取多少页面 所涵盖的作品数量。因为该减慢的是抓取详情的请求。

发生问题时，页面的 URL：（必须）
https://www.pixiv.net/users/ ……

**你的操作系统和浏览器版本号**
Edge 132。

**Comment by xuejianxianzun** [comment]
使准备抓取作品详情的数量（例如70个）小于当前场景及 抓取多少页面 所涵盖的作品数量。
这怎么理解？

**Comment by yfdyh000** [comment]
比如作者有200个作品。今年只有30个作品。设定投稿时间，只抓取今年的。目前会减慢抓取。

**Comment by xuejianxianzun** [comment]
这不是 bug，属于可以优化的情况。
按时间筛选是不需要获取作品的详细数据就可以提前筛选出来的，所以只需要请求筛选后的作品（30 个请求）。
有些筛选条件必须获取每个作品的详细数据，之后才能进行筛选，所以虽然最后只保留了 30 个作品，但依然会发送所有请求。这种就需要使用慢速抓取。
以后我看怎么优化下。

**Comment by xuejianxianzun** [comment]
17.3.0 版本已应用此优化。
