### ISSUE TITLE
功能建议-更新动图保存方式

### ISSUE THREAD

**Issue by NayaCcR** [xuejianxianzun/PixivBatchDownloader#458]
**你需要什么功能？**
是否可以增加一个多选项，在不考虑资源占用的情况下多选动图保存方式
(就像我会想着存一个webm来浏览，再存个apng来存档原图awa)
或者给出一个单独下载其他格式动图的功能
**目的是解决什么问题？**
某种动图格式浏览不方便/失真
**其他软件是否有此类功能可以参考？**
暂无
**附加描述**
这样就不用爬两次了不是嘛x

**Comment by xuejianxianzun** [comment]
目前没有这个计划。
为了避免爬取两次，你可以这样做：
第一次抓取后先正常下载（动图保存为第一种格式）
下载完之后，导出抓取结果
然后在“抓取”的作品类型里面只选择“动图”，并导入抓取结果，这样只会导入动图数据。
![image](https://github.com/user-attachments/assets/b16bd380-aa0a-4bcc-9779-2c721ebd5135)
然后修改动图保存格式为第二种，再次开始下载即可。
