### ISSUE TITLE
[bug] chrome浏览器 版本17.3.0 批量关注提示  recaptcha enterprise score token

### ISSUE THREAD

**Issue by yuanjh12138** [xuejianxianzun/PixivBatchDownloader#461]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**

**如何重现这个问题？**

**诊断信息**

发生问题时，页面的 URL：（必须）

问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**

**Comment by yuanjh12138** [comment]
在关注页面https://www.pixiv.net/users/xxxx/following执行批量关注功能提示
“下载器发送的 API 返回 400 错误（需要 recaptcha enterprise score token），切换到模拟用户点击的方式，这会使用较多的硬件资源。”

**Comment by yuanjh12138** [comment]
> **问题自检**
> 
> 请首先按照以下步骤操作，观察问题是否可以解决：
> 
> 1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
> 2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
> 3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://camo.githubusercontent.com/ae853296505553e6d5f0a2ea04f6be6756e90930f4f2c314a6068572e2c586d4/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f762f72656c656173652f7875656a69616e7869616e7a756e2f50697869764261746368446f776e6c6f61646572)
> 4. 尝试刷新出现问题的标签页，或者重启浏览器。
> 5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。
> 
> 在你报告 Bug 之前，请确认你执行了上述检查。
> 
> **Bug 详情**
> 
> **如何重现这个问题？**
> 
> **诊断信息**
> 
> 发生问题时，页面的 URL：（必须）
> 
> 问题截图：（可选）
> 
> 另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。
> 
> **你的操作系统和浏览器版本号**

**Comment by xuejianxianzun** [comment]
在使用模拟点击的时候，下载器会加载用户主页并寻找关注按钮
![image](https://github.com/user-attachments/assets/42a3d888-95c0-43f7-8fab-0fa103a3565a)
如果找不到，可能是因为加载速度较慢，你可以在晚些时候尝试重新添加关注。

我现在试了添加关注不需要模拟点击，所以没法测试这个情况。

**Comment by yuanjh12138** [comment]
感谢你的回复，晚上用好一点网络的可以了，顺便问一下如果超过1000个关注用户，两次批量关注的冷却时间是0点刷新的吗？

**Comment by xuejianxianzun** [comment]
不是，其实你刷新页面就可以重新添加了，但是不建议这么做。
下载器限制了一次最多添加 1000 个，是因为一天里添加太多关注的话可能会被封号。
