### ISSUE TITLE
在已關注用戶的新作頁面，擷取數量與實際不符。

### ISSUE THREAD

**Issue by e1e1111e1e** [xuejianxianzun/PixivBatchDownloader#463]
**问题自检**

请首先按照以下步骤操作，观察问题是否可以解决：

1. 如果浏览器不是 Chrome 或者 Edge，请使用 Chrome 或 Edge 浏览器安装本扩展程序。
2. 如果你的 Chrome 或 Edge 浏览器不是最新版本，请更新浏览器。
3. 如果本扩展程序不是最新版本，请更新到最新版本。最新版本号：![version](https://img.shields.io/github/v/release/xuejianxianzun/PixivBatchDownloader)
4. 尝试刷新出现问题的标签页，或者重启浏览器。
5. 在本仓库的 issues 列表里搜索问题的关键字，查看是否已经有人报告过此问题。

在你报告 Bug 之前，请确认你执行了上述检查。

**Bug 详情**
「
時間範圍: 2024/12/29 上午12:00:00 - 2024/12/31 下午11:59:00

已擷取清單頁 10 個頁面
清單頁面擷取完成
目前有 353 個作品
開始取得作品資訊

共擷取到 289 個作品
」

在12/30號前時我擷取10頁會出現的是

「

已擷取清單頁 10 個頁面
清單頁面擷取完成
目前有 600 個作品
開始取得作品資訊

共擷取到 x 個作品
」

但今天只抓到353個。我有去看【已關注用戶的新作】頁面，但那邊是能正常顯示出10頁及之後的內容，所以不是作品刪除。
我擷取時間都是固定抓到前天的，不知道這樣會不會漏抓?

**如何重现这个问题？**

**诊断信息**

发生问题时，页面的 URL：（必须）

问题截图：（可选）

另外，如果有必要，你可以导出下载器的设置，或抓取结果，并添加到附件。

**你的操作系统和浏览器版本号**

**Comment by xuejianxianzun** [comment]
你启用了時間範圍: 2024/12/29 上午12:00:00 - 2024/12/31 下午11:59:00
也许10页里的后面几页作品不符合要求，所以不被计入。

**Comment by e1e1111e1e** [comment]
會計入的【共擷取到 x 個作品】
我指的是【目前有 600 個作品】這邊是擷取10頁不管是不是在時間範圍內如果沒有刪作品的話之前都會是600個。但今天不知為何同樣擷取10頁卻【目前有 353 個作品】

**Comment by xuejianxianzun** [comment]
不，设置时间范围之后，下载器会在统计作品数量时，会预先排除掉不符合时间范围的作品。
下载器有内置的 id 与发布时间对照表，之所以前几天会显示有 600 个，是因为对照表里没有包含最新的数据，所以下载器把 600 个都保存了（没有预先排除）。
在昨天更新后，下载器内置的对照表也更新了，所以会预先排除一部分不符合要求的 id。
你应该确认最后几页的作品是不是不符合时间范围，如果不符合，说明总数肯定不会有 600 个。
