### ISSUE TITLE
關於圖片預覽的問題

### ISSUE THREAD

**Issue by 20467321** [xuejianxianzun/PixivBatchDownloader#47]
篩選完作品後無法預覽顯示

![image](https://user-images.githubusercontent.com/59311057/71544054-7f502680-29b5-11ea-8ab7-619ce36423e1.png)
![image](https://user-images.githubusercontent.com/59311057/71544055-8c6d1580-29b5-11ea-81d6-bbe8022aeeac.png)

**Comment by Reinford0** [comment]
@xuejianxianzun 选择<section>岂不合适

**Comment by xuejianxianzun** [comment]
感谢提醒，之前没有发现这个问题，导致此页面的搜索结果显示在“熱門作品”里了。稍后我将发布下一个版本修复它。

**Comment by 20467321** [comment]
感謝你 這個真的好用

**Comment by xuejianxianzun** [comment]
谢谢你的喜欢 mua~
