### ISSUE TITLE
開啟面板的按鈕不見了

### ISSUE THREAD

**Issue by joker307176** [xuejianxianzun/PixivBatchDownloader#48]
本來還能正常使用，可以下載，但是切換視窗換回來之後在作者頁面面板叫不出來，沒有藍色按鈕，快捷鍵也沒用，試過瀏覽器重啟，電腦重啟，換Chrome Beta ，插件重裝，都沒有效，收藏頁面跟標籤頁面都能正常下載。

**Comment by xuejianxianzun** [comment]
这是因为作者页面的url变化了，我正在适配。
新版的如下：
https://www.pixiv.net/users/3869665

**Comment by joker307176** [comment]
我想說中午還可以用怎麼下午就不讓我用了

**Comment by xuejianxianzun** [comment]
之前 pixiv 的改版一般都是分批次对用户更新的，这次一下子就面向所有用户发布了。所以受影响的用户很多。今天晚上下载器应该可以更新到新版本。

**Comment by joker307176** [comment]
這樣阿…
真是感謝你做了這好東西，超好用的~

**Comment by xuejianxianzun** [comment]
谢谢夸奖😊

**Comment by joker307176** [comment]
收藏頁面沒辦法使用{p_user}來建立資料夾嗎?

**Comment by xuejianxianzun** [comment]
不能，收藏页面不是某个人的投稿作品列表，所以不能使用一个统一的用户名。

**Comment by joker307176** [comment]
63993487
58612479
59276537
62105468
61657235
這些下載異常
