### ISSUE TITLE
Fails to download

### ISSUE THREAD

**Issue by CaskoChan** [xuejianxianzun/PixivBatchDownloader#5]
it keeps getting stuck on Crawl finished!, never completes the download.

Would be nice if this gets fixed

**Comment by xuejianxianzun** [comment]
This issue has been fixed before, and the latest version of this extension is 1.3.3. I did not find the problem just after my test.

Another possibility is that Pixiv is undergoing a revision, and I have not changed it yet. This can only wait any longer.
