### ISSUE TITLE
能否考虑加入忽略已下载文件的功能

### ISSUE THREAD

**Issue by ShunyuYao** [xuejianxianzun/PixivBatchDownloader#50]
目前我使用的时候，发现如果之前已经下过的文件会自动覆盖，请问能否加入功能自动跳过已经下载的文件。因为我经常根据tags进行下载，所以每次想只想下最近更新的图，但是又不知道每次更新了多少张图，因此每次都会把之前的旧图又重新下载一次，感觉不太方便。
顺便说下，这个软件真的太好用啦！真的赞！

**Comment by xuejianxianzun** [comment]
检测某个文件是不是已经在硬盘上存在，这个做不到。这是扩展的局限。
根据你的更新情况，你应该考虑这样做：
例如上次下载的图片里，最大 id 是 111111，你下次下载时，设置选项“设置 id 范围”，大于 111111，就不会重复下载到以前下载过的了。
设置时间范围也是类似的作用。

**Comment by ShunyuYao** [comment]
明白了，感谢！
