### ISSUE TITLE
作品下载会出错

### ISSUE THREAD

**Issue by yumehime5** [xuejianxianzun/PixivBatchDownloader#53]
当我下载有些作品，类似：www.pixiv.net/artworks/79399027 的时候，会出现错误的作品下载

**Comment by xuejianxianzun** [comment]
我测试没有问题，你说的“错误的作品下载”指什么情况，能否复现？
建议先阅读wiki的“常见问题”，如果问题仍然存在，补充详细信息。

**Comment by yumehime5** [comment]
在作品页面（www.pixiv.net/artworks/...）里，如果作品的简介出现一个带有其他作者的<a>标签（类似<a href="/users/87007">user/87007</a>），就会触发该问题，下载的内容会跳跃到其他作者（如该例子的87007）的作品，在任何作品页面的 <p  id='expandable-paragraph-0' >标签下添加一个都会触发该问题，应该是获取作者的id 的时候定位出现了问题，识别到了更早出现在html页面里的/users/了

**Comment by yumehime5** [comment]
使用版本：4.0.1
触发页面：www.pixiv.net/artworks/ （实际问题页面：www.pixiv.net/artworks/79399027）
触发条件：作品简介（id 为:expandable-paragraph-0 的 p标签）中，href为 /users/的a链接(如 /users/2344550)
造成结果：下载的作品会变成另一个作者(如该例子的中的2344550)的作品
复现方法：在任何一个作品早于该作品作者（如下图）
![image](https://user-images.githubusercontent.com/49066074/74373250-0f87e500-4e17-11ea-9721-8f2ad2394966.png)之前的地方添加 href 类似 /users/1111 的a标签，均可触发该问题

上个信息中写了标签被识别成html了，这里重新描述一次

**Comment by xuejianxianzun** [comment]
感谢反馈，我会在 4.0.3 版本修复，现在已经提交到了谷歌应用商店审核。
