### ISSUE TITLE
希望增加ip池和更换USER-AGENT的支持

### ISSUE THREAD

**Issue by dkymore** [xuejianxianzun/PixivBatchDownloader#54]
希望增加ip池和更换USER-AGENT的支持
每次下载超过200张IP就会被关小黑屋

**Comment by xuejianxianzun** [comment]
你说的“每次下载超过200张IP就会被关小黑屋”，这数年来都没有用户反馈有这个问题。我刚才测试下载了数百张也没有问题。
你这个问题可能是梯子出现了问题，或者其他原因，使用梯子的话考虑换个线路。
一些日本线路不能在p站下载，这是p站主动屏蔽这些ip导致的。
