### ISSUE TITLE
希望增加 fanbox 批量下载

### ISSUE THREAD

**Issue by IceCodeNew** [xuejianxianzun/PixivBatchDownloader#56]
我发这个 issue 前已经 Google 搜索过，看到 19 年已经有人提过同样的 [建议](https://github.com/xuejianxianzun/XZPixivDownloader/issues/21)（那个 repo 现在已经被存档了

我只是想补充一下很多账号开通 fanbox 以后都会定期更新免费的记事，里面同样有图片可供开发测试。

fanbox 购买后收获图片的体验也实在太糟，要是您能帮助改善一下，我会很感激的，谢谢您。

**Comment by xuejianxianzun** [comment]
fanbox 我现在也没法测试，如果可以的话，你能把你的账号私发给我吗（通过邮箱或者加群私发我）？这样我可以大概评估一下这个功能需要怎么做。
另外免费记事也请给我发一下示例网址。

**Comment by IceCodeNew** [comment]
举例来说像这篇：https://www.pixiv.net/fanbox/creator/532989/post/802279

（这个绘师发布免费记事还挺频繁的，而且几乎都有图在内文里，我觉得应该可以用来模拟绝大多数付费文章中打算批量下载的图片都被绘师直接放在内文的场景

**Comment by xuejianxianzun** [comment]
只有免费记事的不够呀，我想最主要的还是在主页下载所有作品吧，这个我没有赞助账号，没法进行。

**Comment by xuejianxianzun** [comment]
pixiv fanbox 下载器
https://github.com/xuejianxianzun/PixivFanboxDownloader

**Comment by IceCodeNew** [comment]
啊抱歉后来一直没收到 GitHub 的邮件通知，今天再看到通知发现提的 issue 已经被解决了。
不好意思没有配合帮助开发，感谢您的工作。
