### ISSUE TITLE
如果下載後的檔案名稱異常，請停用其他有下載功能的瀏覽器擴充功能。

### ISSUE THREAD

**Issue by wialny** [xuejianxianzun/PixivBatchDownloader#58]
我有段时间没用PixivBatchDownloader了, 最近使用就总是提示这个. 之前没这个问题, 而我在此之间也没有新增其他扩充功能. 且使用无痕模式也由此提示

**Comment by xuejianxianzun** [comment]
使用chrome浏览器
不要使用无痕模式
关闭其他所有扩展再次排查

**Comment by wialny** [comment]
我一直都是使用chrome的. 
抱歉, 因为懒, 以为无痕模式就能关闭所有扩充功能.
经排查是与Nimbus Screenshot & Screen Video Recorder冲突. 可这个扩充比PixivBatchDownloader安装得更早呀. 可能是它最近更新导致的吧
