### ISSUE TITLE
在自己的收藏页里无法获取到{p_user}

### ISSUE THREAD

**Issue by Restore000** [xuejianxianzun/PixivBatchDownloader#59]
于是所有文件挤到一个{p_user}文件夹里了。
![2020-03-01 (1)](https://user-images.githubusercontent.com/53372034/75621034-a05a1100-5bca-11ea-8928-74729c35a2bb.png)也许是我操作不当？

**Comment by xuejianxianzun** [comment]
其实看你的情况，似乎可以用 {user} 而不是使用 {p_user} 
{p_user} 当前页面的画师名字，其实意思是“页面里的这些作品属于同一个画师”，这也就导致它只能在画师列表页面，和作品页面里使用。在其它页面不可以使用，并且下拉框里也不会出现它。
这个说明起来会比较复杂，而且也有一些和你一样对此产生疑惑的用户。下次更新我考虑去掉  {p_user} 和 {p_uid}，多数情况下使用 {user} 和 {uid} 可以替代它们。
