### ISSUE TITLE
feature request: 在“关注”页批量下载已关注画师的图片

### ISSUE THREAD

**Issue by Skimige** [xuejianxianzun/PixivBatchDownloader#60]
有两种页面链接，如下：
[新] https://www.pixiv.net/users/{your-user-id}/following
[旧] https://www.pixiv.net/bookmark.php?type=user

在 [关注的新作品](https://www.pixiv.net/bookmark_new_illust.php) 下载可以部分实现这个 feature，但是似乎最多 100 页，而这也只够今天到 2 月 14 日的量（

**Comment by xuejianxianzun** [comment]
关于你的需求，也许这个工具适合：
https://github.com/Tsuk1ko/pxder

在 关注的新作品 下载的话，你可以参考 wiki - 使用技巧 - 增量更新。
-----
我迟迟不想做这个功能，因为批量下载多个画师的作品有点麻烦，也有潜在的问题。
1. 可能会有人提出需要增加设置，指定下载多少个画师，或其他条件来过滤要下载哪些画师的
2. 可能会有人提出每天打开p站自动增量更新（虽然之前也有人提就是了
3. 网络问题。很多人网络都不好，梯子的快慢、好坏是受外部影响的，甚至很多人上p站不是用的梯子，他们平时少量的下载都会出错，如果抓取、下载数量很多，体验无法保证。
4. 性能问题。因为是在浏览器内进行下载，如果一次任务要下载数万个甚至更多作品，可能会爆内存。

最后，很多p站的长期用户可能关注了数千个画师，要下载他们的所有作品，这实在是太多了！
我在漫长的存图生涯中学到一件事，存的越多，回顾的就越少，所以，我现在只下载有限的图片。

**Comment by Skimige** [comment]
理解，感谢推荐！
