### ISSUE TITLE
该扩展与Pixiv 增强脚本冲突

### ISSUE THREAD

**Issue by catyue** [xuejianxianzun/PixivBatchDownloader#61]
您好，经过排查，在同时开启PixivBatchDownloader扩展与Pixiv 增强脚本（本人使用暴力猴脚本扩展）之后，pixiv首页顶栏（或者说页眉）会由这个样子
![image](https://user-images.githubusercontent.com/23721173/75947775-85deab00-5edc-11ea-8232-e68f224648a0.png)恢复成原来的
![image](https://user-images.githubusercontent.com/23721173/75947859-bd4d5780-5edc-11ea-93c4-60b2f6e1211c.png)这个样子
Pixiv 增强脚本地址如下，使用的人也挺多
[Pixiv 增强脚本](https://greasyfork.org/zh-CN/scripts/34153-pixiv-plus)
您看是否有解决冲突的必要？

**Comment by xuejianxianzun** [comment]
经过检查， pixiv plus 会选择p站顶部的 form 元素，而本扩展会在其他地方创建 form 元素。
本扩展的 form 先加载出来，p站顶部的内容加载的晚（你可以观察一下，经常是是页面主体部分加载完之后，顶部的内容才显示）。这导致 pixiv plus 选择了本扩展的 form，而不是顶部的 form。

pixiv plus 在选择表单时用的代码：
```
let $form = $('form:not([action])');
```
我觉得这个问题的主要原因，在于这个选择器不严谨，如果有其他的脚本、扩展和我一样创建了 form，那么 pixiv plus 也可能会出现同样的错误。建议改成下面这样：
```
let $form = $('#js-mount-point-header form:not([action])');
```
你可以把这个问题向他反馈一下。
