### ISSUE TITLE
开启浏览搜索结果功能后页面样式出现问题

### ISSUE THREAD

**Issue by Lanyangzhi** [xuejianxianzun/PixivBatchDownloader#62]
开启浏览搜索结果功能后页面样式出现问题
已禁用adblockplus和油猴
![image](https://user-images.githubusercontent.com/10362972/75976656-cdcdf400-5f15-11ea-926a-c781f732771a.png)

**Comment by xuejianxianzun** [comment]
p站不定期的改版导致下载器需要适配，所以下载器的更新是滞后的。
虽然我昨天已经修复了这个问题，但是谷歌商店又要审核，现在审核经常需要个两三天，所以用户也更新不上……你可以临时安装离线版使用。
