### ISSUE TITLE
Auto categorized 

### ISSUE THREAD

**Issue by Krusartan** [xuejianxianzun/PixivBatchDownloader#63]
Hello, I have such a question how can I turn off auto categorized after screening and is it even possible to do this.
Thanks in advance for your reply.

**Comment by xuejianxianzun** [comment]
What function or behavior does "auto categorized after screening" refer to?

**Comment by Krusartan** [comment]
When I add random work to Bookmarks, it is assigned the tag #uncatigorized.
However, if before that I click the "Start Screening" button, then those works that I will add to Booksmark should not be achieved in #uncatigorized, but in those tags that were in it.

**Comment by Krusartan** [comment]
I would like all the works that I added to booksmarks, even after screening, be added to #uncatigorized, and not sorted automatically

**Comment by xuejianxianzun** [comment]
也就是说，当收藏作品时，你不希望自动添加 tag。对吗？
之前也有人提出过类似的请求，我会考虑在以后的版本中添加一个开关。

**Comment by Krusartan** [comment]
Exactly!

**Comment by Krusartan** [comment]
Thanks for the answer. Hopefully this update is coming soon. Thanks
