### ISSUE TITLE
turning off `Enable quick bookmark` doesn't work

### ISSUE THREAD

**Issue by NewUserHa** [xuejianxianzun/PixivBatchDownloader#64]
turning off `Enable quick bookmark` doesn't work. reloading the page doesn't help as well.

please fix, thanks!

**Comment by NewUserHa** [comment]
![image](https://user-images.githubusercontent.com/32261870/76815165-ddafd700-6837-11ea-9a3a-ce6745427fc2.png)

**Comment by xuejianxianzun** [comment]
☆ will always be displayed, this is normal. This switch controls whether tags are added automatically.

**Comment by NewUserHa** [comment]
but even disabled `quick bookmark` feature, the tooltip of the icon still displays `quick bookmark` and clicks `like` automatically.

may it work like this?
![image](https://user-images.githubusercontent.com/32261870/76815517-c3c2c400-6838-11ea-99ae-acd6724f8666.png)
and may add an option to move `private bookmark` out of the menu for convenience?

**Comment by xuejianxianzun** [comment]
1. Use ☆ to indicate that this is a button added by the downloader so that such buttons can automatically add tags. The original Favorites button will not add tags even if Quick Bookmark is turned on.
2. Without this feature, pixiv can “Select all” on this page and then operate.

**Comment by NewUserHa** [comment]
may keep the original button for just bookmark?

**Comment by xuejianxianzun** [comment]
This can make the code more cumbersome. I suggest you turn off quick bookmarks.

**Comment by NewUserHa** [comment]
I did like the picture posted above, and that option just didn't work.

**Comment by xuejianxianzun** [comment]
Check again:
Close this option, then open an uncollected work, click the favorite button, and then open this page
https://www.pixiv.net/bookmark.php?untagged=1
If this work is shown here, there is no problem.
