### ISSUE TITLE
Edge for Chromium 下载图片失败

### ISSUE THREAD

**Issue by scighost** [xuejianxianzun/PixivBatchDownloader#65]
无论是作品页面快速下载还是收藏页、画师主页抓取下载，均会出现下载失败的情况，然后在本地保存了一个txt文件。相同的网络环境和账号，用Chrome浏览器时下载正常。
版本 83.0.467.0 (官方内部版本) dev (64 位)

**Comment by xuejianxianzun** [comment]
下载到 txt 99% 的可能是网络问题。但是我无法复现你的网络环境，所以只能你自己去摸索解决，或者只使用 chrome。
我现在用 edge 测试可以正常下载。
