### ISSUE TITLE
Please update to version 5.1.2

### ISSUE THREAD

**Issue by xuejianxianzun** [xuejianxianzun/PixivBatchDownloader#66]
请注意，5.0.0 和 5.1.0 版本存在 bug 会导致错误的排除图片，请等待更新到 5.1.2 版本。谷歌的审核可能需要几天时间。非常抱歉！

你也可以考虑离线安装，立即使用最新版本。

Please note that there are bugs in versions 5.0.0 and 5.1.0 that can lead to incorrectly excluded images. Please wait to update to version 5.1.2. Google ’s review may take several days. very sorry!

You can also consider offline installation and use the latest version immediately.
https://github.com/xuejianxianzun/PixivBatchDownloader/releases

**Comment by Katsudon96** [comment]
Updated to 5.1.2 and i am seeing an issue that even though i chose to only search for works that include specified tags, it ignores this and still searches for all the Works. E.G. i search for something to include 2 tags and it shows 3400 works, but clicking on Crawl it still says 11000 works.

**Comment by xuejianxianzun** [comment]
> Updated to 5.1.2 and i am seeing an issue that even though i chose to only search for works that include specified tags, it ignores this and still searches for all the Works. E.G. i search for something to include 2 tags and it shows 3400 works, but clicking on Crawl it still says 11000 works.

Hello, I just tested it and found no problems.
Please provide the URL of the page and the tag set when the problem occurred.

**Comment by Katsudon96** [comment]
> > Updated to 5.1.2 and i am seeing an issue that even though i chose to only search for works that include specified tags, it ignores this and still searches for all the Works. E.G. i search for something to include 2 tags and it shows 3400 works, but clicking on Crawl it still says 11000 works.
> 
> Hello, I just tested it and found no problems.
> Please provide the URL of the page and the tag set when the problem occurred.

URL: https://www.pixiv.net/en/tags/超次元ゲイムネプテューヌ%20ネプテューヌ/artworks?mode=safe
Search Settings: Tags (Perfect Match), Illustrations

It says 3778 works, but when i click Crawl it says it has acquired 11335 Works

when i remove the Search settings and put the tags into "Must Include" in the PIXIV Downloader. it also says 11335.

**Comment by xuejianxianzun** [comment]
> > > Updated to 5.1.2 and i am seeing an issue that even though i chose to only search for works that include specified tags, it ignores this and still searches for all the Works. E.G. i search for something to include 2 tags and it shows 3400 works, but clicking on Crawl it still says 11000 works.
> > 
> > 
> > Hello, I just tested it and found no problems.
> > Please provide the URL of the page and the tag set when the problem occurred.
> 
> URL: [https://www.pixiv.net/en/tags/超次元ゲイムネプテューヌ%20ネプテューヌ/artworks?mode=safe](https://www.pixiv.net/en/tags/%E8%B6%85%E6%AC%A1%E5%85%83%E3%82%B2%E3%82%A4%E3%83%A0%E3%83%8D%E3%83%97%E3%83%86%E3%83%A5%E3%83%BC%E3%83%8C%20%E3%83%8D%E3%83%97%E3%83%86%E3%83%A5%E3%83%BC%E3%83%8C/artworks?mode=safe)
> Search Settings: Tags (Perfect Match), Illustrations
> 
> It says 3778 works, but when i click Crawl it says it has acquired 11335 Works
> 
> when i remove the Search settings and put the tags into "Must Include" in the PIXIV Downloader. it also says 11335.

You see that the total number of works displayed on the page is 3778, but the downloader shows 11,335. This is because your search condition is "Tags (**perfect match**)", but the downloader will always use "Tags (**partial match**)", which is to get more works.
The URL used by the downloader is this:

https://www.pixiv.net/tags/%E8%B6%85%E6%AC%A1%E5%85%83%E3%82%B2%E3%82%A4%E3%83%A0%E3%83%8D%E3%83%97%E3%83%86%E3%83%A5%E3%83%BC%E3%83%8C%20%E3%83%8D%E3%83%97%E3%83%86%E3%83%A5%E3%83%BC%E3%83%8C/artworks?mode=safe&s_mode=s_tag

If the two tags do not overlap, such as `東方Project` and  `レミリア`, generally there is no problem. But your situation is special because your first tag contains the second tag. In **partial match**, this is equivalent to searching only the first tag.
When you search for multiple tags at the same time, if you are sure that you need **perfect match**, please use the setting items at the same time:  **"Must contain tag"**, enter two tags, for example: `tag1, tag2`.
