### ISSUE TITLE
希望下载地址可以自动导出为txt文件 

### ISSUE THREAD

**Issue by telessa** [xuejianxianzun/PixivBatchDownloader#68]
RT
有时候点击复制地址时chrome页面会崩溃 
下载也不时会停住（有使用飞机场全局代理） 只能刷新 重新再来
导出为txt复制 下载更稳定

另请问使用下载软件 如何在文件名中添加tag 画师id
只能以图片id为文件名吗？

**Comment by xuejianxianzun** [comment]
复制地址时chrome崩溃，是抓取结果太多吗？
下载时机场开启全局代理
命名规则看看 wiki
https://github.com/xuejianxianzun/PixivBatchDownloader/wiki/4.-%E8%AE%BE%E7%BD%AE%E9%80%89%E9%A1%B9#%E8%AE%BE%E7%BD%AE%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99

**Comment by telessa** [comment]
从5.1.6手动更新到6.1.1
Google Chrome 已是最新版本
版本 81.0.4044.138（正式版本） （64 位）
其他扩展只有adblock 
抓取大概1000左右的结果
自动开始下载 到100多 chrome就会卡死
只能强行退出

**Comment by xuejianxianzun** [comment]
这很不正常，你的内存是否太少？
请提供你的抓取网址，条件

**Comment by telessa** [comment]
> 
> 
> 这很不正常，你的内存是否太少？
> 请提供你的抓取网址，条件

Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
	16.0 GB DDR3
	使用中(已压缩)	6.4 GB (128 MB)

网址
Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
	16.0 GB DDR3
	使用中(已压缩)	7.2 GB (128 MB)

网址
https://www.pixiv.net/tags/50000users%E5%85%A5%E3%82%8A/artworks?s_mode=s_tag
条件
![1](https://user-images.githubusercontent.com/30003325/81928970-b77c9c80-9618-11ea-9253-5f704eaf4ab9.PNG)
![2](https://user-images.githubusercontent.com/30003325/81928981-bb102380-9618-11ea-8b66-cfa7403e7345.PNG)
![3](https://user-images.githubusercontent.com/30003325/81928988-bd727d80-9618-11ea-8ba4-190bf5e7e544.PNG)

**Comment by xuejianxianzun** [comment]
明天我测试下

**Comment by xuejianxianzun** [comment]
我全部抓取了，现在下载了400多个也没什么问题
页面内存占用也很少
你的情况比较反常，请自行排查尝试解决，比如重装chrome，或者关闭一些软件试试
![](https://s1.ax1x.com/2020/05/15/YrJtR1.jpg)

**Comment by xuejianxianzun** [comment]
复制这接近10000个文件的url，从打开输出面板，到复制完毕，内存占用增加了大约 100MB，关闭输出面板之后会降回去。感觉没有什么问题。

**Comment by telessa** [comment]
> 复制这接近10000个文件的url，从打开输出面板，到复制完毕，内存占用增加了大约 100MB，关闭输出面板之后会降回去。感觉没有什么问题。

暂时用chrome的便携版解决了

问题可能出在chrome的账户同步上
能用的另外两台电脑上的chrome 在开启同步之后（与问题机是同一账户）变得全部不能用了 
只要打开网页 就会随机卡死
重装chrome  删缓存 关插件 没有解决问题
也不知道同步了什么错误的设置

非常感谢帮助

**Comment by xuejianxianzun** [comment]
6.4.1 版本，当抓取结果数量太多时（大于5000），预览将不会显示，而是保存到一个txt里自动下载。防止一些用户复制的时候页面崩溃。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v6.4.1
