### ISSUE TITLE
在搜索条件里指定了时间后，获取图片网址到一定数量就会停住，没法下载或者复制链接

### ISSUE THREAD

**Issue by huang1332** [xuejianxianzun/PixivBatchDownloader#69]
卡在这里，用别的电脑试也有同样问题
![image](https://user-images.githubusercontent.com/38836674/79436095-07a91480-8003-11ea-81f6-9eab4bc8b602.png)

**Comment by xuejianxianzun** [comment]
设置了筛选图片颜色吗？如果设置了，请更新到5.1.6版本。
如果没有设置，请提供网址，设置条件

**Comment by huang1332** [comment]
![image](https://user-images.githubusercontent.com/38836674/79439669-b2bbcd00-8007-11ea-9bdd-0832f31b68d2.png)
这个只有获取的图片特别多时才会出现，已通过 Chrome Web Store 更新到最新版
