### ISSUE TITLE
看图模式能否增加一个缓存功能

### ISSUE THREAD

**Issue by cafrew** [xuejianxianzun/PixivBatchDownloader#7]
进入看图模式之后，点下一张，如果这张图片没有看过，就要等待图片加载完成，这就很令人着急。
能不能增加一个功能，进入看图模式后自动加载下一张图片，使点击下一张时不需要等待加载。
谢谢！

ps：最好可以设置自动加载的图片数量，比如自动加载下5张、或者下10张图片，这样就更好啦

最后祝这个插件越来越好，hub主天天开心:laughing:

**Comment by xuejianxianzun** [comment]
谢谢亲~
这个主意不错，我现在加入了预读取第一张和下一张图片的功能。不过没有支持自定义数量
