### ISSUE TITLE
在搜索条件里指定了图片清晰度为999px*999px以下时，实际会获取所有清晰度的图片

### ISSUE THREAD

**Issue by huang1332** [xuejianxianzun/PixivBatchDownloader#70]
选择3000px以上和1000-2999px可以正常抓取指定页面，选999以下就会抓取所有页面

**Comment by xuejianxianzun** [comment]
网址和截图？

**Comment by xuejianxianzun** [comment]
图片宽高只能指定“以上”，如果你设置 999 and 999，抓取的是宽高都大于等于 999 的图片

**Comment by huang1332** [comment]
就像这样，选择的选项是“999*999以下”
![捕获](https://user-images.githubusercontent.com/38836674/79438930-c581d200-8006-11ea-9166-ab2259c0c441.PNG)

**Comment by xuejianxianzun** [comment]
之前没有发现`wgt` `hgt` 这俩筛选条件，现在进行了修复，请更新到最新版本试试
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v5.1.6

**Comment by huang1332** [comment]
已经解决，谢谢大佬
