### ISSUE TITLE
下载元数据　メタデータのダウンロード

### ISSUE THREAD

**Issue by p32l** [xuejianxianzun/PixivBatchDownloader#71]
投稿者のキャプション、タグの情報など
メタデータがダウンロードできるようになりませんか？

下面是DeepL的翻译。

投稿人的标题、标签信息等。
你不能把元数据提供给大家下载吗？

**Comment by xuejianxianzun** [comment]
タイトルとラベルをファイル名で保存する場合は、命名規則の右側にドロップダウンボックスがあり、対応するラベルを選択できます。

如果你想把标题和标签保存在文件名中，在命名规则的右侧，有一个下拉框，你可以选择相应的标签。

```
{title} 作品のタイトル
{tags} 作品の tags
```

**Comment by jiaer24** [comment]
このダウンローダーは現在単独のメタデータのダウンロードをサポートしていません。ただし、タイトルやタグなどのメタデータをダウンロードしたファイル名に保存することができます。
設定方法：
ダウンロード - 命名規を設定する

`{title} 作品のタイトル`
`{tags} 作品のタグ`
