### ISSUE TITLE
option download: skip downloading files larger than 500kb / 1mb etc

### ISSUE THREAD

**Issue by mumualpaka** [xuejianxianzun/PixivBatchDownloader#72]
Hi, can add in one additional option in download section to skip files that are bigger than certain sizes? Thank you in advance :)

**Comment by xuejianxianzun** [comment]
Because a large picture may have a relatively large width and height, many people like large pictures. May I ask why do you need this feature?

**Comment by mumualpaka** [comment]
to save bandwidth and to skip large files ie: over 1mb size, faster to download images for users with limited data plans it is useful. most jpg image over 500kb is good enough for viewing, on normal monitors.

**Comment by xuejianxianzun** [comment]
Please upgrade to version 5.2.0.
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v5.2.0

**Comment by mumualpaka** [comment]
Great! its working like how it should, thank you xue ~
