### ISSUE TITLE
下載動圖無法釋放記憶體

### ISSUE THREAD

**Issue by qq123450000** [xuejianxianzun/PixivBatchDownloader#73]
下載大量動圖時
記憶體會無法釋放
最後導致記憶體用盡
瀏覽器頁面報錯
請問如何解決??

**Comment by xuejianxianzun** [comment]
内存是会释放的，但是需要一些时间。
我平时没遇到过，可能是我转换的动图不够多。
动图转换线程设置为 1，会不会好一些？

**Comment by qq123450000** [comment]
下載線程用5
轉換線程用1
最後會吃掉23G的RAM
然後crash

**Comment by xuejianxianzun** [comment]
总共有多少个动图，转换了多少个崩掉了？
其实这个我没有好的办法解决，浏览器扩展程序对内存没什么办法限制
另外下载时不要开 devtools，会增加很多内存占用

**Comment by xuejianxianzun** [comment]
缓解的办法：
1. 保存为 webm 格式，内存占用明显比 gif 少很多
2. 分批下载，比如多页的作品，一次下载一页。下载完之后刷新页面（这会释放很多内存），然后再下载下一页。以此类推。

**Comment by 1686565568** [comment]
没有转换ugoira的方式了吗?

**Comment by 1686565568** [comment]
能否退出转换apng格式动图的方式呢

**Comment by xuejianxianzun** [comment]
> 能否加一个转换apng格式动图的方式呢

apng 体积太大，不打算加

**Comment by xuejianxianzun** [comment]
ugoira 格式的话，下载 zip 把后缀名直接改成 ugoira 就行
