### ISSUE TITLE
希望可以为小说版块添加同样的【快速收藏&给未分类作品添加 tag】功能

### ISSUE THREAD

**Issue by zx2kk** [xuejianxianzun/PixivBatchDownloader#74]
这两个功能太实用了，能在小说版实现的话会方便很多，不知道实现起来困不困难……

**Comment by xuejianxianzun** [comment]
目前暂未支持小说下载，如果以后支持了再添加这些功能吧。

**Comment by xuejianxianzun** [comment]
5.4.0 版本开始已经支持了这个功能

https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v5.4.0
