### ISSUE TITLE
开始下载后没有反应

### ISSUE THREAD

**Issue by shjdgwj** [xuejianxianzun/PixivBatchDownloader#76]
第一次使用，可能是我自己配置单问题，请指教
命名规则{p_title}/{user}/{title}/{id}
我尝试拉取一个画师的所有作品
![QQ截图20200504092113](https://user-images.githubusercontent.com/11689121/80930858-c0839780-8de8-11ea-880f-3d5202ecd05d.jpg)
箭头所指处看似图片下载完成，但是文件管理器仅仅创建了文件夹而已，并没有下载任何图片，
我也单独把标签页拉了出来，应该没有什么资源分配的问题吧
但是就是没有任何图片下载

**Comment by xuejianxianzun** [comment]
有一个可能的原因（但我不是很确定），你看看页面顶部是否有显示“pixiv更新了隐私政策”的提示，如果有，需要点同意。
除此之外似乎偶尔也会发生这种情况，你点暂停，然后再点开始下载试试。

**Comment by shjdgwj** [comment]
> 有一个可能的原因（但我不是很确定），你看看页面顶部是否有显示“pixiv更新了隐私政策”的提示，如果有，需要点同意。
> 除此之外似乎偶尔也会发生这种情况，你点暂停，然后再点开始下载试试。

感谢，重启电脑就好了（尴尬）
非常感谢作者
可惜现在chrome商店暂时不能评价，到时候一定5星支持
