### ISSUE TITLE
Chrome Web Store 审核被拒了，惆怅

### ISSUE THREAD

**Issue by xuejianxianzun** [xuejianxianzun/PixivBatchDownloader#77]
十天前提交的审核被拒了，理由是 **用户数据隐私**。

以下是邮件原文：

-------

尊敬的开发者：

您近期针对 Google Chrome 商品“Powerful Pixiv Downloader”（ID 为 dkndmhgdcmjdmkdonmbgjpijejdcilfh）提出的发布请求被拒，因为此商品不符合我们的政策。

如果您曾在 Chrome 网上应用店中发布过此商品，已发布的版本并未受到影响且仍然可用。

您的产品不符合我们的计划政策的以下部分：

用户数据隐私

您的产品违反了此政策的“权限使用”部分，该部分要求您：

- 必须请求获得为实现该产品的相关功能或服务而需具备的最基本权限。
- 在可以使用多项权限来实现某个功能的情况下，必须请求获得最不需要访问数据或功能的那些权限。
- 不得尝试通过请求可能会给尚未实现的服务或功能带来好处的权限为您产品的未来发展提供保障。

-----------

前两条说的都和权限有关，之前已经在后台详细描述了每个权限的作用，但仍然被拒了。扩展的权限要求并不多，而且都是必须的，没有办法再减少了。

至于第三条，”为了未来发展“，难道检测版本更新（从 github 获取版本号）算吗？其他的我真想不出来了。

我不确定该怎么修改，而且我认为这个质疑是不合理的。

最近版本我没有提交更新了，因为如果再次被拒，可能导致我的开发者账号被封禁。其实去年就被封过一个了，现在谷歌商店的哪个已经是用新的账号发布的了。

**Comment by zx2kk** [comment]
chrome商店越来越严了，虽然安全但是也麻烦……

**Comment by xuejianxianzun** [comment]
> chrome商店越来越严了，虽然安全但是也麻烦……

虽然我觉得这个扩展没问题，但我也没处说理去。

再者，拒绝理由都是公式化的条款，没有更明确的信息，全靠猜，害

**Comment by SuXi210** [comment]
上架Microsoft edge商店试一试？国内还不用挂梯子，美滋滋儿

**Comment by 850710247liu** [comment]
上架极简插件也行，大多数人都是最开始在那里下载谷歌访问助手随后起飞的

**Comment by xuejianxianzun** [comment]
> 上架Microsoft edge商店试一试？国内还不用挂梯子，美滋滋儿

可以，我现在提交到edge审核了，希望一切顺利~

**Comment by xuejianxianzun** [comment]
> 极简插件

极简插件搜了下结果好多，能给个网址吗

**Comment by xuejianxianzun** [comment]
> 上架Microsoft edge商店试一试？国内还不用挂梯子，美滋滋儿

今天在 Edge 商店发布了：
https://microsoftedge.microsoft.com/addons/detail/hpcoocgpiepjcngmhhknkflhpkoklphp

**Comment by Kennnnnnji** [comment]
极简插件应该是这个：https://chrome.zzzmh.cn/

**Comment by xuejianxianzun** [comment]
> 极简插件应该是这个：https://chrome.zzzmh.cn/

原来是这个，我看了下，它只能提交 chrome 商店已有的扩展，并不能把最新版本放上去。
上周提交了一次谷歌的审核，竟然通过了。现在下载器又有更新，不过我不敢继续提交了，因为不知道下次还会不会过。心累
