### ISSUE TITLE
关于小说下载功能的一些修改建议……

### ISSUE THREAD

**Issue by zx2kk** [xuejianxianzun/PixivBatchDownloader#78]
6.0版本基本可以满足我的需求了，感谢作者
但是还有些可以优化的细枝末节……有空的话就拜托修改了……

1.作者的文章说明介绍没有保存。就是标题下方，TAG上方的那些内容，因为有些作者喜欢在这里说些有趣的东西，漏掉的话还是挺可惜的……

2.文章内部具体的代码显示。
这块有些复杂我也不是很懂，但是有点影响阅读体验，可以做成设置放在“其他”里面自行勾选，仅就TXT版来说的话：
[newpage]。这个是用来分页的，但是很多时候忽视掉也没关系，可以直接删掉或是替换成长破折号
[[rb:汉字 > 假名]]。注音，喜欢用这个功能的作者还蛮多的，可以替换成【汉字（注音）】这种感觉
[chapter:本章标题]。见到的比较少，可以直接替换成【本章标题】这种样子
[pixivimage:插画ID]。同样见到的很少，似乎只可以放P站内部的插图，也许EPUB可以直接把图片一并保存下来……txt可以显示成[插画ID:1234567]这样……
[[jumpuri:标题 > 链接目标的URL]]。超链接，epub不太清楚，txt可以直接换成【标题（URL）】这种格式
[jump:链接目标的页面编号]。这个一般是用来制作那种可以跳页阅读的冒险类书籍用的，用的很少，epub好像可以直接跳跃，txt想用的话感觉需要配合上面的[newpage]，显示成[第一页]、[第二页]，通过查找来跳转……（也许还有更好的方法，或者干脆无视）

大致就这些了……

**Comment by xuejianxianzun** [comment]
6.1.0版本已更新，如有问题请反馈

保存简介
txt 移除 html 标签
去掉 [newpage]
替换 rb
替换 chapter
替换 pixivimage 为超链接
替换 jumpuri
去掉 jump
