### ISSUE TITLE
希望能够添加读取关注列表，直接能够下载全部关注用户作品

### ISSUE THREAD

**Issue by Shinaki** [xuejianxianzun/PixivBatchDownloader#79]
如果能够直接读取关注列表，下载全部关注用户作品，能够省事不少，现在关注600多位，一个个页面下载太累了

**Comment by xuejianxianzun** [comment]
6.3.0 版本增加了这个功能，到关注页面开始抓取即可。
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v6.3.0
