### ISSUE TITLE
Download / Parse only xxxxxxx_p0_master1200.jpg

### ISSUE THREAD

**Issue by mumualpaka** [xuejianxianzun/PixivBatchDownloader#80]
Hello, hope not disturbing too much

Is it possible to make an option to only download the images that has the master 

(example: xxxxxxx_p0_master1200.jpg) name on it. normally the size is like under 400kb per image
it is the image when we 'save as' on usual image before we click, then it over size to maximum size.

reason: just preferences, because we can go through later when less busy, and if like that image we can find back easily. I also think this is a good option to have.

**Comment by xuejianxianzun** [comment]
You can download the installation package
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
 and modify the code:
Open `dist/js/content.js`, search for `body.urls.original` and replace  with `body.urls.regular`
Save the file and load the extension.
This method requires you to disable this extension installed previously.

**Comment by mumualpaka** [comment]
oh cool! will try this :D
