### ISSUE TITLE
希望优化一下下载逻辑

### ISSUE THREAD

**Issue by WangWenBin2017** [xuejianxianzun/PixivBatchDownloader#83]
提一个小建议，
这两个都不算是拓展本身的问题，只是优化一下能够更加友好。就是在下载过程中，如果我需要使用{id_num}-{p_num}这种下载方式，且勾选了第一张图不带序号的选项，这样在下载的时候就会出现一个问题，下载第一张的时候会带着"xxxxxx-.jpg"这种类型，能否优化一下，智能去除手动输入的连字符；
第二个问题算是第一个问题的延伸，如果作品有多张图片的情况下，第一张图能否带着-1，第二张图带着-2这种呢，然后只有一张图的作品可以不带作品后面的序号，貌似拓展也没有设置下载判断的选项

**Comment by xuejianxianzun** [comment]
第一个问题，其实如果你使用 {id}，相比 {id_num}-{p_num} 只多了一个字母 "p"，但不会有多余的横线的问题。
如果非要说 {id_num}-{p_num} 的话，有个问题在于不是所有人都使用 - 作为分隔符，可能会有人用下划线，或者 @ 之类的，感觉处理起来有点麻烦。
不过如果将两个标记之间的任意字符都视为分隔符的话，当某个标记为空，就去掉它之前的字符，似乎有可行性，不知道会不会有误伤。

第二个问题是，多图都带序号，单图不带序号？如果是这个意思，那目前没有这个设置，建议不要强迫症(

**Comment by xuejianxianzun** [comment]
今天想了想，觉得还是很难搞，因为“连接字符”可能出现在标记前面，也可能出现在标记后面。
当一个标记为空时，可能需要去掉它前面的连接字符，也可能需要去掉它后面的连接字符。这很难搞，而且也可能会误伤。
建议尽量不使用可能会为空的标记。你这个例子有点特殊，没有好的办法。
