### ISSUE TITLE
Download Ugoira as Animated PNG (APNG)?

### ISSUE THREAD

**Issue by NintendoManiac64** [xuejianxianzun/PixivBatchDownloader#85]
GIF is limited to 256 colors.

But APNG effectively has no color limit (16bit per channel, so 64bit per pixel including alpha channel or 48bit per pixel without alpha)

And APNG now has very good web browser support: https://caniuse.com/#feat=apng

(the only thing is that an unoptimized APNG can have quite a large file size, and I don't know how realistic it is to support the sort of lossless inter-frame optimization that software like "[APNG Optimizer](https://sourceforge.net/projects/apng/files/APNG_Optimizer/)" implements)

**Comment by xuejianxianzun** [comment]
This question has been asked before because someone seems to be a staunch supporter of apng/webp, haha
As you said, the large size of apng is a serious problem. Before I started to write this downloader, I used a software to save pixiv animated pictures, its save format is apng, and since then I realized that the size of apng is too large.
In fact, the size of gif is also large, but apng seems to be larger. Their size is often larger than the original size of the animated picture.
I always recommend users to choose the webm format; the gif format is the most versatile, but it has too many disadvantages. I rarely think about apng, and not many people have this need, so I didn’t try it.

**Comment by NintendoManiac64** [comment]
For APNG the filesize heavily depends on how much of the background is still or of similar colors - such animations can have a file size that is only half as an APNG.  (though unfortunately the insistance of using JPEG for ugoira frames hurts the compression efficiency).

Howeve,r this requires the bit about it being an "opitmized" APNG where it takes into consideration the information in the previous frame (an unoptimized APNG by contrast will store every complete frame as if they were stand-alone images, resulting in a file size larger than even a ZIP download of the individual JPEG frames)

There is one recent ugoira where it as an APNG results in a filesize that is half that of it being a GIF, but it's extremely NSFW and therefore I do not feel comfortable directly linking to it; I'll just say that the pixiv ID URL for the artwork itself is "81225567" (without quotes) and you can find an optimized APNG version linked in the comments (~9MB vs ~17MB for a GIF downloaded from a different source - I did not yet know about your extension at the time).

----------------------------------------------------------------

As for you and others rarely thinking about APNG, brance yourself - rant and tangent warning!

That's because in the late 2000s when APNG was created back before GIF became a household name (much like MP3), there was sadly a bunch of software dev politics that occurred that led to effectively a format war, and as everybody knows all to well knowadays, when there's a format war that doesn't get resolved in a relatively timely fashion (VHS vs Betamax; Blu-ray vs HD-DVD), the winner instead ends up being the very format that you were trying to replace and improve upon (SACD vs DVD-Audio...winner was CD; OGG vs AAC vs WMA vs FLAC...winner was MP3; APNG vs MNG vs WebP vs HTML5 Video...winner was GIF).

Considering the format was created over a decade ago, I can't help but think it would have been a much simpler, more elegant, and generally wiser solution than ugoira being effectively a javascript implementation of motion JPEG - a format never intended for internet usage since it prioritized low CPU encode and decode requirements (extremely useful on early 2000s digital cameras) in exchange for horrible compression efficiency due to not having any interframe optimization (even if every frame is identical, motion JPEG and ugoira will store each full frame individually - talk about a waste of bandwidth; even APNG would instead only store the first frame).

**Comment by xuejianxianzun** [comment]
I searched for JavaScript libraries related to APNG and found that they all parse and play APNG instead of synthesizing APNG.
This is a bit difficult.

**Comment by NintendoManiac64** [comment]
It's fine if it's not worth the effort.

**Comment by xuejianxianzun** [comment]
I don’t know much about image coding, so I can only rely on existing libraries.

**Comment by xuejianxianzun** [comment]
## 7.2.0 2020-09-02

### Animated images can be saved in lossless APNG format
