### ISSUE TITLE
希望在命名规则中增加“作品类型”与“小说系列”标记

### ISSUE THREAD

**Issue by assassingyk** [xuejianxianzun/PixivBatchDownloader#86]
如题，希望增加“作品类型”与“小说系列”这两项命名规则标记。

“作品类型”标记是希望下载小说与插图时能分开保存在不同文件夹中，如果有这个标记就能使用同一个命名规则下载，而不需要在下载小说前单独修改命名规则

“小说系列”是由于某些作者同时有多个小说系列在连载，但同一个系列的小说标题并没有统一格式，多个系列混在一起想阅读时就会比较困难……

**Comment by xuejianxianzun** [comment]
作品类型已经有了
`{type}` 作品类型，分为 illustration、manga、ugoira、novel

系列名称可以考虑，我有空了做吧

**Comment by assassingyk** [comment]
好的，非常感谢!
之前居然没看见作品类型，我的锅）_星际不能免费.jpg_

**Comment by xuejianxianzun** [comment]
6.2.0 版本 对系列作品，新增了两个标记

**series_title**  系列标题

**series_order**  这个作品在系列中的序号
