### ISSUE TITLE
能不能在release里面提供crx文件

### ISSUE THREAD

**Issue by mini536** [xuejianxianzun/PixivBatchDownloader#87]
360极速浏览器、edge开发版等是支持拖拽安装crx的，而且不会显示停用开发者模式安装的软件提示

**Comment by xuejianxianzun** [comment]
没有这个打算，因为：
edge浏览器可以从edge商店安装最新版。
360极速我不考虑， 需要的话可以自行把扩展文件夹打包成cex——这个不是必须由作者打包。
