### ISSUE TITLE
可以重新提供firefox版本的下载器吗？

### ISSUE THREAD

**Issue by mini536** [xuejianxianzun/PixivBatchDownloader#88]
部分浏览器如waterfox可以本地文件安装.xpi并且不会自动禁用

**Comment by xuejianxianzun** [comment]
不会。原因你可以在 changelog.md 里搜索
`放弃对 Firefox 的支持`
条目查看

**Comment by xuejianxianzun** [comment]
Firefox version:
https://addons.mozilla.org/firefox/addon/powerfulpixivdownloader/
