### ISSUE TITLE
请求添加选项使多图作品预览可使用默认缩放版本

### ISSUE THREAD

**Issue by AlphaAnother** [xuejianxianzun/PixivBatchDownloader#89]
RT，因为大部分时间在多图预览主要是为了找特定的一张图，还不能确定是否需要下载的情况下使用缩放版本加载快些。

**Comment by xuejianxianzun** [comment]
你说的是点击多图作品的缩略图查看大图时，只加载普通尺寸的图片吗？
如果是这样的话，p 站的多图作品有个自带的按钮“查看全部”，这个就是普通尺寸的，你试试。

**Comment by AlphaAnother** [comment]
我知道这个 不过在有大量图片的情况下 可能要加载几十张图片才能找到特定的那张（其实就是没有缩略图预览的问题）

**Comment by xuejianxianzun** [comment]
话说，本程序会在多图下方显示缩略图预览啊，不过有些的缩略图本来就没有，就加载不出来
