### ISSUE TITLE
希望加上能够批量下载 下载失败的功能

### ISSUE THREAD

**Issue by cxz31415** [xuejianxianzun/PixivBatchDownloader#90]
目前下载失败的图片会生成一个txt文档，如果只有几个还好，如果下载的数量很多的话，翻墙又不稳定的话，有时候会生成几百上千个txt文档，手动去筛选这些下载失败的图片重新下载的话就失去了用你这个批量下载器的意义了。
能否在生成txt记录的同时，用什么方式记录下载失败的图片的保存路径和网络路径，然后弄个按钮点一下直接读取这个保存起来的列表重新下载那些下载失败的图片

**Comment by xuejianxianzun** [comment]
这种情况下你首先应该考虑改善网络/梯子的质量。可能我用的梯子质量比较好吧，几年来很少发生下载失败的问题。看到有些用户时不时问我这个问题，常常使我觉得我是在为你们的网络问题擦屁股。
你可以考虑复制url然后用其他软件下载，比如迅雷，idm。
这个地方我之后尝试优化一下吧。

**Comment by xuejianxianzun** [comment]
你加qq群找我私聊，我修改之后可以让你试试效果。

**Comment by xuejianxianzun** [comment]
提问者把下载的小说误以为是下载失败的文件了。
