### ISSUE TITLE
BUG：与暗色模式兼容性问题导致收藏按钮消失

### ISSUE THREAD

**Issue by Kennnnnnji** [xuejianxianzun/PixivBatchDownloader#91]
![a.png](https://i.loli.net/2020/07/27/iP8p67vRnbuEqfa.png)
![b.png](https://i.loli.net/2020/07/27/hSCVxZw1qa2NUvi.png)

**Comment by xuejianxianzun** [comment]
版本6.7.0对夜间模式进行了适配，问题解决。
