### ISSUE TITLE
关注页下载时出现：无权访问xxx,跳过该作品

### ISSUE THREAD

**Issue by Shinaki** [xuejianxianzun/PixivBatchDownloader#92]
关注页下载时出现无权访问xxxxxx,跳过该作品，chrome和edge均有出现，使用的是Pixiv Nginx登录pixiv页面，请问这种情况是网络问题吗？

**Comment by xuejianxianzun** [comment]
你打开这个 id 对应的作品页面，看看能否正常浏览。如果你不能正常浏览，下载器就会这么提示。

**Comment by Shinaki** [comment]
作者页和作品页都能正常打开，目前我第11页和13页均出现这个问题，大概每页有400作品出现无权访问。这两页作品数大概2700/3400。

**Comment by xuejianxianzun** [comment]
加群问我吧
