### ISSUE TITLE
图片查看器咨询

### ISSUE THREAD

**Issue by meltyblood2010** [xuejianxianzun/PixivBatchDownloader#93]
RT，请问图片查看器翻页有没有快捷键或鼠标手势？

**Comment by xuejianxianzun** [comment]
目前没有。其实它本来可以通过 ← → 箭头翻页的，但是 pixiv 页面里这会导致作品的切换，所以就禁止了箭头翻页。
其他的翻页方式都不太通用，所以没有设置新的翻页方式了。

**Comment by xuejianxianzun** [comment]
下载器 9.0.0 版本支持了图片查看器的键盘操作
https://github.com/xuejianxianzun/PixivBatchDownloader/releases
