### ISSUE TITLE
能不能在下载动图作品的时候获取帧延迟呢

### ISSUE THREAD

**Issue by NLE3471** [xuejianxianzun/PixivBatchDownloader#95]
如果下载成zip格式后期合成的时候需要设置帧延迟,自己设置的播放效果和p站上有区别,如果能下载的时候获取帧延迟信息就好了

**Comment by xuejianxianzun** [comment]
获取是获取了，但是没保存。
p站的帧延迟可以设置成每一帧不一样的，所以要保存的话只能单独存成个 txt 文件或者 json 了，比较麻烦。

**Comment by NLE3471** [comment]
感谢回复.存储成同名的txt也行.有些延迟不长的动图还好,差别不大,那种延迟长的就难受了.

**Comment by xuejianxianzun** [comment]
这个需求的人数比较少，现在没有打算添加这个功能。
