### ISSUE TITLE
建议：点快速下载按钮同时快速收藏作品（含点赞）

### ISSUE THREAD

**Issue by InoryLwc** [xuejianxianzun/PixivBatchDownloader#96]
RT
一个小小建议，特别是批量下载的时候，心中感觉直接白嫖不行，还得回去挨个点收藏和点赞

**Comment by xuejianxianzun** [comment]
你标题说的是快速下载，针对单个作品倒是可以顺便点赞收藏了。
但是下面说的批量下载，批量下载的里面难免有不喜欢的，不需要收藏。而且也会增加下载完成所需的时间。

**Comment by xuejianxianzun** [comment]
目前不打算添加此功能，单个下载时你点一下收藏按钮吧。2333
