### ISSUE TITLE
一些希望

### ISSUE THREAD

**Issue by LBCHN** [xuejianxianzun/PixivBatchDownloader#97]
1.  小说以外的作品（插画，漫画，动图）都可以生成元数据文本文件，并且每个参数前面用“参数名：”注明。
2. 动图可以转换为APNG以及Webp。
3. 漫画可不可以单独形成一种文件名，或用其他办法让创建文件夹保存时单个文件以其页码命名？

**Comment by xuejianxianzun** [comment]
1. 你会把保存元数据用于什么用途呢？如果只是为了单纯的储存，我是不想做的，或许你可以寻找更合适的爬虫工具。
2. APNG 的体积甚大，转换也很占资源。不过我可以试一试。Webp 我觉得海星，但是我没找到合适的 js 库。如果你找到了好用的 js 的 Webp 库可以发给我。
3. 让文件名用页码命名，你试试 `{p_num}`，记得每个作品建立一个文件夹，否则多个文件名会因重复而产生冲突。目前不能单独针对漫画设置特别的文件名；命名规则会影响所有下载的文件。如果你想针对漫画或特定类型设置独立的命名规则，可以考虑赞助我（https://afdian.net/@xuejianxianzun 200元档）

**Comment by LBCHN** [comment]
> 1. 你会把保存元数据用于什么用途呢？如果只是为了单纯的储存，我是不想做的，或许你可以寻找更合适的爬虫工具。
> 2. APNG 的体积甚大，转换也很占资源。不过我可以试一试。Webp 我觉得海星，但是我没找到合适的 js 库。如果你找到了好用的 js 的 Webp 库可以发给我。
> 3. 让文件名用页码命名，你试试 `{p_num}`，记得每个作品建立一个文件夹，否则多个文件名会因重复而产生冲突。目前不能单独针对漫画设置特别的文件名；命名规则会影响所有下载的文件。如果你想针对漫画或特定类型设置独立的命名规则，可以考虑赞助我（https://afdian.net/@xuejianxianzun 200元档）

1. 上P站毕竟不容易，所以希望收集元数据，当然也确实有用，登记信息时。
2.  感谢。
3. 没问题，我会考虑的。

**Comment by xuejianxianzun** [comment]
1. 元数据的下载没有打算做
2. apng 已经可以转换

https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0

**Comment by CortinthusYu** [comment]
> 1. 元数据的下载没有打算做
> 2. apng 已经可以转换
> 
> https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0

我也希望能够保存元数据，最好是csv格式的，因为我希望能够把图片的pid、标签、标题等数据保存下来，导入我自己的图片管理系统，有一些作品tag非常多，如果全部堆在文件名里很容易有让文件名过长的危险，希望考虑一下

**Comment by xuejianxianzun** [comment]
> > 1. 元数据的下载没有打算做
> > 2. apng 已经可以转换
> > 
> > https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0
> 
> 我也希望能够保存元数据，最好是csv格式的，因为我希望能够把图片的pid、标签、标题等数据保存下来，导入我自己的图片管理系统，有一些作品tag非常多，如果全部堆在文件名里很容易有让文件名过长的危险，希望考虑一下

你的图片管理系统是什么，是如何使用csv的呢？
另外文件名过长会自动截断，可能会丢失部分 tag，但不至于有危险。

**Comment by CortinthusYu** [comment]
自己写的辣鸡系统、以及happypandax+自己写的导入脚本，格式不重要，主要是有文本的元数据的话我可以自己解析

**Comment by CortinthusYu** [comment]
> > > 1. 元数据的下载没有打算做
> > > 2. apng 已经可以转换
> > > 
> > > https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0
> > 
> > 
> > 我也希望能够保存元数据，最好是csv格式的，因为我希望能够把图片的pid、标签、标题等数据保存下来，导入我自己的图片管理系统，有一些作品tag非常多，如果全部堆在文件名里很容易有让文件名过长的危险，希望考虑一下
> 
> 你的图片管理系统是什么，是如何使用csv的呢？
> 另外文件名过长会自动截断，可能会丢失部分 tag，但不至于有危险。

自己写的辣鸡系统、以及happypandax+自己写的导入脚本，格式不重要，主要是有文本的元数据的话我可以自己解析

**Comment by xuejianxianzun** [comment]
> 自己写的辣鸡系统、以及happypandax+自己写的导入脚本，格式不重要，主要是有文本的元数据的话我可以自己解析

你列一下希望保存的字段吧

**Comment by CortinthusYu** [comment]
> > 自己写的辣鸡系统、以及happypandax+自己写的导入脚本，格式不重要，主要是有文本的元数据的话我可以自己解析
> 
> 你列一下希望保存的字段吧

按重要性排序：pid，tags，日期，作者，标题，其实主要是怕tag不完整😂

**Comment by xuejianxianzun** [comment]
> > > 自己写的辣鸡系统、以及happypandax+自己写的导入脚本，格式不重要，主要是有文本的元数据的话我可以自己解析
> > 
> > 
> > 你列一下希望保存的字段吧
> 
> 按重要性排序：pid，tags，日期，作者，标题，其实主要是怕tag不完整😂

那我做一下吧。我在想如果有人像一楼那样要 txt 格式的话，难道要再加个导出 txt 功能吗，有点头疼。
另外发电希望，诶嘿~

**Comment by CortinthusYu** [comment]
> 那我做一下吧。我在想如果有人像一楼那样要 txt 格式的话，难道要再加个导出 txt 功能吗，有点头疼。
> 另外发电希望，诶嘿~

怎么说，既然都有文本格式的元数据了那要用的话自己动手解析也是应该的，再说文本和csv差异也不大（一个东西
好的爱您

**Comment by xuejianxianzun** [comment]
> > 那我做一下吧。我在想如果有人像一楼那样要 txt 格式的话，难道要再加个导出 txt 功能吗，有点头疼。
> > 另外发电希望，诶嘿~
> 
> 怎么说，既然都有文本格式的元数据了那要用的话自己动手解析也是应该的，再说文本和csv差异也不大（一个东西
> 好的爱您

好~ tag 列表使用一个字段存储，用逗号分隔可以吗

**Comment by CortinthusYu** [comment]
> 好~ tag 列表使用一个字段存储，用逗号分隔可以吗
可以的

**Comment by xuejianxianzun** [comment]
> > 好~ tag 列表使用一个字段存储，用逗号分隔可以吗
> > 可以的

你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）

**Comment by CortinthusYu** [comment]
> 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）
每个作品一个吧，因为作品里面所有图的tag是一样的

**Comment by CortinthusYu** [comment]
> 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）

每个作品一个吧，因为作品里面所有图的tag是一样的

**Comment by xuejianxianzun** [comment]
> > 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）
> 
> 每个作品一个吧，因为作品里面所有图的tag是一样的
这种结果如何
![20200908152809.png](https://i.loli.net/2020/09/08/fQUC3wnNgjdLPep.png)

**Comment by CortinthusYu** [comment]
> > > 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）
> > 
> > 
> > 每个作品一个吧，因为作品里面所有图的tag是一样的
> 
> 这种结果如何
> ![20200908152809.png](https://camo.githubusercontent.com/bc4aa05b8a8ac1f29756f903fb290616d5cbe663/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30392f30382f6651554333776e4e676a644c5065702e706e67)

非常完美👍

**Comment by xuejianxianzun** [comment]
> > 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）
> 
> 每个作品一个吧，因为作品里面所有图的tag是一样的

https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.4.0
你安装新版本试试。

**Comment by CortinthusYu** [comment]
> > > 你这个的需求，是每个作品一份数据，还是每个图片一份数据（一个多图作品可能有多份数据）
> > 
> > 
> > 每个作品一个吧，因为作品里面所有图的tag是一样的
> 
> https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.4.0
> 你安装新版本试试。

太好用了，大感谢♥
