### ISSUE TITLE
Error when download tags are too long or has invalid characters

### ISSUE THREAD

**Issue by CELICA3** [xuejianxianzun/PixivBatchDownloader#98]
download error! code: FILE_FAILED. The downloader will try to download the file again

**Comment by xuejianxianzun** [comment]
Why don't you provide the work id?
I tested the file name longer than 400 characters, Chrome will automatically truncated, so no problem will occur.
```
83993034_p0-Nroy--女の子,女孩子,日系,お団子ヘアー,少女,young girl,緑の髪,魅惑の谷間,魅惑的乳沟,肩が出る,ぱっくり背中,露背,原创,original works,萝莉,loli-女の子,女孩子,日系,お団子ヘアー,少女,young girl,緑の髪,魅惑の谷間,魅惑的乳沟,肩が出る,ぱっくり背中,露背,原创,original works,萝莉,loli-女の子,女孩子,日系,お団子ヘアー,少女,young girl,緑の髪,魅惑の谷間,魅惑的乳沟,肩が出る,ぱっくり背中,露背,原创,original works,萝莉,loli-女の子,女孩子,日系,お団子ヘアー,少女,young girl,緑の髪,魅惑の谷間,魅惑的乳沟,肩が出る,ぱっくり背中,露背,原创,original works,萝莉,loli-女の子,女孩子,日系,お団子ヘアー,少女,young girl,緑の髪,魅惑の谷間,魅惑的乳沟,肩が出る,ぱっくり背中,露背,原创,original works,萝莉,loli.jpg
```

**Comment by xuejianxianzun** [comment]
If you get this error while downloading, you can pause the download and then start the download so that the downloader will retry to download the file.

**Comment by CELICA3** [comment]
![image](https://user-images.githubusercontent.com/47961956/91756466-9fa63580-eb81-11ea-96fb-7a2c118b7365.png)
![image](https://user-images.githubusercontent.com/47961956/91756507-ae8ce800-eb81-11ea-9271-5431885b4d8b.png)
without tags can download just fine

**Comment by CELICA3** [comment]
with tags it will freeze
![image](https://user-images.githubusercontent.com/47961956/91756587-d0866a80-eb81-11ea-8df2-927372f3d59a.png)

**Comment by CELICA3** [comment]
![image](https://user-images.githubusercontent.com/47961956/91775988-61b90980-eba1-11ea-95fa-2ecf82f96307.png)
it seems to me it doesn't parse everything correctly

**Comment by CELICA3** [comment]
I found out why now, it is more likely a limitation of chrome itself rather than the faults of this extension, thanks anyways.
The burden is on chrome's inability to save directly to network mapped locations with different formating types

**Comment by xuejianxianzun** [comment]
Is it because it is stored in a network location?
It is also recommended that you add `{p_num}` to the naming rule, otherwise multiple pictures with the same id may be duplicated.

**Comment by CELICA3** [comment]
correct, attempted location is a nas storage, and chrome is so far reluctant to properly support network storage
once it is pointed at a local drive, the problem no longer presents. 
the one i used is {id} - {title} [{tags_translate}]

**Comment by xuejianxianzun** [comment]
I have not encountered this situation before because I did not use NAS.
In fact, NAS may have different disk formats, and the file names that can be stored may be different. This may be a difficult problem to deal with.

**Comment by xuejianxianzun** [comment]
>replaces tag 1 to tag_1
I don`t understand.
Regarding the file name issue, it seems that I need to add a setting item to allow users to set the length of the file name.

**Comment by xuejianxianzun** [comment]
In version 7.3.0, you can set the length of the file name.
