### ISSUE TITLE
无法下载漫画系列

### ISSUE THREAD

**Issue by Kennnnnnji** [xuejianxianzun/PixivBatchDownloader#99]
例如：https://www.pixiv.net/user/7331523/series/72825?p=1
![image](https://user-images.githubusercontent.com/34367558/91697375-95952e80-eba3-11ea-8bb8-a3556ae85028.png)
![image](https://user-images.githubusercontent.com/34367558/91697395-a0e85a00-eba3-11ea-9cca-b7ca5f81c041.png)
最新版插件和chrome

**Comment by xuejianxianzun** [comment]
我试了下是可以的，共抓取到 54 个文件
你刷新一下再试试

**Comment by xuejianxianzun** [comment]
> 例如：https://www.pixiv.net/user/7331523/series/72825?p=1
> ![image](https://user-images.githubusercontent.com/34367558/91697375-95952e80-eba3-11ea-8bb8-a3556ae85028.png)
> ![image](https://user-images.githubusercontent.com/34367558/91697395-a0e85a00-eba3-11ea-9cca-b7ca5f81c041.png)
> 最新版插件和chrome

话说，不引用你发的文字的话，你会收到回复的提醒吗

**Comment by Kennnnnnji** [comment]
奇怪，刷新了还是抓取不到Orz

发帖会自动订阅，能收到通知

**Comment by xuejianxianzun** [comment]
下载面板底部 ，重置设置，再试试

**Comment by Kennnnnnji** [comment]
还是不行，edge也试了Orz

**Comment by Kennnnnnji** [comment]
进去单页漫画能够下载，系列页面不行

**Comment by xuejianxianzun** [comment]
这挺奇怪的，你加qq群吧，我可以使用 teamviewer 帮你远程看看

**Comment by Kennnnnnji** [comment]
申请了

**Comment by xuejianxianzun** [comment]
这是因为系列页面改版了，我最近适配一下

**Comment by xuejianxianzun** [comment]
7.3.0 版本已经适配
https://github.com/xuejianxianzun/PixivBatchDownloader/releases/tag/v7.3.0
